### PR TITLE
Ask for confirmation before clearing queue even if only 1 video in it

### LINKED ISSUE #4459: "Ask for confirmation before clearing a queue" doesn't work if queue contains only one track
### Checklist

- [x] I am using the latest version. 
- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Enable the option "Ask for confirmation before clearing a queue".
2. Add a single track to the background queue (either playing or paused).
3. Play another video in NewPipe normally.

### Actual behaviour
The video starts playing, and background queue is deleted. 

### Expected behavior
A warning "The active player queue will be replaced" should appear. Just because I have only one track in the queue, doesn't mean that I want NewPipe to remove it without warnings.

### Device info

 - Android version/Custom ROM version: Android 11
 - Device model: Pixel 3a

### PR DESCRIPTION
**Pull request by opusforlife2**
#### What is it?
- [x] Bug fix (user facing)
- [ ] Feature (user facing)
- [ ] Code base improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Removed the condition that there must be more than one video in the queue for the confirmation dialogue to be shown.

#### Fixes the following issue(s)

- closes #4459

#### Testing apk

[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5356348/app-debug.zip)

#### Agreement
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by nbmrjuhneibkr** [comment]
I'll also copy this suggestion here, just in case someone thinks that there is a reason to have a choice between current (v0.20) behavior of the option and the one introduced by this PR.

>Instead of being limited to yes or no, "Ask for confirmation before clearing a queue" could have 3 options: always, never and "when the queue contains multiple tracks".

**Comment by opusforlife2** [comment]
@wb9688 Happy now? >:(

**Review by Stypox — APPROVED** [review]
I tested, and it works. Thank you @opusforlife2 @avently ;-)

**Comment by opusforlife2** [comment]
Thank you @avently!

**Comment by avently** [comment]
@opusforlife2 without you it wouldn't be possible.

**Pull request merged**
