### PR TITLE
Add play queue to menu

### LINKED ISSUE #2477: Feature request :  Add a tab in Main Page for the Background Player
Hi NewPipe Team,

I wish to make a suggestion for a feature in the main page content. Could it be possible to add in the main content page, a tab for the background player to be able to access it easily (picture 1).

For this, in the parameters menu "Content of Main Page", when clicking on the "+" there could be a new option to add a tab to access directly the background player (picture 2). This will let the user decide to show this tab or not as he wish.

Thanks for reading

Main Page - Background Player

Parameters - Content of Main¨Page

### PR DESCRIPTION
**Pull request by HybridAU**
#### What is it?
- [ ] Bugfix (user facing)
- [X] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
There is a feature (bug?) in Android 11 and up where media controls can be completely dismissed. The problem is the only way to get the the play queue is clicking on the media controls notification.
- Adds "Play Queue" button to the main menu
- Play Queue activity does not finish when the queue is empty. (So if you click on the Play Queue menu item while it's empty it doesn't flash open for a second and then immediately kick you back out)

#### Before/After Screenshots/Screen Record

- Before:
1_before

- After:
2_after

 - Empty play queue screen:
3_empty_queue

#### Fixes the following issue(s)

**EDITED**: See comments below.

This PR might help address #2477,  #5235 and #7208 although not exactly what they are looking for.

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [X] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mhmdanas** [comment]
@HybridAU this is not what #2477 asks for; the issue asks for the option to add a play queue tab at the top of the main page.

**Comment by HybridAU** [comment]
Hey @mhmdanas that's a good point, I did think about it, and I should have addressed it in my original comment on this PR.

When I was reading through #2477 there were several tickets that were closed as duplicates such as #1409, and several comment such as "that the queue that is accessed from the pull down menu is already a perfect layout" and even @SameenAhnaf has just commented saying they would prefer an icon for play queue on the top right corner.

So my interpretation was a more generally "users want a way to access the background player from with the app". The reason I went with a menu button was that it is a minimal change that allows reuse of the existing functionality and does not add a significant maintenance burden.

However that said I'm happy to change my PR description, to be clear that this dose not exactly do what #2477 is asking for.

**Comment by MD77MD** [comment]
the problem with implementing it this way it would be easily blocked... because the side menu is blocked the moment you interact with NewPipe and not on the main page

so you will have to go back to the main page to open queue which not right... queue should be easliy accessed regardless to whats opened in NewPipe

**Comment by MD77MD** [comment]
my idea is to have a button in the small play bar
like this
Screenshot_20220520-120302_NewPipe SponsorBlock

or

**Comment by SameenAhnaf** [comment]
The best alternative would have been https://github.com/TeamNewPipe/NewPipe/issues/7973. But coding is the only I am afraid.

**Comment by HybridAU** [comment]
@MD77MD I like the idea of adding it in the small player bar. I'll close this PR and open a new one that does that.

**Pull request closed without merging**
