### PR TITLE
Hotfix: Downgrade ExoPlayer

### PR DESCRIPTION
**Pull request by Redirion**
#### What is it?
- [X] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
I just took the commit for PR #6524 and applied it as a patch to master.
- 

#### APK testing 

On the website the APK can be found by going to the "Checks" tab below the title and then on "artifacts" on the right.

#### Due diligence
- [X] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TobiGr** [comment]
Choosing the resolution inside the player is broken on Android 11 in a Pixel emulator. Main and pop-up player are effected

**Comment by Redirion** [comment]
working for me on my real Android 11 Pixel 4a

**Comment by litetex** [comment]
@Redirion 
I can't quite figure that PR out:

As stated in #6524:
> Fixes Buffering video unrelated to connection #6510 (hopefully)

Fixing a bug when not knowing the cause (as far I didin't find one in #6510, #6524 and here) and just downgrading something without a clear reasons is not understandable for me.
ExoPlayer was upgraded nearly 3 months ago (in https://github.com/TeamNewPipe/NewPipe/pull/5856) and no one had problems (or very rare) for at least 3 to 4 releases (was released with [v0.21.0](https://newpipe.net/blog/pinned/release/newpipe-0.21.0-released/))

So some questions regarding that PR:
* How does it fix #6510?
* Why doesn't e.g. upgrading to a newer ExoPlayer version fixes that?
* When the problem is caused by the remote side (e.g. YT servers) how does this PR help fixing that?

**Comment by Redirion** [comment]
1. ExoPlayer 2.12 changed alot, it moved from MediaSource to MediaItem. NewPipe still uses MediaSource. So my wild guess was that beginning with 2.12 the since then deprecated MediaSource was somewhat broken but not all devices were affected so it was unnoticed
2. I tried with #6295 so from that point I thought the only way is to find out if downgrading helpos
3. it won't of course fix anything and if it turns out that that is the issue I will happily directly update to ExoPlayer 2.14.1

**Comment by litetex** [comment]
Downgrade will very likely not help, as stated in https://github.com/TeamNewPipe/NewPipe/issues/6510#issuecomment-867789285

**Pull request closed without merging**
