### PR TITLE
Update ExoPlayer to 2.18.2

### PR DESCRIPTION
**Pull request by Redirion**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [X] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Update ExoPlayer: 2.18.1 -> 2.18.2 ([changelog](https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md))
- Simplify `LoadedMediaSource` by extending the new `WrappingMediaSource` class of ExoPlayer 2.18.2. This basically saves a few lines of code and has smaller memory footprint due to less complexity than the `CompositeMediaSource` used earlier. `PlaceHolderMediaSource` has still to use the `CompositeMediaSource` unfortunately, as `WrappingMediaSource` is not null tolerable.

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [X] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by AudricV** [comment]
Could you rebase this PR, please, so we only have the ExoPlayer changes? Thank you in advance!

**Comment by Redirion** [comment]
Done, if you approve the PR, I can squash and merge it

**Review by Stypox — APPROVED** [review]
LGTM. The `WrappingMediaSource` implements the methods you removed in basically the same way. I tested a bit the player and found no problem. Thanks!

**Comment by Stypox** [comment]
Since this was merged I started getting the following exception on various videos in debug builds.

Steps to reproduce:
- play [this](https://www.youtube.com/watch?v=hsECdMrjh8c) video at 720p (but it also happens with other videos, e.g. [this](https://www.youtube.com/watch?v=J_n1FZaKzF8))
- wait some time (you may also need to switch to another app and let the player in the background, but I could reproduce even without this)
- the player crashes
<details><summary><h3>Exception</h3></summary><p>

* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_FAILED_RUNTIME_CHECK] occurred while playing https://www.youtube.com/watch?v=hsECdMrjh8c
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ YouTube
* __Version:__ 0.24.1
* __OS:__ Linux Android 10 - 29

```
com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:621)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:214)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.lang.IllegalStateException
	at android.media.MediaCodec.native_setSurface(Native Method)
	at android.media.MediaCodec.setOutputSurface(MediaCodec.java:2045)
	at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.setOutputSurface(SynchronousMediaCodecAdapter.java:189)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutputSurfaceV23(MediaCodecVideoRenderer.java:1490)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutput(MediaCodecVideoRenderer.java:693)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:631)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.deliverMessage(ExoPlayerImplInternal.java:1550)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageToTarget(ExoPlayerImplInternal.java:1514)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:1489)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:526)
	... 3 more

```
</details>

**Pull request merged**
