### PR TITLE
Add toolbars to list info items with fast actions

### LINKED ISSUE #2583: Fast actions from mini info item - UI / UX ideas
# Problem
I have been thinking about the long press menu lately, and I realized it is inconvenient because:
1. Entries have no corresponding icon, so our eyes can't distinguish between two entries at the first sight.
2. Entries are not always in the same position on the screen, so we can't use muscle memory. Even though this was partially addressed by #2354 & #2368, the position of entries depends anyway on the menu length.
3. There are too many entries, making the menu too crowded, and there are many requests for new entries (#437 #2198 #2510 #1142).
4. There is no way to select multiple streams and apply an action on all of them.

# Solution
This is the solution I propose, sorry for the bad quality ;-)

menu

Screen A contains normal info item list. By tapping on the blue *stream* info item we get to screen B. Yes, video info is not loaded, instead the item expands to show some action buttons above and below it! Here is why I think this is a good idea:
- Most of the times when I click on a video I just want to play it, and currently I have to wait for video info to load before being able to play anything (#2306). With this solution it would take less time.
- Video info can be loaded by clicking again on the item.
- Icons are always in the same place (relative to the clicked stream) and with the same icon (no text, as icons are representative enough). This solves problems 1. and 2. above. Also, actions about stream content (play&download) are separated from the specific ones that only use stream info (add-to-playlist, share, delete-from-playlist, set-as-playlist-thumbnail, etc.).
- Since play-actions are displayed where the item was before, and the item is shifted down (see how the above separator is not moved in screen B), one can remember where an option is and double-tap in the correct place directly from screen A. This would take no time.
- Background and popup play buttons can be long-pressed to enqueue (consistent with the video info activity).
- There is place for new actions, in case we ever need them. We would just need to add a button to the bar below the item.

By long-pressing on the blue *stream* info item on screen A, the multiple-select options are shown in the action bar (similar to https://github.com/TeamNewPipe/NewPipe/issues/2354#issuecomment-494871457), solving the problem 4. above. By tapping once on any other *stream* info items we can select them, getting to situation C. A tick is displayed above selected items' thumbnails and the action bar is populated with actions about stream content.
The three-dot menu cointains the other actions and also two options useful for selection purposes: "select below" and "select above", only available in non-infinite lists. These can be considered a replacement to a "select all" button, but are more powerful and would solve #2510 #2559. If a playlist is long and is not fully loaded, the "select below" button would lazily select all items so that they are loaded only if needed. 

# Feedback
I would implement this but I need feedback both from designers and from users. Would this idea suit your needs? Would it be pleasant to the eye? If you disagree with any of the assumptions I made above, be sure to tell me ;-)

@theScrabi @TobiGr @TheAssassin @nv95 @Gymcap @karyogamy @justanidea @Lirlisa @gkeegan @BartFarley @xak2000 @jojoxl01

### PR DESCRIPTION
**Pull request by Stypox**
#### What is it?
- [ ] Bug fix (user facing)
- [x] Feature (user facing)
- [ ] Code base improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
<table><tbody><tr><td></td><td>
This unfinished PR introduces the item toolbars promised in #2583, as shown in the images on the left. Even though all buttons are in the layout, only share, add to playlist, and play/enqueue have been implemented so far.<br>
The issue is, I realized this could not be the best UI for non-techy people, as it is not usual that clicking on a list item does not open it but only shows some related actions. So I would like to get some feedback from you: do you find this ui comfortable or did you prefer the long-press menu?<br>
Btw, even though in #2583 I said I would make two different actions for thumbnail and other data double-press, I realised it is better not to put too many things into a small item without a clear indication. So for now clicking twice anywhere on the item first opens the toolbar and then shows info.
</td></tr></tbody></table>

#### Fixes the following issue(s)
- Closes #2583 
- OTHERS (will specify later)

#### Relies on the following changes
- #3930

#### Testing apk
This apk is not complete at all. There are many issues (one of them is: adding local playlists to other local playlists is disabled because strange loops would arise). So don't expect a pleasant experience, but please tell me if the overall way of doing things is in your opinion better or worse.
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4975306/app-debug.zip)

#### Agreement
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by opusforlife2** [comment]
Oh my! What is it with this Apple-like secretiveness and flashy reveal? XD

**Comment by opusforlife2** [comment]
Right off the bat, I noticed that long press on a list item does nothing. I think rather than a single tap to expand and another to open, it would be more intuitive to open on single press and expand on long press instead.

**Comment by heberjeur** [comment]
Can you separate actions, when I click to text It appears icons list and when I click to image it open directly and with one press the video.
shot_01

**Comment by opusforlife2** [comment]
@heberjeur
> Btw, even though in #2583 I said I would make two different actions for thumbnail and other data double-press, I realised it is better not to put too many things into a small item without a clear indication.

**Comment by tomjuggler** [comment]
I have to say I just tried this and I am a big fan of the one-click menu popup. Maybe making the play button more prominent would be a suggestion I could make (simply putting it closer to the middle of the screen would work). To be honest I never used the long press anyway. If you just added the download button in there I would be very happy with this change myself.

**Comment by opusforlife2** [comment]
Crash: Malformed URL when opening a channel page on any service.

**Comment by MD77MD** [comment]
bug: "add to playlist" button is showing in playlists toolbar when it should not.

**Comment by MD77MD** [comment]
I love how long pressing acts as enqueue however this should be mentioned in like a tips section or how to use introduction when using newPipe for the first time.. it

also long pressing on the play button could act as enqueue next.

I also like previous suggestion. having the toolbar while pressing on thumbnail to play video directly is a great combination.

**Comment by opusforlife2** [comment]
#3076 reminded me: Since text has been replaced with just icons, you should absolutely show tooltips for all of them. The current "hold to append" tooltip for background and popup icons should show for the list item icons as well, if the toggle is on.

**Comment by MD77MD** [comment]
in your proposal, you mentioned multi select feature... I hope that is not gone. this online is considered a big update. imagine how much less clicking is needed whenever y want to add or remove a bunch of videos from playlists or queues.

**Comment by heretoenhance** [comment]
> also long pressing on the play button could act as enqueue next (play next). this would be even more useful after updating to unified player.

I was going to open a feature request for this, having "play next" would be an awesome addition to this already ultra awesome app. Thank you all guys for your work!

**Comment by MD77MD** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/4405#issuecomment-710826700

**Comment by Stypox** [comment]
I will not continue thir PR, as I changed my mind about #2583: having such a menu popping up below items, with rather small buttons, would feel strange and probably also difficult to use.

**Pull request closed without merging**
