### PR TITLE
Release v0.16.2

### PR DESCRIPTION
**Pull request by TobiGr**
We should release bug fixes from time to time... :)

 [newpipe_0.16.2_rc2_debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/3179992/newpipe_0.16.2_rc2_debug.apk.zip) (by @TobiGr)

Please report crashes and bugs in #2314 

# Changelog

### Improvements
- add support for opening [Invidio.us](https://invidio.us) links
- make links in comments clickable, increase text size #2168
- seek on clicking timestamp links in comments #2207 
- show preferred tab based on recently selected state #2247 
- add playlist to queue when long clicking on 'Background' in playlist window #2023 
- search for shared text when it is not an URL #1963 
- add "share at current time" button to the main video player #2271 
- add close button to main player when video queue is finished #1969 
- add "Play directly in Background" to longpress menu for video list items #2198 
- improve English translations for Play/Enqueue commands #2237
- small performance improvements #2178, #2179 
- remove unused files #2183
- update ExoPlayer to 2.9.6 #2184, #2311 

### Fixed
- fixed scroll w/ comments and related streams disabled #2176 
- fixed CheckForNewAppVersionTask being executed when it shouldn't #2161
- fixed youtube subscription import: ignore ones with invalid url and keep ones with empty title https://github.com/TeamNewPipe/NewPipeExtractor/pull/160
- fix invalid yt url: signature tag name is not always "signature"  preventing streams from loading https://github.com/TeamNewPipe/NewPipeExtractor/pull/163

### ToDo

- [ ] Update Weblate translations

### CODE REVIEW

**Comment by Brimont** [comment]
I have test this release, and it work Well! Thanks for your work :)

**Comment by Artuist** [comment]
Correct me if I'm wrong but I think the Close button when a video ends doesn't work as intended. To elaborate:
1. Enable "Minimize to popup player" on app switch
2. Open up a video and when it ends press the Close button
The video will start over on the popup player. Is that how it's supposed to work? 
Thanks for your work!

**Comment by TobiGr** [comment]
Nice catch. @nv95 do you have time to look at it?

**Comment by TobiGr** [comment]
@Artuist Thanks for reporting. I tried to track this down, but unfortunately, this is wrong behaviour is not limited to the close button, but to all player exit actions when minimize to background/popup is enabled.  I first tried to find any related code which has been touched during the work on this release. After debugging and searching for too long, it turned out that this bug existed in previous versions, too.

Whenever a video is left by either closing it or switching to a different player, the player to minimize to is opened. For example, set minimize to background, open a video and than switch to popup. Both players will be started. 

Therefore, I wouldn't see this as a blocker for this release. nevertheless, we should open a ticket.

@theScrabi AFAICS only the weblate update is missing to get this release out to the people.

**Comment by TobiGr** [comment]
Thanks to @Stypox, we can ship two more fixes with 0,16.2:
- prevent streams from not loading
- fix YouTube subscription import

Here is the new RC: [newpipe_0.16.2_rc2_debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/3179992/newpipe_0.16.2_rc2_debug.apk.zip)

**Comment by theScrabi** [comment]
> @theScrabi AFAICS only the weblate update is missing to get this release out to the people.

I see.

You can add `https://hosted.weblate.org/git/newpipe/strings/` as a git repository, and just pull from the dev branch there. You will have a million of commits coming from there messing up your commit history. However rebasing is not possible as it  takes forever.

**Comment by Pentaphon** [comment]
Yes, please. It's been too long. We are almost at June.

**Comment by TobiGr** [comment]
@theScrabi No, I just didn't see it at first

**Pull request merged**
