### PR TITLE
Remove support for android 4.1 - 4.3

### PR DESCRIPTION
**Pull request by theScrabi**
This PR will:
- Deprecate Android 4.1, 4.2, 4.3 since these are pourly supported and not tested anymore
- Remove deprecated "Old Player"
- Move "autoplay next" preference element into the player "Behaviour" section.

### CODE REVIEW

**Comment by Brimont** [comment]
I have phone with android 4.2.1 i can use newpipe on future? This is my only phone!

**Comment by gkeegan** [comment]
@Brimont You can still use any versions that have been released before this date. Also, if newpipe stops working in the future on your device (due to YouTube changing something in how videos are served) you can probably install a custom rom (if your phone has any available).

**Comment by SC1040-TS2** [comment]
I was away for a number of days, so seeing this PR is a bit of news to me. It would appear that after some thought, the original intent of my issue was valued above more conservative means of deprecation.

I presume that with all things considered, the move away from older forms of Dalvik was especially given value, as well as streamlining development. I suspect that NewPipe will eventually drop support for the runtime environment entirely in two or so version releases, depending on what the actual development timeline looks like.

Other than that, I send my regards for the time being.

**Comment by Riotous** [comment]
@Brimont Time to buy a new phone

**Comment by bidaian** [comment]
@theScrabi, I own a tablet and a phone with 4.2 and I love NewPipe. Getting a new ROM or a new phone is not really an option right now. Would forking NewPipe work for a while at least? I could revert the commits for this issue and follow you.

**Comment by gkeegan** [comment]
Forking and reverting commits would not work, as some recent commits were made to fix the way YouTube gave videos. If you reverted those commits, you would not be able to play or download videos. 

There is some discussion about making a fork that would keep compatibility with older versions of Android, but as far as I know, as of this moment, there is no working build.

**Comment by Riotous** [comment]
@bidaian If you can't buy a new phone and tablet, you should consider flashing these devices with newer versions of Android if you can. If you can't, there's no other solution for you than to buy new devices.  4.3 and below is being deprecated by a lot of software and you should really not be using anything older.

**Comment by gkeegan** [comment]
I would not necessarily say no other option, as there are still alternatives such as using  SkyTube (which as far as I know still has support for 4.2) for your YouTube needs.

**Comment by orinjus** [comment]
I would just like to add that I don't use my old devices for anything sensitive, and I can't buy a new device just for youtube. Previous NewPipe (0.14.1) worked (unstable but adequate) on android 4.0.4 though not "supported".

I appreciate this project deeply, partially _because_ I could use it on older devices.  I don't know how difficult/complex it is to write for older APIs, and I totally understand this is a volunteer project, so... yeah, you do what you need to do.  For my part though, this will limit my options a lot.

**Comment by Riotous** [comment]
@orinjus @gkeegan 
https://dentex.github.io/apps/youtubedownloader/
https://github.com/ram-on/SkyTube

**Comment by d-g** [comment]
Riotous wrote:
> https://dentex.github.io/apps/youtubedownloader/

It’s nonfree.

**Comment by gkeegan** [comment]
I don't understand what you mean. Please elaborate. SkyTube (not the extra version) is FOSS.

**Comment by d-g** [comment]
Keegan Given wrote:
>>> https://dentex.github.io/apps/youtubedownloader/
>>
>> It’s nonfree.
>
> I don't understand what you mean. Please elaborate. SkyTube (not the extra version) is FOSS.

Hmm, I believed, I cited a relevant line while replying; did it get mangled?

SkyTube is free, Dentex’s ‘YouTube Downloader’ is not.

**Comment by gkeegan** [comment]
I believe its something with my app. Looks fine in a browser.

**Comment by starks** [comment]
There are older devices out there (sticks, headunits, etc) that run pre-4.4 Android and cannot be easily upgraded. They need a solution.

**Comment by d-g** [comment]
starks <notifications@github.com> wrote:
> There are older devices out there ... that run pre-4.4 Android and cannot be easily upgraded. They need a solution.

Did not NewPipe maintainers restored support for older Android about a month ago as a separate build [0]?

(And I’d like to take the opportunity to sincerely thank them for that, as Android toys are indeed typically designed to became obsolete quite soon, and it’s not easy for an unsophisticated buyer to predict, how soon.)

[0] https://f-droid.org/en/packages/org.schabi.newpipelegacy

**Pull request merged**
