### PR TITLE
Add sonar plugin and github actions file for sonar analysis

### LINKED ISSUE #5825: [SonarQube] Add workflow file for analysis and adjust gradle file
Make adjustments to repo according to setup guide of sonarcloud.

https://sonarcloud.io/project/configuration?analysisMode=GitHubActions&id=TeamNewPipe_NewPipe

### PR DESCRIPTION
**Pull request by XiangRongLin**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [x] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Add sonar plugin and github actions file for sonar analysis
- Copied from sonarcloud.io setup page with minor adjustments. Adjusted branch to 'dev' and updated versions

#### Fixes the following issue(s)

- closes #5825 

#### Relies on the following changes

- #5822 This needs to be done beforehand

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by XiangRongLin** [comment]
@TobiGr Do you have any idea why checkstyle fails of JDK 11?

**Comment by TobiGr** [comment]
I have no idea. Maybe the checkstyle suppressions are ignored? I changed a few lines, could you try it again after rebasing on https://github.com/TobiGr/NewPipe/tree/listHelper ?

**Comment by XiangRongLin** [comment]
does not work. I don't even need to rebase, just checking out you project and running `gradle build` with jdk 11 fails.

**Comment by TobiGr** [comment]
it looks like the `checkstyle-suppressions.xml` is not process correctly. All the failing checks are mentioned in that file and should be ignored.

**Comment by TobiGr** [comment]
Try this:
``` diff
diff --git a/app/build.gradle b/app/build.gradle
index c75bd43178f..957597ad955 100644
--- a/app/build.gradle
+++ b/app/build.gradle
@@ -116,6 +116,7 @@ configurations {
 
 checkstyle {
     configFile rootProject.file('checkstyle.xml')
+    suppressionsLocation rootProject.file('checkstyle-suppressions.xml')
     ignoreFailures false
     showViolations true
     toolVersion = checkstyleVersion
```

**Comment by XiangRongLin** [comment]
@TobiGr That fails before even running checkstyle with: `No signature of method: build_dfldf361ev1py0dzqgbyjtld3.checkstyle() is applicable for argument types: (build_dfldf361ev1py0dzqgbyjtld3$_run_closure4) values: [build_dfldf361ev1py0dzqgbyjtld3$_run_closure4@2814b9cd]`

I would translate it to "no method with given parameters exists"

**Comment by TobiGr** [comment]
try also adding this:
`suppressionsFileExpression checkstyle.suppressions.file`

**Comment by TobiGr** [comment]
Screw it, Do not even try that. But this looks promising:
``` diff
diff --git a/checkstyle.xml b/checkstyle.xml
index af8c5480f88..c1405c2ce36 100644
--- a/checkstyle.xml
+++ b/checkstyle.xml
@@ -23,7 +23,7 @@
     <!-- https://checkstyle.org/config_filters.html#SuppressionFilter -->
     <module name="SuppressionFilter">
         <property name="file" value="${org.checkstyle.sun.suppressionfilter.config}"
-                  default="checkstyle-suppressions.xml" />
+                  default="${config_loc}/checkstyle-suppressions.xml" />
         <property name="optional" value="true"/>
     </module>
```

**Comment by XiangRongLin** [comment]
@TobiGr Checkstyle problem is solved.

Are you sure, you set the secret corretly? It fails with unauthorized error

**Comment by TobiGr** [comment]
The auth error is probably caused by you opening the PR from a fork. Please push this branch to our repo and open another PR.

**Comment by TobiGr** [comment]
#5844 succeeded. We should work on that branch, so this pr can be closed.

**Pull request closed without merging**
