### PR TITLE
Add Artist and Duration to MediaDescription

### LINKED ISSUE #1507: Send track informations via A2DP/AVRCP (on bluetooth)
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

On a Mazda Demio (Mazda2),  I was streaming audio via bluetooth with NewPipe v0.13.5 from f-droid on LineageOS 14.1 (Android 7.1.2) on a Samsung Galaxy S7. The car screen did not show artist/track information. I searched around and I think this is related
https://stackoverflow.com/questions/15527614/send-track-informations-via-a2dp-avrcp
I would gladly contribute a patch, but the car is not mine so I have no immediate way to debug :(

### PR DESCRIPTION
**Pull request by Redirion**
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

this fixes #1507 

On my car only the title of the current video was shown when I used NewPipe with Bluetooth. Now it also shows the Artist.

Duration was not shown on my car though (playback was still shown as "streaming"). This might require further investigation. I have added it nonetheless.

Tested with Android 7.1.2.

### CODE REVIEW

**Comment by theScrabi** [comment]
Your fix looks ok, but you should not merge the dev branch into your branch, rather do it with rebase.

**Comment by Redirion** [comment]
I have now made:
git remote add upstream https://github.com/TeamNewPipe/NewPipe.git
git fetch upstream
git rebase v0.15.1
git pull
git push -u origin ArtistInfo

was that the correct way?

**Comment by theScrabi** [comment]
almouse you have wanted to rebase with `dev`.

**Comment by theScrabi** [comment]
I cherry picked the right commit. instead of merging this.

**Comment by Redirion** [comment]
sorry for that. I will respect that in the future. However your cherry pick did not close the issue 1507. You might also want to do that as my commit did address this issue.

**Comment by theScrabi** [comment]
> sorry for that.

Everything is fine. Thanks for your commit :)

**Pull request closed without merging**
