### PR TITLE
Use List.of().

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Update `compileSdkVersion` to 30.
- Use the `List.of()` factory methods introduced in API level 30, which are desugared for API levels below 30:
Screenshot 2020-11-06 101401

#### APK testing 

[debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5499128/debug.zip)

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by opusforlife2** [comment]
Was the build.gradle change intentional?

**Comment by Isira-Seneviratne** [comment]
> Was the build.gradle change intentional?

Yeah, because `List.of()` (and the other Java 9 collection factory methods) were added in API level 30.

**Review by Stypox — COMMENTED** [review]
@Isira-Seneviratne code looks good to me. Thank you!
Are you sure that increasing the `compileSdkVersion` to `30` doesn't break backwards-compatibility with API 19, since we're using the old `file://` scheme there which afaik is not allowed on Android 11?

**Comment by TobiGr** [comment]
We should not touch the `minSDKVersion` or the `compileSDKVersion` until F-Droid fixed their v2 signing for reproducible builds.

**Comment by Isira-Seneviratne** [comment]
> @Isira-Seneviratne code looks good to me. Thank you!
> Are you sure that increasing the `compileSdkVersion` to `30` doesn't break backwards-compatibility with API 19, since we're using the old `file://` scheme there which afaik is not allowed on Android 11?
> See #3777

I didn't know there was such a restriction.

**Comment by litetex** [comment]
Closing this for now:
* no progress
* no GitHub actions builds (Tests are not executed!)
* merge conflicts

Also in my opinion this PR should be split into 2 smaller parts:
1. Where the compileSDK is updated
2. Where the code improvements are done

Makes it easier and faster to review. 

Feel free to reopen it when there is progress again 😄

**Pull request closed without merging**
