### PR TITLE
Add fastforward button to notification

### PR DESCRIPTION
**Pull request by Gracecr**
Expanding off of #316, This adds a fast forward button to the notification pane that skips ahead 15 seconds. This is the same behavior as in the video player.

### CODE REVIEW

**Comment by timofonic** [comment]
Why 15 seconds instead more granularity?

**Comment by Gracecr** [comment]
I did it this way because this matches the behavior of the built in player.

**Comment by Gracecr** [comment]
Merged conflicts. Sorry about the two reverted commits.

**Comment by theScrabi** [comment]
We are already working on something similar: https://github.com/TeamNewPipe/NewPipe/pull/377

**Pull request closed without merging**
