### PR TITLE
Add korean translation of README.md

### PR DESCRIPTION
**Pull request by KIMMINTAE98**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [x] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Added README_KO.md which is korean translation of README.md 
to active the participation of the Korean contributors or download of Korean users.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Stypox** [comment]
Is this the standard way to provide a translated README for GitHub repositories? Will Korean users automatically see it when opening the repo?

**Comment by opusforlife2** [comment]
@Stypox See for example https://github.com/tiimgreen/github-cheat-sheet/blob/master/README.md which contains links to translated versions of itself.

However, it uses README.ko.md instead of README_KO.md like Min-Tae has done here.

**Comment by Stypox** [comment]
@KIMMINTAE98 thank you! Can you rename the file to `README.ko.md` as requested by opusforlife2? Then this can be merged, can't it @B0pol @opusforlife2?

**Comment by opusforlife2** [comment]
@Stypox Note that I haven't found any official Github documentation on this. What I've said above is just from researching what seem to be the best practices in other repos.

**Comment by B0pol** [comment]
@Stypox no, in README.md there shoul be a line like "korean translation", otherwise nobody will know about this translation.

Also, why are section titles not translated?

**Comment by opusforlife2** [comment]
@B0pol The Readme I linked has:
> Read this in other languages: English, 한국어, 日本語, 简体中文, 正體中文.

We could add that to our Readme.

**Review by Stypox — APPROVED** [review]
Thank you!

**Pull request merged**
