### PR TITLE
Some untranslatable string improvements

### PR DESCRIPTION
**Pull request by TacoTheDank**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
- Move untranslatable strings to a donottranslate file (the [most hip file](https://stackoverflow.com/questions/32934292/attribute-translatable-false-to-the-root-resources-element) for strings too cool for multilingualism)
- Update two of the links
- Remove redundant XML attributes in settings_keys (makes them more readable IMO)

#### APK testing 
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

APK probably not needed though.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by litetex — APPROVED** [review]
LGTM

Tested the apk: Works as expected

**Comment by litetex** [comment]
This PR will have conflicts when we merge #2335

**Comment by TacoTheDank** [comment]
It's fine. I can rebase :)

**Review by Stypox — APPROVED** [review]

**Comment by Stypox** [comment]
I just saw there are some untranslatable strings in the `util/Constants.kt` file, too. Maybe you could take them out of that file and move them to `settings_keys.xml`?

**Comment by litetex** [comment]
2 requests from my side:
1. Please wait with merging until #2335 is done as it introduces new untranslatable stuff. It's now nearly finished and will get merged soon (hopefully).
2. This PR needs to be rebased (but better do it after 1. is done).

**Comment by TacoTheDank** [comment]
I will fix the error later.

**Comment by litetex** [comment]
>     1. Please wait with merging until [New streams notifications #2335](https://github.com/TeamNewPipe/NewPipe/pull/2335) is done as it introduces new untranslatable stuff. It's now nearly finished and will get merged soon (hopefully).

Note: I think we should no longer let this PR wait for #2335 because there is currently little progress.

**Comment by TacoTheDank** [comment]
Took way too long lol but updated 👍

**Review by litetex — COMMENTED** [review]
``litetex failed to click on Approved``

**Review by litetex — APPROVED** [review]
> Took way too long lol but fixed👍

Better late than never 😄 

Anyway LGTM, did a quick test, seems to work as expected.

**Pull request merged**
