### PR TITLE
Disable shrinkResources

### PR DESCRIPTION
**Pull request by wb9688**
#### What is it?
- [ ] Bug fix (user facing)
- [ ] Feature (user facing)
- [ ] Code base improvement (dev facing)
- [x] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
Needed for F-Droid reproducible builds. Will make the APK about 20 kB bigger.

#### Agreement
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by opusforlife2** [comment]
Question: as of 0.19.8, is it possible to install all three versions (F-Droid, Newpipe's F-Droid repo, Github releases) over each other?

**Comment by wb9688** [comment]
@opusforlife2: Now F-Droid publishes 2 APKs. F-Droid's F-Droid ≠ F-Droid's F-Droid with our signature ≈ NewPipe's F-Droid = NewPipe's GitHub.

**Comment by opusforlife2** [comment]
Both the F-Droid app and website show just one apk. Which one is it? And where is the other?

**Comment by opusforlife2** [comment]
Oh wait. The website shows 2. What's up with the app, then?

**Comment by wb9688** [comment]
@opusforlife2: F-Droid's app does show both, notice how v0.19.8 appears twice under versions.

**Comment by opusforlife2** [comment]
Ah. Yes. I had to enable "Include incompatible versions". So, just to clarify once more, the apk you publish on Github, the one you publish on your repo, and the one _you send_ to F-Droid (not the one they build themselves) all have the same signature, right?

**Comment by wb9688** [comment]
@opusforlife2: To clarify:

The one we publish on GitHub and our F-Droid are exactly the same. They are signed with v1 and v2 signatures.

The one we send the signatures of to F-Droid is signed with the same signature, but only v1 as F-Droid doesn't support v2 yet.

F-Droid then compiles our APK and checks whether the signature we sent them is correct for that APK they built. If that's the case, they sign it with their signature and publish that APK. Then they also replace their signature with our signature and publish that as well.

**Comment by opusforlife2** [comment]
Thanks. I think this info should be put somewhere on the homepage of the Newpipe website.

**Comment by opusforlife2** [comment]
Oh, by the way, apart from the v2 signature, there's another difference between the F-Droid built apk and yours, right? The update functionality.

**Comment by wb9688** [comment]
@opusforlife2: Nope, that's 100% the same in all APKs, but it checks the signature and only runs with our signature. That does mean it does indeed also run on the one in F-Droid's F-Droid repo with our v1 signature.

**Comment by opusforlife2** [comment]
Should the download URL be configurable now that you can get the update from 3 places?

**Comment by opusforlife2** [comment]
@DI555 here you go. Difference between apks.

**Pull request merged**
