### PR TITLE
Add local playlist to queue when long clicking on 'Background/Popup'

### PR DESCRIPTION
**Pull request by dotvirus**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

Guten Abend,

just a follow-up on my previous PR (https://github.com/TeamNewPipe/NewPipe/pull/2023).
Same functionality, but this time for local playlists.

### CODE REVIEW

**Comment by monirul-bd1** [comment]
NewPipe app do not play video song continuously by Auto Play. Please need to fix it. After one or two song will stop playing.

**Comment by monirul-bd1** [comment]
How can I fix this problem.?

**Comment by monirul-bd1** [comment]
Video song do not change by Auto play .

**Comment by monirul-bd1** [comment]
It is big problem for NewPipe.

**Comment by gkeegan** [comment]
@monirul-bd1 when you make comments please condense them to one message. 

Also, the issue you are describing has nothing to do with this PR as far as I can tell.

**Pull request merged**
