### PR TITLE
Improve playlist header layout: align with info items

### LINKED ISSUE #3937: Playlist has too few padding around header causing misalignments
I did not test if this is also in the current version, but the info should be aligned properly.

_Originally posted by @TobiGr in https://github.com/TeamNewPipe/NewPipe/pull/3930#issuecomment-663591008_

### PR DESCRIPTION
**Pull request by Stypox**
#### What is it?
- [x] Bug fix (user facing)
- [ ] Feature (user facing)
- [ ] Code base improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
This PR changes paddings and margins for elements in the header of local and remote playlists. ~~I noticed the title for local playlists has a different behaviour from that of remote ones, should I make it more consistent?~~ The local playlist title is now consistent with the remote's one.

<table><tr><td></td><td></td></tr></table>

#### Fixes the following issue(s)
Fixes #3937

#### Testing apk
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4987950/app-debug.zip)

#### Agreement
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by TobiGr** [comment]
>  I noticed the title for local playlists has a different behaviour from that of remote ones, should I make it more consistent?

What do you mean exactly?

**Comment by Domiuns** [comment]
This work Well on my phone, playlist button don't make crush

**Comment by Stypox** [comment]
> What do you mean exactly?

@TobiGr the screenshot on the left (local playlist) has a oneline marquee title, while the one on the right (remote) has a 2-line ellipsized title.

**Comment by TobiGr** [comment]
good catch! multi-line seems to be the better thing here. We should be consistent.

**Comment by Stypox** [comment]
@TobiGr done, updated screenshot and debug apk: [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4987950/app-debug.zip)

**Pull request merged**
