### PR TITLE
Code improvement (replacing switch case  using resourceID with if/else)

### PR DESCRIPTION
**Pull request by sauravrao637**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

Replaced switch case with if/else because [resource_id will be non final soon](https://stackoverflow.com/questions/64335374/how-to-resolve-resource-ids-will-be-non-final-in-android-gradle-plugin-version)

#### Fixes the following issue(s)

- Fixes future issues ;)

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Redirion** [comment]
Can you please explain what this improves?

From my understanding I would say replacing if else cascade with switch is a code improvement, not the other way around. A switch case is also internally lesser burden on CPU as it internally relies on a map, which is easier to track for schedule optimizations than conditional code branching.

**Comment by sauravrao637** [comment]
Hi @Redirion 
Please have a look at the answers in the link attached in this PR ("resourceId will be non final soon").

**Comment by Redirion** [comment]
http://tools.android.com/tips/non-constant-fields

This is only affecting library projects. NewPipe is not a library project.

**Comment by sauravrao637** [comment]
I didn't know it will just be affecting library projects
but still shouldn't the warnings be addressed as closely as possible?

**Comment by Redirion** [comment]
Fixing a false warning does not sound useful to me. But we could disable the warning: https://stackoverflow.com/a/64377108

**Comment by sauravrao637** [comment]
But like in ErrorActivity (line 192) also if/else has been used instead of switch .

**Comment by Redirion** [comment]
> 
> 
> But like in ErrorActivity (line 192) also if/else has been used instead of switch .

this could be improved by a switch case then. Would you like to create a PR with disabling that false warning and improving if/else to switch case?

**Comment by sauravrao637** [comment]
Sure , I'll do it :) @Redirion

**Pull request closed without merging**
