### PR TITLE
Added feature to open NewPipefrom the share menu of YT.

### PR DESCRIPTION
**Pull request by SUguy**
NewPipe can now open videos from the share menu of YT. This is the most convenient and fastest way. Shouldn't this be included in the main app?

### CODE REVIEW

**Comment by timofonic** [comment]
I'm just an user. What do you mean? YT app or site? I fail to understand it.

**Comment by theScrabi** [comment]
He means to put the feature of this [app](https://github.com/TeamNewPipe/ShareWithNewPipe) into main NewPipe app.

**Comment by SUguy** [comment]
Yeap... Shouldn't it be included in the main app....?

**Comment by teod0r** [comment]
I think that it should be included in the app.
For those who want to just download, there should be an option in settings with 3 options:
* always download
* always play video
* always ask if  download or play

**Comment by SUguy** [comment]
@theScrabi I back @teod0r. Can you please conduct a **poll** to collect user opinion.

**Comment by theScrabi** [comment]
All right now. You want it you get it, but I did it my self though :)

**Pull request closed without merging**
