### PR TITLE
Downloader fixes

### LINKED ISSUE #247: Downloads via cell network even though WiFi is available
- NewPipe 0.7.6
- Android 6.0.1_r22
- WiFi > advanced settings > avoid poor connections: OFF
- WiFi connection established
- Data usage > restrict app background data: ON

I started a video-download and half a minute later NewPipe had used up my high speed cell data volume :(

I'm not sure it is actually NewPipe's fault. How could that happen given the settings mentioned above?

If that is indeed possible I suggest a setting that allows the user to limit network usage to WiFi only. 

Thanks in advance!

### LINKED ISSUE #274: Length of downloaded audio not saved
I think the length of downloaded audio files is not being saved with the file. As a result, many audio players just show the length as "0:00" or "Buffering..." and seeking the audio forward/backward is not possible. Can this be fixed?
screenshot_2016-04-19-14-03-16_naman14 timber

### LINKED ISSUE #281: [FR] Download with NewPipe intent
In addition to the "Open with NewPipe app" option, add option to download videos in the background automatically from links.

This could work with #95.

### LINKED ISSUE #645: Wrong order of downloads after restarting the app
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.

When you download a video and then open the download dialog, the last downloaded video or audio is shown in the upper left corner.  After restarting the app the order of the items in the downloads view has changed and the downloads don't seem to be listed in a logical order (download date, file name, file size or file extension).

As I did some tests on this I recognized some other issues with this downloads view. Normally you can differentiate whether a file is a video or audio by the icon and the color of the tile. This works fine, except you have a `.web` file. Because these files can provide a video and an audio stream **or** only an audio stream, the video icon is displayed even when if there is no video stream. Is it possible to find out whether a video stream exists in this file?

I also wondered why we color all tiles with `.3gp` files different then the others. Is there a reason for it?

Furthermore we could also add a text like `This is the place where your can control your downloaded files once you have started a download.` to the download activity if no download is listed.

### LINKED ISSUE #1262: [feature] Remuxing for video-only streams for downloading
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

When downloading, it would be nice if for things like 1080p60, a script could run to stitch the audio and video together in an MKV or some sort to keep things intact.

### LINKED ISSUE #1730: Download location settings change requires app restart
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

A slight annoyance that I noticed:

1. Set download location to SD-Card
2. Try and download a video
3. Get notification that download to SD-card is not supported yet, *confirm reset of download location*
4. Try and download again, get the same notification
5. Check settings, it's *already changed to internal storage*
5. Restart app through the task manager and it works

Currently running 14.1 from F-Droid on Lineage OS

### LINKED ISSUE #1906: Share downloaded video file
Just put a share item on completed downloads three dots menu to turn possible share the video file directly (not link) to other apps. Just have play - delete - checksum. I need share - play - delete - checksum. Thanks!

### LINKED ISSUE #1952: On long press on video, add Download option.
I woul like you to add download option to long press menu on item. What do you think about it?

### LINKED ISSUE #2006: Doesn't respect metered wifis
The app doesn't treat metered wifis as mobile data.

https://developer.android.com/reference/android/support/v4/net/ConnectivityManagerCompat#isActiveNetworkMetered(android.net.ConnectivityManager)

### LINKED ISSUE #2063: [Suggestion]Tell me if I've already downloaded a video when I go to download it so I don't download it twice.
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

### LINKED ISSUE #2072: All downloads start as "Queued"
- [ x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ x] I checked if the issue/feature exists in the latest version.
- [ n/a] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

All downloads are added as queued when added from share menu or from main application, is this intended behavior? 
It always downloaded as soon as added in 0.14.
I'm assuming i'm not the only one having this issue

I add sometimes 20 to 30 or more videos to download at one time since i just go through my sub feed and download anything that interests me on my wifi, for later watching at work where i have 0 cell signal. Having to go into the newpipe application and manually start each download is a real pain. 

I've tried unchecking the "queued" checkbox and it doesn't seem to have any effect whether i do it on a single download or each one. New downloads always start as "queued" I was waiting for an update hoping it would be fixed but still have this issue with 0.15.1. An option in the settings at least would be nice since i understand why this would be default behavior in certain use cases, but having no way to undo or change this behavior is kinda counter intuitive.

Assuming this is somehow related to #457 but this behavior only started with 0.15 as a regression maybe?

### LINKED ISSUE #2077: Checksum bug newpipe
MD5 bug
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ IT
* __Service:__ none
* __Version:__ 0.15.1

<details><summary><b>Crash log</b></summary><p>

```
java.lang.ClassCastException: org.schabi.newpipe.App cannot be cast to android.app.Activity
	at us.shandian.giga.ui.adapter.MissionAdapter$ChecksumTask.<init>(MissionAdapter.java:721)
	at us.shandian.giga.ui.adapter.MissionAdapter.handlePopupItem(MissionAdapter.java:489)
	at us.shandian.giga.ui.adapter.MissionAdapter.access$200(MissionAdapter.java:68)
	at us.shandian.giga.ui.adapter.MissionAdapter$ViewHolderItem.lambda$buildPopup$2(MissionAdapter.java:700)
	at us.shandian.giga.ui.adapter.-$$Lambda$MissionAdapter$ViewHolderItem$WMTXzvtjV6uhlyLXNG5QCw_ELrY.onMenuItemClick(lambda)
	at android.widget.PopupMenu.onMenuItemSelected(PopupMenu.java:142)
	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:735)
	at com.android.internal.view.menu.SubMenuBuilder.dispatchMenuItemSelected(SubMenuBuilder.java:81)
	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:149)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:874)
	at com.android.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:156)
	at android.widget.AdapterView.performItemClick(AdapterView.java:298)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1128)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:2812)
	at android.widget.AbsListView.onTouchEvent(AbsListView.java:3583)
	at android.view.View.dispatchTouchEvent(View.java:7262)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2235)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1932)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1946)
	at android.widget.PopupWindow$PopupViewContainer.dispatchTouchEvent(PopupWindow.java:1592)
	at android.view.View.dispatchPointerEvent(View.java:7442)
	at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3610)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3538)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4790)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4750)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4902)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:179)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:125)
	at android.os.Looper.loop(Looper.java:140)
	at android.app.ActivityThread.main(ActivityThread.java:5297)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	at dalvik.system.NativeStart.main(Native Method)

```
</p></details>
<hr>

### LINKED ISSUE #2087: [0.15.1] Downloading/Muxing files cause App crash
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Downloads of need-to-be-muxed (1080p) videos crash the app right at the end of muxing, leaving the file broken:

Filename.mp4

Code 1007
Post-processing failed

java.lang.Runtime.Exception: stopped unexpectedly

Affected version is 0.15.1, 0.15.0 doesn't have this.
I know the guidelines say we shouldn't create issues here referring to crashes, but here's the catch:

Unfortunately, no .json is generated to be emailed for further investigation, so I just can describe what to do to reproduce the bug:

1. Search/open/go to any video you'd like to download that's available in at least 1080p (requires muxing, 720p versions can be downloaded "as is" which isn't usable for this scenario).

2. Tap on download, choose 1080p, hit OK.

3. Wait for the file to be downloaded, then muxed.

4. Experience a sudden FC right when muxing reaches 99,9%

5. Check the file and see that it's broken beyond repair. (Doesn't play in any player, tried VLC, MX ...)

### LINKED ISSUE #2114: WebM muxer fails for some videos
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

The postprocessing of some downloaded WebM videos fails. 
One video where this reproducibly fails is https://www.youtube.com/watch?v=W5SdgWRxGsw
I tested at least 1080p and 480p.

The stack trace produced at 1080p is this:
```
02-10 23:16:01.204 30803  9084 E DownloadMission: Post-processing failed. algorithm = webm  args = [  ]
02-10 23:16:01.204 30803  9084 E DownloadMission: java.io.EOFException: parser go beyond limits of the Element. type=0xf43b675 offset=52866594 size=574621 position=98017261
02-10 23:16:01.204 30803  9084 E DownloadMission:       at org.schabi.newpipe.streams.WebMReader.ensure(WebMReader.java:212)
02-10 23:16:01.204 30803  9084 E DownloadMission:       at org.schabi.newpipe.streams.WebMReader.access$500(WebMReader.java:15)
02-10 23:16:01.204 30803  9084 E DownloadMission:       at org.schabi.newpipe.streams.WebMReader$Segment.getNextCluster(WebMReader.java:433)
02-10 23:16:01.204 30803  9084 E DownloadMission:       at org.schabi.newpipe.streams.WebMWriter.getNextBlockFrom(WebMWriter.java:350)
02-10 23:16:01.204 30803  9084 E DownloadMission:       at org.schabi.newpipe.streams.WebMWriter.build(WebMWriter.java:227)
02-10 23:16:01.204 30803  9084 E DownloadMission:       at us.shandian.giga.postprocessing.WebMMuxer.process(WebMMuxer.java:37)
02-10 23:16:01.204 30803  9084 E DownloadMission:       at us.shandian.giga.postprocessing.Postprocessing.run(Postprocessing.java:103)
02-10 23:16:01.204 30803  9084 E DownloadMission:       at us.shandian.giga.get.DownloadMission.doPostprocessing(DownloadMission.java:612)
02-10 23:16:01.204 30803  9084 E DownloadMission:       at us.shandian.giga.get.DownloadMission.notifyFinished(DownloadMission.java:379)
02-10 23:16:01.204 30803  9084 E DownloadMission:       at us.shandian.giga.get.DownloadRunnable.run(DownloadRunnable.java:176)
02-10 23:16:01.207 30803  9084 E DownloadMission: notifyError() code = 1007
```

On 480p it is quite similar:
```
02-10 23:22:45.460 30803 12960 E DownloadMission: Post-processing failed. algorithm = webm  args = [  ]
02-10 23:22:45.460 30803 12960 E DownloadMission: java.io.EOFException: parser go beyond limits of the Element. type=0xf43b675 offset=14396281 size=154168 position=130246593
02-10 23:22:45.460 30803 12960 E DownloadMission:       at org.schabi.newpipe.streams.WebMReader.ensure(WebMReader.java:212)
02-10 23:22:45.460 30803 12960 E DownloadMission:       at org.schabi.newpipe.streams.WebMReader.access$500(WebMReader.java:15)
[same as above]
```

It also fails for https://www.youtube.com/watch?v=ark3tT2WPSw with the same stack trace.

Version tested: 0.15.1
Android Version: 8.1

### LINKED ISSUE #2145: Unable to write SD card, although another app such as Amaze (from F-Droid) can
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Hi,
NewPipe seems to be unable to write to the SD card while another app such as Amaze v3.3.2 (from F-Droid) can, why not have a look at the way they are doing it despite the Android permission restrictions : 

```
{
"user_action": "ui error",
"request": "App crash, UI failure",
"content_language": "GB",
"service": "none",
"package": "org.schabi.newpipe",
"version": "0.15.1",
"os": "Linux Android 5.0 - 21",
"time": "2019-02-23 15:06",
"exceptions": [
"java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.\n\tat android.support.v7.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:555)\n\tat android.support.v7.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:518)\n\tat android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:466)\n\tat android.support.v7.app.AppCompatDialog.setContentView(AppCompatDialog.java:94)\n\tat android.support.v7.app.AlertController.installContent(AlertController.java:232)\n\tat android.support.v7.app.AlertDialog.onCreate(AlertDialog.java:279)\n\tat android.app.Dialog.dispatchOnCreate(Dialog.java:463)\n\tat android.app.Dialog.show(Dialog.java:288)\n\tat us.shandian.giga.ui.adapter.MissionAdapter.showError(MissionAdapter.java:438)\n\tat us.shandian.giga.ui.adapter.MissionAdapter.handlePopupItem(MissionAdapter.java:466)\n\tat us.shandian.giga.ui.adapter.MissionAdapter.access$200(MissionAdapter.java:68)\n\tat us.shandian.giga.ui.adapter.MissionAdapter$ViewHolderItem.lambda$buildPopup$2(MissionAdapter.java:700)\n\tat us.shandian.giga.ui.adapter.-$$Lambda$MissionAdapter$ViewHolderItem$WMTXzvtjV6uhlyLXNG5QCw_ELrY.onMenuItemClick(lambda)\n\tat android.widget.PopupMenu.onMenuItemSelected(PopupMenu.java:201)\n\tat com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)\n\tat com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:155)\n\tat com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)\n\tat com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)\n\tat com.android.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:218)\n\tat android.widget.AdapterView.performItemClick(AdapterView.java:334)\n\tat android.widget.AbsListView.performItemClick(AbsListView.java:1536)\n\tat android.widget.AbsListView$PerformClick.run(AbsListView.java:3669)\n\tat android.widget.AbsListView$3.run(AbsListView.java:5593)\n\tat android.os.Handler.handleCallback(Handler.java:739)\n\tat android.os.Handler.dispatchMessage(Handler.java:95)\n\tat android.os.Looper.loop(Looper.java:145)\n\tat android.app.ActivityThread.main(ActivityThread.java:5944)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat java.lang.reflect.Method.invoke(Method.java:372)\n\tat com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)\n"
],
"user_comment": ""
}
```

### LINKED ISSUE #2152: M4A audio download and Dash header issues
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

When I download audio from YouTube it's an AAC with a "dash" header.

Contrary to other apps like TubeMate, when there isn't any issue playing the songs, files downloaded with NewPipe shows some issues :

- When I skip time on a track on my music player,   it seems like there isn't some sort of "keyframe". e.g, if I want to go to 00:53, it will warp to 00:50.

- When the audio track is ending, the player freezes for some seconds before reacting againg.

Anyway, that header is strange, and it'd be better to use a simpler M4A header/codec.

### LINKED ISSUE #2190: Video Download Glitch
This happens when I try and download a video once it gets to the post-processing part. See screenshot [screenshot.](http://tinypic.com/r/30c3r4p/9)

### LINKED ISSUE #2229: Error Downloading When Using Quotes in Filename
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

When downloading a video with quotation marks in the final filename, NewPipe throws an error. Specifically:
`Code: 1002
java.io.IOException: Invalid argument.`

Removing the quotes from the final filename lets it download perfectly. This is obviously as a result of quotes not getting the proper escape character to let them pass as part of the filename argument, but they shouldn't need to be exempted anyway since both Windows and *nix filesystems don't support quotation marks in the filenames.

The real issues here are:
1. Quotes need to be put on the blacklist for filenames and set to automatically replace them with underscores like slashes, backslashes, and other invalid characters.
2. Some sort of detection method needs to be implemented to prevent users from accidentally entering an invalid character into the filename and thereby causing this error which most people would be unable to make sense of.

### LINKED ISSUE #2230: No support for the "SD Card Write Access" on Android 6.0
The app doesn't ask for this permission at the storage selection of the download section, if you pick an SD folder this result an "error 1003: action denied by system"(sort of)
Code: Java.io.IOException:open failed: EACCESS (permission denied)
When you try to download something.

### LINKED ISSUE #2246: Icons for Icon and List
The icons for switching between list and icon are switched. As you can see, I am already in list mode but the icon is a list.  
photo_2019-03-23_19-28-43

### LINKED ISSUE #2264: Newpipe Stuck at post-processing donwloaded videos
- [] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

Hi,
So I downloaded the following video through new pipe;
https://www.youtube.com/watch?v=WShlkAOI7XQ
and after downloading the video the newpipe is stuck at post processing at 0%.
It's been an hour.
The video does not have any audio so I was thinking is there anyplace else where new pipe saves the audio before merging it with the video.

### LINKED ISSUE #2279: Code: 1007 Error post processing failed.
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.
IMG-20190410-WA0000
It is happening only, while downloading 480p, 720p, 1080p video files.

### PR DESCRIPTION
**Pull request by kapodamy**
Main changes:
* use the "Error Reporter" for non-http errors
* implement "metered networks"
* add buttons in "Downloads" activity to start/pause all pending downloads, ignoring the queue flag or if the network is "metered"
* add workaround for VPN connections and/or network switching.
* fix missing offset for KaxCluster (WebMWriter.java), manifested as no thumbnails on file explorers
* fixes #247 close #2063 (already implemented) 

Download queue:
* remember queue status, unless the user pause the download (un-queue)
* semi-automatic downloads, between networks. Effective if the user create a new download or the downloads activity is starts
* allow enqueue failed downloads
* new option, queue limit, enabled by default. Used to allow one or multiple downloads at same time
* hopefully fixes the #2072 #2290 issues

Miscellaneous:
* fix crash while selecting details/error menu (my mistake)
* allow overwrite paused downloads
* fix wrong icons for grid/list button in downloads. fixes #2246 
* add share option. close #1906
* check if the WiFi is metered. close #2006 
* correct misspelled words in strings.xml (es) (cmn)
* fix crash during device shutdown
* declare downloads database scheme in the database doc
* fix double-quote escaping the download filename. fixes #2229 

Muxers:
* new mp4 muxer (from dash) with this, muxing on Android 7 is possible now!!!  fixes #2087 fixes #2279 fixes #274 
* strip m4a DASH files to normal m4a format (for youtube) **works on winamp** :smiley: . close #2152 
* download the audio stream first
* close #1262 

Storage changes:
* warn to the user if is choosing a "read only" download directory (for external SD Cards), useless is patched :)
* deal with "insufficient storage" error in downloads
* implement **Storage Access Framework**. resolves #2230 
* SAF Tree API support on Android Lollipop or higher
* storage helpers: StoredDirectoryHelper & StoredFileHelper
* best effort to handle any kind of SAF errors/exceptions
*  fixes #2114 fixes #2190 fixes #1730 fixes #2264

Downloader related issues that are already fixed from other PRs:
* close #281 close #645 close #1952 close #2077

Screenshots
Screenshot_1555291900
Screenshot_2019-04-19-15-29-27Screenshot_1555697640
Screenshot_1555292529 Screenshot_1555293210

giga

### CODE REVIEW

**Comment by TobiGr** [comment]
@kapodamy  Thanks for your work! Is there any specific reason for closing this PR?

**Comment by Flashwalker** [comment]
Downloads doesn't auto starts any more until call menu for each download and select start it. Is it bug or feature?

**Comment by kapodamy** [comment]
@TobiGr yes, needs to polish some things and i was very busy

**Comment by kapodamy** [comment]
implements #2230 (WIP)

**Comment by TobiGr** [comment]
That's good to hear! 👍 
I am working on some the documentation about the database atm.  @theScrabi created the EERM for the "normal" app database some time ago by (see #2136 for some info on the tool he used). Can you please also add the scheme for the download database to the `assets` directory once you have finished the PR? This would be time saving for me and I guess just five minutes work for you as you refactored the db in the lasts month.
Feel free to ping us once your done with this huge PR so we can start testing :)

**Comment by kapodamy** [comment]
ready for review and testing

**Comment by kapodamy** [comment]
@Flashwalker 50/50 the implementation is not well thought out

**Comment by TobiGr** [comment]
Nice work 👌 Tons of bugfixes, improvements and new features! Can you please provide an APK so other people can start testing, too?

I want to release 0.16.2 soon, so I will not review this in detail soon. But from taking a look at the screenshots and reading the description, I'd like to raise some points for discussion.

1. You posted the table which shows the differences between SAF-, SAF and Java IO. This is good for us to understand the advantages and new features. However, how can users understand what is best for them? Do you use an algorithm to detect whether SAF or IO is the best thing to use or is this completely dependent on the settings entry? If yes, how can users understand what to choose? 

2. IIRC the clear button in the downloads wipes the database, but not the downloads from the phone. If this is still the case, we should change the description of the dialog.

**Comment by theScrabi** [comment]
@kapodamy @TobiGr well SAF is usefull if you want to save something on the SD card, while java IO can be used for saving something on the app internal storage as well as on the emulated sdcard (internal storage). As we do not need to save downloads to the app internal storage I suggest to move over to SAF completely. The user should not be getting in touch weather he wants to use Java IO or SAF.

**Comment by TobiGr** [comment]
> The user should not be getting in touch weather he wants to use Java IO or SAF.

That's exactly what I meant.

**Comment by kapodamy** [comment]
@TobiGr 
1. I had not thought about it. SAF should be the used by default and keep java IO for older devices
2. yes the button does not delete the files, only clear the database. maybe it was not understood why I do not speak english or if there is a guideline that says the opposite.

**Comment by theScrabi** [comment]
Well SAF was introduced with android 4.4 in theorie we can remove javaIO, the question is just, how much do we want to keep for the legacy app. Id be for removing, javaIO, the legacy app should then use an older version of the downloader. What do you think?

**Comment by kapodamy** [comment]
@theScrabi keep javaIO. SAF directory API is supported on older devices.
Also, with lastest changes javaIO only will be used on older devices.

kitkat:
Screenshot_2019-04-19-15-29-27
lollipop or newer:
Screenshot_1555697640

**Comment by kapodamy** [comment]
pr rebased (near dead) done

**Comment by TobiGr** [comment]
Thanks, I'll test and merge once 0.16.2 is released. So hopefully this weekend.

**Comment by TobiGr** [comment]
Hey @kapodamy,

now that 0.16.2 is out, I have some time to take at the open PRs. Unfortunately, when trying to download a video, I get a crash immediately. This happens when I press the download button after opening a video detail page. Especially, the second one occurs quite often.
JFYI: I rebased your work. You can find the it [on my fork](https://github.com/TobiGr/NewPipe/tree/ps-branch). Feel free to use it.

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ DE
* __Service:__ none
* __Version:__ 0.16.2
* __OS:__ Linux ,release-keys 6.0 - 23


<details><summary><b>Crash log</b></summary><p>

```
java.lang.RuntimeException: Unable to bind to service us.shandian.giga.service.DownloadManagerService@43a4c49 with Intent { cmp=org.schabi.newpipe.debug/us.shandian.giga.service.DownloadManagerService }: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not for an application
	at android.app.ActivityThread.handleBindService(ActivityThread.java:2935)
	at android.app.ActivityThread.-wrap2(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
Caused by: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not for an application
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:583)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:310)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
	at android.app.Dialog.show(Dialog.java:319)
	at us.shandian.giga.service.DownloadManagerService.onBind(DownloadManagerService.java:296)
	at android.app.ActivityThread.handleBindService(ActivityThread.java:2922)
	... 8 more
android.view.WindowManager$BadTokenException: Unable to add window -- token null is not for an application
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:583)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:310)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
	at android.app.Dialog.show(Dialog.java:319)
	at us.shandian.giga.service.DownloadManagerService.onBind(DownloadManagerService.java:296)
	at android.app.ActivityThread.handleBindService(ActivityThread.java:2922)
	at android.app.ActivityThread.-wrap2(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

```
</p></details>
<hr>

## Exception
* __User Action:__ ui error
* __Request:__ 
* __Content Language:__ GB
* __Service:__ YouTube
* __Version:__ 0.16.2
* __OS:__ Linux ,release-keys 6.0 - 23


<details><summary><b>Crash log</b></summary><p>

```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:2080)
	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:2106)
	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:683)
	at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:637)
	at android.support.v4.app.DialogFragment.show(DialogFragment.java:144)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.openDownloadDialog(VideoDetailFragment.java:1198)
	at org.schabi.newpipe.MainActivity.onRequestPermissionsResult(MainActivity.java:432)
	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:6567)
	at android.app.Activity.dispatchActivityResult(Activity.java:6446)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3716)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3763)
	at android.app.ActivityThread.-wrap16(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1403)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

```
</p></details>
<hr>

**Comment by TobiGr** [comment]
@kapodamy Did you fix these two bugs? I cannot reproduce them with the current commits, but also don't see a commit which fixes something. Did you squashed the fixes and the old commits?

**Comment by kapodamy** [comment]
@TobiGr  they are new bugs, related to this pr

**Comment by TobiGr** [comment]
About the second bug, I cannot reproduce it either. I'd suggest to merge this and then bring out a release candidate for 0.17 soon, so we have a wider range of devices and android versions to test with.
@kapodamy  What do you think?

**Comment by kapodamy** [comment]
ok, sound good

**Comment by theScrabi** [comment]
@kapodamy There is still abounty open that has the size of about 300$ concerning this toppic:
https://www.bountysource.com/issues/53420964-refactor-download-manager

Related issue: https://github.com/TeamNewPipe/NewPipe/issues/962

If we don't pay it out the money is lost so... :D Your interested?

**Comment by TobiGr** [comment]
@theScrabi You are absolutely right. @kapodamy has done an anwesoe job :+1:

**Comment by kapodamy** [comment]
@theScrabi yes

**Comment by theScrabi** [comment]
You may need to claim the money so we can say yes to the claim.

**Pull request merged**
