### PR TITLE
Clicking on title should open video details

### LINKED ISSUE #3700: Click on title should in background player should open video details
#### Describe the feature you want

I'd like that when i click on the title in background player — **i'm not talking about the queue but the title just above controls** — it leads me to video detail page
#### Is your feature request related to a problem? Please describe it

People must know that they should long press on the video in queue, click open details. this way would make it easier
#### Additional context

i'm talking about the red circle
image
image

#### How will you/everyone benefit from this feature?

It will make NewPipe easier to use!

### PR DESCRIPTION
**Pull request by budde25**
#### What is it?
- [ ] Bug fix (user facing)
- [x] Feature (user facing)
- [ ] Code base improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Clicking the video title on the Main Player and Background Player opens the details page for that video.

#### Fixes the following issue(s)

- fixes #3700 

#### Testing apk

[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4839930/app-debug.zip)

#### Agreement
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by budde25** [comment]
@B0pol 

> It doesn't work on Android TV, I believe it's because you have removed `android:focusable=true`

I added focus back in for the children so that it should be selectable from from a device without a touchscreen. I also realized I forgot to make the changes to the large-land.xml which might be the reason too. I don't have an android TV to test on but plugging a keyboard into my phone did work. I've updated the testing apk.

> And please next time compress the apk with a zip file, don't just rename the file extension. 1) compression means less to download 2) makes more sense


Thanks for the tip! For some reason I was under the impression that .apk files where already compressed. I will make sure to do that going forward!

**Comment by Stypox** [comment]
<sub>Another tip: use [closing keywords](https://help.github.com/en/articles/closing-issues-using-keywords) when pointing out a fixed issue, so that GitHub closes it automatically on merge</sub>

**Comment by hunkjazz** [comment]
This is a good PR, but needs enhancement on:

- main player;
- popup player.

#### Main Player

When clicking on title, while using the main player, this happens:

1. main player closes;
2. details page is shown.

I don't think this is quite a good UX.
Instead, this should be the flow:

- switch to popup player;
  - if phone is in portrait:
      - fit popup's width to phone's;
      - move popup to the top of the screen.
- details page is shown underneath popup;
- user expands popup (back to main player);
- NewPipe restores and saves popup width and position back what it was before user clicked to see details;
- page that was active before replacement by details page is restored.

#### Popup Player

I think it's important to add a details icon under _expand_ icon. In this 
way popups opened by other apps can redirect users to further details, 
for example.

This same icon can be hidden, if popup gest too small.

This icon should be hidden, when clicking to see details in main player (if former enhancement suggestion is accepted).

**Comment by MD77MD** [comment]
I think this should be looked at after the unified player feature

**Comment by MD77MD** [comment]
this has suddenly became less useful after unified player or am I missing something?

**Comment by TobiGr** [comment]
@MD77MD  Correct, turning the screen opens the details now.
@budde25 Thank you for your contribution!

**Comment by TobiGr** [comment]
Oh, my bad. This is still a good feature.
@budde25 Please rebase your PR.

**Comment by MD77MD** [comment]
@TobiGr sorry but I don't get it. when could you use this? title do not show up in pop mode,  in portrait mode info is already there. that's the same for background mode. the only time you can click title is in landscape mode in which pressing the back button will give you the same thing.

However, a new implementation of this feature would be to add a info button in the pop-player. the button when pressed can take us back (reopen) the video info. now that's useful. 

p.s: another implementation would be in notification. when pressing on the video title the video info would show up instead of play queue. which I would rather not but mentioned it for argument sake.

**Comment by opusforlife2** [comment]
The lad has a point. Even for landscape mode, there is now the ability to swipe up on the fullscreen button to view video details (thanks, avently!) . And if system rotation is unlocked, then the user can just turn the phone to see them.

**Comment by MD77MD** [comment]
>Even for landscape mode, there is now the ability to swipe up on the fullscreen button to view video details (thanks, avently!) 

@opusforlife2 please tell me how to enable this😰! omg newPipe is becoming sooo awesome. (thanks everyone👏).

**Comment by justanidea** [comment]
@MD77MD See the end of #4121

**Comment by opusforlife2** [comment]
@justanidea You could always link directly to the relevant comment.

@MD77MD https://github.com/TeamNewPipe/NewPipe/issues/4121#issuecomment-674752068

**Comment by justanidea** [comment]
Ok i didnt think my github client actually could, but it does
TY

**Comment by MD77MD** [comment]
@justandidea @opusforlife2
 thank you guys

**Comment by hunkjazz** [comment]
@MD77MD @opusforlife2 

Would you happen to have a link to download a working `apk` with the unified player?

**Comment by opusforlife2** [comment]
@hunkjazz https://github.com/TeamNewPipe/NewPipe/projects/17#card-42918515

**Comment by Stypox** [comment]
Yeah, I don't see why this should be merged, now that we have unified ui @TobiGr

**Comment by budde25** [comment]
@Stypox Yeah that makes sense to me

**Comment by mhmdanas** [comment]
@budde25 I'm closing this PR since it seems like it's not necessary anymore, but please make comment if I turn out to be wrong so I can re-open it. Thanks!

**Pull request closed without merging**
