### PR TITLE
youtube-dl on newpipe

### PR DESCRIPTION
**Pull request by yausername**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

I am pretty sure this is never getting merged but I tried it nonetheless.

So I used [youtubedl-android](https://github.com/yausername/youtubedl-android) to run youtube-dl on android. It is slow since it runs the python executable on android.
Now newpipe can open all [youtube-dl supported sites](https://rg3.github.io/youtube-dl/supportedsites.html).

Demo

### CODE REVIEW

**Comment by FaizKhan5** [comment]
Showing error on Dailymotion and other sites videos.

**Comment by yausername** [comment]
> Showing error on Dailymotion and other sites videos.

What error?

**Comment by FaizKhan5** [comment]
{
   "user_action": "something",
   "request": "null",
   "content_language": "PK",
   "service": "none",
   "package": "org.schabi.newpipe.debug",
   "version": "0.15.1",
   "os": "Linux HUAWEI\/RNE-L21\/HWRNE:8.0.0\/HUAWEIRNE-L21\/334(C185):user\/release-keys 8.0.0 - 26",
   "time": "2019-02-17 16:24",
   "exceptions": [
      "java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.schabi.newpipe.extractor.linkhandler.LinkHandlerFactory.acceptUrl(java.lang.String)' on a null object reference\n\tat org.schabi.newpipe.extractor.StreamingService.getLinkTypeByUrl(StreamingService.java:315)\n\tat org.schabi.newpipe.extractor.NewPipe.getServiceByUrl(NewPipe.java:75)\n\tat org.schabi.newpipe.RouterActivity.lambda$handleUrl$0(RouterActivity.java:130)\n\tat org.schabi.newpipe.-$$Lambda$RouterActivity$jGbV3sDp3V_oonJa1z1jLD1TKkg.call(Unknown Source:4)\n\tat io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:43)\n\tat io.reactivex.Observable.subscribe(Observable.java:12090)\n\tat io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)\n\tat io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)\n\tat java.lang.Thread.run(Thread.java:784)\n"
   ],
   "user_comment": ""
}

**Comment by yausername** [comment]
how did you build the apk? What extractor version are you using?

**Comment by FaizKhan5** [comment]
I simply build apk from your fork, I don't know what extractor version it is.

**Comment by yausername** [comment]
I think you might have built the wrong branch. what is the output of `git branch`?

**Comment by yausername** [comment]
Can you try this prebuilt [apk](https://anonfile.com/g0Den0ubbc/app-debug_apk) ?

**Comment by FaizKhan5** [comment]
Why this apk size is big from normal apk and also VirusTotal shows it as a Trojan/Win32.Zpevdo ?

Check this: https://www.virustotal.com/#/file/9df5856a6d91e6615372fed1490e59b06cb48c82a35f0935c8d9f7063118dbea/detection

**Comment by yausername** [comment]
Well you can build apk yourself. Just make sure that you are building from branch `youtubedl`
Run `git checkout youtubedl` before building. 
Also, the apk size is big because it has python and youtube-dl executables inside it.

**Comment by theScrabi** [comment]
Its interesting, but youtube-dl only partly solves our porblem, and it bloads our app. So while i think indeed it is cool, it will not be merged.

**Comment by FaizKhan5** [comment]
>  but youtube-dl only partly solves our porblem, and it bloads our app.

how ?

**Comment by theScrabi** [comment]
But to be honest this is kind of very cool :thinking:

**Comment by yausername** [comment]
Here is the debug apk. Size is big because of python and youtube-dl inside it.
[youtubedl-on-newpipe.zip](https://github.com/TeamNewPipe/NewPipe/files/2882383/youtubedl-on-newpipe.zip)

**Comment by utack** [comment]
I think you should just split this off, new icon new name  
An app that can play all sorts of streams with Youtube-dl and a good UI would definitely be amazing on android

**Comment by theScrabi** [comment]
I've tried it for a while, and I think I like it. However if we want to really include this wed have to talk about several issues first.

- How can we get complient with fdroid: The python binaries should be pulled from a place where fdroid is ok with
- Multiarch support: You added python binaries for aarch64 we however should also think about x86 and amrv6.
- Integration with NewPipe extractor: Best situation, take the newpipe extractor to retrive playlists etc, and youtube-dl to get the streams (maybe). However where should youtube-dl be placed then. In the extractor (if that is possible), in the frontend (like it is now), or should your youtube-dl library utalize the extractor and the frontend only knows youtube-dl then?

**Comment by theScrabi** [comment]
Or should we go another direction. @karyogamy wanted to make our player a separate module. You could try to create a separate app and utilize our player.

**Comment by yausername** [comment]
> Or should we go another direction. @karyogamy wanted to make our player a separate module. You could try to create a separate app and utilize our player.

I am not sure about creating an app but I like the idea of a separate player module. The player module  could use youtube-dl to get streams from url which could then be used in foss apps like redreader, mastalab, etc.

**Comment by yausername** [comment]
> Multiarch support: You added python binaries for aarch64 we however should also think about x86 and amrv6.

I agree. FYI, around 98-99% devices are covered with armeabi-v7a and arm64-v8a architectures. [source](https://android.stackexchange.com/questions/186334/what-percentage-of-android-devices-runs-on-x86-architecture)



> Integration with NewPipe extractor: Best situation, take the newpipe extractor to retrive playlists etc, and youtube-dl to get the streams (maybe). However where should youtube-dl be placed then. In the extractor (if that is possible), in the frontend (like it is now), or should your youtube-dl library utalize the extractor and the frontend only knows youtube-dl then?

NewPipeExtractor is a pure java library while youtubedl-android is an android library, so it not possible to place youtubedl-android in NewPipeExtractor in its current form. Placing youtube-dl in the frontend is the only option for now.

**Comment by theScrabi** [comment]
I see :/

**Pull request closed without merging**
