### PR TITLE
Add some stuff to `paths-ignore`

### PR DESCRIPTION
**Pull request by mhmdanas**
#### What is it?
- [x] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
Add `.github/FUNDING.yml` and everything in `doc` to `paths-ignore`.

#### APK testing 
Not needed.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by litetex — APPROVED** [review]
LGTM

Btw, I think we could also ignore all markdown files...

**Comment by mhmdanas** [comment]
> Btw, I think we could also ignore all markdown files...

Sure, should I push a commit here?

**Comment by litetex** [comment]
> Sure, should I push a commit here?

Feel free to do so.
If you open another branch I'm also fine 😄

**Comment by mhmdanas** [comment]
> If you open another branch I'm also fine 😄

I'll do that then. Merge this?

**Comment by litetex** [comment]
> Guess we should wait till 0.22.0 is out...

Why should we?
The ``dev``-branch is not blocked and I see no problems that could affect the release.
So merging it is.

**Comment by mhmdanas** [comment]
@litetex indeed, but it creates more work for a certain blog post author, which is why I thought we may want to avoid it.

**Comment by Poolitzer** [comment]
they said one. Now I wonder who from us mhmdanas meant...

**Comment by opusforlife2** [comment]
Schrodinger's blogger.

**Pull request merged**
