### PR TITLE
Simplify the feature request template

### PR DESCRIPTION
**Pull request by opusforlife2**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [x] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Reduced and simplified the sections in the feature request template.
- Changed the comments to make them easier to understand.

#### Fixes the following issue(s)

- Poor adherence to the template.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by opusforlife2** [comment]
@mhmdanas It's waiting for a nonexistent CI check. How can this be fixed?

**Comment by mhmdanas** [comment]
Honestly, I'm not really sure. I'll try to take a look soon.

**Comment by mhmdanas** [comment]
@TobiGr do you have any idea if you can fiddle around with the repo's settings to fix this?

**Comment by TobiGr** [comment]
we cannot fix that without disabling the "Require status checks to pass before merging" setting. Maybe we need to re-think the approach and latthe test pass immideatly if one of these "skip"-conditions applies. I cannot find the PR which introduced the bahaviour (is it missing in the release notes?)

**Comment by mhmdanas** [comment]
I'm the one who opened that PR, so leave it up to me to clean the mess. :P

The PR is #6789 (just noticed the numbering, nice). You can revert it for now if you want.

**Comment by opusforlife2** [comment]
@mhmdanas @Poolitzer You guys still have to review it.

**Review by Poolitzer — APPROVED** [review]
simplification this is.

**Review by mhmdanas — APPROVED** [review]

**Pull request merged**
