### PR TITLE
Change "not available" image from PNG to vector format

### LINKED ISSUE #5609: The "Video unavailable" thumbnail on "unavailable" videos needs some changes
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Video unavailable message is hardcoded to the thumbnail on unavailable/unplayable videos. It would be great if it's changed to a "Video unavailable" text that follows app language instead of using this [English] thumbnail on every video and on every language.

#### Additional context

Example video: https://m.youtube.com/watch?v=r4JWI4UDOrc

Screenshot: 
Screenshot_20210216-202417

#### How will you/everyone benefit from this feature?

People will better understand what's going on because they will see the message in their language also the text on the thumbnail is a bit out of the border (text is too close to the border and not aligned to the center also part of of the last letter E is "cut").

### PR DESCRIPTION
**Pull request by sherlockbeard**
changed the not available .png to a xml file

Fixes #5609

fixed the issue of large devices  . extension of  #5925

#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

photo1628868390

tablet view
Screenshot_1628868849

### CODE REVIEW

**Comment by Stypox** [comment]
I tested on API 19 (Android 4.4) and it works only on white theme. Otherwise a gray or black background is just shown.

**Comment by sherlockbeard** [comment]
@Stypox i just tested on virtual machine android version  4.4   api 19. i was not able to reproduce your error .


untitled

**Comment by nadiration** [comment]
@sherlockbeard thank you for reconsidering this. No more boring grey background

**Comment by sherlockbeard** [comment]
@Stypox can you give me more information about the issue and the device you are testing with

**Comment by Stypox** [comment]
<hidden text="Turn off Show age restricted content and turn on YouTube's restricted mode in Settings -> Content. Then search for `MmBeUZqv1QA` (from [NewPipeExtractorAgeRestrictedTest](https://github.com/TeamNewPipe/NewPipeExtractor/blob/514ed7bdc1d367159b082ae82ac70e44e3ba49e3/extractor/src/test/java/org/schabi/newpipe/extractor/services/youtube/stream/YoutubeStreamExtractorAgeRestrictedTest.java))."/>

**Comment by sherlockbeard** [comment]
@Stypox . Ok so you are not able to reproduce so should I consider the issue (the one you mentioned in the comment) fixed?

**Review by Stypox — APPROVED** [review]
Yes, consider it fixed. Thank you!

**Comment by tsiflimagas** [comment]
I guess this can be merged(?)

**Comment by Stypox** [comment]
@tsiflimagas yes, I forgot about it, thank you :-)

**Pull request merged**
