### PR TITLE
Do not set reCaptcha cookie when there is no cookie stored

### PR DESCRIPTION
**Pull request by TobiGr**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
choose the correct default value when getting the reChaptcha cookie from the preferences.
In DownloaderImpl#getCookies(String url) the reChaptcha cookie is set if it is not null. For this reason, the cookie was set in every request.

#### APK testing 

On the website the APK can be found by going to the "Checks" tab below the title and then on "artifacts" on the right.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Redirion** [comment]
Looks plain simple and easy. Anything we are waiting for? Should be good to merge.

**Comment by XiangRongLin** [comment]
@Redirion Can't you then just merge it? You have the rights to approve and merge it

**Comment by Redirion** [comment]
but TobiGr requested a review from Stypox. So there could be more into it that requires (regional) testing

**Comment by TobiGr** [comment]
we should merge this. I requested a review from Stypoc, because he has a very good overview of the whole reChaptcha mechanism implemented in NewPipe. I think, this should be good to merge.

**Review by XiangRongLin — APPROVED** [review]

**Review by Stypox — APPROVED** [review]

**Pull request merged**
