### PR TITLE
AutoBackup

### PR DESCRIPTION
**Pull request by yausername**
output

- [x] Moved import/export options from content settings to backup/restore category.
- [x] Added ability to schedule auto backups at a specified folder.
- [x] Encrypt file (auto backup password is stored in encrypted shared prefs which are not backed up.)

### CODE REVIEW

**Comment by yausername** [comment]
apk for testing [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4284073/app-debug.zip)

**Comment by opusforlife2** [comment]
@thiswillbeyourgithub Here you go. Periodic backup, just as you asked.

@yausername Can you please provide a new test apk?

**Comment by TobiGr** [comment]
I never saw this PR :eyes: No idea, how this happened...
I'll come back once we are done with the 0.20.0 release.

**Comment by MD77MD** [comment]
each time any of us want to make a backup, he must go through a hunt to fine the backup folder. so will this pr solve this and remember the default folder for backups?

if not.. please make it so. its worth it.

**Comment by wb9688** [comment]
@MD77MD: No, but we could easily add that after #3777

**Comment by onelharrison** [comment]
@TobiGr @yausername It's been a few months since we seen any activity on this PR, but the feature request seems to be well-loved by members of the community. I, for one, think it would be a great addition to NewPipe's feature set. Any updates on what might be blocking this (besides the merge conflicts)? The  0.20.0 release has been done with for some time now 😁

**Comment by SameenAhnaf** [comment]
I know it's quite late. But could you please add "Always after exiting the app" frequency option? (Here, exit means nothing on background or recent apps). This will let us avoid losing any type of data.

**Comment by litetex** [comment]
No feedback since >2 weeks closing this PR... 🙁

**Comment by litetex** [comment]
No feedback since >1 month closing this issue now.

**Comment by NSTAdventure** [comment]
> No feedback since >1 month closing this issue now.

Hi sir is there any new or latest release with this feature included? 🙏😁

**Comment by thiswillbeyourgithub** [comment]
4 years later I'm still very interested in this feature. Having an automatic backup means that using syncthing I could have it always synced on my computer, allowing me to write some AI tools based on this. My [AI summary tool already rocks IMHO](https://github.com/thiswillbeyourgithub/WDoc).

What happened for this feature to be apparently working but never merged?

Pinging @yausername  @opusforlife2 

I can afford to make a little donation like $20 for anyone who makes this happen if that helps (be it to the person or to newpipe itself)

Thanks!

**Comment by thiswillbeyourgithub** [comment]
Still interested in the autobackup / autoexport feature btw. I could build a small app that creates embeddings and clustering from your watchlater playlist and help you choose what to see!.

Pinging @yausername  and @opusforlife2  :)

My small $20 donation is still up for grabs of course!

**Pull request closed without merging**
