### PR TITLE
Reintroduce "Settings" button in app bar

### PR DESCRIPTION
**Pull request by Stypox**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

As noted by @opusforlife2 in https://github.com/TeamNewPipe/NewPipe/issues/3114#issuecomment-589933537 it is sometimes useful to access settings from activities other than the main one. So this PR readds *some* "Settings" buttons removed in #2960.

In particular, the activities where the button is restored are:
- Queue (background and popup queue activities)
- VideoDetail (see @opusforlife2 usecase)
- Playlist (same as VideoDetail)
- Channel (same as VideoDetail)
- Download (I'm not really sure about this one, because the Download activity is only accessible via the drawer and the user could just press "back", so it would categorize as one of the activities below that do not require the button, but I feel like it would be useful anyway sometimes... **could you give some feedback?**)

Other activities that I think don't need the button, because accessing settings from there is unusual or pressing "back" once is enough:
- MainActivity (just open the drawer)
- Kiosk (press back and the drawer is already open because it was used to open the KioskActivity itself)
- Bookmarks (same as Kiosk)
- What's New (same as Kiosk)
- Subscriptions (same as Kiosk)
- History (same as Kiosk)

### CODE REVIEW

**Comment by Stypox** [comment]
@opusforlife2 @TobiGr @B0pol what do you think about the Download activity?

**Comment by opusforlife2** [comment]
I was hoping you'd revert this commit 9d773d6e8aa892e929439ba62d2a0985f4e8deb4, actually.

Anyway, I don't think you need the Settings button in the Download activity, as you can't change some Download setting and see its effect there. You'd have to back out of it and download something for that.

**Comment by gillhash** [comment]
@Stypox  As a long time user of NewPipe i urge devs to revert the change which removed dot menu function, Please.

It was so easy to change webm to Mp4 &  vice-versa while loading video.

**Comment by opusforlife2** [comment]
@gillhash This PR fixes exactly that.

**Comment by Stypox** [comment]
@opusforlife2 @gillhash could you test this apk and see if it works correctly?
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4239166/app-debug.zip)

**Comment by opusforlife2** [comment]
Tested all bullets. Everything is fine.

> press back and the drawer is already open because it was used to open the KioskActivity itself

This doesn't check out though. The drawer isn't already open for any of these activities. You have to open it again. I don't see why that matters, anyway.

**Pull request merged**
