### PR TITLE
Save and restore whether pitch and tempo are unhooked or not

### LINKED ISSUE #1536: [Feature Request] Make 'Unhook' the default for altered playback speed (or remember it)
I watch most videos on faster than default speed and I have to check 'Unhook' every time, if I don't want a pitch change as well.
Youtube and almost every other video player out there alters the speed without changing the pitch, so it seems like a reasonable thing to do.

I wouldn't even mind if the altered playback speed itself was remembered across videos.

### PR DESCRIPTION
**Pull request by Stypox**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

Now the `PlaybackParameterDialog` saves in SharedPreferences the state of the "Unhook" checkbox, so that the user does not have to slide down and click on the unhook checkbox every time. This is one of the proposed solutions in #1536. The other proposed solution was to make the checkbox checked by default, and based on the current pr code it could be implemented just by resetting the saved unhook preference to `true` every time a player is opened, but I think save&restore is better because not every user needs unhook-by-default.
I also fixed the `unhook_checkbox` string, to make it more English-y.

Fixes #1536
Debug apk: [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4144406/app-debug.zip)

### CODE REVIEW

**Comment by gillhash** [comment]
Thanks @Stypox for this PR, debug apk working smoothly as intended. I am going to use this for daily basis for days. Remembering speed/pitch-coupling checkbox state & having the unlink checked as default behaviour.

However I might add "If the altered playback speed itself is remembered across videos" (atleast until closing the app) that would be +1.

**Comment by gillhash** [comment]
Possibilities discussed in #735 issue & in #1823 can be touched later as this PR is such a simpler fix for the time being.

I personally feel "If the altered playback speed itself is remembered across videos" (atleast until closing the app) that would be a big +1.
..But that could be done in a different PR.

**Comment by gillhash** [comment]
@TobiGr is this going to be added in 0.18.3 ?

**Comment by Stypox** [comment]
@gillhash No, this will probably be postponed to 0.18.4

**Pull request merged**
