### PR TITLE
Add support for CSV+ZIP subscriptions (Google Takeout)

### PR DESCRIPTION
**Pull request by talanc**
#### What is it?
- [x] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
Fixes https://github.com/TeamNewPipe/NewPipe/issues/6757

Google Takeout now exports YouTube subscriptions as a CSV file (in a zip file).
This PR requires changes to NewPipeExtractor (now merged to dev).
It allows the user to select a CSV files for importing subscriptions.
If the user selects a ZIP file, it will go through the CSV files inside it and attempt to find the subscriptions file (the finding is a bit complicated due to different localizations).

#### Relies on the following changes
- TeamNewPipe/NewPipeExtractor#709
- TeamNewPipe/NewPipeExtractor#721

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by talanc** [comment]
I've updated the instructions in strings.xml as well.
I don't know if there's an additional localization process required.
Do I just delete the old translated strings because they're displaying the wrong information?

**Comment by TobiGr** [comment]
Please update the extractor version to your fork allowing the build to complete successfully and testers to check if everything works fine.

**Comment by talanc** [comment]
@TobiGr 
I think it's done now...
If not I'll need a bit more guidance on what to do.

**Review by Stypox — CHANGES_REQUESTED** [review]
Please rebase this and update the extractor commit, and it is ready.

**Comment by talanc** [comment]
@Stypox
All done.

**Comment by Stypox** [comment]
@talanc I added a commit to change the way the mime type is obtained. Your solution only worked when SAF was enabled, but would throw a `NullPointerException` with the old file picker. Is it ok? I also squashed your commits.

**Review by TobiGr — APPROVED** [review]
Thank you

**Comment by talanc** [comment]
@Stypox No problem. I was a bit unsure of that code. Thanks for improving it.

**Review by Stypox — APPROVED** [review]

**Comment by Stypox** [comment]
Thank you @talanc :-D

**Pull request merged**
