### PR TITLE
Simplify some sharing utilities

### PR DESCRIPTION
**Pull request by TacoTheDank**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
- These are handled internally by the methods I implemented in the PR.
  - At least I'm pretty sure.

#### APK testing 
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TiA4f8R** [comment]
Sorry, but I will probably close this PR.

Let me explain why: you are reverting my share sheet improvements on EMUI devices, which allow these devices to get the preview title (and soon the thumbnail of the content) of the content shared by using Android system chooser instead of EMUI chooser. See #5187 (the PR which introduced the changes) for the difference.

I know that's something we didn't have to do if Huawei didn't change this, but as you can see, the improvement by the use of the Android share sheet is really big in terms of information show to the user.

Hope you can understand.

**Comment by opusforlife2** [comment]
@TiA4f8R Is the Huawei-specific code marked as such? Or do you have a comment somewhere which explains why that code shouldn't be touched?

**Comment by TacoTheDank** [comment]
image

Curses, foiled again! Damn you Android fragmentation!

**Comment by TacoTheDank** [comment]
But yeah I understand, I didn't even know that was intentional (I guess I should've looked at the git blame though).

Perhaps some code commenting is in order?

(Also @TiA4f8R did you install the debug build and see if this PR actually did screw up the share sheet (seeing as you have an EMUI device)? I'd check, just in case. If you already did, then alrighty. 👍)

**Comment by TiA4f8R** [comment]
@TacoTheDank I did and the Android share sheet is still shown when sharing a content (for an unknown reason).

But the EMUI one is back when using the `Open in browser` command or when sharing a download (which was not the case, even before my PR (the Android one was shown, unless Huawei did more changes in the `Intent` class with a security patch) (it tries to generate an `hwCHOOSER` intent first and fallbacks to the Android one if the first one is null).

**Comment by cketti** [comment]
What is special about EMUI? Does `Intent.createChooser()` create an intent that is different from a manually created `Intent.ACTION_CHOOSER` intent?

**Comment by TiA4f8R** [comment]
> What is special about EMUI? Does `Intent.createChooser()` create an intent that is different from a manually created `Intent.ACTION_CHOOSER` intent?

Yes, see my comment above:

> it tries to generate an hwCHOOSER intent first and fallbacks to the Android one if the first one is null

(where the Android one is `Intent.ACTION_CHOOSER`)

**Comment by litetex** [comment]
I think we can close this or?

**Comment by TacoTheDank** [comment]
I'll close it.

**Pull request closed without merging**
