### PR TITLE
Rewrite ExceptionUtils methods as extension functions.

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Rewrite the `ExceptionUtils` methods as extension functions for better discoverability in Kotlin.

#### APK testing 

[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5577428/app-debug.zip)

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by XiangRongLin — DISMISSED** [review]
From code standpoint it looks fine to me. I did not try the apk.

`@file:JvmName("ExceptionUtils")` to keep the java world happy is nice and in the IDE it does get correctly indexed/linked.

Only thing i have is that the test class for `Throwable` is called `ThrowableExtensionsTest`, but that should be fine, if NewPipe wants to stick with this style.

**Review by Stypox — DISMISSED** [review]
I tested and it works. Thank you for all of the improvements :-D

> but that should be fine, if NewPipe wants to stick with this style.

Yeah, I think this is ok.

**Comment by Stypox** [comment]
Oh, but [compilation fails](https://travis-ci.org/github/TeamNewPipe/NewPipe/builds/749783528), could you fix this?

**Comment by Isira-Seneviratne** [comment]
> Oh, but [compilation fails](https://travis-ci.org/github/TeamNewPipe/NewPipe/builds/749783528), could you fix this?

I did.

**Review by TobiGr — APPROVED** [review]
Looks good to me

@Stypox Can we merge this?

**Pull request merged**
