### PR TITLE
Add CODEOWNERS file

### PR DESCRIPTION
**Pull request by mhmdanas**
#### What is it?
- [x] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners for how this works. The hope is that this will lead to more efficient PR triaging and less delays for PRs to be merged.

For now, I assigned myself `.github` and the READMEs, and @Redirion the player code (I hope you're fine with that :) ). I'll be waiting for the other team members to state what parts of the repo they want to "own," so this will be a draft for now.

I have no idea why those extra commits are there; please squash them when merging.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Redirion** [comment]
I think the general idea / purpose of this is to take some burden from the project lead (TobiGr). As of now everyone seeks Tobis advice / decision on anything that affects any part of NewPipe. By introducing some divide and conquer we don't introduce hard borders or create roles that overrule anyone else. It is more like that owners are a "person to contact" for this specific section and that this person is most likely active and familiar with issues and PRs regarding this section so that people can ask those instead of TobiGr. And of course owners should feel responsible of reviewing PRs that are within their section.

I also find the player package rather huge. It might be useful to have more than one owner for such big sections if we can't find useful further divide possibilities.

**Comment by mhmdanas** [comment]
@litetex I think there is some misunderstanding here. I put "own" in quotes for a reason: a code owner doesn't really own the code; the point is just that their review will be requested on a PR that modifies files that they "own," and their review isn't even required to merge the PR.

> I also find the player package rather huge. It might be useful to have more than one owner for such big sections if we can't find useful further divide possibilities.

Yeah, you're right; I'm open to any suggestions.

**Comment by opusforlife2** [comment]
Nice! I didn't even think of this solution, even though I've seen it happening over at the Fenix repo.

Regarding doubts about its effectiveness, we can always revert the change if it doesn't seem to be working for us. But there is no harm in trying it out, is there?

**Comment by mhmdanas** [comment]
Seeing as this PR didn't really progress at all since it was opened, I'm closing it. if anybody's interested in this though, feel free to make a comment.

**Pull request closed without merging**
