### PR TITLE
Use DisplayCutoutCompat in VideoPlayerImpl.

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
#### What is it?
- [ ] Bug fix (user facing)
- [ ] Feature (user facing)
- [x] Code base improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Use `DisplayCutoutCompat` instead of `DisplayCutout` in `VideoPlayerImpl`.

#### Testing apk

[debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5289781/debug.zip)

#### Agreement
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Review by Stypox — COMMENTED** [review]
Isn't it impossible for devices with an Android version < P to have insets?

**Comment by blackbox87** [comment]
> Isn't it impossible for devices with an Android version < P to have insets?

The Nokia 7.1 has a notch and was originally sold with Android Oreo, so I guess there's a few other devices too. But most of these devices did receive updates to Android 9 and 10.

**Comment by Isira-Seneviratne** [comment]
> Isn't it impossible for devices with an Android version < P to have insets?

Insets were actually introduced in API level 20. Display cutouts were introduced in API level 28.

**Review by Stypox — DISMISSED** [review]
Oh ok, I see, then the code looks good to me. Thank you!

**Comment by Isira-Seneviratne** [comment]
@Stypox I fixed a merge conflict.

**Review by TobiGr — APPROVED** [review]

**Pull request merged**
