### PR TITLE
Replace JUnit asserts with AssertJ in HistoryRecordManagerTest 

### PR DESCRIPTION
**Pull request by XiangRongLin**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

Replace JUnit asserts with AssertJ in HistoryRecordManagerTest 
They provide a wider range of assertions, which allow for more detailed error messages.  
Also convert SearchHistoryEntry to kotlin data class for better error messages, since toString() is implemented.

examples
```
java.lang.AssertionError: 
Actual and expected have the same elements but not in the same order, at index 1 actual element was:
  "B"
whereas expected element was:
  "AA"

	at org.schabi.newpipe.local.history.HistoryRecordManagerTest.getRelatedSearches_emptyQuery(HistoryRecordManagerTest.kt:114)

```
```
java.lang.AssertionError: 
Expecting actual:
  [SearchHistoryEntry(creationDate=2022-01-14T10:31:08.273Z, serviceId=1, search=B),
    SearchHistoryEntry(creationDate=2022-01-14T10:31:08.273Z, serviceId=0, search=B)]
to contain exactly (and in same order):
  [SearchHistoryEntry(creationDate=2022-01-14T11:31:08.273+01:00, serviceId=1, search=B)]
but some elements were not expected:
  [SearchHistoryEntry(creationDate=2022-01-14T10:31:08.273Z, serviceId=0, search=B)]
when comparing values using HistoryRecordManagerTest$$ExternalSyntheticLambda0
	at org.schabi.newpipe.local.history.HistoryRecordManagerTest.deleteSearchHistory(HistoryRecordManagerTest.kt:79)
```
#### Fixes the following issue(s)

- https://github.com/TeamNewPipe/NewPipe/issues/7553 Allows to see a more detailed error message

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

❗ Squash merge

### CODE REVIEW

**Comment by XiangRongLin** [comment]
Can I just say how stupid this ktLint is. There is no profil for Android Studio for the codestyle used in ktLint, so I'm using the default one. The output of that breaks ktLint 🤦‍♂️

**Review by litetex — APPROVED** [review]
LGTM

Tested the app seems to work also as expected 😄

**Review by mhmdanas — CHANGES_REQUESTED** [review]

**Review by mhmdanas — APPROVED** [review]

**Comment by tsiflimagas** [comment]
I made a build on dev branch and when I installed it, I got this

**Comment by TiA4f8R** [comment]
@XiangRongLin ^

**Comment by XiangRongLin** [comment]
@TiA4f8R I already saw it

---

~~I don't see any reason why this change would cause that error~~

java -> kotlin 🤦

**Comment by XiangRongLin** [comment]
So the exact reason is because of ambiguous nullability in java, which then were made explicit in kotlin during the conversion. see the error messag below

```
java.lang.IllegalStateException: Migration didn't properly handle: search_history(org.schabi.newpipe.database.history.model.SearchHistoryEntry).
 Expected:
TableInfo{name='search_history', columns={search=Column{name='search', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0, defaultValue='null'}, creation_date=Column{name='creation_date', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=0, defaultValue='null'}, id=Column{name='id', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=1, defaultValue='null'}, service_id=Column{name='service_id', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=0, defaultValue='null'}}, foreignKeys=[], indices=[Index{name='index_search_history_search', unique=false, columns=[search]}]}
 Found:
TableInfo{name='search_history', columns={search=Column{name='search', type='TEXT', affinity='2', notNull=false, primaryKeyPosition=0, defaultValue='null'}, service_id=Column{name='service_id', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=0, defaultValue='null'}, id=Column{name='id', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=1, defaultValue='null'}, creation_date=Column{name='creation_date', type='INTEGER', affinity='3', notNull=false, primaryKeyPosition=0, defaultValue='null'}}, foreignKeys=[], indices=[Index{name='index_search_history_search', unique=false, columns=[search]}]}
```

**Comment by XiangRongLin** [comment]
@tsiflimagas fix with #7674

**Pull request merged**
