### PR TITLE
Spelling of file formats

### PR DESCRIPTION
**Pull request by comradekingu**
As per
https://en.wikipedia.org/wiki/MPEG-4_Part_14#.MP4_versus_.M4A
https://en.wikipedia.org/wiki/WebM
https://en.wikipedia.org/wiki/3GP_and_3G2

### CODE REVIEW

**Comment by mauriciocolli** [comment]
Only the "3GPP → 3GP" change is valid, the others are keys for the settings and are not visible to the user (they were left lower case in purpose) and if we change that now, users will lose its configurations.

**Comment by comradekingu** [comment]
@mauriciocolli Thought they might be. However there are quite a few "m4a" strings and such. Should be M4A or .m4a

**Comment by mauriciocolli** [comment]
The commits are now messed up, it seems like @theScrabi squashed some commits.

Can you rebase it?

**Comment by theScrabi** [comment]
Thanks. Sorry for that debase mess.

**Pull request merged**
