### PR TITLE
[WIP] Android TV

### PR DESCRIPTION
**Pull request by wb9688**
I've added an initial Android TV version (#899). It looks like the following:

Screenshot

Things to do:

- [x] Merge `dev` into it (I started working on this some time ago and today was the first day I had time for this again)
- [ ] Make it possible to watch the videos
- [ ] Implement search
- [ ] Add real settings
- [ ] Add TV flavor to F-Droid (@theScrabi? Btw I've to test first if it doesn't crash on an Android phone, since F-Droid has no way to detect Android TV, but prioritizes the flavor with the highest min API version)
- [ ] Clean up code
- [ ] Design logo (@TobiGr?)

@theScrabi: Could you test if it runs (just the main screen) on your Fire TV?

### CODE REVIEW

**Comment by theScrabi** [comment]
Looks awesome O.o

**Comment by wb9688** [comment]
@theScrabi: The code isn't updated to Android 27 yet, so the build will fail. Without https://github.com/TeamNewPipe/NewPipeExtractor/pull/55 it doesn't show New & hot. Also please use `tvImplementation` instead of `tvCompile`.

Besides that, Travis needs to use the correct build commands (now they contain `tv` in it).

**Comment by theScrabi** [comment]
> The code isn't updated to Android 27 yet, so the build will fail. 

The build passed for me, I could run it. However I had to change about 4 lines of code for that.

> Also please use `tvImplementation` instead of `tvCompile`.
>
> Besides that, Travis needs to use the correct build commands (now they contain `tv` in it).

Right fixed that.

**Comment by wb9688** [comment]
@theScrabi: You don't have to run the normal ones on Travis, since tv is a superset of normal.

**Comment by theScrabi** [comment]
> I still see the MediaPlayerGlue, which is deprecated in 27.

It is that is true, but still worked.
It's [these linese](https://github.com/TeamNewPipe/NewPipe/pull/939/commits/845a202a54353b27281fb6e5525b409261bc6e44#diff-f5d81d1862adb0fcffe2c5c5b18e4702R27).

**Comment by theScrabi** [comment]
@wb9688 Someone at [34c3](https://events.ccc.de/) wrote an app called [chaosflix](https://github.com/NiciDieNase/chaosflix-leanback) maybe we can take his code as a template for our own leanback UI.

**Comment by theScrabi** [comment]
By the way what is the status of this project?

**Comment by wb9688** [comment]
Well, I'm on a holiday in Germany ;)

**Comment by theScrabi** [comment]
Ah cool. Well have a nice time then 😉

**Comment by Cormak** [comment]
Will this also work for FireTV or is that a separate project? I'm an Android TV user but I bet there's more FireTV users out there right now.

**Comment by wb9688** [comment]
@Cormak: Fire TV is just Android TV, but with some small extra features.
This means Android TV apps will automatically also work on Fire TV, but
without those small extras, until you also add support for them.

**Comment by Cormak** [comment]
@wb9688 Are those small extras worth adding for FireTV users? 

FireTV users are currently without a Youtube app so I can see Newpipe exploding in popularity once every TV box can sideload Newpipe and get a TV-friendly UI, so this is a very exciting PR.

**Comment by theScrabi** [comment]
Actually the idea of this project was to support fireTV :)

**Comment by TobiGr** [comment]
@o-l-a-v suggested some icons [here](https://github.com/TeamNewPipe/NewPipe/issues/717#issuecomment-359202958).
@wb9688 @theScrabi I just made a first try and got these three. Please tell me what kind of logo you like more. They are in a really early state and I am going to finish them later.
1. [white](https://user-images.githubusercontent.com/17365767/35188519-a0a3a28c-fe36-11e7-8b42-27131d4bc602.png) (I need to correct the icon's shadow direction)
2. [red](https://user-images.githubusercontent.com/17365767/35188649-d9fce2a2-fe39-11e7-9ec9-c161ad6f823b.png)  (needs some more space between New and Pipe)
3. [red](https://user-images.githubusercontent.com/17365767/35188521-a0e74faa-fe36-11e7-94d6-4aaeab00b9e5.png) 



I'll try to make a black / dark one too. Another idea is to use some kind of the triangle like in the F-Droid banner. Unfortunately I don't have any Android TV so I can't see whether the font size is large enough, but compared to the default videos launcher icon it seems good to me.

Maybe @bagelcake can help us too as he already made the F-Droid banner.

**Comment by wb9688** [comment]
>Unfortunately I don't have any Android TV

Can't you run it in an emulator? That should give you a pretty good idea I
think.

**Comment by TobiGr** [comment]
> Can't you run it in an emulator? 

Yes, I did. But that does not make my screen larger.

**Comment by wb9688** [comment]
Oh, yeah, that's right. My monitor is 32" though, so I forgot that.

**Comment by Cormak** [comment]
@TobiGr Number 2 is definitely the best one. Fits in the best with existing Android TV icons for other apps.

**Comment by o-l-a-v** [comment]
Would it not be better to build a single APK for both TV and mobile? Plex is doing this.
I imagine it would make for easier maintainance. Both TV and mobile could share the same logic, the only thing really seperating the two would be visual/ layout.

**Comment by wb9688** [comment]
We're doing that, but we also have a mobile-only APK, since TV supports
only from a certain Android version, while regular NewPipe also supports
from a lower Android version and we want those users still to be able to
use NewPipe.

**Comment by TobiGr** [comment]
Hey guys, 
here is a quick second round with some more random ideas for a launcher icon. They are all not perfect (many need more margin to the right side) but I want to show you other ideas to get an idea in which direction I should go on. So please give me feedback about what you liked and also what not.

[1. a](https://user-images.githubusercontent.com/17365767/35780791-35120f3e-09e1-11e8-8b02-5283e5c2db3a.png)
[1. b](https://user-images.githubusercontent.com/17365767/35780792-35361c3a-09e1-11e8-8087-35d39eee785d.png)
[2.](https://user-images.githubusercontent.com/17365767/35780793-354e01ce-09e1-11e8-81a6-ed2ca7036572.png)
[3.](https://user-images.githubusercontent.com/17365767/35780794-3564b018-09e1-11e8-81fc-9ec1aff5eaf2.png)
[4.](https://user-images.githubusercontent.com/17365767/35780983-e75b960e-09e3-11e8-9ab8-183871b42e22.png)
[5. a](https://user-images.githubusercontent.com/17365767/35780986-f75cd504-09e3-11e8-8b60-9b0df4ec4388.png)
[5. b](https://user-images.githubusercontent.com/17365767/35780989-023b064e-09e4-11e8-8a01-d3d5d5fa9848.png)

**Comment by justanidea** [comment]
Even if I feel something missing, I love 5a and 5b

**Comment by wb9688** [comment]
The shadow and the font feel 'off'. What font are you using? Try Roboto.

Btw I should finish this PR, but I've been really busy.

**Comment by TobiGr** [comment]
Yes, I didn't draw much attention to the shadows. I am using Arial right now. Roboto sounds good. I actually thought about using it for the website some time ago.

**Comment by karyogamy** [comment]
I too think 5.a looks the best but is missing something, perhaps combine 1.a's icon with 5.a's background?

**Comment by theScrabi** [comment]
4 or 5.a :)

**Comment by theScrabi** [comment]
More 4

**Comment by Cormak** [comment]
@TobiGr I think 2 would be the best one if the font were Roboto. I don't see the point of putting a round touch icon in a square TV icon. The Newpipe logo shouldn't be encircled by anything else. The other icons look too busy. Newpipe should be clean, easy to read, and distinctive while still keeping a uniform red color.

**Comment by o-l-a-v** [comment]
I think those, especially the all read ones, look like the netflix tile.
I like my idea, looks more "NewPipe" and "Android TV" IMHO. And, Roboto font.
org schabi newpipe_dark_big

**Comment by theScrabi** [comment]
Well and the newpipe logo looks like german arbeitsamt. 😂 I don't know I think the 4 is good. Wed just had to remove the shadow beneath the font so it does not look to much like netflix.

**Comment by o-l-a-v** [comment]
[Image](https://user-images.githubusercontent.com/6450056/35804371-dcfc0f7e-0a77-11e8-87a6-f51394a9a029.png)
^ More like this maybe?

**Comment by theScrabi** [comment]
I don't know I liked the little bits in the background. Is that to much netflix, if not 4. was awsome.

**Comment by TobiGr** [comment]
Thanks for the feedback. I'll improve the logos and come back with new ideas soon. 
Btw. I didn't see any conflict between Netflix' and our logo but I'll try to avoid it in the future 😅 

@o-l-a-v I wouldn't split the name into two words. People should recognize the app, its name and the colors so they can identify with them.

**Comment by justanidea** [comment]
You should maybe try to add lightening effects ()

**Comment by milencollin** [comment]
Hi,

Where I can find this apk? I have a xiaomi Android Tv and I would like try on this box.

Thanks.

**Comment by wb9688** [comment]
@milencollin: Nowhere, since it isn't even close to finished.

**Comment by milencollin** [comment]
@wb9688 oh ok! If you need beta tester I can do it to help you ;)

**Comment by theScrabi** [comment]
abandoned ... at least for now. Maybe we can catch up with this later on.

**Comment by h-2** [comment]
Just wanted to add that Android TV support with a UI designed for large screens would be **very welcome**, thanks for you initial work on this already!

**Comment by theScrabi** [comment]
I think the best solution was to make the current UI responsive for tv. We are already working on that :)

**Comment by theScrabi** [comment]
Alghtough help for d-pad support was welcome.

**Pull request closed without merging**
