### PR TITLE
Change subscription update icon

### PR DESCRIPTION
**Pull request by TotalCaesar659**
RSS logo is using now for subscription RSS feed only (https://github.com/TeamNewPipe/NewPipe/issues/2552).

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by nv95** [comment]
Why not vector drawable?

**Comment by TotalCaesar659** [comment]
It's for uniformity, other icons are [drawn](https://github.com/TeamNewPipe/NewPipe/tree/dev/app/src/main/res/drawable-xxxhdpi) in PNG too.

**Comment by Stypox** [comment]
I think the long-term plan is to convert all pngs to vector drawables, so I don't think it would be a problem to have an inconsistent vector drawable.

**Comment by TotalCaesar659** [comment]
It would be better to merge it now and let vectorizing for a future. I'm not good in this, maybe someone else will do it.

**Comment by justanidea** [comment]
You may be interested in #1232 in some points.

**Comment by Stypox** [comment]
@TotalCaesar659 could you please provide a screenshot?

**Comment by TotalCaesar659** [comment]
Yep.

**Comment by wb9688** [comment]
I'm not sure whether I prefer the update icon. @TobiGr: What do you think?

If we're going to change it, you should use vector drawables though.

**Comment by gkeegan** [comment]
Changing the what's new logo to a loading spinner like that seems like it would update, not take you to a page where you can update your feeds.

**Comment by TobiGr** [comment]
Thank you for the effort. Sorry for getting back to you that late. 
I agree with the others. Apart from that, subscription handling has changed.

**Pull request closed without merging**
