### PR TITLE
Only show "mark as watched" when watch history is enabled

### PR DESCRIPTION
**Pull request by TobiGr**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
Only display the "mark as watched" item in the feed context menu when the watch history is enabled.

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SameenAhnaf** [comment]
Thanks for the PR! Not sure if it's worth noting here. But there's a related bug.

'Show/Hide played items' icon works neither for now. Maybe, 'Mark as Watched' should work as 'Temporary watch history' instead if 'Watch history' is disabled.

**Comment by TobiGr** [comment]
> 'Show/Hide played items' icon works neither for now.

@SameenAhnaf  Please tell us what exactly does not work and the used history settings and stream states (not watched, stream position somewhere in the middle, watched completely). I cannot reproduce that.

**Comment by SameenAhnaf** [comment]
Sorry if I was not clear. I'm talking about this button. This button works neither when 'Watch history' is disabled. So, it should be hidden as well.

Should I open a separate issue?

IMG_20210823_012640

**Comment by TobiGr** [comment]
It works for me when the history is disabled. One can have watched items in the history when the history is paused.
Note that when disabling the watch history it is _not_ cleared. We need to make this more obvious.

**Pull request merged**
