### PR TITLE
Implement channel menu (closes #759)

### LINKED ISSUE #759: [bug] "Open in browser" does not work
1.open a video
2. go to channel
3. click three dots
4. select "open in browser"
nothing happens

### PR DESCRIPTION
**Pull request by coffeemakr**
- [X] I carefully reed the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

The share and open in browser menu items are not linked in channel view.

To do:
 - [x] Test it
 - [x] Check if the channel info is loaded.

### CODE REVIEW

**Comment by theScrabi** [comment]
I've tried it, but the open in browser function only opens NewPipe it self again.

**Comment by coffeemakr** [comment]
Hm strange. It works for me. Maybe you have configured NewPipe to always open these links? I'm not sure if there is a possibility to say the link should be opened with another app.

**Comment by theScrabi** [comment]
I did that I't didn't work. But it's not a suprise. I had such trouble with some other of my apps on Android 7. Are you running NP on Android 7?

**Comment by wb9688** [comment]
It works fine for me too, I'm running Android 7. In settings > apps >
newpipe > open by default > open supported links is set to always ask and
it says no standard values setted up (if not press the button above it)?

**Comment by coffeemakr** [comment]
@theScrabi Yes Android 7.0.

Unrelated question: Why do we use the field DEBUG in MainActivity instead of the BuildConfig.DEBUG?

**Comment by coffeemakr** [comment]
> I've just realized it needs some checks while loading so no NullpointerException occurs.

Fixed

**Comment by theScrabi** [comment]
Well that problem with my phone is not gone yet tho :/

**Pull request merged**
