### PR TITLE
Dismiss download dialog correctly

### LINKED ISSUE #6256: Downloading via share menu using SAF while no dowload folder was set before does not work
Download from in-app works, but when I try to download from outside the app, with Vanced, by sharing, it doesn't work. It just creates an empty file, and it won't even show in the download manager.

### Checklist

- [x] I am using the latest version - **0.21.2** 
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to YouTube Vanced
2. Choose any video, click on share, choose NewPipe
3. Tap Download

### Actual behaviour
 Download screen pops up
Screenshot_20210508_162637

Creates a file
Screenshot_2021_0508_162915

But won't download, 0.00 kb

### Expected behavior

I expected it to download the video, like it does when downloading from inside the app.

### Device info

 - Android version/Custom ROM version: Android 11
 - Device model: Vivo Y220

### LINKED ISSUE #6667: I can't download a video if I go through YouTube->share->NewPipe
### Checklist

- [x] I am using the latest version - 0.21.6 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to a YouTube video
2. Press on share
3. Swipe down to NewPipe
4. Select format and resolution

### Actual behavior
When I'm on a YouTube video which I want to download, I go to share, newpipe but nothing happens

### Expected behavior
 the video should start downloading after selecting the resolution and format

### Screenshots/Screen recordings
https://photos.app.goo.gl/nCYmhXXAkst7eKf47

### Device info

- Android version/Custom ROM version:MIUI12.5.1RJKMIXM Android 11
- Device model: Xiaomi Poco F2 Pro

### PR DESCRIPTION
**Pull request by Stypox**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
The first commit just reorders some methods in the `DownloadDialog` class and adds some comment section separators. 
The second commit fixes the `DownloadDialog` (which is a `DialogFragment`) dismissing according to [this thread](https://stackoverflow.com/questions/11201022/how-to-correctly-dismiss-a-dialogfragment): every reference to `getDialog().dismiss()` is replaced with just `dismiss()`. I also removed references to `getDialog().setOnDismissListener()` and replaced them with a new `onDismissListener` in `DownloadDialog`, required by `RouterActivity` to be able to `finish()` itself when the dialog dismisses. Then I removed the part of code that used to `finish()` the `RouterActivity` inside the `DownloadDialog` (it was in the wrong place), as that's now done correctly by the listener.

#### Fixes the following issue(s)
Fixes #6667
Fixes #6256

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.
@Pass1Vlax @khumarahn @skyGtm @TacoTheDank could you tell me if this works for you?

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Pass1Vlax** [comment]
I can't find the options in check, can you please send me a direct link?

**Comment by khumarahn** [comment]
@Pass1Vlax look for "artifacts".

I installed the new version. Was able to download a youtube video without problems.

**Comment by skyGtm** [comment]
Works good for both SAF enabled or disabled case.

**Comment by skyGtm** [comment]
Might fix these issues: 
https://github.com/TeamNewPipe/NewPipe/issues/6687
https://github.com/TeamNewPipe/NewPipe/issues/6665
https://github.com/TeamNewPipe/NewPipe/issues/6256

**Comment by Stypox** [comment]
@Pass1Vlax [direct link](https://github.com/TeamNewPipe/NewPipe/suites/3271913974/artifacts/76200818)

**Comment by Pass1Vlax** [comment]
> @Pass1Vlax [direct link](https://github.com/TeamNewPipe/NewPipe/suites/3271913974/artifacts/76200818)

It works, Good job!

**Review by TobiGr — APPROVED** [review]
Looks good to me

**Comment by TacoTheDank** [comment]
Works! You're the best! :P

**Comment by khumarahn** [comment]
Thanks! Is it reasonable to ask for a bugfix release for this issue? It seems quite essential.

**Comment by Pass1Vlax** [comment]
> Thanks! Is it reasonable to ask for a bugfix release for this issue? It seems quite essential.

I agree, it would help a lot of people that use this option

**Comment by pixel2user** [comment]
> Thanks! Is it reasonable to ask for a bugfix release for this issue? It seems quite essential.

@TeamNewPipe - Please release this fix as a hotfix-release on F-Droid. The bug makes NewPipe unusable on Android 10 and 11! :-(

**Pull request merged**
