### PR TITLE
[WIP] Fix New drawables and icons #1199

### PR DESCRIPTION
**Pull request by michaelsam94**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
Fix New drawables and icons #1199

### CODE REVIEW

**Comment by theScrabi** [comment]
497 Files changes. How comes?

**Comment by michaelsam94** [comment]
I replace all png's with vectors

**Comment by theScrabi** [comment]
I see. We already have so many of them?

**Comment by michaelsam94** [comment]
can you merge them?

**Comment by theScrabi** [comment]
I need to see.

**Comment by michaelsam94** [comment]
sure I don't change any name all names of vectors are the same png's names

**Comment by theScrabi** [comment]
Nice :D yea I'll check it.

**Comment by michaelsam94** [comment]
the app will crash on pre lollipop devices I fix many problems by using support library but it still there is some issues

**Comment by theScrabi** [comment]
I see. Well that should not happen. Pleas change the name of the isse to have a [WIP] in front.

**Comment by michaelsam94** [comment]
I change title of this pull request there is any thing else I would change

**Comment by theScrabi** [comment]
Jup remove wip once you are done 👌

**Comment by michaelsam94** [comment]
still there is some issues with drawable top I fix some but the method require android api 17 there is anther solution we can make but it requires every vector to have another file which have layerlist tag if there another solutions you can suggest it Thanks

**Comment by mauriciocolli** [comment]
Notice that are multiple issues to fix yet:
- Different sizes
- Icons with different proportions
- Strange vector path, very different than the png images
- Lose the `ldrtl` resources

I don't know how you generated the vectors, but you should have used Android Studio's new vector asset.

And personally I wouldn't replace all of the images, just the ones that we want to scale like the play button and some others (for example, to the popup resizing and the play button animation). I also don't know how stable this is in older versions of Android (pre-lollipop) so I would use vector only where it needs to be.

**PS**: Please, check _ALL_ the usages before replacing any image, as when we created the layouts, we used the images with the specific size/proportions.

**PS 2**: I also don't remember exactly what bug occurred with the preference support library v7, but that's why I used the v14. I will look at this further later on.

**Comment by michaelsam94** [comment]
so we only replace some png's that is better than replace all png's because still vector not well supported I can revert and we can decide which png will be converted and remove other vectors replace them with png's

**Comment by michaelsam94** [comment]
BTW I use Inkscape to convert pngs to vector

**Comment by theScrabi** [comment]
> And personally I wouldn't replace all of the images, just the ones that we want to scale like the play button 

> BTW I use Inkscape to convert pngs to vector

Inkscape is awesome, but probably misplaced here. As @mauriciocolli said, all the png resources we use are already available as svg, so we don't need to convert them :)

**Pull request closed without merging**
