### PR TITLE
Use the Kotlin Parcelize annotation.

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
#### What is it?
- [ ] Bug fix (user facing)
- [ ] Feature (user facing)
- [x] Code base improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Use the Parcelize annotation provided by Kotlin to automatically generate the boilerplate code for classes that implement the `Parcelable` interface.

#### Testing apk

[debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4975523/debug.zip)

#### Agreement
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by Stypox** [comment]
Great! I see code is greatly simplified, thank you!

**Review by Stypox — APPROVED** [review]
Looks good to me and works, I tested restoring from RAM on Android 4.4 and 7.0 :-D
Thank you ;-)

**Comment by vkay94** [comment]
I just found out that `Parcelize` is part of the Kotlin Android Extensions compiler plugin and this plugin is deprecated starting from Kotlin `1.4.20` (NewPipe uses `1.4.10` currently). But there is a standalone plugin for it (`kotlin-parcelize`). [Here](https://proandroiddev.com/migrating-the-deprecated-kotlin-android-extensions-compiler-plugin-to-viewbinding-d234c691dec7)). is an article about it. @Isira-Seneviratne

**Comment by Isira-Seneviratne** [comment]
> I just found out that `Parcelize` is part of the Kotlin Android Extensions compiler plugin and this plugin is deprecated starting from Kotlin `1.4.20` (NewPipe uses `1.4.10` currently). But there is a standalone plugin for it (`kotlin-parcelize`). [Here](https://proandroiddev.com/migrating-the-deprecated-kotlin-android-extensions-compiler-plugin-to-viewbinding-d234c691dec7)). is an article about it. @Isira-Seneviratne

Thanks, I'll create a PR with the necessary changes.

**Comment by XiangRongLin** [comment]
@Isira-Seneviratne Can you run the `ErrorInfoTest`?
For me it always fails at `gradle :app:compileDebugAndroidTestJavaWithJavac`, with 
```
error: incompatible types: Object cannot be converted to ErrorInfo
        final ErrorInfo infoFromParcel = ErrorInfo.CREATOR.createFromParcel(parcel);
```

At first i thought it was because i was using windows, but this time it also failed in a CI action
https://github.com/XiangRongLin/NewPipe/runs/1645255340?check_suite_focus=true#step:6:57137
line 57317

**Pull request merged**
