### PR TITLE
Issue #1951 - Search shared text

### LINKED ISSUE #1951: Shared text can also be a search
It would be very useful if when one shares some selected text from another app (ie. Browser, notes, etc) into new pipe, if the text isn't an URL, then the app could make a search with that text

Currently if one tries it, the response is an error saying invalid URL...

Cheers! :)

- [x ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ x] I checked if the issue/feature exists in the latest version.
- [ x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

### PR DESCRIPTION
**Pull request by Klearchos-K**
Added function handleText() in RouterActivity.java for #1951 issue.
Now if you select text in other apps (eg Browser) you can share it to NewPipe. If it is not a URL, NewPipe will search for videos.

- [ x ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

----

closes #1951

### CODE REVIEW

**Comment by TobiGr** [comment]
Forgot to merge this :D @Klearchos-K Sorry
@theScrabi Can we include this into 0.16.0 or would you like to hold back any further changes except bug fixes and wait until 0.16.0 is released?

**Comment by theScrabi** [comment]
Release phase of 0.16.0 has alreafy begun so no.

**Comment by Redirion** [comment]
@TobiGr merge?

**Comment by TobiGr** [comment]
Thanks again. I am sorry for the delay.

**Comment by illustribe** [comment]
Thanks a lot!

Great work!!

**Pull request merged**
