### PR TITLE
Simple playback-speed-controls improvements

### LINKED ISSUE #4913: Speedmenu layout in landscape mode
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I think the speed control should have another layout  in landscape mode, so most users don't have to scroll.
There is an image how it could look

#### Is your feature request related to a problem? Please describe it

At the moment you have to scroll through the menu and see not all options at the same time. 
I have to admit that my phone screen may be a bit thin and long but i think it is the same issue on many other devices that the menu is too big in vertical and has enough space left on the sites. 

#### Additional context

At the time:
old_speed-menu
My suggestion:
new_speed-menu

#### How will you/everyone benefit from this feature?

Its just a detail, but i think it would improve UX because you see everything after opening it up and don't have to scroll anymore - it would just feel cleaner.

### PR DESCRIPTION
**Pull request by litetex**
#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
- Improved some paddings/margins in ``dialog_playback_parameter.xml``
- Removed the header, see https://github.com/TeamNewPipe/NewPipe/pull/7363#issuecomment-962605601

"Why another PR for this issue?" → https://github.com/TeamNewPipe/NewPipe/issues/4913#issuecomment-961309165

Probably supersedes
- #7351
- #6150

<details><summary>In case we also want to change the order of the checkboxes...</summary>

No new layout is required, simply implement this:
```java
    private void setDialogMode(final View view, final boolean landscapeMode) {
        final LinearLayout layoutAdditionalOptions =
                view.findViewById(R.id.additionalOptions);
        final List<CheckBox> additionalOptionsCheckboxes =
                Arrays.asList(
                        view.findViewById(R.id.unhookCheckbox),
                        view.findViewById(R.id.skipSilenceCheckbox)
                );

        layoutAdditionalOptions.setOrientation(
                landscapeMode
                        ? LinearLayout.HORIZONTAL
                        : LinearLayout.VERTICAL
        );

        for (final CheckBox checkBox : additionalOptionsCheckboxes) {
            final LinearLayout.LayoutParams layoutParams =
                    (LinearLayout.LayoutParams) checkBox.getLayoutParams();
            layoutParams.width =
                    landscapeMode
                            ? 0
                            : LinearLayout.LayoutParams.MATCH_PARENT;
            layoutParams.weight = landscapeMode ? 1 : 0;

            checkBox.setLayoutParams(layoutParams);
        }
    }
```

</details>

#### Before/After Screenshots/Screen Record
- Before: grafik

- After: grafik

#### Fixes the following issue(s)
- Fixes #4913

#### APK testing 
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by MD77MD** [comment]
if both check boxes where put at the same raw... to eliminate scrolling... which is the point of all the PRs

**Comment by litetex** [comment]
> if both check boxes where put at the same row... to eliminate scrolling... which is the point of all the PRs

This does not work on some languages like e.g. German (where the "Unhook"-text is relatively large) or on small devices. 
The scrollbars will always be there in some kind of situation.

**Review by Pi-Bouf — DISMISSED** [review]

**Comment by Fs00** [comment]
A personal opinion on this: I would remove the "Playback Speed Controls" title rather than constrict it at the top, which doesn't look too good.
I think that the purpose of the dialog would be clear enough even without the title.

**Comment by litetex** [comment]
> A personal opinion on this: I would remove the "Playback Speed Controls" title rather than constrict it at the top, which doesn't look too good. I think that the purpose of the dialog would be clear enough even without the title.

I like this idea.
It is really kind of obvious that these are the playback speed controls so I guess we can remove the title without harm :)

Update: Applied and committed (see issue-description for updated demo image)

**Comment by opusforlife2** [comment]
So has the need for scrolling been removed completely after removing the title?

**Comment by litetex** [comment]
> So has the need for scrolling been removed completely after removing the title?

Yes. On "normal" devices like a Pixel 3a (5 inch display).

However small ones like a Nexus S (from 2011; Android 2.3.x with 4 inch display) will always have this kind of problem. It's "unfixable" there.

**Comment by MD77MD** [comment]
i think it's a good enough now

**Comment by opusforlife2** [comment]
Alright. Seems like this is the best we can achieve here. 👍

**Review by Redirion — APPROVED** [review]
lgtm

**Comment by yashpalgoyal1304** [comment]
> It is really kind of obvious that these are the playback speed controls so I guess we can remove the title without harm :)

bad bad, i dont agree :(

especially bad when getting the elder people onboard with "smartphones" and stuff

**Pull request merged**
