### PR TITLE
Use view binding in activities.

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Use [view binding](https://developer.android.com/topic/libraries/view-binding) in the activities, as Kotlin synthetics have been [deprecated](https://proandroiddev.com/migrating-the-deprecated-kotlin-android-extensions-compiler-plugin-to-viewbinding-d234c691dec7) in favor of view binding.

#### APK testing 

[debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5611546/debug.zip)

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Disqu3-mirOir-qt** [comment]
for me work , some bug fixed , perfect 

i get only 1 error

**Comment by Disqu3-mirOir-qt** [comment]
{

"user_action":"requested stream",

"request":"https://www.youtube.com/watch?v=fCZVL_8D048",

"content_language":"fr",

"content_country":"FR",

"app_language":"fr",

"service":"YouTube",

"package":"org.schabi.newpipe.debug.Useviewbindinginactivities",

"version":"0.20.2",

"os":"Linux HUAWEI/RNE-L21/HWRNE:8.0.0/HUAWEIRNE-L21/339(C432):user/release-keys 8.0.0 - 26",

"time":"2020-11-02 03:54",

"exceptions":[

"org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:194)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)\n\tat org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$YTHJjScxCJNO1LTCqs3IKy35iyY.call(Unknown Source:4)\n\tat io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)\n\tat io.reactivex.Single.subscribe(Single.java:3666)\n\tat io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)\n\tat io.reactivex.Single.subscribe(Single.java:3666)\n\tat io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4290)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14935)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4290)\n\tat io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)\n\tat io.reactivex.Single.subscribe(Single.java:3666)\n\tat io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)\n\tat io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)\n\tat java.lang.Thread.run(Thread.java:784)\n"

],

"user_comment":""

}

**Comment by Stypox** [comment]
@Disqu3-mirOir-qt that error is not related to the contents of this PR

**Comment by TacoTheDank** [comment]
@Isira-Seneviratne You should change the target branch to https://github.com/TeamNewPipe/NewPipe/tree/view-binding (you may have to rebase).

**Comment by Stypox** [comment]
@TobiGr I'd like to merge this as soon as possible, otherwise @Isira-Seneviratne will be overwhelmed by rebasing. I will review and test tomorrow.
@Isira-Seneviratne could you rebase one last time? Thank you!

**Comment by TacoTheDank** [comment]
@Stypox It's been updated. Merging time! :)

**Review by Stypox — DISMISSED** [review]
Code looks good to me, thank you! I tested on API 19 and on Android 7.0 and everything worked well. Could someone else review, before merging, though? I have no experience with view binding ;-) @TacoTheDank @TobiGr @vkay94

**Comment by TacoTheDank** [comment]
Did a quick test on my Android 10 device and everything seems to work as it should. Nice job!

**Comment by vkay94** [comment]
I checked the "id moving" (discussed here in another view binding PR: https://github.com/TeamNewPipe/NewPipe/pull/5029#discussion_r532177104), but it should be fine since the Id isn't used in the code :)

**Review by TobiGr — DISMISSED** [review]
Thank you!
Code looks good to me. I could not find any bugs on Android 4..4, 5.0, 9 and 11 while testeing various scenarios. 

It looks like @Stypox - how dare you :P - caused a merge conflict. Can you rebase one last time, please?

**Comment by TacoTheDank** [comment]
> It looks like @Stypox - how dare you :P - caused a merge conflict. Can you rebase one last time, please?

Lol stop torturing this poor guy!

**Review by Stypox — APPROVED** [review]
Thank you again! :-D

**Pull request merged**
