### PR TITLE
Add yewtu.be Invidious instance

### PR DESCRIPTION
**Pull request by avoidr**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by avoidr** [comment]
It's been 8 hours and this still isn't merged. Is the project dead?

**Comment by gkeegan** [comment]
8 hours isn't an unreasonable time to wait. By no means is the project dead.

**Comment by wb9688** [comment]
If you had actually read the contribution guidelines, you would've seen the following:

>Please test (compile and run) your code before you submit changes! Ideally, provide test feedback in the PR description. Untested code will not be merged!

You've obviously not done that, as this also needs a change in NewPipeExtractor before this would work.

Besides, a wait time of 8 hours isn't unreasonable at all and this project isn't dead. Most of us are in the German timezone, plus we've been busy with getting v0.18.5 ready on time.

**Comment by Stypox** [comment]
@avoidr there are currently other PRs waiting for review and merge, and it takes time to check code and decide toghether if it is ok to merge. So it is normal for PRs to be merged even after a month, if they do not add a critical feature or fix an important bug. You can see the plan for next versions here: https://github.com/TeamNewPipe/NewPipe/milestones

**Comment by avoidr** [comment]
You're right, I'm sorry I didn't actually test it because I am not an app developer and don't have it all set up. But to my defense, I did check the git log and found 6a8e38476f93fe2b75950fe378740cec248d9770, which led me to believe that it's enough.

But now it seems that this instance has been down for almost 12 hours now. I don't know if it's down for good or what. But I/we used it because the domain name was so easy to type.

By the way, would it be possible to match the URL for "/watch?v=" to handle all instances? I don't know how the "open with" prompt works, was just a thought.

Sorry if I upset any of you, I wasn't actually serious about the 8 hours.

**Comment by TobiGr** [comment]
@avoidr Feel free to re-open your PR when yewtu.be is up again.

**Comment by trymeouteh** [comment]
I think users should be able to add invidious instances just like you can add peertube instances. And have invidio.us as the default instance.

**Comment by B0pol** [comment]
> I think users should be able to add invidious instances just like you can add peertube instances. And have invidio.us as the default instance.

You can't edit manifest dynamically. So it's not possible for invidious. Plus invidious as of now is just opening links, nothing else. For PeerTube, you can't open links, but just use the content within the app.

**Comment by trymeouteh** [comment]
> > I think users should be able to add invidious instances just like you can add peertube instances. And have invidio.us as the default instance.
> 
> You can't edit manifest dynamically. So it's not possible for invidious. Plus invidious as of now is just opening links, nothing else. For PeerTube, you can't open links, but just use the content within the app.

It is not possible to add a URL within the to open in Newpipe? This must be programmed into the app?

**Pull request closed without merging**
