### PR TITLE
Dark theme

### PR DESCRIPTION
**Pull request by ksyko**
Some icons like thumbs and rss have similar color as background
App needs to be restarted manually

### CODE REVIEW

**Comment by ksyko** [comment]
screenshot_20161231-153637
screenshot_20161231-153712
screenshot_20161231-153728
screenshot_20161231-153750

**Comment by theScrabi** [comment]
All right I'll take a look at it.

**Comment by theScrabi** [comment]
All right good work :) I like it, but there are several things we have to fix before we can release.
- [ ] 1. Fix detailed view background so the overlapping window is not transparent
- [ ] 2. Make the thumbs white
- [ ] 3. Use a dark pixmap for the FAB button
- [x] 4. (I can't count to 4) (fix me)
- [ ] 5. Fix the color at the report screen ( use a ((string) null).length() bomb to get there)
- [ ] 6. Call the theme option "Theme"
- [ ] 7. Don't make Dark theme the default option
- [ ] 7.1 Don't show numbers as option show "Dark" or "Bright"

asdf

**Comment by krompus** [comment]
Oh man, I want this so bad. An AMOLED (true black) theme would be wonderful as well. Any way I can assist?

**Comment by ksyko** [comment]
screenshot_20170117-203516
screenshot_20170117-203847
screenshot_20170117-203450

**Comment by ksyko** [comment]
pjimage

**Comment by ksyko** [comment]
@theScrabi 
pjimage 2
pjimage 3

**Comment by theScrabi** [comment]
Why sorry? Good work :)

**Comment by ksyko** [comment]
@krompus need a better way to set theme.

**Comment by theScrabi** [comment]
Nicely done :)

**Pull request merged**
