### PR TITLE
Sync weblate

### LINKED ISSUE #7688: Weblate out of sync
I got a warning that weblate is not in sync with the main repo anymore:

grafik

```
Rebasing (1/30)
error: could not apply ed6a08011... Translated using Weblate (Telugu)
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply ed6a08011... Translated using Weblate (Telugu)
Auto-merging app/src/main/res/values/strings.xml
Auto-merging app/src/main/res/values-zh-rTW/strings.xml
Auto-merging app/src/main/res/values-zh-rHK/strings.xml
Auto-merging app/src/main/res/values-vi/strings.xml
Auto-merging app/src/main/res/values-uk/strings.xml
Auto-merging app/src/main/res/values-tr/strings.xml
Auto-merging app/src/main/res/values-te/strings.xml
Auto-merging app/src/main/res/values-sv/strings.xml
Auto-merging app/src/main/res/values-sc/strings.xml
Auto-merging app/src/main/res/values-ru/strings.xml
Auto-merging app/src/main/res/values-pt/strings.xml
Auto-merging app/src/main/res/values-pt-rPT/strings.xml
Auto-merging app/src/main/res/values-pt-rBR/strings.xml
Auto-merging app/src/main/res/values-pl/strings.xml
Auto-merging app/src/main/res/values-nl/strings.xml
Auto-merging app/src/main/res/values-nb-rNO/strings.xml
Auto-merging app/src/main/res/values-ja/strings.xml
Auto-merging app/src/main/res/values-it/strings.xml
Auto-merging app/src/main/res/values-in/strings.xml
Auto-merging app/src/main/res/values-hu/strings.xml
CONFLICT (content): Merge conflict in app/src/main/res/values-hu/strings.xml
Auto-merging app/src/main/res/values-hr/strings.xml
Auto-merging app/src/main/res/values-he/strings.xml
Auto-merging app/src/main/res/values-fr/strings.xml
Auto-merging app/src/main/res/values-fa/strings.xml
Auto-merging app/src/main/res/values-eu/strings.xml
Auto-merging app/src/main/res/values-es/strings.xml
Auto-merging app/src/main/res/values-el/strings.xml
Auto-merging app/src/main/res/values-de/strings.xml
Auto-merging app/src/main/res/values-cs/strings.xml
Auto-merging app/src/main/res/values-b+zh+HANS+CN/strings.xml
Auto-merging app/src/main/res/values-ar/strings.xml
 (1)
```

### PR DESCRIPTION
**Pull request by litetex**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
* Syncs weblate into dev branch

#### Fixes the following issue(s)
- Fixes #7688

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TobiGr** [comment]
grafik

You might want to commit the pending changes in weblate before merging this

**Comment by litetex** [comment]
@TobiGr 

> You might want to commit the pending changes in weblate before merging this

Wouldn't it be better to first merge the PR and then commit the changes (and do a second PR) so that we don't get more merge conflicts?

**Comment by TobiGr** [comment]
Depends on how you want to merge this PR. If you want to squash the commits (which I'd suggest), you need to reset weblate which whipes out all pending changes. If you do a normal merge, there shouldn't be problems. But if there are conflcits with the pending changes, you need to open and merge another PR before weblate can be syncronized.

**Comment by litetex** [comment]
> Depends on how you want to merge this PR. If you want to squash the commits (which I'd suggest), you need to reset weblate which whipes out all pending changes. If you do a normal merge, there shouldn't be problems. But if there are conflcits with the pending changes, you need to open and merge another PR before weblate can be syncronized.

Ok, I will commit the changes and update this PR.

Update: Done

**Review by TobiGr — APPROVED** [review]
LGTM.
I removed a few unused strings.

**Comment by litetex** [comment]
@TobiGr 
There is another #7699

**Pull request merged**
