### PR TITLE
support for invidio.us links

### LINKED ISSUE #1614: support invidious link opening
[invidious](https://invidio.us/) is another hooktube like client to watch youtube videos. it would be great to include support for opening its links in newpipe. thanks.

### PR DESCRIPTION
**Pull request by anoymouserver**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

I adapted the link support of `hooktube.com` for `invidio.us` which closes #1614.
Actually, I'm not an android developer, but I hope the change works. 😃 

Oh, I just see that this would require some additional changes in the NewPipeExtractor.
I'll see if it can be adapted the same way, but I don't know if I figure it out.

### CODE REVIEW

**Comment by connectety** [comment]
this also closes https://github.com/TeamNewPipe/NewPipe/issues/1962, (which seams to be a duplicate of https://github.com/TeamNewPipe/NewPipe/issues/1614) and maybe https://github.com/TeamNewPipe/NewPipe/issues/1867

**Comment by anoymouserver** [comment]
Currently there seems to be an unfinished, not working state in the app, because it reacts to the links, but the changes in the backend (TeamNewPipe/NewPipeExtractor#137) are not yet merged.

**Comment by theScrabi** [comment]
Uff i see. Thank you for depicting this

**Comment by pred2k** [comment]
Amazing to see his feature being merged. Thank you all!

**Pull request merged**
