### PR TITLE
Chromecast support

### PR DESCRIPTION
**Pull request by KeizerDev**
Hi,

I added Chromecast support today to the `PlayVideoActivity.java`! :)
Because I'm not in contact with the developers I don't really know where I should implement it else then that activity.
It's still very basic, (I've started with a very basic state enum but not implemented it).

This is what I have so far:
- [X] Cast videos.
- [X] Cast videos with metadata(title: Video title, subtitle: video url).
- [X] Play video notifications with working play, pause, delete buttons
- [X] Play video background on lock screen.
- [ ] More metadata, thumbnail e.g.
- [ ] State implementation, local or remote.
- [ ] Stop the video playback, this is also a state thing.
- [ ] Play/pause for player buttons support(should be implemented with the state)  

**Optional:**
- [ ] Make the volume buttons work with the Chromecast, now you can just click on the cast icon in the `PlayVideoActivity.java`  

<br>

You can merge it to a new branch if you want to work on it together.  
Again I would like to come in contact with you about the app because I'd like to implement some more cool stuff :) @theScrabi 

   <br>

Ps. It is really a deal now to use this app because it supports the Chromecast Audio and the official app does not :+1:

### CODE REVIEW

**Comment by theScrabi** [comment]
I'm on vacation right now. Please wait until next week ;)

**Comment by theScrabi** [comment]
But one thing I can tell you so far is, that you would not get this through. Newpipe is Free Software, and strictly follows the f-droid restrictions since its the official distribution way. Therefore having gsm core as a library within NP is unacceptable.

I'm sorry, but unless you do something via UPnP you would not be able to bring cromecast support into fdroid NewPipe

**Comment by KeizerDev** [comment]
@theScrabi It would be the only reason to use this, the official Youtube app doesn't support the Chromecast Audio and mine implementation does. I think it would be a huge opportunity, but it's up to you to decide.

**Comment by theScrabi** [comment]
I'm sorry, still no.
Please read the commend above. If there is an opensource library for supporting chromecast, we could talk about that.

**Comment by KeizerDev** [comment]
@theScrabi https://github.com/DroidsOnRoids/Casty, let's implement this!

**Comment by theScrabi** [comment]
All right +1 great :)

**Comment by Echolon** [comment]
Any updates on chromecast?

**Pull request closed without merging**
