### PR TITLE
Run Instrumented tests in CI pipeline

### PR DESCRIPTION
**Pull request by XiangRongLin**
#### What is it?
- [x] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- expand ci.yml to run instrumeted test
- only run ci pipeline on push/pr against dev and master.
- uses https://github.com/marketplace/actions/android-emulator-runner
- showcase: XiangRongLin/NewPipe#8
- adds 7-8 min to CI pipeline, part of which is parallelized

#### Relies on the following changes

- #5359 needs to be adresses which i just did by updating kotlin here.

#### Notes
- There currently are only 2 instrumentet tests, which means this doesn't really add much value yet. But i think having this already in place for when it is needed is good.
- At first i wanted it to run it on API level 19 and 29 (min and max SDK) but it fails on 19 with it not being able to find the test (https://github.com/XiangRongLin/NewPipe/runs/1657271924?check_suite_focus=true#step:5:247). I assume its because of some problem with multidex and API < 21 since when i run it normally on API 19 emulator it logs a lot of errors with `Could not find class 'xyz'`.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Stypox** [comment]
Everything seems ok to me, though I don't have much experience with CI. What about also testing on API 21, alongside API 29?

**Review by Stypox — APPROVED** [review]
Looks good to me, but let's wait for @TobiGr's opinion ;-)

**Comment by XiangRongLin** [comment]
@Stypox The API level 29 was running for multiple hours for some reason. lets see if it is still like this on a rerun

**Comment by XiangRongLin** [comment]
Its working now. @TobiGr after merging the required check needs to be changed since i renamed it to `build-and-test-jvm`

**Comment by Stypox** [comment]
@XiangRongLin I guess it is normal that `build-and-test` is skipped, since it was replaced by `build-and-test-jvm`, wasn't it? If that's the case then this is ready to merge I think.

**Review by TobiGr — APPROVED** [review]

**Comment by TobiGr** [comment]
> after merging the required check needs to be changed since i renamed it to `build-and-test-jvm`

Done. All workflows need to be run again now

**Pull request merged**
