### PR TITLE
Specify emulator-build version in CI job

### PR DESCRIPTION
**Pull request by XiangRongLin**
#### What is it?
- [x] Bugfix (user facing)

#### Description of the changes in your PR

- temporary fix from https://github.com/ReactiveCircus/android-emulator-runner/issues/160

#### Fixes the following issue(s)

All actions for instrumented tests fail due to emulator not starting properly
```
/Users/runner/Library/Android/sdk/platform-tools/adb shell getprop sys.boot_completed
adb: no devices/emulators found
The process '/Users/runner/Library/Android/sdk/platform-tools/adb' failed with exit code 1
Error: The operation was canceled.
```

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Stypox** [comment]
I don't feel like I know enough to review this, sorry

**Comment by XiangRongLin** [comment]
@Stypox Who does then? With that mindset I think no one can review this

This PR only adds `emulator-build: 7425822`, which comes from the linked issue

**Review by TobiGr — APPROVED** [review]
Looks good

**Review by Stypox — APPROVED** [review]
> Who does then? With that mindset I think no one can review this

Mmmh ok, sorry. By looking at the issue you linked it seems like this should work, so I'm approving it, though I really do not know much about the CI.

**Pull request merged**
