### PR TITLE
Update some libraries

### PR DESCRIPTION
**Pull request by TacoTheDank**
#### What is it?
- [x] Codebase improvement (dev facing)

#### Description of the changes in your PR
- Update Sonarqube 3.5.0.2730 -> 4.0.0.2929 ([changelog](https://github.com/SonarSource/sonar-scanner-gradle/releases/tag/4.0))
- Update Checkstyle 10.3.1 -> 10.11.0 ([changelog](https://checkstyle.sourceforge.io/releasenotes.html))
- Update ExoPlayer 2.18.5 -> 2.18.7 ([changelog](https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md))
- Update desugar_jdk_libs 2.0.2 -> 2.0.3 ([changelog](https://github.com/google/desugar_jdk_libs/blob/master/CHANGELOG.md))
- Update jsoup 1.15.3 -> 1.16.1 ([changelog](https://jsoup.org/news/))
- Update OkHttp 4.10.0 -> 4.11.0 ([changelog](https://github.com/square/okhttp/blob/master/docs/changelogs/changelog_4x.md#version-4110))
- Update RxJava 3.1.5 -> 3.1.6 ([changelog](https://github.com/ReactiveX/RxJava/releases))
- Update Test Junit 1.1.3 -> 1.1.5 ([changelog](https://developer.android.com/jetpack/androidx/releases/test))
- Update Test Runner 1.4.0 -> 1.5.2 ([changelog](https://developer.android.com/jetpack/androidx/releases/test))
- Update Kotlin 1.8.20 -> 1.8.21 ([changelog](https://github.com/JetBrains/kotlin/blob/master/ChangeLog.md#1821))
- Update Android Gradle Plugin 8.0.1 -> 8.0.2 ([changelog](https://developer.android.com/build/releases/gradle-plugin#patch-releases))
- Update Gradle 8.1 -> 8.1.1 ([changelog](https://docs.gradle.org/8.1.1/release-notes.html))

#### APK testing
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by AudricV** [comment]
ExoPlayer [2.18.7](https://github.com/google/ExoPlayer/releases/tag/r2.18.7) has been released. Could you update it to this version in this PR?

**Comment by TacoTheDank** [comment]
Done.

**Comment by wb9688** [comment]
AGP can be upgraded to 8.0.2 as well

https://github.com/TeamNewPipe/NewPipe/blob/7874ef41a3d46a8a01ddc72d52b62ce8bd8a84ba/build.gradle#L10

**Comment by TacoTheDank** [comment]
> AGP can be upgraded to 8.0.2 as well

Done.

**Review by Isira-Seneviratne — APPROVED** [review]
LGTM

**Pull request merged**
