### PR TITLE
Restricted mode setting for youtube

### PR DESCRIPTION
**Pull request by vnagel**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

~~This pull request is meant to address #776.~~
EDIT: #3410 has addressed age-restricted content. This PR now adds a separate setting to enable youtube's [restricted mode](https://support.google.com/youtube/answer/174084).

When the "Restricted mode" setting is on, the Downloader uses the PREF=f2=8000000 cookie when making requests to youtube.com. The presence of this cookie activates youtube's "Restricted Mode".

Thumbnails still restricted content. This includes those in bookmarked playlists and history. I would appreciate advice on how to filter these.

This has been confirmed to work in search results, direct url search, trending, ~~what's new~~, and channel pages. EDIT: what's new also shows restricted content in the thumbnails.

Screenshots (warning, these are gory):
search: [off](https://i.imgur.com/jvzrigN.jpg), [on](https://i.imgur.com/llMNzOV.jpg)
direct url search (https://www.youtube.com/watch?v=7RoHyOFR6Vk): [off](https://i.imgur.com/rCWDjra.jpg), [on](https://i.imgur.com/Cck8Hjf.jpg)
trending: [off](https://i.imgur.com/ekFEIhZ.jpg), [on](https://i.imgur.com/rVvcwQ6.jpg)
channel page: [off](https://i.imgur.com/7UuUZvw.jpg), [on](https://i.imgur.com/Ti22pwt.jpg)

For the following, the thumbnails still show the restricted content, but clicking a video results in ["video not available"](https://i.imgur.com/Cck8Hjf.jpg) when the setting is on.
[bookmarked playlists](https://i.imgur.com/01ZIREm.jpg), [individual playlist](https://i.imgur.com/WJyN1Ry.jpg), [history](https://i.imgur.com/9LAIyRG.jpg). Restricted content is also shown in the thumbnails of "what's new".

### CODE REVIEW

**Comment by TobiGr** [comment]
Thanks for providing a fix. I am sorry for not responding earlier.

> It has not been confirmed whether the "PREF" cookie affects services other than youtube.

You might want to check the service id and only set it when youtube is the current service

**Comment by vnagel** [comment]
> You might want to check the service id and only set it when youtube is the current service

Thanks for the advice. My last commit made this change.

Should I be handling age-restricted content in bookmarked playlists, individual playlist, and history? If so, do you have any advice on how I can do that?

**Comment by Stypox** [comment]
I think it is ok that local playlists and history (also local) show thumbnails of age-restricted videos, for now. This could be fixed in a future PR, and it would require many changes in the way local things are handled (and probably also a new entry in the database to store whether a video is restricted or not).

**Comment by vnagel** [comment]
Okay, thanks for the info. I'll work on getting this branch up to date with dev. Also, I think there's possibly currently a bug with my changes where if a user sets the cookie while using youtube and then changes to a different service, the cookie won't be removed and so it will be used in the requests with the other services. I'll test this out to confirm if this is the case.
It might be 1-2 weeks before I can get to this.

**Comment by Stypox** [comment]
@vnagel does your approach overwrite the current cookie in the downloader? If so this could be an issue, since recaptchas do the same thing

**Comment by Stypox** [comment]
@vnagel ^

**Comment by vnagel** [comment]
Sorry, I will get to this tomorrow. My current approach does overwrite the current cookies in the downloader. I'll look into changing the implementation so it doesn't do that.

**Comment by vnagel** [comment]
The current approach no longer overwrites the cookies. It also doesn't check that the current service is youtube and instead checks the url that it is sending the request to. I did this because, even when the current service is youtube, it makes requests to other websites like i.ytimg.com, suggestqueries.google.com, and yt3.ggpht.com. It seems like ReCaptchaActivity only adds cookies for youtube, but I wasn't sure so right now it will send them will all requests.
I could pull out the cookie-related logic in DownloaderImpl into another class or use something like a CookieManager if you think the current implementation isn't organized well.

I get this error when I have a channel tab that has only age-restricted content (https://www.youtube.com/channel/UCUdTV6ABEbvUxVzIwFg4RKw) and I turn the show_age_restricted_content setting is off. I would appreciate help with figuring out a fix:
```
{
   "user_action": "requested channel",
   "request": "https:\/\/www.youtube.com\/channel\/UCUdTV6ABEbvUxVzIwFg4RKw",
   "content_language": "en_US",
   "service": "YouTube",
   "package": "org.schabi.newpipe.debug.agerestrictedcontentv",
   "version": "0.18.6",
   "os": "Linux Android 10 - 29",
   "time": "2020-03-16 03:20",
   "exceptions": [
      "java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Iterator com.grack.nanojson.JsonArray.iterator()' on a null object reference\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor.collectStreamsFrom(YoutubeChannelExtractor.java:225)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor.getInitialPage(YoutubeChannelExtractor.java:180)\n\tat org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:19)\n\tat org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:82)\n\tat org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:47)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$getChannelInfo$4(ExtractorHelper.java:128)\n\tat org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$u5W7VszTe8AoEexIsFM9huQfbkM.call(Unknown Source:4)\n\tat io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4154)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14479)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4154)\n\tat io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)\n\tat io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)\n\tat java.lang.Thread.run(Thread.java:919)\n"
   ],
   "user_comment": ""
} 

```

**Comment by wb9688** [comment]
This seems to block more than just age restricted videos. E.g. https://www.youtube.com/watch?v=OGS7c0-CmRs is also blocked, plus that whole channel. I think this should be a separate setting, and you should just make the current setting show the content unavailable when `getAgeLimit()` is not `NO_AGE_LIMIT`. Anyway, I'll fix the NPE.

**Comment by vnagel** [comment]
I made it into a separate setting. You're right that it blocks more than just age-restricted videos. It
actually toggles youtube's [restricted mode](https://support.google.com/youtube/answer/174084). This branch is still not ready to merge though because of the NPE.

**Comment by wb9688** [comment]
@vnagel: Please call the setting something like "Enable YouTube Restricted Mode" so that it's clear that it's YouTube-specific. As for the NPE, I'll take a look at that in a few days. It should be good to merge then.

**Comment by vnagel** [comment]
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4467020/app-debug.zip)

**Comment by wb9688** [comment]
@vnagel: NPE is fixed as a side-effect of TeamNewPipe/NewPipeExtractor#317 (which is something I had already expected)

**Comment by vnagel** [comment]
Just rebased dev.
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4507394/app-debug.zip)

**Comment by vnagel** [comment]
@wb9688 is there anything else I should do get this merged?

**Comment by wb9688** [comment]
@vnagel: I'll take a look at it soon. It's planned for v0.19.4, as you could see, and v0.19.3 just got released.

**Pull request merged**
