### PR TITLE
add database doc in dia

### PR DESCRIPTION
**Pull request by theScrabi**
This will add a databasedocumentation created using [dia](http://dia-installer.de/index.html.de). It is stored in the `assets` folder, and is ment to be used in the wiki/documentation.

@TobiGr it would be nice if you could put the svg to it somewhere usefull :).

db

### CODE REVIEW

**Comment by TobiGr** [comment]
👍 Will do this next week after I finished my last exam.

**Comment by theScrabi** [comment]
Uff two tables have the name search_history :/. Well the one pointing to streams should be called watch_history. (I think).

**Comment by TobiGr** [comment]
Yes, you're right

**Comment by TobiGr** [comment]
> it would be nice if you could put the svg to it somewhere usefull :).

@theScrabi I'd suggest to put it into the wiki and
a) create a new chapter in the documentation explaining which steps should be followed before/when implementing a new feature or
b) create a new chapter about the NewPipe's. (btw. what about the giga / downloads database which is located [here](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/java/us/shandian/giga/get/sqlite/DownloadMissionHelper.java)?)

**Pull request merged**
