### PR TITLE
Fix unwanted rich text formatting when pasting

### LINKED ISSUE #5912: Text copied from HTML is rendered in search bar
### Checklist

- [x] I am using the latest version - 0.20.11 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Copy a standard HTML tag (hX, b, i, u) from your web browser (tested in Chrome Mobile)
2. Paste into search bar

### Actual behaviour
HTML tags are rendered (see images)

### Expected behavior
Test is pasted as raw text, no rendered HTML

### Screenshots/Screen recordings

Screenshot_20210325-010906_NewPipe
Screenshot_20210325-011246_NewPipe

### Device info

 - Android version/Custom ROM version: Android 11
 - Device model: Samsung S20 FE

### PR DESCRIPTION
**Pull request by Imericxu**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
 - Use `getSpans` and `removeSpan` to remove text styling when pasting

#### Fixes the following issue(s)

- Fixes #5912 

#### APK testing 

On the website, the APK can be found by going to the "Checks" tab below the title and then on "artifacts" on the right.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TobiGr** [comment]
thank you. please add a comment in the code that it removes rich text formatting

**Comment by Imericxu** [comment]
Since this issue seems to only occur when pasting, should I modify the solution to an override of the paste method so there are no unnecessary checks in the TextWatcher?

**Comment by TobiGr** [comment]
thank you. Is there are reason for placing the code in `afterTextChanged` and not  in `onTextChanged`?

**Comment by Imericxu** [comment]
@TobiGr Unless I’m mistaken, only `afterTextChanged(…)` allows you to edit the text. Here’s the StackOverflow post where I got my info about `TextWatcher` methods: [Link](https://stackoverflow.com/questions/476848/android-textwatcher-aftertextchanged-vs-textwatcher-ontextchanged).

**Review by TobiGr — APPROVED** [review]
Thanks for the explanation!

**Pull request merged**
