### PR TITLE
Allow installation on external storage

### LINKED ISSUE #251: Allow install on external memory card
Can you set the flag to allow it to be installed on an external memory card?

### PR DESCRIPTION
**Pull request by mhmdanas**
#### What is it?
- [x] Feature (user facing)

#### Description of the changes in your PR

Allow installation on external storage.

Unfortunately, I'm not in possession of an external SD card, so I can't test this. Those who have SD cards, could you please test this?

Note that NewPipe uses [`Service`s](https://developer.android.com/reference/android/app/Service), which Android's docs state as one of [the features that if present in an app, would mean that it shouldn't be allowed to be installed on external storage](https://developer.android.com/guide/topics/data/install-location). I'm not sure if this means we shouldn't merge this PR, but I figured it would at least be relevant.

#### Fixes the following issue(s)

- Fixes #251.

#### APK testing 

https://github.com/TeamNewPipe/NewPipe/suites/2463929014/artifacts/52944489

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by AlexN1997** [comment]
It works (LG G5 android 8.0)

**I noticed a bug:**


**how to reproduce:**
play a video 
change the audio

**Comment by mhmdanas** [comment]
@AlexN1997 that doesn't seem like an issue caused by my changes. Can you try out [the latest development APK at the time](https://github.com/TeamNewPipe/NewPipe/actions/runs/735610463) and see if the bug is present there too?

**Comment by AlexN1997** [comment]
Its still here, so as you said, its not this PR causing the problem

**Review by Redirion — APPROVED** [review]
lgtm

**Pull request merged**
