### PR TITLE
Add support for comment replies

### LINKED ISSUE #2277: Display comment replies
It's great that NewPipe has the feature to view comments since the version 0.16.0! But I miss a function to view the answers of the comments.

### LINKED ISSUE #10012: SoundCloud large playlist can’t load
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.1

### Steps to reproduce the bug

This issue particularly shows up on the "Monstercat Uncaged" playlist, with 401 songs as of April 8th.
1. Open NewPipe;
2. If not already, select the SoundCloud source;
3. Search "Monster Uncaged" _or_ access it if it's saved;
4. Tap the playlist (it has 401+ songs)
5. Some elements will briefly load, but...
6. You end up with a "No videos" error.

### Expected behavior

The playlist should correctly load, listing the first songs (sorted by upload date or not), and load the next songs by scrolling.

### Actual behavior

The playlist fails to load with error message "No videos", and a disappointed Lenny.

### Screenshots/Screen recordings

Screenshot_20230408_184931_NewPipe
**Fig. 1: the saved playlist**

Screenshot_20230408_184906_NewPipe
**Fig. 2: the playlist failing to load**

### Logs

N/A

### Affected Android/Custom ROM version

OneUI 5.1 (Android 13)

### Affected device model

Samsung Galaxy A71 4G (SM-A715F/DS)

### Additional information

- playlist exists and is public on SoundCloud
- attempted on fresh install of NewPipe
- attempted on Wi-Fi with 433 Mbit/s (≈ 54 Mb/s)
- disabled VoLTE due to Exynos vulnerability
- disabled "Calls over Wi-Fi" due to Exynos vulnerability

### PR DESCRIPTION
**Pull request by Stypox**
#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

The most basic implementation of comment replies. The replies are shown in a fragment opened from the main activity, instead of on top of the video detail fragment. Although this might be a bit unexpected, this can be improved later, since I tried and found it too cumbersome to open fragments on top of each other*.

\* *Yet another broken thing in the current app architecture: opening new fragments from within one fragment. With the old Android APIs it would take something like 100 lines of code spread across many files, since you would have to create a stack of fragments in the base activity, then implement proper state saving in the stack, then push and pop items from the stack in the correct way, ... If we used the modern APIs instead, after the initial setup in the topmost activity, it would be as simple as writing something along the lines of `findNavController(...).navigate(viewId, arguments)`.*

#### Implementation notes

- I removed the comment mini variant since it was never used. Now only one variant exists, which reduced code duplication and made it simpler to edit the layout to add the replies button.
- The comment item layout had a few changes (other than adding the replies button) that fixed RTL warnings.
- I moved `RelatedItemsInfo` in the same folder as `RelatedItemsFragment`, since it wouldn't make sense for that class to stay in `util`. I also simplified the code in that class. Although this is an unrelated change, I did it because I also added `CommentRepliesInfo` that works in a similar way, and put it in the same folder as `CommentRepliesFragment`.
- At first I though that to load comment replies the extractor needed the original `CommentsInfo` object, so I made bb01da3691ff1d5c3dccd41b7ca1a5deb1b5676f, but then I found out that the url is enough, so I reverted that change in 50a3ae67d21538f70c91d26cebc28156f0ea2c10.
- The replies page has at the top the starting comment of which replies are shown. The text size there is a bit larger than for comment items, and the comment content is always expanded.
- The only code smell reported by Sonar is about `CommentInfoItemHolder.updateFromItem`, but I would ignore this warning since I already simplified many parts of that method in 8bd42d952e52d98a4e33c8046fab5a200f5a5130 and added comments to separate the various actions being performed.

#### Before/After Screenshots/Screen Record
<table>
  <tr>
    <th>Before</th>
    <th>Video details page</th>
    <th>Replies page</th>
    <th>With heart and pin</th>
  </tr>
  <tr>
    <td>Before</td>
    <td>Video details page</td>
    <td>Replies page</td>
    <td>With heart and pin</td>
  </tr>
</table>

<sup>Note to blog post writers: I just noticed these images contain some aggressive comments in Italian, so they need to be taken again</sup>

#### Fixes the following issue(s)

- Closes #2277
- Fixes #10012 thanks to https://github.com/TeamNewPipe/NewPipe/commit/e236d370c85cbc9766fbd64330d6cf5754fee81d, also see https://github.com/TeamNewPipe/NewPipeExtractor/pull/1049

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

This PeerTube video has nested replies, but they don't seem to work: https://share.tube/w/vxu4uTstUBAUromWwXGHrq.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

----
**Notes for the website team:**  make sure to modify the [corresponding FAQ entry](https://newpipe.net/FAQ/#bugs-read-comments) when updating the page for the release.

### CODE REVIEW

**Comment by tsiflimagas** [comment]
It works good and pagination works well too, I can load 500 comments. Though, I think that "List view mode" shouldn't affect the way comments are displayed (grid view for comments doesn't look well). Probably I'm ignoring that's an impact of how the fragment is opened, but idk the technical stuff.

**Comment by Stypox** [comment]
@TobiGr this PeerTube video has nested replies, but they don't seem to be returned by the extractor: https://share.tube/w/vxu4uTstUBAUromWwXGHrq.

**Comment by nicoursi** [comment]
This is nice but there's a behaviour I think should be fixed: when comment replies are open, the android back button should just close the replies and not get back to the last video list.

**Comment by Stypox** [comment]
That's an inconsistent behavior that is independent of this PR and is definitely strange. According to @opusforlife2 in Android the expected behavior for the top-left back button is to go to home, while the system back button should go to the previous fragment. This can be fixed in a separate PR.

**Comment by TobiGr** [comment]
> @TobiGr this PeerTube video has nested replies, but they don't seem to be returned by the extractor: https://share.tube/w/vxu4uTstUBAUromWwXGHrq.

See TeamNewPipe/NewPipeExtractor#1052

**Comment by MD77MD** [comment]
i think the approach in [Show comment replies #9410] by @xz-dev  is much better because:
1. it does not take us to a new page
2. if we scroll down throw comments and finish reading  a reply, going back will always take me to the top of the comments page then we need to scroll back to where we were.
3. and most important,  it open replies in an expandable/ retractable list that doesn't cut our flow off reading

**Comment by MD77MD** [comment]
198816463-3fbb757b-e897-432f-94d3-f381135fd57f

**Comment by Stypox** [comment]
@MD77MD yes, if only it didn't have bugs and object cloning. I have already explained why this choice is being made.

**Review by TobiGr — APPROVED** [review]
Annotations are missing. Once added, this can be merged

**Comment by Stypox** [comment]
I think tour commit does not provide a proper behaviour:
- pressing the system back button correctly closes the replies fragment and brings you back to the video
- pressing the back arrow at the top left of the screen does not close the replies fragment
- when there are nested replies, going back correctly closes only the top fragment, but the video is always brought up even if you were looking at the replies of a nested comment, which is unexpected imo (you can test with the URL in the PR description)

**Comment by TobiGr** [comment]
I fixed the behaviour you pointed out above.

One thing that I noticed is that the DetailFragment is scrolled to top after it is expanded from the BottomSheetBehaviour. I pushed a second commit which should help us to scroll to the last clicked comment. However, when calling `CommentsFragment.scrollToComment` nothing happens. Any ideas why?

**Comment by ayyyiieneheuihues** [comment]
Why isn't this in the NewPipe app yet?

**Comment by Univers4craft** [comment]
hello here are two photos of the new and old ones in case they can be useful to you.

Screenshot_20231124_214731_NewPipe

Screenshot_20231124_214750_NewPipe

**Comment by C-O-D** [comment]
What is the current status of the comment replies? It's quite difficult to see through all the requests to find out which one is the current one and how things have been left...

**Comment by Stypox** [comment]
I rebased, fixed various problems with going back from the replies fragment to the video details fragment, and added the `@NonNull` annotation as requested by @TobiGr's review. If nobody has anything against it, I will merge this PR as it is now. I might try to open another PR soon that implements PipePipe's behavior: https://github.com/TeamNewPipe/NewPipe/pull/10018#issuecomment-1679714985.

**Pull request merged**
