### PR TITLE
Remove padding from the end of the mini-player

### LINKED ISSUE #8615: There is a gap at bottom-left of miniplayer near close button
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

Recently i got to know that there is little gap near botton-left of miniplayer (collapsed video player) near the close button, sometime when we try to press close button, the gap get clicked causing miniplayer to expand to full player which is annoying. So i want to ask if this gap is there for some obvious reason or just a bug that left out unnoticed ?

### Additional information

Here are some images:

IMG_20220712_150142_775

App version 0.23.1
Android: 11

### PR DESCRIPTION
**Pull request by shivambeohar**
#### What is it?
- [x] Bugfix (user facing)

#### Description of the changes in your PR

- removed right-padding of close button LinearLayout.

#### Before/After Screenshots/Screen Record

<table>
  <tr>
    <th>Before</th>
    <th>After</th>
  </tr>
  <tr>
    <td>Before</td>
    <td>After</td>
  </tr>
</table>

#### Fixes the following issue(s)

- fixes #8615

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by shivambeohar** [comment]
Hey, @mhmdanas,
Can you please review the PR, I couldn't able to add the reviewer for this PR.

**Comment by Stypox** [comment]
@shivambeohar I edited the description to make it more readable, please take a look at my changes

Also see my comment in https://github.com/TeamNewPipe/NewPipe/issues/8615#issuecomment-1207274342

**Review by Stypox — CHANGES_REQUESTED** [review]
This is not the proper way to do it: tapping on `R.id.overlay_buttons_layout` should not close the player. What I propose is to remove all padding from the `overlay_buttons_layout` (you can remove the lines) and change widths, heights and paddings of the `overlay_play_pause_button` and `overlay_close_button` in order to get the same layout as the current one, but with more clickable space for those buttons.

**Review by Stypox — APPROVED** [review]
I pushed a commit that correctly considers the space to the right of the close button as part of the close button. I also added a content description to the buttons, and made sure the `large-land` layout is up-to-date with the non-`large-land` one.

**Pull request merged**
