### PR TITLE
Implement resizable popup

### PR DESCRIPTION
**Pull request by mauriciocolli**
- Resizable popup
    - You can enter in resize-mode when you longpress one of the sides of the popup
    - Remember/save the popup position and size 
- Fix bug occurring after screen rotation
    - Check if position is greater than the bounds of the (new sized) screen

### CODE REVIEW

**Comment by theScrabi** [comment]
Nicely done, but please remember to fix https://github.com/TeamNewPipe/NewPipe/issues/517 its important.

**Comment by mauriciocolli** [comment]
Lol, did you read the message of the pull request?

But nevertheless, this is a sign that this feature is not very user discoverable.
Maybe show a tip on the first use? Maybe other gesture? Idk...

But I think you should merge it, as it fixes a bug in the popup, and if something better comes to mind, I'll open another PR.

**Comment by theScrabi** [comment]
Yea, no didn't reed you're right.
I thought it was some kind of two finger gesture.

**Comment by mauriciocolli** [comment]
Will this be merged?

**Comment by theScrabi** [comment]
Yes ... I'll alway try to merge and release on weekends, but I'm ill at the moment, and I'm almost not able to leave the bed.

**Comment by mauriciocolli** [comment]
Oh okay, good recover to you.

**Comment by theScrabi** [comment]
thanks :)

**Comment by theScrabi** [comment]
Although my opinion is still that two finger resize feels more swift, and is more intuitive. So maybe we can have both ;)

**Comment by SteveJobzniak** [comment]
@theScrabi Two finger resize is more intuitive, it was the first thing my mom tried.

Btw when is the resizable popup coming to F-Droid's repo? My mom's tablet has a postage stamp sized video lol.

**Comment by theScrabi** [comment]
@SteveJobzniak you can tell your mom next release is on its way ;).
We are basically waiting for f-droid to build the new release, which takes usually about two or three days. So since I released yesterday, it may be available on Thursday or Wednesday.

**Comment by SteveJobzniak** [comment]
@theScrabi Thanks, she's happy from the news. :-) Soon she can watch larger cat video popups while doing her puzzle games. xD

**Pull request merged**
