### PR TITLE
Add an option to Ignore hardware media button events

### LINKED ISSUE #9745: Add an option to disable prev/next track buttons on headsets
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

My plan is to add a new option under Video and audio/Behavior, which would look like this:
```
Ignore headset media button presses  
Notice: In the case of a Bluetooth headset, all media button events will be ignored, which breaks the Media Control UI in the notification area
```

When the option is enabled, it should do precisely what its description states.
Because it is impossible to distinguish between events that come from a Bluetooth headset and the control UI, it will ignore events from both sides. However, this should only occur when a Bluetooth headset is detected.
See also: https://code.videolan.org/videolan/vlc-android/-/merge_requests/1633

### Why do you want this feature?

I sleep with my headset on. However, I often press the prev/next track buttons on the headset by accident, which causes the video to rewind or skip. Needless to say, this is quite inconvenient.  
Unfortunately, on Android, there is no way to disable media buttons globally without rooting the phone or physically blocking the pin (which also disables the mic). This means I need the option to make the player ignore those presses.
I'm planning to implement it myself today. But I would also like to know if someone else is interested in such a feature.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by NyanCatTW1**
#### What is it?
- [ ] Bugfix (user facing)
- [X] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Adds an option called "Ignore hardware media button events", which disables any pause/play and the prev/next track buttons, including ones on a headset. It helps prevent accidental touches and makes the app more usable on a headset with broken buttons.

#### Before/After Screenshots/Screen Record

The option is inside the Video and audio category.
- Before:
image

- After:
image

#### Fixes the following issue(s)

- Fixes #9745

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [X] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by Stypox — CHANGES_REQUESTED** [review]
Thanks! I don't think it's a good idea to add the `BLUETOOTH_CONNECT` permission. Unfortunately unless there is a different way to tell media button events apart, I don't think this will be merged.

**Comment by NyanCatTW1** [comment]
Actually, it seems like only hardware media events go through the custom handler. Therefore, it should be safe to just not distinguish them.
I will make the changes in two or three days

**Comment by Stypox** [comment]
Ok, thanks. So the setting description should be updated to explain that all hardware actions will be blocked (including bluetooth ones). Then it will be up to users to choose if they want to enable this setting or not.

**Comment by NyanCatTW1** [comment]
I made a mess with the git history on the fork, but it should be ready for preview now  
It now ignores all events that go through the MediaButtonEventHandler, which should hopefully be exactly what's needed to achieve the desired behavior

**Comment by Stypox** [comment]
I pushed some improvements to make code shorter and a bit more performant. I tested with a bluetooth speaker and the hardware buttons get correctly blocked when the setting is on. Are the changes I pushed ok, in your opinion? Thanks!

**Comment by NyanCatTW1** [comment]
Looks nice! So I suppose it's ready for merge now?

**Review by Stypox — APPROVED** [review]
Yes, thanks for confirming :-)

**Pull request merged**
