### PR TITLE
Include media.ccc.de click handlers

### PR DESCRIPTION
**Pull request by codingHahn**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

This is my first time contributing to a android app.
Is there anything else to do besides changing the AndroidManifest.xml?

### CODE REVIEW

**Comment by chetan00000007** [comment]
How to do this

**Comment by TobiGr** [comment]
Did you test your changes? This needs changes in the extractor as well.

**Comment by codingHahn** [comment]
I did not. I have not gotten the Android Environment to work yet. Do you have some pointers to the required changes?

**Comment by Stypox** [comment]
@codingHahn somewhere in here most probably: https://github.com/TeamNewPipe/NewPipeExtractor/tree/dev/extractor/src/main/java/org/schabi/newpipe/extractor/services/media_ccc/linkHandler

**Comment by wb9688** [comment]
This has already been added to NewPipe by #3090 now

**Pull request closed without merging**
