### PR TITLE
Pull up support lib version so all always match

### PR DESCRIPTION
**Pull request by Jawnnypoo**
- [ X ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

Pretty simple thing, hope it will make updating this less of a headache later

### CODE REVIEW

**Comment by theScrabi** [comment]
Have you checked if this will compile with the current fdroid build environment?

**Comment by Jawnnypoo** [comment]
Hrm, wow that is frustrating. I thought I remembered F-Droid trusting by maven url and not by individual artifacts. Sounds good though 👍

**Comment by avently** [comment]
Nice trick

**Comment by theScrabi** [comment]
According to fdroid its supported now :)

**Comment by Jawnnypoo** [comment]
Nice! 👍

**Pull request merged**
