### PR TITLE
Change Autoplay to Autoqueue to reduce ambiguity

### PR DESCRIPTION
**Pull request by opusforlife2**
#### What is it?
- [x] Bug fix (user facing)

#### Description of the changes in your PR

- The toggle which appends related streams is called Autoplay. Now that there is an actual Autoplay setting, this can cause confusion for users.

#### Fixes the following issue(s)

- Confusion

#### Agreement
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Review by TobiGr — APPROVED** [review]
Looks good to me. I don't have time to test the change and see it in the app.

**Comment by wb9688** [comment]
Is it possible to remove `autoplay_title` or do we depend on it elsewhere?

**Comment by opusforlife2** [comment]
Settings > The _actual_ autoplay setting (off, wifi, always).

**Comment by wb9688** [comment]
Hmm… where is `autoplay_by_calling_app_title` used then?

**Comment by opusforlife2** [comment]
Wow. Nowhere. It's only present in XMLs.

**Review by Stypox — APPROVED** [review]
Tested, works as expected. Thank you ;-)

**Pull request merged**
