### PR TITLE
first commit

### LINKED ISSUE #8179: Download popup file already exists action buttons display issue
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

1. Go to "Settings" -> "Video and audio" -> Behavior / Preferred 'open' action -> Select "Download"
2. Open Chrome (should work with other web browner)
3. Go to a video link (search "me at the zoo" for example)
4. Open the link with NewPipe
5. The NewPipe download box will open, click on OK to download the video.
6. Wait the download is over
7. On Chrome, select again the same video link
8. Open the link with NewPipe
9. The NewPipe download box will open, click on OK to download the video.
10. The popup "A downloaded file with this file name is already exists" will open but the action buttons "Cancel" and "Overwrite" will not be display

### Expected behavior

Action buttons "Cancel" and "Overwrite" should be display in the the popup "A downloaded file with this file name is already exists"

### Actual behavior

Action buttons "Cancel" and "Overwrite" are not display in the the popup "A downloaded file with this file name is already exists"
The button are there because we can click on them to have the good behavior but they are not displayed.

### Screenshots/Screen recordings

Screenshot_20220412-121359
Screenshot_20220412-122153__01
Screenshot_20220412-122147__01
Expected : 
Screenshot_20220412-122330

### Logs

_No response_

### Affected Android/Custom ROM version

Android 11 / OxygenOS 11.1.2.2

### Affected device model

OnePlus 6T

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by blackwang08**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Because In some cases, the original way of creating Alterdialog will make the text of the button become white so it seems to be invisible. To solve this question, I force the text of the button become black to avoid this problem.

#### Before/After Screenshots/Screen Record

- Before:

https://user-images.githubusercontent.com/76472486/165544923-2387ed48-0eaf-45a9-9f9e-22368d649285.mp4

- After:

https://user-images.githubusercontent.com/76472486/165545112-60d4cd50-ce13-49ba-b4b3-783093c8e050.mp4

#### Fixes the following issue(s)

- Fixes #8179 

#### Relies on the following changes

- 

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by litetex** [comment]
This PR has multiple problems:
1. You didn't read the contribution guidelines
   * The branch-name, commit and PR title are not meaningful
2. The PR does not fix the problem: NewPipe has a dark mode; black text on dark background is not a good idea
    We also use styles and themes for styling and not hardcoded values.
    You may consider reading https://developer.android.com/guide/topics/ui/look-and-feel/themes

**Comment by blackwang08** [comment]
I have change the way to fix this question using styles and themes instead of hardcoded values, and some mistake in pull request format. new pull request have fix this question in three color mode.

**Comment by blackwang08** [comment]
I'm very sorry for the inconvenience

**Comment by blackwang08** [comment]
here is the new pull request. https://github.com/TeamNewPipe/NewPipe/pull/8305

**Pull request closed without merging**
