### PR TITLE
Change "Export" to "Import" in Korean Readme instructions

### PR DESCRIPTION
**Pull request by opusforlife2**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [x] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Both the middle and last steps said to "export database". Changed the latter to "import".

#### Fixes the following issue(s)

- Possible confusion in Korean users.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TobiGr** [comment]
Is there no Korean translation of these strings in the app? Why are the English words used here?

**Comment by opusforlife2** [comment]
You'll have to ask Kim Min-Tae. ¯\\\_(ツ)\_/¯

**Comment by TobiGr** [comment]
CC @KIMMINTAE98

**Comment by opusforlife2** [comment]
You could just merge this and change the language later, when a Korean contributor is available.

**Review by TobiGr — APPROVED** [review]

**Pull request merged**
