### PR TITLE
Fix various issues in the search suggestions list

### PR DESCRIPTION
**Pull request by Stypox**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
This PR fixes the various issues that arose after upgrading the search suggestions list code in #8719: inconsistent item icons on the left sometimes (e.g. history icon when the item is not from history), strange item movements when changing the list, strange scrolling behavior when the suggestions change (i.e. not scrolling always to the top on change). See the three commits' messages for more information. @Isira-Seneviratne could you review?

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Isira-Seneviratne** [comment]
@Stypox Thanks for the improvements for my changes, I'll be checking soon.

**Comment by MD77MD** [comment]
I'm not sure if this is related or i should open a new issue  but there are bugs when you trying to edit the wording of a search sentence in the search field. 
first one, when you do a long press to select a certain word in search sentence, the hole search sentence is selected instead. 

the other one is if you try to select multiple words using swipe select (by long pressing a certain word to activate select, then moving right and left while holding) it will work but in a broken way.. the swipe select will work but the point of activation would jump from the word you long pressed to the first word of the search sentence

**Comment by privacyonly** [comment]
off topic by a little but since the title says fix various issues in the search suggestion list,

if suggestqueries.google.com is blocked, there will be multiple warning at the bottom of the screen "Sorry, Something went wrong" Report.

can we not show this?

**Comment by opusforlife2** [comment]
> if suggestqueries.google.com is blocked, if we type something in the search box, there will be multiple warnings at the bottom of the screen, "Sorry, Something went wrong" Report.

Why not turn off search suggestions if you don't want them?

**Comment by privacyonly** [comment]
didn't know it was there. thanks. but shouldn't the error be more specific like search suggestion error or something.

**Comment by opusforlife2** [comment]
You could open a new issue for that.

**Pull request merged**
