### PR TITLE
Long Volume Button Press for Playback Control

### LINKED ISSUE #6874: Volume Button Long Press Playback Control.
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.  <-- I did and found noothing -->
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I would like NewPipe to have the ability to **_react to volume button long presses by skipping_** to the next or previous track.
This would require an additional entry in the "Video and Audio" Settings to enable.

**Implementation** would simply follow along existing tutorials / implementations (https://stackoverflow.com/questions/12950215/onkeydown-and-onkeylongpress) and call the required function to skip to the next or previous track.

The settings entry to enable this feature would need to check the permission  `android.permission.SET_VOLUME_KEY_LONG_PRESS_LISTENER` to enable receiving the long press.
Failure could show a toast that the permission is missing.

This is in my opinion the only caveat if this feature as there is no neat android implementation for such a permission request. It has to be granted by adb.
`adb shell pm grant org.schabi.newpipe android.permission.SET_VOLUME_KEY_LONG_PRESS_LISTENER`
However this would not disrupt the usual amateur end user as it is a little known (and thus not expected) Android feature anyways, serving usually only those who know about it. 

**Alternative** is a external app that runs all the time when music is played, for example: https://github.com/Cilenco/skipTrackLongPressVolume, which leads to additional battery drainage and resource usage.

#### How will everyone benefit from this feature?

In most Android Roms there is currently no other way to use this available feature, which would enrich music listening experience by quite a lot. Especially since NewPipe supports music playing while the screen is off.
It would provide a very accessible way to control music playback, while not being able to use the touchscreen of the device (on a car ride/ on a run/ while working).

I intent on looking into implementing this feature myself, although I am unsure on where to best place the onLongPress function (Main? idk) and how to implement the settings entry (this should be solved by looking through other examples in code).

### PR DESCRIPTION
**Pull request by yashaswigalhotra**
#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
- Added a new feature :- Long Volume Button Press for Playback Control

#### Before/After Screenshots/Screen Record
<table>
  <tr>
    <th>Before</th>
    <th>After</th>
  </tr>
  <tr>
    <td>This is an image before long press of volume button</td>
    <td>This is an image after long press of volume button which activates the playback control and plays the next video</td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
</table>

#### Fixes the following issue(s)
- Fixes #6874

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Stypox** [comment]
Thank you! :-)
Unfortunately the build fails, and you seem not to have followed the advice from the user in #6874. Also, this feature would have to be enabled only on phones where the `android.permission.SET_VOLUME_KEY_LONG_PRESS_LISTENER` permission is active, as not to be in the way of all other users, since it would have to be granted via `adb` anyway, according to #6874. @yashaswigalhotra @z3r0r4

**Comment by mhmdanas** [comment]
@stypox let's avoid putting `waiting-for-author` on PRs for now. 14 days is a little too short for them.

**Comment by Stypox** [comment]
Oh ok, I see

**Comment by z3r0r4** [comment]
First of all; I am indeed surprised that someone besides me has shown interest and tried to implement this. I tried and sadly ended up running out of the time I had free.
This however might serve as a good starting point and I'll try to verify and tie up lose ends if possible.

> Also, this feature would have to be enabled only on phones where the `android.permission.SET_VOLUME_KEY_LONG_PRESS_LISTENER` permission is active, as not to be in the way of all other users, since it would have to be granted via `adb` anyway, according to #6874. @yashaswigalhotra @z3r0r4

Yes this was my initial intention, it should not be a feature that taunts the less tech-savy users but rather one that improves the experience of those that know about it by a lot.

**Comment by z3r0r4** [comment]
> This is normally an OS level feature: ...
> Edit: the user in the linked issue seems to be asking for this feature when the screen is off, so I'm assuming only some Custom ROMs or OEM ROMs offer this feature currently. In that case, this should be modified to work only when the screen is off.

Your edit explains my reasons @opusforlife2.
Personally I've only seen this feature implemented in custom ROMs (LineageOs) and am missing it dearly in the Samsung One Ui. Thus at least from my perspective its a feature that's normally missing from.
And yes this feature was mostly meant to be useful in situations where touch control is very inconvenient (driving, running, writing...), although admittedly imo its a faster way to control playback when the screen is on as well.

**Comment by z3r0r4** [comment]
I am not convinced that this code is complete. 
Most of the used variables and symbols in the new lines dont seem to resolve and the changes to the onKeyDownListener are incompatible with existing code. 
Good starting point, but does not work yet.

**Comment by litetex** [comment]
No feedback since over a month and also the PR is not compiling.
Converted it to a draft and closing it for now.

Feel free to reopen it again when there is further progress.

**Pull request closed without merging**
