### PR TITLE
Improve long-press menu strings

### PR DESCRIPTION
**Pull request by Stypox**
#### What is it?
- [x] Bug fix (user facing)
- [ ] Feature (user facing)
- [ ] Code base improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
According to a user on IRC "the menu is confusingly worded, [...], it seems to correctly enqueue in the miniplayer and in the background, it just calls it "a new" miniplayer even if there is already a miniplayer, which obscures the fact that the action will enqueue a song". So I removed the `new` word from the long-press menu strings

#### Agreement
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by B0pol** [comment]
You should've done that through weblate

**Comment by Stypox** [comment]
I didn't know english strings can be changed through weblate, sorry

**Comment by B0pol** [comment]
It can, and it's much faster since the other translators will be instantly allowed to translate it.
Now it requires a sync

**Comment by TobiGr** [comment]
@B0pol I'll merge weblate later today

**Comment by TobiGr** [comment]
Weblate is in sync with our dev branch. I didn't need to take action.

**Pull request merged**
