### PR TITLE
Update FilePicker to our custom fork and disable Jetifier

### PR DESCRIPTION
**Pull request by TacoTheDank**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
- Use our custom fork: please acknowledge the changes found [here](https://github.com/TeamNewPipe/NoNonsense-FilePicker/compare/4.2.1...5.0.0).
- Disable Jetifier.

#### APK testing 
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Stypox** [comment]
Thank you! Is there still something you need to do before this PR is ready for review?

**Comment by TacoTheDank** [comment]
> Thank you! Is there still something you need to do before this PR is ready for review?

I think everything is good now. I'll undraft.

**Review by litetex — APPROVED** [review]
Code LGTM

Tested it by using an Android 5 emulator and disabling SAF, seems to work as expected:
grafik

**Comment by opusforlife2** [comment]
What if we went all-in on SAF and removed NNFP completely? 👀

**Comment by TacoTheDank** [comment]
@opusforlife2 According to Stypox, that isn't really possible. :( https://github.com/TeamNewPipe/team/issues/25#issuecomment-1147639284

**Review by Stypox — APPROVED** [review]
I read the diff you provided and changes look good.
I tested the changes by enabling NNFP and then importing, exporting, setting download folders and downloading, and everything worked.
Why are the library's `compileSdk` and `targetSdk` 28? Not that it makes any difference.

**Comment by TacoTheDank** [comment]
> Why are the library's `compileSdk` and `targetSdk` 28?

It's the minimum required to use AndroidX. Also, 29 is where Google started messing around with filesystems and pushing SAF (and I agree with why, it's just annoying and the API is doodoo). So there isn't really a reason to bump it beyond 28 (at least for now).

**Comment by Stypox** [comment]
Right, thanks for clarifying

**Comment by TobiGr** [comment]
This PR increased the build time by 3 minutes, which is almost twice the time it needed before.
See the [build of 571bf39](https://github.com/TeamNewPipe/NewPipe/runs/7801688840?check_suite_focus=true) and [the build of the previous commit on dev](https://github.com/TeamNewPipe/NewPipe/runs/7707468959?check_suite_focus=true).

**Comment by TacoTheDank** [comment]
@TobiGr Hmm... Looking at the build-test-and-jvm CI you linked, the original filepicker build had a weird issue where the "Post set up JDK 11" step took a whole minute. I reran the build and now it looks [much more normal](https://github.com/TeamNewPipe/NewPipe/runs/7811978506?check_suite_focus=true).

Is there a way to analyze how much time each task takes for the `./gradlew assembleDebug lintDebug testDebugUnitTest --stacktrace -DskipFormatKtlint` command used in `Build debug APKs and run jvm tests`? Obviously the only thing I can see is the total amount of time (which isn't helpful if we want to inspect individual tasks).

**Pull request merged**
