### PR TITLE
add tablet screenshot

### PR DESCRIPTION
**Pull request by theScrabi**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by TobiGr** [comment]
[Fastlane and F-Droid allow us](https://f-droid.org/docs/All_About_Descriptions_Graphics_and_Screenshots/) to make a difference between phone and tablet screenshots. Instead of using the `phoneScreenshots` directory, we can use either `sevenInchScreenshots` or `tenInchScreenshots`. 
@theScrabi Which directory is the correct one?

**Comment by theScrabi** [comment]
tenInchScreenshots

**Comment by TobiGr** [comment]
Thanks. I'll add these changes to my current PR.

**Comment by theScrabi** [comment]
Nice :)

**Pull request merged**
