### PR TITLE
Add RTL layout support

### LINKED ISSUE #3882: RTL UI for rtl languages such as ckb,ku,ar,urdu...etc
Hey
Can we have RTL UI when we will change the language to an RTL language? three dash menu goes to righ side and texts also.

Best Regards.

### PR DESCRIPTION
**Pull request by mhmdanas**
#### What is it?
- [x] Feature (user facing)

#### Description of the changes in your PR

Add RTL layout support to NewPipe.

Based on https://github.com/TeamNewPipe/NewPipe/pull/3488 by @Royosef (thank you for your work!). Differences:
- Fixed merge conflicts
- Removed RTL handling from `AboutActivity`, since ViewPager2 supports RTL natively
- Other minor refactors

Issues to fix:

- [ ] Dialog action buttons should be reversed in order
- [ ] Broken with #4833
- [x] ~~fast-forward/reverse seek in player (double taps) are not reversed accordingly~~ seekbar isn't flipped anymore, so this isn't necessary (it might be necessary to investigate the player more closely in general)

#### Before/After Screenshots/Screen Record

| Before | After |
| ------ | ----- |
| Subscriptions before | Subscriptions after |
| Drawer before | Drawer after |
| Comments before | Comments after |
| Player before | Player after |
| About us before | About us after |
| Licenses before | Licenses after |

#### Fixes the following issue(s)

- Fixes #3882

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

**NOTE**: SQUASH MERGE

### CODE REVIEW

**Comment by mhmdanas** [comment]
Regarding this suggestion from https://github.com/TeamNewPipe/NewPipe/pull/3488:

> I'd merge LocalizeLayoutUtils (used to know if the device should be RTL and one method around that) and AndroidTvUtils to DeviceUtils.

I don't think we should merged `LocalizeLayoutUtils` to `DeviceUtils`. A device can not be RTL; a locale _can_ be RTL. Also, if the user chooses a language in NewPipe different from their system, then it's not really related to their device anymore.

**Comment by opusforlife2** [comment]
> It doesn't make sense to call a device RTL

Indeed.

**Comment by mhmdanas** [comment]
The CI is failing because of this line:
https://github.com/TeamNewPipe/NewPipe/blob/dd9772cde20535fba1ff0372895795c91d1212f3/app/src/androidTest/java/org/schabi/newpipe/local/history/HistoryRecordManagerTest.kt#L71

On first look this doesn't seem to be related to the PR, but no such failure is present on `dev`, so either the test is flaky, or I've messed up something.

**Comment by mhmdanas** [comment]
So the only issue I found so far with my PR is this:
App in Arabic but system in English

Both app and system in Arabic

In both screenshots, NewPipe's language is Arabic, but in the first one, the system language is English, while in the second it's Arabic. As you can see, the buttons are in different positions. I've checked with some other apps (e.g. Tasks) and they don't seem to exhibit this issue (i.e. they behave as the second screenshot when in RTL).

Do you think this is a blocker?

**Comment by mhmdanas** [comment]
If I want to always use LTR in certain places, is it better to use `left` and `right`, or should I use `start` and `end` but with `android:layoutDirection="ltr"`?

**Comment by Stypox** [comment]
@mhmdanas probably `left` and `right` so that only the things that you specify are affected, otherwise (I think) `android:layoutDirection="ltr"` would propagate to all attributes and children. Unless you just want the latter ;-)

**Comment by mhmdanas** [comment]
The player is too complicated for me to touch in this PR, so I'll try to leave it as-is for now, and perhaps open an issue when this PR is merged.

**Comment by mhmdanas** [comment]
I don't think I'll be picking this up, so I'll be closing it (though I'd be happy to see someone else finish up the work).

**Pull request closed without merging**
