### PR TITLE
Increased the description and upload date text size

### LINKED ISSUE #9738: font  description vídeos
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Videos description font, the size of the letters are too small, I want to ask to increase the size

### Why do you want this feature?

> to improve the visualization of the information of the videos
Screenshot_20230203-005343

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Marius1501**
#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Increased the text size of the video description and of the upload date

#### Before/After Screenshots/Screen Record

| Before  | After |
| ------------- | ------------- |
| grafik | grafik|

#### Fixes the following issue(s)

- Fixes #9738 

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Stypox** [comment]
@opusforlife2 the system font size setting is always enforced, as a multiplier to all of the text sizes specified as `sp`.

**Comment by Stypox** [comment]
I don't know whether merging this would make sense. Text sizes are different all over the place in NewPipe. For example, comments are even smaller, at 12dp. So we would need a complete overhaul of text sizes in NewPipe.

**Comment by Marius1501** [comment]
@Stypox Allright, thank you for your advice!

**Comment by Marius1501** [comment]
So, should I close this PR? @Stypox

**Comment by Stypox** [comment]
> Then shouldn't all text in Newpipe that is meant to be read match the exact size of the "lorem ipsum" text in the system Font Size menu?

No, since we can still specify the size of text based on `sp`. For instance, let's say that when the "lorem ipsum" text is 20px high, then e.g. 8sp corresponds to 10px. If the user then scales the "lorem ipsum" text to be 30px high, then 8sp will correspond to 15px.

> So, should I close this PR?

Yes, thanks anyway :-)

**Comment by Stypox** [comment]
The text size for labels is usually smaller (see [the material design 3 spec for jetpack compose](https://developer.android.com/jetpack/compose/designsystems/material3#typography)), but other than that yeah, all other texts should be at least "body" (which should match the lorem ipsum size).

**Comment by Stypox** [comment]
It will be a choice when we will rewrite the app, but yeah, if you want to open an issue feel free to proceed

**Pull request closed without merging**
