### PR TITLE
Add Weblate widget to README

### PR DESCRIPTION
**Pull request by Stypox**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [x] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
While taking a look at FreeTube repo I found out they had a great-looking weblate widget, and I thought NewPipe should also have it. I took the dark "Big status badge" from [here](https://hosted.weblate.org/widgets/newpipe/), let me know if you would prefer another one.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by opusforlife2** [comment]
I like it.

**Comment by TobiGr** [comment]
Good idea°
I prefer the white widget

**Comment by opusforlife2** [comment]
If not black, then grey?

**Comment by Stypox** [comment]
@TobiGr I made it grey

**Review by TobiGr — APPROVED** [review]

**Pull request merged**
