### PR TITLE
Use Objects methods in the extractor.

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Use `Objects` methods in the extractor.

#### Relies on the following changes

- https://github.com/TeamNewPipe/NewPipeExtractor/pull/419

#### APK testing 

debug.zip

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Stypox** [comment]
This is unneeded if the API of the Extractor exposed to the app didn't change

**Comment by Isira-Seneviratne** [comment]
> This is unneeded if the API of the Extractor exposed to the app didn't change

In that case, shall I close this? And should the create PR option in the Extractor PR be unchecked?

**Comment by opusforlife2** [comment]
> I agree to create a pull request for NewPipe as soon as possible to make it compatible with the changed API.

If the API didn't change, you don't need to open a PR. But you can still leave the box checked because you're not refusing it, you just don't need it.

**Comment by Isira-Seneviratne** [comment]
> > I agree to create a pull request for NewPipe as soon as possible to make it compatible with the changed API.
> 
> If the API didn't change, you don't need to open a PR. But you can still leave the box checked because you're not refusing it, you just don't need it.

Okay, thanks!

**Pull request closed without merging**
