### PR TITLE
Fix error notification on KitKat

### PR DESCRIPTION
**Pull request by Stypox**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
The app was crashing when trying to display an error notification on KitKat, this PR fixes that by using a non-vector-drawable on API < Lollipop. I also replaced `NotificationManager` with `NotificationManagerCompat`, just like in the player's `NotificationUtil`.

The crash was encountered while testing other thing and is about "Bad notification posted from package ... Couldn't create icon ..."

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by litetex — CHANGES_REQUESTED** [review]
Superseded by #7613

**Comment by Stypox** [comment]
@litetex I know, but if we release another release without #7613 this can be merged (but let's make next release with #7613)

**Comment by Stypox** [comment]
@litetex can you review and merge? #7613 will not be in this release

**Review by litetex — APPROVED** [review]
LGTM (didn't test it so far)

And another merge conflict for #7613 I guess... yay.

**Comment by L33Tech** [comment]
Thank you, as a KitKat NewPipe user I appreciate it! Hope this gets merged and released before support drops.

**Comment by opusforlife2** [comment]
Ping, so someone merges this approved PR.

**Pull request merged**
