### PR TITLE
Release v0.24.1

### PR DESCRIPTION
**Pull request by TobiGr**
# Download APK for testing

[NewPipe_0.24.1_RC2.zip](https://github.com/TeamNewPipe/NewPipe/files/9938718/NewPipe_0.24.1_RC2.zip) (reuploaded from [this CI artifact](https://github.com/TeamNewPipe/NewPipe/suites/9129095010/artifacts/424034330))
**DO NOT report issues / bugs here!** New bugs and regressions can be reported in the corresponding issue: #9292

# Changelog

## App
<details><summary>read more</summary>

### New
- Add monochrome icon #8987
- Add link to FAQ in the app #9164
- Add an "Open in browser" button on error panel #9180
- Add option to display channel groups as list instead of grid #9207
- Long-click on stream segment to share timestamped URLs (for YouTube only) #9203

### Improved
- Add play queue button to video details fragment #8946
- Show "Hold to enqueue" tip in local playlists #9196
- Support YouTube handles #9291

### Fixed
- Fix potential cast exception in comments text #9065
- Fix `DownloadDialog` crash on screen rotation #9079
- Fix crash when clicking download and quitting the history fragment #9143
- Fix job for removing watched streams from playlist not executing only once #8706
- Fix duplicate videos in feed group "All" #9230

### Localization
- Add new localizations (Icelandic, Latvian, Malayalam) to language selector #9179
- Update translations #9092, #9179, #9256
- Remove empty localizations #9256

### Development
- Use `LinkifyCompat` #8934
- Utilize `useSimpleSummaryProvider` attribute #9011
- Improve `FeedGroupDialogViewModel` factory #8734
- Update Android Gradle Plugin to 7.3.0 #8986
- Use range-limiting methods in more places #8747
- Use Okio's `ByteString` for download checksums #8767
- Calculate search score using streams #8739
- Use `TextViewCompat.setCompoundDrawableTintList()` #8655
- Update AppCompat to 1.5.1 and compileSdk to 32 #8768
- Update PrettyTime from 5.0.3 to 5.0.6 to include new localizations made by NewPipe contributors #9272
- Update NewPipe Extractor #9291
</details>

## Extractor

<details><summary>read more</summary>

### New
- [YouTube] Add comment reply count support TeamNewPipe/NewPipeExtractor#936
- [YouTube] Add `uploaderUrl()` and `uploaderVerified()` to `PlaylistInfoItem` TeamNewPipe/NewPipeExtractor#959
- [YouTube] Support handles TeamNewPipe/NewPipeExtractor#964

### Improved
- [YouTube] Support new metadata format of playlists TeamNewPipe/NewPipeExtractor#958
- [YouTube] Add support for attributed text description TeamNewPipe/NewPipeExtractor#953

### Fixed
- [media.ccc.de] Avoid possible NullPointerException in `MediaCCCRecentKiosk` TeamNewPipe/NewPipeExtractor#930
- [SoundCloud] Fix `SoundcloudPlaylistExtractor`: tracks are in correct order TeamNewPipe/NewPipeExtractor#939
- [SoundCloud] Fix getting more comments TeamNewPipe/NewPipeExtractor#943
- [YouTube] Workaround 403 HTTP errors of ANDROID client streams TeamNewPipe/NewPipeExtractor#960
- [YouTube] Support richGridRenderer on channel page to fix extraction of videos in channels TeamNewPipe/NewPipeExtractor#944
- [YouTube] Support all channel usernames TeamNewPipe/NewPipeExtractor#964

### Development
- Bump junit-bom to 5.9.1 TeamNewPipe/NewPipeExtractor#931
- Bump spotbugs-annotations from 4.7.1 to 4.7.3 TeamNewPipe/NewPipeExtractor#924 TeamNewPipe/NewPipeExtractor#945
- Use `EnumMap` in `PatternsHolder` TeamNewPipe/NewPipeExtractor#888
</details>

### CODE REVIEW

**Comment by Nizami20052022** [comment]
This version is not on GitHub.

**Comment by GameOverFlowChart** [comment]
I wish the extra button to the minimised bottom player would have been optional in the settings, as I want to avoid queue in general. The queue was a function I happily forgot that it existed and now it reappears as a button in an already small gui element.

**Comment by opusforlife2** [comment]
> as I want to avoid queue in general

Why?

**Comment by GameOverFlowChart** [comment]
I use YouTube interactive meaning that I decide which video to watch next after watching one. I never know in advance which videos I want to watch. So in best case I don't need the queue  at all. In worst case it gets in my way (like I click a video to watch it now, and gets queued instead, but by experimenting with the settings I solved this). I installed the app on the device of 4 other persons, all which also don't need the queue since their workflows is very simple. Queues introduce state which make the usage of the app more complex (I know that it's a great feature for others, the question was why I avoid it). Also most of the time if I have the video minimised is because I'm looking for an video which I could watch instead of the one that's running in the background. If I find none than I return to the minimised one.

**Pull request merged**
