### PR TITLE
Updated/Fixed "Get it on F-Droid"

### PR DESCRIPTION
**Pull request by litetex**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
* Fixes the broken "Get it on F-Droid" button in the Readme, which is also displayed at GitHub
* Shrinks the SVGs to 80px in height so that they don't use half of the side

See also https://gitlab.com/fdroid/artwork/tree/master/badge#badge

#### Before/After Screenshots/Screen Record
<details><summary>Click to expand</summary>

- Before: 
grafik grafik

- After:
grafik grafik

</details>

#### APK testing 
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by Redirion — APPROVED** [review]
I like that you also added an accessibility text.

**Comment by Stypox** [comment]
Mmmh, the url https://fdroid.gitlab.io/artwork/badge/get-it-on-es.svg seems to keep loading forever...

**Comment by litetex** [comment]
@Stypox 
Everything is working on my side:
grafik
↓ Loading stats
grafik

**Comment by Stypox** [comment]
Oh, now it works for me too, who knows

**Pull request merged**
