### PR TITLE
Fix NPEs after OnSharedPreferenceChangeListener changes

### LINKED ISSUE #9692: [Nightly] Crash on Importing Database
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.2 (nightly 30)

### Steps to reproduce the bug

1. Export db in NewPipe 0.24.1
2. Open NewPipe nightly and open a video / the video detail fragment
3. minimize player and Import db in current nightly

### Expected behavior

No crash

### Actual behavior

NewPipe finished the import and crashes afterwards.

### Logs

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
 at org.schabi.newpipe.local.feed.FeedFragment.onCreate$lambda-0(FeedFragment.kt:125)
 at org.schabi.newpipe.local.feed.FeedFragment.$r8$lambda$SVZC3B9xz0HrRxuxOiEkSYdQHMY(Unknown Source:0)
 at org.schabi.newpipe.local.feed.FeedFragment$$ExternalSyntheticLambda13.onSharedPreferenceChanged(Unknown Source:2)
 at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:629)
 at android.app.SharedPreferencesImpl$EditorImpl.commit(SharedPreferencesImpl.java:617)
 at org.schabi.newpipe.settings.ContentSettingsManager.loadSharedPreferences(ContentSettingsManager.kt:102)
 at org.schabi.newpipe.settings.ContentSettingsFragment.lambda$importDatabase$6$org-schabi-newpipe-settings-ContentSettingsFragment(ContentSettingsFragment.java:235)
 at org.schabi.newpipe.settings.ContentSettingsFragment$$ExternalSyntheticLambda3.onClick(Unknown Source:4)
 at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at ...
```

### PR DESCRIPTION
**Pull request by Stypox**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

According to `OnSharedPreferenceChangeListener`'s documentation, this was caused by #9306 (even though it is not mentioned in [Android 11's upgrading page](https://developer.android.com/about/versions/11/behavior-changes-all)):

> Apps targeting API 30 on devices running OS versions Android R/11 or later, will receive a `null` value when preferences are cleared.

So I modified all of our overrides of that function to make sure to handle null values gracefully.

#### Fixes the following issue(s)

- Fixes #9692

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by TobiGr — APPROVED** [review]

**Comment by TobiGr** [comment]
don't merge yet

**Comment by Stypox** [comment]
Mmmh, strange, I asked for AS to give me a list of all implementors... Apparently I missed something, thanks for double-checking. :-)

**Comment by TobiGr** [comment]
i used grep, i don't trust AS anymore xD

**Comment by Stypox** [comment]
Noteworthy code smell from sonar and Android Studio:

> Notifications should only launch a Service from notification actions (addAction)

**Comment by TobiGr** [comment]
Those should be addressed in a separate PR. I only fixed Sonar here because it blocked merging this PR.

**Pull request merged**
