### PR TITLE
Refactor VideoDetailFragment.

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Use lambdas for view listeners in `VideoDetailFragment`.

#### Fixes the following issue(s)

- Fixes #

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tsiflimagas** [comment]
It seems like the player crashes (though without a notification) when entering or leaving fullscreen.

**Comment by Isira-Seneviratne** [comment]
> It seems like the player crashes (though without a notification) when entering or leaving fullscreen.

Thanks for the feedback, will look into this.

**Comment by Isira-Seneviratne** [comment]
I undid the view model changes in this PR, I'll make them in a separate one.

**Comment by tsiflimagas** [comment]
It seems to be working fine in general now.

**Review by Stypox — APPROVED** [review]
I pushed two small commits. Other than that, LGTM, thanks!

**Pull request merged**
