### PR TITLE
Usability Update Follow-up

### PR DESCRIPTION
**Pull request by karyogamy**
- Added "Add to playlist" menu item to service player play queue.
- [#1204] Fixed LIVE button to use untranslatable string.
- Fixed service player play queue not refreshed when existing play queue is replaced.
- Fixed potential ArrayOutOfBound exception when checking if player window is live.
- Fixed strange pausing behavior when main video player goes into multiwindow mode.

### CODE REVIEW

**Comment by theScrabi** [comment]
> Made playback speed dialog translucent.

actually I liked it non translucent better

**Comment by karyogamy** [comment]
Well, the reason the dialog is made translucent is to have the video being played in the background still be visible on the main player. I do realize having translucent dialog is inconsistent with the other dialogs on the service player activity, so it's probably better to have an opaque background on that dialog, while keeping the one on main player still translucent. What do you think?

**Comment by theScrabi** [comment]
> What do you think?

Hm I'd make both opaque. It just feels better. However maybe we need the opinion of a third here.

**Comment by karyogamy** [comment]
Just reverted the translucent dialog, I think it's probably better to add a debated change like this in another PR. As for the playlist cleaning, I'll have to do some more testing to figure out a better timing for it.

**Comment by theScrabi** [comment]
So merge or not?

**Comment by karyogamy** [comment]
If you are fine with the changes, go for it. This PR now doesn't introduce anything new, just some refactoring and bugfixes.

**Comment by theScrabi** [comment]
Yea ... I want to release 0.13.1 because everything is better than 0.11.6

**Comment by theScrabi** [comment]
Ok. I wanted to put a little more stable release on fdroid, but i think you are right.

**Pull request merged**
