### PR TITLE
Tablet ui and grid list layout

### PR DESCRIPTION
**Pull request by nv95**
| screenshot_2018-08-22-11-58-55 | screenshot_2018-08-22-11-59-17 |
|---|---|
| screenshot_2018-08-22-11-58-46 | screenshot_2018-08-22-11-58-30 |

### CODE REVIEW

**Comment by theScrabi** [comment]
I'm going to take a look at this once I'm done with the other PRs :)

**Comment by theScrabi** [comment]
@nv95 very hard like. While you are on it, could you take a look at [this](https://github.com/TeamNewPipe/NewPipe/issues/717). Currently we are missing d-pad support, maybe you could also add that :)

**Comment by theScrabi** [comment]
You can emulate android tv

**Comment by nv95** [comment]
@theScrabi ok, I'll do it.
About the point 2: I think, it wil be good to add default mode "Auto", that means list for phones and grid for tables, ok?

**Comment by nv95** [comment]
Done

**Comment by theScrabi** [comment]
Lets first get tablet view to work here. If this works we can talk about tv. @nv95 already opened a seperate pr for dpad supporr.

**Comment by theScrabi** [comment]
Could you please [rebase](https://github.com/TeamNewPipe/NewPipe/wiki/How-to-merge-a-PR) your PR with dev.

**Comment by theScrabi** [comment]
@nv95 nice work thank you :)

**Pull request merged**
