### PR TITLE
Release v0.16.0

### LINKED ISSUE #1866: Settings layout broken
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- I did not use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

In 0.14.2 and later the layout of the sub-setting pages is wrong. It looks like there is an additional column for icons.

### PR DESCRIPTION
**Pull request by theScrabi**
I guess its time for another release.

As always pleas help to do QA, and test this a few days before we can finally release it.
[NewPipe-v0.16.0-RC1_release.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/2898441/NewPipe-v0.16.0-RC1_release.apk.zip)
[NewPipe-v0.16.0-RC1_debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/2898442/NewPipe-v0.16.0-RC1_debug.apk.zip)

# Changelog

### New
- Basic MediaCCC support
- Comments support #1650 by @yausername 

### Improvements
- support for youtube-nocookie.com #2092
- add support for amazon fire tv virtual keyboard
- removing search history items using swipe
- clearing watch history using options menu

### Fixed
- Add Artist and Duration to MediaDescription #2080 
- Fix padding in settings layout (Fixes #1866) #2107
- Fix random Popup player crash #2133 
- Fix delayed ducking of Audio #2120

### CODE REVIEW

**Comment by Brimont** [comment]
it works fine, but it missing shows other answers and also support links in the comments

**Comment by yausername** [comment]
> Nice work it works fine, but it missing shows other answers and also support links in the comments

I think we can do these in a future release. I'll try to do the links part tomorrow.

**Comment by yausername** [comment]
hey @theScrabi 
Looks like this PR of extractor https://github.com/TeamNewPipe/NewPipeExtractor/pull/141 is not included in the release.

**Comment by yausername** [comment]
https://github.com/TeamNewPipe/NewPipe/pull/2153 was merged to dev but did not make it to the release

**Comment by theScrabi** [comment]
f***. Well did RCs have this issue?

**Comment by yausername** [comment]
I'm afraid they did.

**Pull request merged**
