### PR TITLE
Somali README.md

### PR DESCRIPTION
**Pull request by nadiration**
Somali translation of the README.md

#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)
- [x] README.md Translation

#### Description of the changes in your PR

- translated README.md to Somali

### CODE REVIEW

**Review by opusforlife2 — CHANGES_REQUESTED** [review]
Pffft. Don't delete the English Readme. Some of us need it. :P

**Comment by nadiration** [comment]
> Pffft. Don't delete the English Readme. Some of us need it. :P

I created a new Readme.so

**Comment by opusforlife2** [comment]
Look at the "Files changed" tab. You've deleted the README.md file, and created the README.so.md file.

**Comment by nadiration** [comment]
> Look at the "Files changed" tab. You've deleted the README.md file, and created the README.so.md file.

My bad. Sorry i thought i was creating a different file

**Comment by opusforlife2** [comment]
You've... not changed anything yet. Maybe you're pushing to the wrong branch?

**Comment by nadiration** [comment]
> You've... not changed anything yet. Maybe you're pushing to the wrong branch?

How do i fix it

**Comment by opusforlife2** [comment]
Yeah, since you've changed the dev branch directly, it's better to start over. I'm laying out some steps to make it easy.

Keep a backup of your translated Readme somewhere and delete your fork of Newpipe from repo settings. Then fork it again.

From the main page of your repo fork, create a new branch from dev using the instructions here: https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-and-deleting-branches-within-your-repository

After you're on the new branch, click on "Add file", and then "Create new file". Paste the translated text here and name the file appropriately.

Then commit it to the branch directly, using the first option at the bottom. When you're done, the main page of your repo fork will give you the option of starting a pull request to the main Newpipe repo.

**Pull request closed without merging**
