### PR TITLE
Silence CheckForNewAppVersionTask

### LINKED ISSUE #2197: Update check crashes on startup
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
- [X] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Title.

Crash report: 

## Exception
* __User Action:__ something
* __Request:__ could not parse app update JSON data
* __Content Language:__ US
* __Service:__ none
* __Version:__ 0.16.0
* __OS:__ Linux lge/lucye_nao_us/lucye:8.0.0/OPR1.170623.032/182541455e902:user/release-keys 8.0.0 - 26

<details><summary><b>Crash log</b></summary><p>

```
org.json.JSONException: Value <html><title>500 of type java.lang.String cannot be converted to JSONObject
	at org.json.JSON.typeMismatch(JSON.java:111)
	at org.json.JSONObject.<init>(JSONObject.java:163)
	at org.json.JSONObject.<init>(JSONObject.java:176)
	at org.schabi.newpipe.CheckForNewAppVersionTask.onPostExecute(CheckForNewAppVersionTask.java:104)
	at org.schabi.newpipe.CheckForNewAppVersionTask.onPostExecute(CheckForNewAppVersionTask.java:46)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.-wrap1(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6710)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

```
</p></details>
<hr>

### LINKED ISSUE #2421: app update API fail due to bad reception
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

I got this exception when my mobile data connection wasn't so good. It looks like the background update check failed due to bad reception, this should probably fail more silently.

## Exception
* __User Action:__ something
* __Request:__ app update API fail
* __Content Language:__ PH
* __Service:__ none
* __Version:__ 0.16.2
* __OS:__ Linux Android 9 - 28

<details><summary><b>Crash log</b></summary><p>

```
java.net.SocketTimeoutException: SSL handshake timed out
	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
	at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:383)
	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:231)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:319)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:283)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:168)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
	at okhttp3.RealCall.execute(RealCall.java:92)
	at org.schabi.newpipe.CheckForNewAppVersionTask.doInBackground(CheckForNewAppVersionTask.java:90)
	at org.schabi.newpipe.CheckForNewAppVersionTask.doInBackground(CheckForNewAppVersionTask.java:48)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```
</p></details>
<hr>

### PR DESCRIPTION
**Pull request by Redirion**
Closes #2421
Closes #2197

This is a very simple change to not annoy users when the internet connection isn't stable. The task will run again on another occasion.

- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by TobiGr** [comment]
Can you please do the same in line 119 to close https://github.com/TeamNewPipe/NewPipe/issues/2197 as well?

**Comment by Stypox** [comment]
I think a Toast or a Snackbar should be shown in these cases, just to let the user know. Maybe with `Snackbar/Toast.LENGTH_SHORT` to make it disappear after a short amount of time.

**Comment by Redirion** [comment]
like this @Stypox ?

**Comment by Stypox** [comment]
Yes

**Comment by TobiGr** [comment]
Good, idea @Stypox. I think in this case it might be better to not show `Can not connect to the server`, but something like `(Connection) error during app update check`.  Showing `Can not connect to the server` without any context which is visible to the user might cause irritations. 
btw. Shouldn't it be `Cannot connect to the server`?

**Comment by Stypox** [comment]
Both "can not" and "cannot" are accepted by english, afaik

`Connection error during app update check` is short and explanatory, +1 👍

**Comment by phatloot123** [comment]
In my opinion the user should not be notified about this. This is just an app update check. It probably happens often so if it fails every now and then it's not a big deal. imo it should be hidden from the user since the user is usually not aware of this anyway so when they see an error it will just confuse them since no action on the users side is needed

**Comment by theScrabi** [comment]
Well we should still get notifications when something failes, however if its a simple SSL issue because the host could not be reached I would not send a notification at all just as you said.

**Comment by Redirion** [comment]
okay, I have removed the Toast messages again.

**Pull request merged**
