### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by TobiGr**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

- Replaced the screenshots which was showing a playlist with a bookmark screenshot. Furthermore we now use compressed screenshots. 
- Linked the liberapay site (see #1153 and #1127 ) in the donation section

### CODE REVIEW

**Comment by TheAssassin** [comment]
@TobiGr looks good so far, but how about replacing the QR codes with SVG files? They're probably quite a bit smaller, and being scalable is always a plus.

**Comment by TobiGr** [comment]
@TheAssassin I tried SVGs but these files are larger. The PNG files have sizes of 346, 714 and 815 bytes while the corresponding SVG files have sizes of~37kB.  That's why I'd keep the PNG. I can remove the margin/ white border around these images to make them even smaller.
About the scaling: At the moment I use 100px images (87px qr code and 13px margin) which is good enough for phone cameras. We just use the QR codes in the readme, so why do we have to think about scaling?

**Comment by TheAssassin** [comment]
@TobiGr then those SVG files were pretty bad ones. A QR code is a set of `x^2*2` squares and a few lines. I'll give it a try.

**Comment by TobiGr** [comment]
I used https://www.the-qrcode-generator.com/

**Comment by TheAssassin** [comment]
QtQR produces quite large files, too, but they're < 30 kiB already, so quite a bit smaller. However, I can't reach the PNGs' sizes.

**Comment by TobiGr** [comment]
Me either. I tested plenty only QR code generators now :D
Just removed the margin as mentioned above.

**Comment by TheAssassin** [comment]
> Just removed the margin as mentioned above.

That's a bad idea. The QR code specification requires a margin of at least 4 point widths around the code. See http://www.qrcode.com/en/howto/code.html.

**Comment by TobiGr** [comment]
Yes, you're right.

**Pull request merged**
