### PR TITLE
Added the feature of squared avatars

### LINKED ISSUE #5610: Squared avatars
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I'd like to have a switch for round/square/square-with-rounded-corners avatars (userpics). I have some experience creating Android apps and can try to implement it.

#### Is your feature request related to a problem? Please describe it

I don't like round avatars. Unfortunately, every app creator seems to follow this fancy trend for some reason.

#### How will you/everyone benefit from this feature?

I'm sure that I'm not the only one who dislikes round avatars.

### PR DESCRIPTION
**Pull request by Marius1501**
#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Added the feature of setting the channels' avatars to a squared or squared with rounded corners shape
- Added this to those views where the channel avatar is shown
- Added a setting in appearance-settings where you can choose between round, square or square with rounded corners

#### Before/After Screenshots/Screen Record

| Views with squared avatars | Appearance-Settings | Square with rounded corners |
| ------------- | ------------- |  ------------- |
|NewPipe2 – ChannelItem kt  NewPipe2 app main  27 01 2023 12_01_36 | NewPipe2 – ChannelItem kt  NewPipe2 app main  27 01 2023 11_58_24 | NewPipe2 – ChannelItem kt  NewPipe2 app main  27 01 2023 11_56_29 |
|  NewPipe2 – ChannelItem kt  NewPipe2 app main  27 01 2023 12_02_56 | NewPipe2 – ChannelItem kt  NewPipe2 app main  27 01 2023 11_59_39  |
| NewPipe2 – ChannelItem kt  NewPipe2 app main  27 01 2023 12_04_35 | 
|NewPipe2 – ChannelItem kt  NewPipe2 app main  27 01 2023 12_05_56 |
|NewPipe2 – ChannelItem kt  NewPipe2 app main  27 01 2023 12_07_23|
| NewPipe2 – ChannelItem kt  NewPipe2 app main  27 01 2023 12_08_52 |

#### Fixes the following issue(s)

- Fixes #5610 

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Stypox** [comment]
Mmmh, I am not sure on the usefulness of that switch. The vast majority of users wouldn't use it at all. I would not create an option, but rather just replace circle avatars with rounded-corners-square avatars everywhere. What do you think? Thanks for looking into this.

**Comment by Stypox** [comment]
Yt uses round thumbnails

**Comment by TobiGr** [comment]
> What does YT use? If it has circular avatars, then channels probably create their avatars in such a way as to best suit the available space. So maybe follow YT on this?

We should not follow yt, but try to get a design which matches the overall feeling and UX of the app. before adding many custom UI tweaks, we need to set up a design / ui guide for NewPipe. The current UI concept is not as good as it could / should be, but is somewhat consistent. Rounded corners are a feature of Material Design 3. Adding just _one_ MD3 feature feels wrong and breaks that consitency.

**Comment by Stypox** [comment]
Mmmh, right. Let's keep them circular, as they fit well into our design after all.

**Comment by Marius1501** [comment]
@Stypox So should I close this PR?

**Comment by Stypox** [comment]
I have to disagree. The vast majority of users wouldn't use it at all. It adds maintenance burden, complicates logic in some places, and requires UI designers to think about the ui in the three different ways. This is just excessive customization that can cause more problems than it solves, imo. @SameenAhnaf feel free to close any related issue as "won't fix". Sorry @Marius1501, and thanks anyway for trying :-)

**Pull request closed without merging**
