### PR TITLE
Use minimum required permissions for GitHub workflows

### PR DESCRIPTION
**Pull request by mhmdanas**
#### What is it?
- [x] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

Use minimum needed permissions for GitHub workflows and jobs. This reduces the attack surface if the workflows are ever compromised.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mhmdanas** [comment]
The SonarCloud failure is unrelated, this should be good to go.

**Review by litetex — APPROVED** [review]
LGTM

@TobiGr @Stypox @TheAssassin 
You may have a look at @mhmdanas last comment...

**Comment by litetex** [comment]
See also https://github.com/TeamNewPipe/NewPipeExtractor/pull/869

**Review by TheAssassin — APPROVED** [review]

**Review by Stypox — APPROVED** [review]
Now that we have manually specified permissions for each workflow, I made the default permissions read-only. Let's see if this works correctly...
image

**Comment by opusforlife2** [comment]
Did it?

**Pull request merged**
