### PR TITLE
Change YouTube subscription import instructions to Google takeout

### LINKED ISSUE #4720: Youtube import subscription instructions is not working anymore
# Description 

Following the instructions at https://newpipe.schabi.org/FAQ/tutorials/import-export-data/#import-youtube to download subscriptions no longer works as it seems like Youtube has changed its interface. Going to https://www.youtube.com/subscription_manager?action_takeout=1 no longer starts a download, but it redirects to https://www.youtube.com/feed/channels. This prevents importing of subscriptions list which could have been then loaded to Newpipe app.

# Expected behavior

It should be possible to import subscriptions from youtube account using instructions at https://newpipe.schabi.org/FAQ/tutorials/import-export-data/#import-youtube. 

# Actual Behavior

Instructions given to import subscriptions from Youtube not working anymore. The instructions ask you to download subscriptions using the URL: https://www.youtube.com/subscription_manager?action_takeout=1, but this merely redirects to https://www.youtube.com/feed/channels and does not start a download.

# Steps to reproduce

1. Read import instructions from https://newpipe.schabi.org/FAQ/tutorials/import-export-data/#import-youtube

2. Follow the link at https://www.youtube.com/subscription_manager?action_takeout=1

3. Gets redirected to https://www.youtube.com/feed/channels. No download starts.

4. Cannot import subscriptions from youtube

# Platform

All platforms

### PR DESCRIPTION
**Pull request by Stypox**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
This are the new steps:
1. Go to this URL: https://takeout.google.com/takeout/custom/youtube
2. Log in when asked
3. Click on \"All data included\", then on \"Deselect all\", then select only \"subscriptions\" and click \"OK\"
5. Click on \"Next step\" and then on \"Create export\"
6. Click on the \"Download\" button after it appears and 
7. From the downloaded takeout zip extract the .json file (usually under \"YouTube and YouTube Music/subscriptions/subscriptions.json\") and import it here

Point 7, i.e. extracting things from the archive, can't be done automatically, due to the different structure for different localizations.

#### Fixes the following issue(s)
Fixes #4720

#### Relies on the following changes
TeamNewPipe/NewPipeExtractor#452

#### APK testing 
@simula67 @inigosola @Djay86 @IvanProgramming @Saecki 
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5471647/app-debug.zip)

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TobiGr** [comment]
Instructions should also be changed on the website: https://newpipe.schabi.org/FAQ/tutorials/import-export-data/

https://github.com/TeamNewPipe/website/blob/master/_tutorials/import-export-data.html

**Comment by Djay86** [comment]
Tested the .apk, import worked with no isssue.

**Comment by IvanProgramming** [comment]
Tested .APK file, no issues was found

**Comment by Saecki** [comment]
Works for me too.

**Comment by Stypox** [comment]
I updated the url to https://takeout.google.com/takeout/custom/youtube , see the extractor PR for discussion
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5474147/app-debug.zip)

**Comment by simula67** [comment]
@Stypox The import works with the debug app.

Thanks for doing this.

**Comment by atar-axis** [comment]
Works, the only issue is that google sends you an archive and you will have to extract the json by hand. You should therefore maybe also note that on the instructions or let newpipe extract it if necessary

**Comment by Stypox** [comment]
@atar-axis as I said I don't think we can have NewPipe extract the json automatically, sincs different localizations have different names and structures

**Comment by atar-axis** [comment]
I think all we need to do is finding thw json where it says `"kind" : "youtube#subscription",` should be pretty easy I guess

**Comment by Stypox** [comment]
@TobiGr this should also be merged, it is only a string change

**Comment by atar-axis** [comment]
The instructions don't tell the user to extract the file, find the subscriptions.json on beforehand. At least those instructions should be added before merging

**Comment by Stypox** [comment]
@atar-axis no, it does: `From the downloaded takeout zip extract the .json file (usually under "YouTube and YouTube Music/subscriptions/subscriptions.json")`

**Comment by atar-axis** [comment]
So then it is an translation issue, it doesn't on the german version. Thanks for clarification!

**Comment by atar-axis** [comment]
> I think all we need to do is extracting the `.zip` and searching for the json where it says `[ { ..., "kind" : "youtube#subscription", ... } ]` should be pretty easy I guess.

@Stypox what do you think about that? I could give it a try, shouldn't be too hard

**Comment by Stypox** [comment]
> So then it is an translation issue, it doesn't on the german version.

Oh, yeah, translations will be there only after syncing with WebLate

**Comment by Stypox** [comment]
> So then it is an translation issue, it doesn't on the german version.

Oh, yeah, translations will be there only after syncing WebLate ;-)

> @Stypox what do you think about that? I could give it a try, shouldn't be too hard

I am not sure if that would work out perfectly (maybe there are still issues in some localizations? idk). Anyway, after a second thought I think we should detect automatically if the user is passing us a json file directly (in which case we parse it as we do currently) or a zip archive (in which case we try to look for the json). This should bring us the best of both worlds, since we would both be able to pass a single file and the whole archive. Feel free to open a PR in the NewPipe repo (imo it's better not to put this part in the Extractor since it has to do with files, zips, etc.). Thank you :-D

**Comment by ochen1** [comment]
The APK worked like a charm! Thanks for doing this!

**Pull request merged**
