### PR TITLE
Fixed double tapping the replay button

### LINKED ISSUE #6217: Replaying a video in any player requires tapping the replay button twice
### Checklist

- [x] I am using the latest version - 0.21.2 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
A weird bug, but also weirdly consistent. 
1. Start playing a video in any player.
2. Wait for it to finish.
3. Swipe down to open up the notification tray, and tap the "replay" button, or tap the button in the main/popup player.
4. Observe the video doesn't replay.
5. Tap the replay button again, and watch it replay.

### Actual behaviour

Included above. Funnily enough, this behavior also persists after closing the notification tray or locking the phone - eg. if you tap it once, turn off the phone, and then turn it on and tap it again, it'll play.

### Expected behavior

The video should replay after one tap.

### Device info

 - Android version/Custom ROM version: GrapheneOS 11
 - Device model: Pixel 4a

### PR DESCRIPTION
**Pull request by litetex**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
Simpler successor to #6322.
Fixes double tapping the replay button

#### Fixes the following issue(s)

- Fixes #6217 

#### APK testing 
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by opusforlife2** [comment]
Ah. Yes. Please merge this soon. Quite an annoying bug. When was it introduced? I think it was in the 0.21.x series.

**Comment by tsiflimagas** [comment]
It works great, thank you for this!

**Comment by litetex** [comment]
@opusforlife2 
Maybe we should add the ASAP label?
I think it must have happened somewhere in <=0.21.2

You can also review/test it and give it a ✔️ then it may be even faster merged 😄

**Review by TobiGr — APPROVED** [review]
Looks good. Thanks!

**Comment by opusforlife2** [comment]
> You can also review/test it and give it a ✔️ then it may be even faster merged 😄

I'm not supposed to do that, since I'm not a dev. 👀

**Comment by litetex** [comment]
@opusforlife2 
Whoops I didn't know that 😆

**Pull request merged**
