### PR TITLE
Add FSFE-Tube PeerTube instance

### LINKED ISSUE #7480: fsfe tube
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.   
🔍 - [fsfe tube](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aopen+fsfe-tube) | [fsfe tube](https://github.com/TeamNewPipe/NewPipeExtractor/issues?q=is%3Aopen+fsfe+tube)
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

Support for fsfe-tube
- [home page](https://media.fsfe.org/)
- [example video](https://media.fsfe.org/w/7cH6EATpmPwaMsEZN8vfyj)

#### Why do you want this feature?

The videos there looked like of interest to me, and there seemed to be ample videos there. So, if that's not much debt to have this, then i guess it will be cool to have.

### PR DESCRIPTION
**Pull request by mhmdanas**
#### What is it?
- [x] Feature (user facing)

#### Description of the changes in your PR

Add [FSFE-Tube](https://media.fsfe.org) PeerTube instance.

#### Fixes the following issue(s)

- Fixes #7480

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

@yashpalgoyal1304 does this fix the issue for you?

### CODE REVIEW

**Comment by yashpalgoyal1304** [comment]
sharing the direct link to download apk here 'cz the "app" button is somehow not clickable on my phone (even despite "desktop site" being enabled): https://github.com/TeamNewPipe/NewPipe/suites/4522728956/artifacts/120990646

**Comment by yashpalgoyal1304** [comment]
hey, so, 
* as far as the changes are concerned, sure they work. on clicking the [media.fsfe.org/...] link from some app (telegram in my case), sure ths newpipe debug app is shown in the open with dialog. 
* butttt i am not sure that the following behaviour is okay. so i am kinda documenting all of it with my comments
1. shown in the newpipe popup dialog is "video player, popup player, download, add to playlist" but not show video details. is that expected?
2. on choosing (tapping) video player:
    + loaded, then went blank, and exited w/o error: 1st, 3rd, 
    + crashed: 2nd, 4th, 5th, 6th try

[media.fsfe.org/...]: https://media.fsfe.org/videos/watch/9f8588b3-51b1-43a7-91c2-81fa2aa2cf75

----
### Crash report on 2nd try:

Open media.fsfe.org link and choose video player
## Exception
* User Action: ui error
* Request: ACRA report
* Content Country: US
* Content Language: en-US
* App Language: en_US
* Service: none
* Version: 0.21.13
* OS: Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NumberFormatException: For input string: ""
 at java.lang.Integer.parseInt(Integer.java:627)
 at java.lang.Integer.parseInt(Integer.java:650)
 at org.schabi.newpipe.util.ListHelper.compareVideoStreamResolution(ListHelper.java:488)
 at org.schabi.newpipe.util.ListHelper.compareVideoStreamResolution(ListHelper.java:503)
 at org.schabi.newpipe.util.ListHelper.$r8$lambda$UGNhfSv5KuYwsqrcThyeG189sI0(Unknown Source:0)
 at org.schabi.newpipe.util.ListHelper$$ExternalSyntheticLambda0.compare(Unknown Source:4)
 at java.util.Collections$ReverseComparator2.compare(Collections.java:5235)
 at java.util.TimSort.countRunAndMakeAscending(TimSort.java:360)
 at java.util.TimSort.sort(TimSort.java:220)
 at java.util.Arrays.sort(Arrays.java:1492)
 at java.util.ArrayList.sort(ArrayList.java:1470)
 at java.util.Collections.sort(Collections.java:206)
 at org.schabi.newpipe.util.ListHelper.sortStreamList(ListHelper.java:269)
 at org.schabi.newpipe.util.ListHelper.getSortedStreamVideosList(ListHelper.java:243)
 at org.schabi.newpipe.util.ListHelper.getSortedStreamVideosList(ListHelper.java:130)
 at org.schabi.newpipe.fragments.detail.VideoDetailFragment.handleResult(VideoDetailFragment.java:1602)
 at org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$runWorker$6$org-schabi-newpipe-fragments-detail-VideoDetailFragment(VideoDetailFragment.java:913)
 at org.schabi.newpipe.fragments.detail.VideoDetailFragment$$ExternalSyntheticLambda2.accept(Unknown Source:8)
 at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
 at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
 at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
 at android.os.Handler.handleCallback(Handler.java:938)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:261)
 at android.app.ActivityThread.main(ActivityThread.java:8259)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```

</details>
<hr>

**Comment by mhmdanas** [comment]
> shown in the newpipe popup dialog is "video player, popup player, download, add to playlist" but not show video details. is that expected?

Hmm, not sure.

Regarding the crash, looks like #6860 to me.

**Comment by yashpalgoyal1304** [comment]
Nice that u could find the crash's dedicated issue and documented it. but just saying, i am like illiterate for crash logs. so, i dont know about it at all 😅 

also, any idea for the case when it just goes blank??

**Comment by yashpalgoyal1304** [comment]
update: yeah, seems the u are right and also, that issue itself is heading in right direction. as i tried accessing peertube's video from within newpipe (by changing in the sidebar) and yes, opening any video crashed it, and playing it in bg eventually showed the toast that "couldnt play this stream"

**Comment by mhmdanas** [comment]
> and playing it in bg eventually showed the toast that "couldnt play this stream"

Note that playing PeerTube videos in the background is not supported: #3671

**Comment by litetex** [comment]
LGTM
However I'm not sure if we should add this instance in the first place:
https://media.fsfe.org/about/instance
There are only ~120 videos (uploaded by one user) with under 2k views within the last 5 years on that instance. 
The other instances in that list usually have > 100k views and 

I think in the long term we can't add every Peertube instance inside that list. We need a new solution like #7456

**Review by 6543 — APPROVED** [review]
nice

**Comment by mhmdanas** [comment]
@litetex this PR merely adds link support for FSFE-Tube, so I don't see why we should hold back.

> I think in the long term we can't add every Peertube instance inside that list. We need a new solution like #7456

Maybe, but until then, we're stuck with this. :)

**Review by litetex — APPROVED** [review]

**Review by Stypox — APPROVED** [review]

**Comment by yashpalgoyal1304** [comment]
hi, so, am glad that this is merged. but i'd say this should be release only when the corresponding issues to peertube are fixed. lest the end experience will be worse and there'll be plathora of bug reports on it.

**Pull request merged**
