### PR TITLE
Remember adjustment step size for playback controls (speed and pitch)

### LINKED ISSUE #7031: Remember step for playback speed controls
Make playback the step width in percent a sticky option, which saves its last state. Usually it's always reset to 25% if you re-open the option dialog on the video screen.

I usually work with 1,15x average speed for speech channels and 5% step width, with the need to adjust according to content and situation, but I always need to adjust the width first, which is annoying.

### PR DESCRIPTION
**Pull request by ktprograms**
#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Save `adjustmentStepSize` to shared preferences, pass it back and forth
between PlaybackParameterDialog and Player/PlayQueueActivity.
- Made `DEFAULT_STEP` in PlaybackParameterDialog public so it can be used as
the default `adjustmentStepSize` value in the Player.

#### Before/After Screenshots/Screen Record

| Before | After |
|--|--|
| <video src="https://user-images.githubusercontent.com/71804605/151766501-807ca760-ad0c-494a-a1f3-9c1de85a2b05.mp4"> | <video src="https://user-images.githubusercontent.com/71804605/151766566-86420278-19d6-4bec-96c0-c5433dcca642.mp4"> |

#### Fixes the following issue(s)

- Fixes #7031

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by Stypox — CHANGES_REQUESTED** [review]
I don't think you should pass around the `adjustmentStepSize` as a playback parameter. It's not something influencing the playback, it's just a value to save to / read from preferences. You should just read it when the `PlaybackParameterDialog` is setup, and save it when the user changes it inside the same dialog.

**Comment by ktprograms** [comment]
@Stypox Sorry, I was busy so I didn't have time to look at the code.

I'm guessing this should be done similarly to how `setupHookingControl` handles accessing the preferences?

https://github.com/TeamNewPipe/NewPipe/blob/af80d96b9ed701ec44c36d1ea8e37c11dbae56f5/app/src/main/java/org/schabi/newpipe/player/helper/PlaybackParameterDialog.java#L237-L260

**Comment by Stypox** [comment]
@ktprograms yes, I think that's the way to go

**Comment by ktprograms** [comment]
@Stypox Since the step size will now be saved to shared preferences, should I remove the code that saves it to/reads it from outState?

**Comment by Stypox** [comment]
@ktprograms yes, there is no need to save/restore it there

**Comment by ktprograms** [comment]
@Stypox Done, basically rewrote the entire commit, so here's the overview of everything changed:
- Add `adjustment_step_key` to `settings_keys.xml` to be used when
saving/loading the step size.
- Remove the global `stepSize` variable and the code that saves it to
`outState`/loads it from `savedInstanceState` because it's now saved to
Shared Preferences.
- Move initially setting step size to `setupStepSizeSelector` to be
consistent with the other view setup methods, using the value loaded
from Shared Preferences.
- Save the step size to Shared Preferences inside `setStepSize`.

**Review by Stypox — COMMENTED** [review]
Thank you! Code looks good to me, I'm going to test it later :-)

**Review by Stypox — APPROVED** [review]
I tested and everything seems to work well :-)

**Comment by ktprograms** [comment]
Thanks!

**Pull request merged**
