### PR TITLE
Update most dependencies

### PR DESCRIPTION
**Pull request by Stypox**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
This is basically #4508 but also contains:
- further update `androidx.constraintlayout:constraintlayout` from `2.0.2` to `2.0.4`
- re-enable **ktlint**

Other than that, it is identical to #4508 (by @wb9688, he told us we could continue his PRs):
- Update all dependencies except ExoPlayer. Most changes come from upgrading to RxJava 3, which unfortunately requires upgrading to an alpha version of Room, and Ktlint rules changes.
- Note how I've added 3 dependencies: `androidx.documentfile:documentfile` and `androidx.localbroadcastmanager:localbroadcastmanager` were previously part of some other AndroidX library, while `com.squareup.leakcanary:plumber-android` is a new feature from LeakCanary that fixes known memory leaks in the Android framework.
- I did not upgrade ExoPlayer, as we probably want to use certain new features like audio offloading, `Media2` (replacement for `MediaSessionCompat`, which is now deprecated) support, and maybe toplevel playlist support. @Redirion: Do you want to do that in some PR? Also see https://github.com/TeamNewPipe/NewPipe/pull/4508#issuecomment-710915907

#### APK testing 
I tested a little bit on 4.4 but didn't have much time for further testing. @Poolitzer @mhmdanas @mqus @MD77MD @opusforlife2 could you test this, if you have some time? You'd have to just go through the screens and the buttons the app has and verify nothing crashes.
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5579523/app-debug.zip)

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mhmdanas** [comment]
I'm on it.

**Comment by Redirion** [comment]
its a bit more complicated this time to upgrade ExoPlayer. We need to provide a [MediaItem](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/source/MediaSource.java#L287). And media2 is incompatible with the MediaButtonReceiver. I did not find any replacement for that yet (or don't know if this is even required). For now we could just try ExoPlayer and investigate media2 afterwards, but we still need that MediaItem. I wanted to take a look at ExoPlayer's internals for that, as it converts MediaItems back to MediaSources for playback. Therefore it should hopefully not be hard to also get it working the other way around so that we can return suitable data there.
Are you okay with this approach or do you have other opinions?

**Comment by mhmdanas** [comment]
I tried everything I could think of and found no issues.

**Comment by opusforlife2** [comment]
> change compileSdkVersion and targetSdkVersion from 29 to 30.

Are we ready for this? Don't we need the SAF PR as a prerequisite for this?

**Comment by Stypox** [comment]
> Don't we need the SAF PR as a prerequisite for this?

Oh, do we? I have no idea, maybe it's better if I revert that part and let somebody else change it with more knowledge about what changes

**Comment by Stypox** [comment]
@opusforlife2 I reverted the change to the target sdk version

**Comment by MD77MD** [comment]
Screenshot_20201102-220530

 not sure if related but clicking on any of the highlighted buttons in an empty channel would crash newpipe.

**Comment by Stypox** [comment]
@MD77MD that also happens in 0.20.2, so it's not caused by this. #4555 fixes it.

**Comment by MD77MD** [comment]
> @MD77MD that also happens in 0.20.2, so it's not caused by this. #4555 fixes it.

oh i see, i went crazy trying everything like you asked.. i would never realize this in normal use...  why would anyone play an empty channel 🤣

**Comment by Isira-Seneviratne** [comment]
Maybe [RxJavaBridge](https://github.com/akarnokd/RxJavaBridge#rxjavabridge) could be used? That way an alpha version of Room wouldn't have to be used.

**Comment by Stypox** [comment]
@Isira-Seneviratne I think we are good using an alpha version of Room, since there are [no open issues](https://issuetracker.google.com/issues?q=componentid:413107%20status:open%20rxjava%7Crxjava3%7Creactivex%7Crx) about the new RxJava3 support and there are [no breaking changes](https://developer.android.com/jetpack/androidx/releases/room#2.3.0-alpha03) regarding what we are already doing. Therefore I think using another library to achieve RxJava3 support, just to ditch it when upgrading Room to a stable 2.3 version, is not convenient ;-)

**Comment by Stypox** [comment]
I fixed some ktlint errors arisen after rebase

**Comment by mqus** [comment]
Tested the provided apk on Android Kitkat(api19) and found no bugs.

**Comment by Isira-Seneviratne** [comment]
@Stypox [`desugar_jdk_libs`](https://github.com/google/desugar_jdk_libs) has also been updated to 1.1.0.

**Comment by Stypox** [comment]
I rebased after Java-8-date-time changes. I also enabled ktlint's autoformatting by default and used version `1.1.0` of `desugar_jdk_libs` (thank you @Isira-Seneviratne). Here is another APK: [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5497208/app-debug.zip)

**Comment by Isira-Seneviratne** [comment]
> I rebased after Java-8-date-time changes. I also enabled ktlint's autoformatting by default and used version `1.1.0` of `desugar_jdk_libs` (thank you @Isira-Seneviratne). Here is another APK: [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5497208/app-debug.zip)

It's been updated again to 1.1.1.

**Comment by Stypox** [comment]
Rebased and updated `desugar_jdk_libs` to 1.1.1: [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5574205/app-debug.zip)

**Comment by Stypox** [comment]
Again: [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5574329/app-debug.zip)

**Comment by Stypox** [comment]
@TobiGr I think I tested this well enough, can it be merged before creating any new conflict?

**Comment by TobiGr** [comment]
uh yeah. we should merge. Can you resolve the conflicts on more time, please?

**Comment by Stypox** [comment]
I rebased again @TobiGr : [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5579430/app-debug.zip)

**Comment by Stypox** [comment]
Update checkstyle (8.36.2 -> 8.37) and mockito-core (3.5.13 -> 3.6.0): [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5579505/app-debug.zip)

**Comment by Stypox** [comment]
I checked manually every library we are using and they were all up to date except those two (which I updated). Since those library are not used by the code but only for testing purposes, there is no difference.
Oh, it's rebase time again ;-)

**Comment by Stypox** [comment]
Ok, rebased again, hopefully the last one ;-)
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5579523/app-debug.zip)

**Review by TobiGr — APPROVED** [review]

**Pull request merged**
