### PR TITLE
Added Expiration to InfoCache and other improvements.

### PR DESCRIPTION
**Pull request by karyogamy**
- Fixes problem described in #760 (I'm a simple man, I see bounty, I try to fix =P). This only fixes the problem caused by expiring Youtube links though, and does not save timestamp on source and renderer errors. Unexpected errors will have timestamp saved temporarily but you will be out of luck if your connection is bad or your device can't support certain formats, where the timestamp will reset. If we want to store the timestamp, we will need to put it in the database. Might be coming on the next PR on local playlists which will have a stream info table for this feature.
- Adds feature requested in #840, screenshot below.
- Fixes text color inconsistency issue in #836 by using fixed text coloring on notifications.
- Modifies the info item dialog banner to show uploader name (if one exists) instead of type name, screenshot below.
- Fixes popup player not running in foreground when launched externally, causing it to get gc'ed when video is still playing.
- Fixes exception when launching popup player externally without launching the player internally first after fresh installation.

Screenshots:

### CODE REVIEW

**Comment by theScrabi** [comment]
> I'm a simple man, I see bounty, I try to fix =P

Will that mean that you are the first who gets paid for working on NewPipe? Congrats :)

**Comment by theScrabi** [comment]
@karyogamy if you join us on Bountysource, I can pay you out your bounty.

**Comment by karyogamy** [comment]
@theScrabi I was only joking, isn't the bounty was aimed at the persistent timestamp feature request rather than a just a bugfix? But anyways, keep the bounty. You and the existing team before me deserve it more. Or better yet, reinvest it into some other high priority issue =D

**Comment by theScrabi** [comment]
¿You fixed that bug dind't you? Am I wrong? So whats the deal? If you fixed it you earned yourself 15$. People would not pay money if they didn't want others to get it for a certain work they did. Also I want to see how this works with boutysource (only if you like of cource).

**Comment by karyogamy** [comment]
Alright, I've added myself on bountysource =D

**Comment by karyogamy** [comment]
Please close #840 and #836.

**Pull request merged**
