### PR TITLE
Remove JCenter when possible

### PR DESCRIPTION
**Pull request by TobiGr**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [x] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
The JCenter repository is going to be shut down. This PR tries to resolve as many dependencies as possible from other repositories.

#### Fixes the following issue(s)
#5837 

#### APK testing 

On the website the APK can be found by going to the "Checks" tab below the title and then on "artifacts" on the right.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jimman2003** [comment]
Try porting group to jitpack! I have done it at my own fork

**Comment by jimman2003** [comment]
Also exoplayer from google repo

**Comment by litetex** [comment]
@TobiGr 
What's the progress here?
``trove4j`` is now on Maven central -> https://youtrack.jetbrains.com/issue/IDEA-261387 

So I think we can drop ``jcenter`` completely 

Also somehow the build seems to be messed up. Maybe rebase?

**Comment by litetex** [comment]
Build failure is due to 
> Cause 1: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.google.android.exoplayer:exoplayer:2.12.3.
> Cause 2: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.google.android.exoplayer:extension-mediasession:2.12.3.


Exoplayer 2.12.3 is not published at https://maven.google.com/:
https://mvnrepository.com/artifact/com.google.android.exoplayer/exoplayer

Only versions >= 2.13.3 are

**Comment by litetex** [comment]
ExoPlayer is now on ``2.14.2`` so let's see if we can get a green build...

**Review by litetex — APPROVED** [review]
Everything is green 🥳

**Pull request merged**
