### PR TITLE
Play queue theme

### PR DESCRIPTION
**Pull request by Stypox**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- record videos
- create clones
- take over the world

#### Before/After Screenshots/Screen Record
With SoundCloud selected:
<table>
  <tr>
    <th>Before</th>
    <th>After</th>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
</table>

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SameenAhnaf** [comment]
Unfortunately, this PR doesn't work for me. This is how the UI looks in both #6847 and #6841 apk files.

https://user-images.githubusercontent.com/79245641/128218242-28e93b24-3795-43d2-9bb5-6f2d3102c301.mp4

**Comment by skyGtm** [comment]
@Stypox I think you forgot to commit the code part.
The 'Files Changed' tab is showing 'version bump' and 'changelog' files only.

This might be the reason it's not working @SameenAhnaf

**Comment by Stypox** [comment]
@skyGtm I am stupid, sorry for wasting your time. I've pushed the correct code now...

**Comment by skyGtm** [comment]
Its working for me.
Play Queue theme is same as that of selected service.

**Comment by SameenAhnaf** [comment]
Thanks. It's working now.

Btw, the behavior of buffering icon seems to be inconsistent. I personally think, playback controls should match service colour all over the UI. 

Wdyt? Should I open a new issue or will you fix it now?

<details><summary> Screenshot </summary>



</details>

**Comment by litetex** [comment]
> Description of the changes in your PR
> * record videos
> * create clones
> * take over the world

👀

**Review by TobiGr — APPROVED** [review]
Looks good

**Pull request merged**
