### PR TITLE
Lithuanian strings xml

### PR DESCRIPTION
**Pull request by mobtechpd**
Lithuanian translation

### CODE REVIEW

**Comment by mauriciocolli** [comment]
Hey, thanks for your help.

We do have a translation system in place [here](https://hosted.weblate.org/projects/newpipe/strings) (WebLate).

So you can go to the [Lithuanian language](https://hosted.weblate.org/projects/newpipe/strings/lt) >  `Files > Upload translation` and then you can upload this file (note that you have to be logged on to do that, but it's very easy as you can integrate it with your GitHub account).

**Comment by TobiGr** [comment]
What about this translation? The file has not been uploaded, but since many strings have already been translated, we should use them.

**Comment by mauriciocolli** [comment]
I noticed it too, what about we wait some more before uploading it (maybe didn't get notified/missed)? Then he can get the credit for his work.

**Comment by TobiGr** [comment]
Since this translation was made, some English strings were modified. I am going to upload an improved version of this translation, which you can find [here](https://gist.github.com/TobiGr/33a32bf26d8938ce44c73056d2fc7882), soon.  

Here's a small comparison of my changes.

I removed following strings:

- video_is_age_restricted
- storage_permission_denied
- views
- short_thousand
- short_million
- short_billion
- view

I changed these strings:
- autoplay_by_calling_app_summary
- kore_not_found
- finish
- m4a_description

**Pull request closed without merging**
