### PR TITLE
Show subscriber count on video details page

### LINKED ISSUE #2587: The number of subscribers of a youtube channel is not shown below the video
1
When a video clicks in the search. Then the main page comes and sees the name of the youtube channel below the video.

But unfortunately does not show how many subscribers the youtube channel has. only if you type on the youtube channel.

Here an example:
https://github.com/TeamNewPipe/NewPipe/blob/dev/fastlane/metadata/android/en-US/images/phoneScreenshots/shot_06.png

### PR DESCRIPTION
**Pull request by Theta-Dev**
#### What is it?
- [ ] Bugfix (user facing)
- [X] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
I added the subscriber count to the channel tag on the player page. It currently only shows on YouTube videos because NPE does not return the subscriber count for streams on other platforms, but that can be fixed in the extractor later.

#### Fixes the following issue(s)
- Fixes #2587 

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [X] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tsiflimagas** [comment]
Related issue #2587.
Thanks for the change btw!

**Review by TobiGr — APPROVED** [review]
LGTM! Thank you

**Comment by AudricV** [comment]
Thanks for this feature!

I am not sure if the method used to add the subscriber count is the good one, in terms of code and for RTL languages (even if I don't really know Android specific things). Could you check this, please?

**Comment by tvnmguy** [comment]
Make subscribers count dimmed

**Review by Stypox — APPROVED** [review]
I rebased and made the text dimmer. Thank you :-D
image

**Pull request merged**
