### PR TITLE
Add basic support of playlist

### PR DESCRIPTION
**Pull request by BlenderViking**
Hi,

I made the playlist support for your greatest app 👍 

You can made a local playlist and add item for the search :

[](https://cloud.githubusercontent.com/assets/5410525/20182780/413286c2-a763-11e6-9bc0-06e90dd424f3.png)

If you tap on the more button these contextual menu is show :

[](https://cloud.githubusercontent.com/assets/5410525/20182977/efa3bdde-a763-11e6-87d4-88325b40af5f.png) [](https://cloud.githubusercontent.com/assets/5410525/20182980/f2188cc0-a763-11e6-801c-5d29be15aca4.png)
playlist 55
[](https://cloud.githubusercontent.com/assets/5410525/20183107/89834e42-a764-11e6-8eb2-7454f9cba101.png)

You can access to playlist screen with the contextual menu : 

[](https://cloud.githubusercontent.com/assets/5410525/20183227/ec252016-a764-11e6-9ab8-1967bfc5c708.png) [](https://cloud.githubusercontent.com/assets/5410525/20183256/02fd5380-a765-11e6-9b1e-7c99a29ce23a.png)
[](https://cloud.githubusercontent.com/assets/5410525/20183446/a0e7073a-a765-11e6-9ece-75bd3ccb7ccf.png)

An auto-play option mode for local playlist is now available : 
[](https://cloud.githubusercontent.com/assets/5410525/20183300/1fbcb51a-a765-11e6-93c9-75ef1c8dd3b2.png) [](https://cloud.githubusercontent.com/assets/5410525/20183381/62be9bd0-a765-11e6-8a9e-39dfe32ce500.png)

Retrieve a playlist directly from youtube is now supported : 

[](https://cloud.githubusercontent.com/assets/5410525/20183409/80781890-a765-11e6-9bb5-8b435943f6f5.png) [](https://cloud.githubusercontent.com/assets/5410525/20220009/29d78a1c-a82c-11e6-926c-cfb5619eaa6b.png)

It's possible to convert to local playlist a youtube playlist, but the content is limited to local loaded items

[](https://cloud.githubusercontent.com/assets/5410525/20220018/31080db6-a82c-11e6-9212-74fec7d4de2a.png)

The local playlist is store on sqlite database : 

I have added [stetho](https://facebook.github.io/stetho/) on project for help to debug sqlite database

With chrome a select my device :

sqlite

And i can query directly my device database :

table_schema

It's missing :

- Allow youtube playlist to autoplay audio or video

### CODE REVIEW

**Comment by theScrabi** [comment]
Thats a lot O.o

**Comment by BlenderViking** [comment]
No problem, I don't usually develop on android, so doing a review of my code seems good to me :-)

**Comment by theScrabi** [comment]
All right I've started testing it. Seems like a lot of work to me. Not bad, but we have to fix certain things.
What would you say if I add your changes to a feature branch, and we try to fix those issues?

**Comment by BlenderViking** [comment]
I agree to join the team and made needing change on the code.

But I have a newbie question, it's my first team work on GitHub: I don't know how to work with this repo, I just need to clone the new url repo and I can push bug fixes into it ?

**Comment by theScrabi** [comment]
Thinks that are need to be done:

StreamInfoItem:
- Fix StreamInfoItem Layout (margin the three dots so they are in the right location)
- make the StreamInfoItem button cover the whole Item not just the top (like it was before)
- Remove the share and play option form the StreamInfoItem context menu
- Make the StreamInfoItem context menu a local drop down menu (like the once of the download items)

Extractor:
- Make the extractor part of the NewPipe extractor (my part)
- Make the extractor fit the NewPipe architecture (my part)
- Write unit tests for the extractor (can only be done before the first two parts are done)

ChannelActivity:
- Create a new layout for play list and queuing
- Use the original layout for ChannelActivity again

Queuing- PlayListActivity:
- Stick to android style guidelines (only one floatingbutton each activity)

Notification:
- Make the rewind button, and the "last video button" be the same
  (if the music runs for more than 2 second rewind, if it runs longer go back to the last video)
- Make, that the notification wont crash if there is no more video in the queue and someone hits the next/last button

etc.
There are some smaller things to, but I think this will be enough for the moment.

**Comment by Rob--W** [comment]
@BlenderViking

To use the repo (let's call it "upstream"):

```sh
git remote add upstream (put the repository's git or ssh URL here, depending on your way of authentication)
git fetch upstream

# new branch based on master
git checkout -b yourfeaturename upstream/master
```

To import commits from your other branch you can use `git cherry-pick`. 

Tips to get much more familiar with git: https://git-scm.com/book/en/v2
https://git-scm.com/book/en/v2/Git-Branching-Remote-Branches
Manual page for `git remote`: https://git-scm.com/docs/git-remote
Index of manual pages: https://git-scm.com/docs

**Comment by theScrabi** [comment]
@BlenderViking
Also at the moment you only have read access. For now you can send a pull request, not to master, but to [playlist](https://github.com/TeamNewPipe/NewPipe/tree/playlist) branch.

**Comment by BlenderViking** [comment]
@theScrabi , @Rob--W 
Thanks you for these information on workflow with GitHub :-)

I have created a local branch playlist with upstream/playlist, process a merge with the current upstream/master for realign diff between these branch and push it to my origin/playlist (on my GitHub page) and it's seen working like a charm 👍 

I will now begin to make the changes to be made to validate the pull request.

**Comment by Rob--W** [comment]
@theScrabi I have never used it, but protected branches seem to fit your needs: https://help.github.com/articles/configuring-protected-branches/

On Github, I usually fork the project, create a branch in my fork and then open a PR on the upstream project when it is ready for merging or feedback. Then other collaborators can review PRs and merge when all is good (`git push -f origin mybranchname` - note force pushing should only be done in your own branches, e.g. to update the PR after amending / rebasing commits in your local repo/branch).

**Comment by theScrabi** [comment]
How is work going on?

**Comment by BlenderViking** [comment]
I made all the points on the checklist on this pull request (on playlist branch) : 

https://github.com/TeamNewPipe/NewPipe/pull/382

Except these points :
- Make the extractor part of the NewPipe extractor
- Make the extractor fit the NewPipe architecture

**Comment by BlenderViking** [comment]
Oups, i miss

**Comment by theScrabi** [comment]
All right I'll take a looknat it

**Comment by timofonic** [comment]
Any news about when will this be available on mainline? What about exporting and importing playlists over YouTube and in some kind of file format too?

**Comment by BlenderViking** [comment]
Hi @timofonic ,

Everything in the checklist: [https://github.com/TeamNewPipe/NewPipe/pull/377#issuecomment-261767552](https://github.com/TeamNewPipe/NewPipe/pull/377#issuecomment-261767552)
Are implemented, it's just missing the `Extractor` part.

Actually the playlist code is available in the playlist branch, see here: [https://github.com/TeamNewPipe/NewPipe/pull/382](https://github.com/TeamNewPipe/NewPipe/pull/382)

It's support import from YouTube (only public playlist), but we can't provide an export to YouTube.

**Comment by theScrabi** [comment]
@BlenderViking @timofonic I'm on it, at the moment I'm not ready yet, but I'll take a look at it.

**Comment by theScrabi** [comment]
Sorry that I kept you waiting for so long. I've made a lot of changes since you submitted your request. Can you please try to merge your request with the current version.

**Comment by BlenderViking** [comment]
@theScrabi 

This can take time, I see a lot of change in main code base.

I will look on when I not busy. But not for now, i need more free time, I will notify you when I start the code refactor (Not in this month, maybe in April).

**Comment by theScrabi** [comment]
All right thank you.

**Comment by andersonvom** [comment]
First of all, great job for getting this done! It's quite impressive! \o/

I don't know if, given the current state of affairs, this advice will be useful or not, but may I suggest that, instead of trying to get all 60+ commits merged at once, while the main code base keeps changing, that you try to get a smaller number of commits in?

That is, try to add as little functionality as possible that doesn't break anything and build on top of that going forward. This will reduce the burden for folks that need to review the code and also make it easier on you, since you'll have to deal with less conflicts. =)

For instance, you could first add behavior to just have a single queue where users can add to, without being able to manage it; then you can add the screen to view the current queue; then be able to manage that songs (reorder, remove, etc); etc...

Since you have already written a lot of code, this might not make too much sense, but I thought I'd give my two cents since I'm quite excited about having this available! Keep it up!

**Comment by BlenderViking** [comment]
This Sunday I started the refactor of this pull request.

For avoid a big merge of the hell, I split it in multiple step and I don't want to start the next step before the current step isn't approval for avoid a to big change in the code base.

The first part is here and goal is retrieve playlist from a provider (YouTube)  : https://github.com/TeamNewPipe/NewPipeExtractor/pull/2

@andersonvom Thanks you :-)

**Comment by theScrabi** [comment]
[Extractor](https://github.com/TeamNewPipe/NewPipeExtractor) does now support playlist, thanks to BlenderViking

**Comment by theScrabi** [comment]
@BlenderViking you can use the old ChannelActivity layout, since we have a new one, and it's not used anymore. Also you where already using that layout, so I wanted to tell you that you can now continue to use it :)

**Comment by BlenderViking** [comment]
Hi @theScrabi,

This weekend, I continued to work on the refactor. You can follow changes on branch [playlist_sqlite](https://github.com/BlenderViking/NewPipe/tree/playlist_sqlite).

Currently, it's I just made the stuff for the SQL Database manipulation.

**Comment by SUguy** [comment]
Sorry, I know asking for ETA is bad. But I am very excited for this feature. @BlenderViking Any progress?

**Comment by nate2014jatc** [comment]
@SUguy I'm also excitedly waiting for this function

**Comment by mauriciocolli** [comment]
I think we can close it now.

**Comment by turdusmerula** [comment]
This look like a great work !
Is there any planed release date for this functionality?

**Pull request closed without merging**
