### PR TITLE
Created Somali Readme

### PR DESCRIPTION
**Pull request by nadiration**
Created README.so.md file

#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [x] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

Created Readme file for Somali

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mhmdanas** [comment]
Thanks for creating an PR! You usually shouldn't add new items to the "What is it?" section. In this case, you should remove your "read me translation" item and instead check "Meta improvement to the project (dev facing)" since this is not a user-facing change and isn't strictly related to code.

**Comment by nadiration** [comment]
> Thanks for creating an PR! You usually shouldn't add new items to the "What is it?" section. In this case, you should remove your "read me translation" item and instead check "Meta improvement to the project (dev facing)" since this is not a user-facing change and isn't strictly related to code.

Done

**Comment by TobiGr** [comment]
Thank you, please link this translations in the other two READMEs
https://github.com/TeamNewPipe/NewPipe/blob/dev/README.md
https://github.com/TeamNewPipe/NewPipe/blob/dev/README.ko.md

**Review by nadiration — COMMENTED** [review]
If by linking you mean the link in 'Read this in another language' i already did that from the beginning. Now (third update) i added : sign next to the word "Warning:" (the one that warns about the beta version) which i forgot before.

**Comment by TobiGr** [comment]
What I meant was linking this translation in the other READMEs, so it can be found :)

**Comment by nadiration** [comment]
> What I meant was linking this translation in the other READMEs, so it can be found :)

How do i do that?

**Comment by opusforlife2** [comment]
@nadiration You edit the other README files and add a link to the Somali README in them.

**Comment by nadiration** [comment]
@TobiGr done. I linked them and created PR for them

**Review by TobiGr — APPROVED** [review]
Well, you don't need to open a PR for every file you edit. While editing the files, just make sure you are on the branch of your PR.

**Pull request merged**
