### PR TITLE
Change loop index from float to int

### PR DESCRIPTION
**Pull request by bd0n4lds**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

Codacy found issues "Don't use floating point for loop indices. If you must use floating-point, use double."

#### Fixes the following issue(s)

- 

#### Relies on the following changes

- 

#### APK testing 

debug.zip

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Redirion** [comment]
I don't think that is how it should be handled. This just looks wrong.

**Comment by bd0n4lds** [comment]
Redid the casting on the for loop indices and changed back the variable mMarqueeProgress to float.

**Comment by TobiGr** [comment]
why is `i` still a double? Can't we use `int`?

**Comment by bd0n4lds** [comment]
> 
> 
> why is `i` still a double? Can't we use `int`?

Made the change

**Comment by Redirion** [comment]
looks okay now. Please squash your commits.

**Review by Stypox — APPROVED** [review]
@bd0n4lds thank you for noticing this ;-)
@Redirion I squashed

**Pull request merged**
