### PR TITLE
Android TV banner with text

### PR DESCRIPTION
**Pull request by starsep**
#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

I added text to Android TV banner.
According to https://developer.android.com/training/tv/start/start#banner
> The banner should be an xhdpi resource with a size of 320 x 180 px. **Text must be included in the image**. If your app is available in more than one language, you must provide separate versions of the banner with text for each supported language.

I edited existing banner, moved the logo to the left and added white NewPipe text.
Font is Sans-serif 40px.

#### Before/After Screenshots/Screen Record

- Before:
First screenshot from a TV, rest is from emulator.
image
image
image

- After:
image
image

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

⚠️ Dev Note: Squash merge this PR to keep the git commit history small

### CODE REVIEW

**Comment by mhmdanas** [comment]
Thanks for the PR! Since we're changing the banner anyway, would you mind if I losslessly (i.e. without any visual changes) compressed it?

**Comment by starsep** [comment]
> Thanks for the PR! Since we're changing the banner anyway, would you mind if I losslessly (i.e. without any visual changes) compressed it?

Sure! It's so small that I haven't even considered using something like oxipng. I just used GIMP defaults.

**Comment by mhmdanas** [comment]
Done. For the one who merges the PR, please squash merge.

> Sure! It's so small that I haven't even considered using something like oxipng. I just used GIMP defaults.

Yeah, but it's still smaller. :D

**Review by mhmdanas — DISMISSED** [review]
LGTM, will merge if no objections arise.

**Review by TiA4f8R — COMMENTED** [review]
Thank you for the pull request!

In my opinion, when I compare to the other apps in the screenshot of the app list you uploaded, the result doesn't look really good. I think the text is too close to the the logo and the font doesn't really match with Android TV's UI.

Can't you use Roboto to make the text look like this (it's the appearance of what looks like the Settings page window title of NewPipe in French with Material Design version 2)?

Settings French Material Design v2

What do you think?

**Comment by starsep** [comment]
> Thank you for the pull request!
> 
> In my opinion, when I compare to the other apps in the screenshot of the app list you uploaded, the result doesn't look really good. I think the text is too close to the the logo and the font doesn't really match with Android TV's UI.
> 
> Can't you use Roboto to make the text look like this (it's the appearance of what looks like the Settings page window title of NewPipe in French with Material Design version 2)?
> 
> Settings French Material Design v2
> 
> What do you think?

I think Roboto looks better indeed. Unfortunately I don't have an access to a computer right now due to holidays. I could tweak font/margins in a few days. If anybody wants to send some banner proposal in the meantime feel free to do so :).

**Comment by peat80** [comment]
newpipe_tv_banner-roboto (compressed)

**Comment by starsep** [comment]
Roboto Heavy size 48, logo moved 10px to the right, smaller distance between logo and text
image
image
image
image

**Comment by litetex** [comment]
@mhmdanas

**Comment by TiA4f8R** [comment]
@starsep Why did you decrease distance between text and logo? In my opinion it looks worse than before.

Maybe you should decrease the logo size instead so you can get more space between the logo and the text.

**Comment by mhmdanas** [comment]
I agree with @TiA4f8R. Also, maybe the text is a little too bold? What do you think?

**Comment by AioiLight** [comment]
アートボード 1

It should use theme color of NewPipe. I also thought pure red (FF0000) and white (FFFFFF) is too bright.
Above image is also adjusted font's weight and size. @mhmdanas How do you feel?

**Comment by starsep** [comment]
> アートボード 1
> 
> It should use theme color of NewPipe. I also thought pure red (FF0000) and white (FFFFFF) is too bright. Above image is also adjusted font's weight and size. @mhmdanas How do you feel?

I think it looks great and it solves aforementioned issues. I commited it and pushed.
image
image
image

**Comment by mhmdanas** [comment]
@AioiLight looks great, thanks!

**Comment by AioiLight** [comment]
Nice! I put the vector image file for future changes.
[android-tv-banner.zip](https://github.com/TeamNewPipe/NewPipe/files/7822733/android-tv-banner.zip)

**Comment by litetex** [comment]
> Nice! I put the vector image file for future changes. [android-tv-banner.zip](https://github.com/TeamNewPipe/NewPipe/files/7822733/android-tv-banner.zip)

Thank you.
I think we should put the file into the assets folder, so that it is tracked in Git.

**Comment by AioiLight** [comment]
> Thank you.
> I think we should put the file into the assets folder, so that it is tracked in Git.

Indeed. We can use this file for other purpose by putting it.

**Comment by litetex** [comment]
@starsep Ping.
I would upload the files myself if I could. However I can't push files to the PR-branch.

**Comment by starsep** [comment]
> @starsep Ping. I would upload the files myself if I could. However I can't push files to the PR-branch.

I commited it in d0218cba2a5e76705c4a0ec90dda4c96f8b0d976

**Review by litetex — APPROVED** [review]
LGTM

**Comment by mhmdanas** [comment]
@litetex give me a bit, I'll optimize the image.

**Review by mhmdanas — APPROVED** [review]
LGTM, thanks!

**Comment by mhmdanas** [comment]
> I would upload the files myself if I could. However I can't push files to the PR-branch.

@litetex that's weird, I can push to this branch just fine.

**Pull request merged**
