### PR TITLE
[WIP] autoplay on screenrotation

### PR DESCRIPTION
**Pull request by scubajeff**
1. Use SYSTEM_UI_FLAG_LOW_PROFILE instead of SYSTEM_UI_FLAG_HIDE_NAVIGATION in full screen play mode, so that the back navigation button can be easily pressed.

2. Turn handset into landscape mode will start playing the current media automatically, a feature I think is worth borrowing from the Google Youtube app.

### CODE REVIEW

**Comment by scubajeff** [comment]
Regarding the full screen mode UI, I agree that screen estate should be dedicated to content, so I suggest adding a back button to the action bar which shows up when user touch the screen. For now, user has to swipe down or up to show the system navigation bar, this swipe gesture is often mistaken as the volume/brightness increase/decrease gesture.

**Comment by karyogamy** [comment]
> user has to swipe down or up to show the system navigation bar

This should be fixed with 13.2 release.

**Comment by theScrabi** [comment]
It is

**Comment by scubajeff** [comment]
Sorry, my first time doing this pull request thing. What is nr.?

**Comment by theScrabi** [comment]
Your swcond point you wrote.

**Comment by theScrabi** [comment]
@karyogamy but somehow on the current debug version sys ui is not vissible again.

**Comment by karyogamy** [comment]
@theScrabi wat? screenshots please

Btw, I don't think there was any change made to the main player code since 13.2, maybe the build is on a modified/different branch?

**Comment by scubajeff** [comment]
So, do I have to create a new pull request for the second point?

**Comment by theScrabi** [comment]
what is the status of this PR?

**Comment by scubajeff** [comment]
The following is my suggestion on this PR:

a. If the device is tablet, disable autoplay feature
b. Create a autoplay toggle preference, default is on for phone devices
c. If autoplay is on, and the user rotate the device to landscape mode in detail fragment, the media will play automatically
d. If user enter the detail fragment in landscape mode, the media won't start playing automatically, so that user will have a chance to see all those info. in the fragment. If the user rotate the handset afterwards, the media will start to play.
e. Autoplay feature is for main player only, not for popup player or backgroud player

Please comment.

**Comment by theScrabi** [comment]
I think we shouldn't do some advanced checks. I think a simple point in the settings should be enough.

**Comment by scubajeff** [comment]
landscape mode auto play menu item added.

**Comment by scubajeff** [comment]
What's the status now?

**Comment by theScrabi** [comment]
I currently have some time issues, but I will take a look at this and all other pending things once I have spare time.

May take up to two weeks tho.

**Comment by theScrabi** [comment]
Could someone please QA this.

**Pull request closed without merging**
