### PR TITLE
Use ExoPlayer default values for buffers

### PR DESCRIPTION
**Pull request by Redirion**
#### What is it?
- [X] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

ExoPlayer 2.12 noted this in the changelog:
_Set the default minimum buffer duration in DefaultLoadControl to 50 seconds (equal to the default maximum buffer), and treat audio and video the same._

Maybe there was a reason they decided to have both minimum and maximum buffer identical since 2.12. NewPipe used years old constants which are now removed in favor of ExoPlayer constants so that future versions will keep up with what changes at ExoPlayer.

#### Fixes the following issue(s)

Hopefully fixes some of the buffer issues we have lately like #6510 

#### APK testing 

On the website the APK can be found by going to the "Checks" tab below the title and then on "artifacts" on the right.

#### Due diligence
- [X] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by opusforlife2** [comment]
It does seem like this solves the issue.

In fact, it seems to have taken Newpipe back to the old behaviour, where it keeps buffering the video endlessly, unless you rewind or fast forward (may not work), or change the resolution (usually works).

**Comment by tsiflimagas** [comment]
@opusforlife2 I got the same error too, without this commit, so maybe it's not related to it.

**Comment by litetex** [comment]
Is this pull request anymore required?

The exact problem was found and we got https://github.com/TeamNewPipe/NewPipe/pull/6673 that hopefully fixes it 😄

**Comment by XiangRongLin** [comment]
Unless there are good reasons to deviate from the default values, I would still merge this. The guys from exoplayer probably put more thought into those values than we.

**Review by TobiGr — APPROVED** [review]
Looks good to me. I did not ran into any issues while testing.

**Pull request merged**
