### PR TITLE
Check that playlist name doesn't exist before creating. Fail with toa…

### PR DESCRIPTION
**Pull request by nmurali94**
#### What is it?
- [x] Bug fix (user facing)
- [ ] Feature (user facing)
- [ ] Code base improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Prevent users from creating multiple playlists with the same name when appending a stream to a playlist
- Retain the playlist pop-up to allow users to cancel creating new playlist and append video to an existing one
- Add toast message when we fail to create playlist. Improve text of other toast messages.
- Vertically align the "New Playlist" button with video title in the playlist menu

#### Fixes the following issue(s)

-  https://github.com/TeamNewPipe/NewPipe/issues/4132

#### Testing apk

[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5081977/app-debug.zip)

#### Agreement
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by MD77MD** [comment]
🙏I wish this would not prevent us from creating playlists with empty names (blank)... 

when I'm in hurry or don't have time to finish my play queue, I usually save it as a playlists with blank name. I then delete these playlists later whenever I complete one... this way I don't waist time and energy naming them. 

P.S:   playlists with blank name show on top as a bonus too

**Comment by nmurali94** [comment]
@MD77MD If I understand you correctly, you want a quick to create a temporary but identifiable playlist. If there's enough ask for it we could add a button that would handle this. For example, it would create a playlist "default-0". If it already exists then "default-1" and continue to increase if necessary. But obviously loses the convenience of being the first result (maybe https://github.com/TeamNewPipe/NewPipe/issues/3870 can solve that problem)

You can still largely use your current approach with a slight increase in user effort. The current implementation still allows multiple playlists with non visible names so you create playlists with 1) no input,  2) one white space 3) two white spaces so on.  During display, they will be shown in the same order as listed here.

**Comment by opusforlife2** [comment]
How about a default "Watch later" playlist?

**Comment by litetex** [comment]
Closing this for now:
* no progress
* no GitHub actions build
* merge conflicts
* Found todo comments and various other unfinished code / typos - assuming this is a draft

Feel free to reopen it when there is progress again.

**Pull request closed without merging**
