### PR TITLE
Added night variant for splash_background.xml

### LINKED ISSUE #7048: Darker splash screen for system wide night mode
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
I think when using system wide dark mode, darker splash screen should be shown instead of the bright one.

#### Is your feature request related to a problem? Please describe it
"Oopps it's so bright even in darker mode" is what comes to mind every time I launch New Pipe :)

#### Additional context

as discussed in #6244 

#### How will you/everyone benefit from this feature?
I know users using dark mode definitely want this.

### PR DESCRIPTION
**Pull request by sauravrao637**
#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

added night value in res for Opening Theme
added splash_background_night

#### Before/After Screenshots/Screen Record

- Before: Bright launch screen even when using dark mode system wide
- After: Now it's darker :)

#### Fixes the following issue(s)

- Fixes #7048

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sauravrao637** [comment]
@opusforlife2 how does the darker splash screen looks?

**Comment by opusforlife2** [comment]
@sauravrao637 Well, I would need before/after screenshots to compare. Please add them to the description, since this is a UI change. But if it's the same dark red colour as the app, then I think it would look great. That's the colour I was expecting the splash screen to be after your earlier PR.

(Though I did fantasise for a moment about a dark shadowed Newpipe icon on a dark grey background, to be honest.)

**Comment by sauravrao637** [comment]
@opusforlife2  Yup it's the same dark color, we can make it black or dark grey as well , what do you think will be better?

**Comment by tsiflimagas** [comment]
I like the colour, but is it possible to make it follow the app's theme (or if you intended to do it so, is it possible to fix it?).

**Comment by mhmdanas** [comment]
@tsiflimagas that's not possible unfortunately, see https://github.com/TeamNewPipe/NewPipe/pull/6244#issuecomment-912691756.

**Comment by tsiflimagas** [comment]
@mhmdanas oh, I see, thank you. No problem then :)

**Comment by opusforlife2** [comment]
@sauravrao637 I think the current colour is fine for this PR. If you have some spare time later, we could experiment with colours in a new issue. :D

**Review by TobiGr — APPROVED** [review]

**Comment by opusforlife2** [comment]
@sauravrao637 You put the code changes as the PR title again. :P

Edited.

**Pull request merged**
