### PR TITLE
Crop the notification thumbnail in 1:1 mode instead of stretching it

### LINKED ISSUE #8478: Crop the notification thumbnail in 1:1 mode instead of stretching it
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

When the "Scale thumbnail to 1:1 aspect ratio" setting is enabled, the thumbnail should be cropped down as to make it 1:1, instead of it being scaled to be 1:1.

### Why do you want this feature?

While using the whole thumbnail for the notification's large icon works fine on Android 10 and below, it breaks down on Android 11/12, in which it looks out of place. The 1:1 option is also not ideal here, as it distorts the thumbnail in an unappealing manner.

### Additional information

I have a fork with this fix already implemented [here](https://github.com/OxygenCobalt/NewPipe/tree/crop-notification-large-icon), I just want to know whether there are any issues with cropping the thumbnail in such a way, hence why scaling was used instead.

### PR DESCRIPTION
**Pull request by OxygenCobalt**
#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
While using the whole thumbnail for the notification's large icon works fine on Android 10 and below, it breaks down on Android 11/12, in which it leaves a large amount of whitespace. The 1:1 option is also not ideal here, as it distorts the thumbnail in an unappealing manner.

This PR changes the scaling mechanism used to crop the thumbnail to a 1:1 ratio instead of stretching it. More specifically, it picks the smaller dimension from the thumbnail and then scales the larger dimension down to fit, cropping the thumbnail to the center in the process. I feel this is much better than how the option currently works.

#### Before/After Screenshots/Screen Record

- Before:
image

- After:
image

#### Fixes the following issue(s)

- Resolves #8478

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by opusforlife2** [comment]
Go ahead. 👍

**Comment by OxygenCobalt** [comment]
Done. This can probably be merged now @opusforlife2.

**Review by Stypox — APPROVED** [review]
Looks good to me. Thank you!

**Comment by AudricV** [comment]
Note: we have to delete translations of the strings updated in this PR in order to apply their changes in translations.

**Comment by Stypox** [comment]
Uhm, no? Weblate already takes care of asking translators to re-translate outdated strings, if I remember correctly.

**Pull request merged**
