### PR TITLE
Update some AndroidX libraries

### PR DESCRIPTION
**Pull request by TacoTheDank**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
This PR is meant as a follow up to https://github.com/TeamNewPipe/NewPipe/pull/6702.

- https://github.com/TeamNewPipe/NewPipe/pull/6633#issuecomment-882505567
- Update AndroidX AppCompat 1.3.0 -> 1.3.1 ([changelog](https://developer.android.com/jetpack/androidx/releases/appcompat#version_131_3))
- Update AndroidX Core 1.3.2 -> 1.6.0 ([changelog](https://developer.android.com/jetpack/androidx/releases/core#core_and_core-ktx_version_160_2))
- Update AndroidX Fragment 1.3.5 -> 1.3.6 ([changelog](https://developer.android.com/jetpack/androidx/releases/fragment#version_136_3))
- Update AndroidX Lifecycle 2.2.0 -> 2.3.1 ([changelog](https://developer.android.com/jetpack/androidx/releases/lifecycle#version_231_2))
- Users are basically already using these versions internally because of AppCompat's upgrade to 1.3.0 (other than Core 1.6.0, because AppCompat 1.3.0 uses Core 1.5.0 internally)

#### APK testing 
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by Stypox — APPROVED** [review]
I've read the changelogs and could not find anything that could break NewPipe, though I do not know enough about AndroidX libraries.

**Comment by Redirion** [comment]
assuming further appCompat versions will also update it's transitive dependencies to recommended versions, would anything speaking against removing the dependencies to core and lifecycle completely from the build.gradle?

Would make future updates easier / require less maintenance for the dependencies.

**Comment by TacoTheDank** [comment]
> assuming further appCompat versions will also update it's transitive dependencies to recommended versions, would anything be speaking against removing the dependencies to core and lifecycle completely from the build.gradle?
> 
> Would make future updates easier / require less maintenance for the dependencies.

I would probably recommend keeping them, as they can also be updated separately, and allow for usage of Kotlin extensions as well (core-ktx, lifecycle ktx, etc.).

**Comment by TacoTheDank** [comment]
AndroidX AppCompat 1.3.1 and AndroidX Fragment 1.3.6 came out today, so I'll include those in this PR as they're just bugfix releases.

**Review by Stypox — APPROVED** [review]
@Redirion merge this if you think it looks fine

**Pull request merged**
