### PR TITLE
Remove IP range

### LINKED ISSUE #1148: [data protection] IP address request to third party service leaks information about users
At the moment, the service https://ipv4.icanhazip.com is used by the crash report activity to (whyever) fetch the public IPv4 of a user, which is then "anonymized" by removing the last two bytes.

Not only this information doesn't really add anything to the crash reports (at least nothing I could think of), it also shares the following details with this service (which, so far, nobody checked, regarding data protection and privacy):
  - complete IP address (and therefore an approximation of their location)
  - user's operating system
  - user is using NewPipe (user agent thing)
  - time of the crash (allows for generating stats like frequency, ...)

In my opinion, this "feature" should be removed entirely from NewPipe, following the data protection principle of "Datensparsamkeit" (a.k.a. "data economy", i.e., reduce the amount of data collected to the absolute minimum).

If there are good reasons to continue to collect this information, however, the implementation needs to be improved to ensure users' privacy (otherwise, one of our USPs, "privacy", doesn't apply):
  - validate service's ToS and ensure they won't collect and/or share the information
  - implement multiple providers (I'd say at least 5) and choose a random one every time (round-robin like)
  - ask user whether they want to share this information, maybe with a checkbox they can uncheck, and request service only when the user confirms they want to send a mail (i.e., don't auto fetch it when the activity is shown)

By the way, according to https://major.io/icanhazip-com-faq/, the software is open source, but the requests are all logged and there is no word about deletion of logs. Also, we don't know anything about where it's hosted and how many "service providers" the provider makes use of have access to the data or network streams.

CC @theScrabi

### PR DESCRIPTION
**Pull request by wb9688**
This would close #1148. I haven't tested it myself yet. @TheAssassin: Could you update the Sentry part?

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by TheAssassin** [comment]
@wb9688 I'll put it on my TODO list. Might take a couple of days.

**Comment by theScrabi** [comment]
Mucho gracia.

**Comment by speednroll** [comment]
it says "muchas gracias" :joy:

**Comment by TheAssassin** [comment]
I thought the same, @speednroll, but as I don't speak Spanish, I didn't want to comment first.

**Comment by theScrabi** [comment]
@speednroll corrected ... Yea my skills in Spanish are still very basic

**Pull request merged**
