### PR TITLE
Improve new stream notifications

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Create individual stream notifications so that they can be selected to load the video directly. The notifications are [grouped together on Android 7.0 and later](https://developer.android.com/develop/ui/views/notifications/group) and are individually actionable. The old behavior (showing a summary notification containing the stream names which opens the channel) is preserved on Android versions below 7.0.
- Simplify the summary notification, showing the number of streams when collapsed and the stream titles when expanded.
- Fix vertically alignment of NewPipe pure logo / white triangle

#### Before/After Screenshots/Screen Record

- Before:

All versions of Android:

Screenshot_20230507_130806_NewPipe

- After:

Android versions below 7.0:

Screenshot_20230507_185711

Android 7.0 and later (screenshots were taken on Android 13):

Screenshot_20230507_115715_One UI Home
Screenshot_20230507_131704_Gallery

https://user-images.githubusercontent.com/31027858/236666385-f0fbe9b1-0c98-4734-a4ff-18f499bb99b0.mp4

#### Fixes the following issue(s)

- Fixes #

#### Relies on the following changes

- 

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Isira-Seneviratne** [comment]
> Is there no way to include stream information`5 new streams` notification above all channel names `BBC News, Al Jazeera and 2 more` in case of Android 7.0 and below?

The stream names are shown in the expanded view on Android versions below 7.0. I couldn't expand the notification in that screenshot I took on an emulator.

**Review by snaik20 — APPROVED** [review]

**Comment by TobiGr** [comment]
Fixed the NewPipe icon. The triangle was not centered in the pure export for some reason.
grafik

**Comment by Isira-Seneviratne** [comment]
> Is it possible to still display the channel logo, too?
> 

Yeah, it should be possible by setting the stream notifications' large icons.

**Comment by TobiGr** [comment]
Good. Do you have time to implement that or should I give it a try?

**Comment by Isira-Seneviratne** [comment]
I'll implement it.

**Review by TobiGr — APPROVED** [review]

**Pull request merged**
