### PR TITLE
fix scrolling in video detail fragment. fixes #2627

### LINKED ISSUE #2437: Scrolling jumps when "Animator duration scale" is set
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] ~~I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.~~

On my phone, I set "Animator duration scale" to Off (0 duration). Then I open the "Youtube video info screen" (with a large tappable video image).

- When I scroll up and release my finger *with the video icon partially on the screen*, the entire page snaps up to the top of the page.
- If I scroll down and release my finger *with the video icon partially on the screen*, the entire page snaps down so the video is entirely off-screen, and then normal momentum scrolling begins.

The bug goes away if I change "Animator duration scale" to 1x duration.

Moto G5 Plus, Android 7.0, Newpipe 0.16.2 (F-Droid?).

### LINKED ISSUE #2627: Scrolling issue
Do not have a log for this but it seems that scrolling down through comments or recommended videos is smooth but when you go back up it just almost instantly pulls the video preview up. It works fine but the activation for it to trigger is super sensitive. Ive tested holding a finger on the screen to stop it from scrolling and that works but if it has even a little motion (without a finger on the screen) going back towards the video bam instantly pop preview back up.

### PR DESCRIPTION
**Pull request by yausername**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

Fixes #2627 
Fixes #2437
Also, ParalaxScrollView is removed from dependencies and credits since it is not being used any more.

### CODE REVIEW

**Comment by Stypox** [comment]
When the description is open scrolling issues are still there. I can send a video, in case you can't reproduce.
Debug apk from commit 5d9b5a063bbda7a3825b6a0509d5e7c3777fc95f: [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/3667674/app-debug.zip)

**Comment by yausername** [comment]
Hi @Stypox 
What are the steps to reproduce? A video will help too.
Thanks

**Comment by Stypox** [comment]
Here is a video of the issue. The only two steps needed to trigger the issue are to open the video description and to scroll down until the description is not visible anymore, then scroll back up.
I uploaded both a 20fps version and a 25fps one since the bouncing could sometimes not be seen otherwise (the gif converter I use does not allow for fps>25). @yausername   

20fps
20fps

25fps
25fps

**Comment by yausername** [comment]
@Stypox can you check again? I have made some changes.

**Comment by yausername** [comment]
[app-debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/3679714/app-debug.apk.zip) for testing

**Comment by Stypox** [comment]
Now the issue has disappeared, thank you!

**Comment by Stypox** [comment]
This also fixes #2437

**Comment by yausername** [comment]
@TobiGr would be nice to have this fix go in the next release.

**Comment by TobiGr** [comment]
Sure, I'll just do some testing with a KitKat emulator.

**Pull request merged**
