### PR TITLE
Moved player notification setting to notification section

### LINKED ISSUE #8232: Move `Player Notifications` setting into `Notifications` section
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

Latest version after https://github.com/TeamNewPipe/NewPipe/pull/2335 got merged

### Steps to reproduce the bug

1. Go to `Settings`
2. Go to `Notifications`

### Expected behavior

As new stream notifications are now implemented, it's expected to see player notifications as a separate sub-section in `Notifications`. 

### Actual behavior

Player notifications are moved to `Appearence` section. 

### Screenshots/Screen recordings

_No response_

### Logs

_No response_

### Affected Android/Custom ROM version

_No response_

### Affected device model

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by pratyaksh1610**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

Moved player notification setting to notification section

#### Before/After Screenshots/Screen Record

<table>
  <tr>
    <th>Before</th>
    <th>After</th>
  </tr>
  <tr>
    <td>

https://user-images.githubusercontent.com/76740999/208883449-8ae038c2-409c-4939-a85d-31479dd6ee47.mp4

</td>
    <td>

https://user-images.githubusercontent.com/76740999/208883465-53aa48a4-1fa9-4bd7-b0a8-451181d3a8cf.mp4

</td>
  </tr>
</table>

#### Fixes the following issue(s)

- Fixes #8232

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Stypox** [comment]
I agree with @SameenAhnaf

**Comment by Stypox** [comment]
(sorry my mistake, I forgot about #9587)

**Comment by XilinJia** [comment]
This seems like not ready for review?  Still need author to respond.

**Review by Stypox — APPROVED** [review]
Thank you!

**Pull request merged**
