### PR TITLE
Use AndroidX Media compat in AudioReactor

### PR DESCRIPTION
**Pull request by TacoTheDank**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
- Updates AndroidX Media from a transitive version of 1.0.1 to a declared version of 1.2.1 ([changelog](https://developer.android.com/jetpack/androidx/releases/media))
- Simplifies some methods, as the compat classes use the appropriate code automatically

#### APK testing 
[app-debug-androidx-media-audioreactor.zip](https://github.com/TeamNewPipe/NewPipe/files/5626506/app-debug-androidx-media-audioreactor.zip)

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Redirion** [comment]
you can update to 1.2.1 :)

**Comment by TacoTheDank** [comment]
@Redirion 👍

**Comment by TacoTheDank** [comment]
Ok there we go. That was weird 🤔

**Comment by mhmdanas** [comment]
Now that I take a look at Gradle dependencies, I noticed that none of the AndroidX dependencies have entries in the licenses page. Is this intentional?

**Comment by TacoTheDank** [comment]
@mhmdanas Coincidentally, I made a PR dealing with updating the displayed licenses around the same time as this one: https://github.com/TeamNewPipe/NewPipe/pull/5066

**Review by Stypox — APPROVED** [review]
Looks good to me, thank you :-D
@Redirion could you also approve, if you think it's ok?

**Comment by Redirion** [comment]
```
    public int getMaxVolume() {
        return audioManager.getStreamMaxVolume(STREAM_TYPE);
    }
```

Could be replaced with:
```
    public int getMaxVolume() {
        return AudioManagerCompat.getStreamMaxVolume(audioManager, STREAM_TYPE);
    }
```

**Comment by TacoTheDank** [comment]
@Redirion Completely missed that!

**Review by Redirion — DISMISSED** [review]
@Stypox looks ready to merge

**Comment by TacoTheDank** [comment]
@Stypox Sorry for another mention, but idk if this was missed (repo activity looks mighty hectic right now). This should be all good to merge :)

**Review by Redirion — APPROVED** [review]

**Comment by Redirion** [comment]
I would like to merge this, but due to the "2 vulnerabilities" it isn't possible. @theScrabi can you check why this is blocking? I don't have access to snyk.

**Comment by TacoTheDank** [comment]
Some of the other PRs around the time this one was made have also faced the same issue 🤔

**Comment by opusforlife2** [comment]
> but due to the "2 vulnerabilities" it isn't possible

That used to be the case earlier. Now you can see that it doesn't have the "Required" label, which `build-and-test` does. So the Snyk check isn't blocking the merge, the `build-and-test` Action is.

Why it isn't either running or finished is a mystery. The Checks tab should show a job, and there are currently none.

**Comment by TacoTheDank** [comment]
@opusforlife2 Do you think it would regenerate the checks if I repushed the commit? 🤔

**Comment by TacoTheDank** [comment]
> @opusforlife2 Do you think it would regenerate the checks if I repushed the commit? 🤔 I'll give it a try.

It worked :)

**Review by Redirion — APPROVED** [review]

**Comment by opusforlife2** [comment]
Yay!

**Pull request merged**
