### PR TITLE
Updated de (German) translation

### PR DESCRIPTION
**Pull request by squeezer11**
Commit made via Stringlate

### CODE REVIEW

**Comment by wb9688** [comment]
Please use our [Weblate](https://hosted.weblate.org/engage/NewPipe/).

**Comment by TobiGr** [comment]
Thanks for you work. We are using [Weblate](https://hosted.weblate.org/projects/newpipe/#languages) for translations. As you can see Stringlate added a bunch of unnecessary lines. Weblate also allows good reviews and discussions on the translation. You can use Weblate with your GitHub acconunt.

**Comment by squeezer11** [comment]
The German Translations has been improved now. there were several translations before, that made completely another sense in your app. i am supporting your app. i will send you  soon some improvement proposals for the newpipe app. maybe its interesting for you.

cheers

**Comment by theScrabi** [comment]
Why did you reopen the issue?

**Pull request closed without merging**
