### PR TITLE
Dynamically get package name

### PR DESCRIPTION
**Pull request by B0pol**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- remove usage of harcoded package name `org.schabi.newpipe`
- it fixes issues with forks or debug builds, e.g. when you open two newpipe apps (with debug or fork apps), close one notification, it closes all newpipe notifications

#### Fixes the following issue(s)

- fixes https://github.com/TeamNewPipe/NewPipe/issues/4653
- https://github.com/TeamNewPipe/NewPipe/issues/4653#issuecomment-717509756
- When you pause a video, it resumes on the other newpipe instance
- https://github.com/polymorphicshade/NewPipe/issues/18
- other related bugs

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TobiGr** [comment]
There are two more references in SubscriptionsImportService. However, I am not sure if we should change that.
``` bash
tobias@tobias-mint-3:~/Dokumente/NewPipe/NewPipe/app/src/main/java$ grep -irn '"org.schabi.newpipe'
org/schabi/newpipe/local/subscription/services/SubscriptionsImportService.java:69:    public static final String IMPORT_COMPLETE_ACTION = "org.schabi.newpipe.local.subscription"
org/schabi/newpipe/local/subscription/services/SubscriptionsExportService.java:53:    public static final String EXPORT_COMPLETE_ACTION = "org.schabi.newpipe.local.subscription"
org/schabi/newpipe/local/feed/service/FeedLoadService.kt:70:        private const val ACTION_CANCEL = "org.schabi.newpipe.local.feed.service.FeedLoadService.CANCEL"
org/schabi/newpipe/player/MainPlayer.java:67:            = "org.schabi.newpipe.player.MainPlayer.CLOSE";
org/schabi/newpipe/player/MainPlayer.java:69:            = "org.schabi.newpipe.player.MainPlayer.PLAY_PAUSE";
org/schabi/newpipe/player/MainPlayer.java:71:            = "org.schabi.newpipe.player.MainPlayer.OPEN_CONTROLS";
org/schabi/newpipe/player/MainPlayer.java:73:            = "org.schabi.newpipe.player.MainPlayer.REPEAT";
org/schabi/newpipe/player/MainPlayer.java:75:            = "org.schabi.newpipe.player.MainPlayer.ACTION_PLAY_NEXT";
org/schabi/newpipe/player/MainPlayer.java:77:            = "org.schabi.newpipe.player.MainPlayer.ACTION_PLAY_PREVIOUS";
org/schabi/newpipe/player/MainPlayer.java:79:            = "org.schabi.newpipe.player.MainPlayer.ACTION_FAST_REWIND";
org/schabi/newpipe/player/MainPlayer.java:81:            = "org.schabi.newpipe.player.MainPlayer.ACTION_FAST_FORWARD";
org/schabi/newpipe/player/MainPlayer.java:83:            = "org.schabi.newpipe.player.MainPlayer.ACTION_SHUFFLE";
org/schabi/newpipe/player/MainPlayer.java:85:            = "org.schabi.newpipe.player.MainPlayer.ACTION_RECREATE_NOTIFICATION";
org/schabi/newpipe/fragments/detail/VideoDetailFragment.java:148:            "org.schabi.newpipe.VideoDetailFragment.ACTION_SHOW_MAIN_PLAYER";
org/schabi/newpipe/fragments/detail/VideoDetailFragment.java:150:            "org.schabi.newpipe.VideoDetailFragment.ACTION_HIDE_MAIN_PLAYER";
org/schabi/newpipe/fragments/detail/VideoDetailFragment.java:152:            "org.schabi.newpipe.VideoDetailFragment.ACTION_PLAYER_STARTED";
org/schabi/newpipe/fragments/detail/VideoDetailFragment.java:154:            "org.schabi.newpipe.VideoDetailFragment.ACTION_VIDEO_FRAGMENT_RESUMED";
org/schabi/newpipe/fragments/detail/VideoDetailFragment.java:156:            "org.schabi.newpipe.VideoDetailFragment.ACTION_VIDEO_FRAGMENT_STOPPED";
```
Code looks good to me. I didn't test the changes yet.

**Comment by B0pol** [comment]
fixed in the last commit

**Review by TobiGr — APPROVED** [review]
Code changes look good and everything seems to work fine (tested on Android 4.4, 7, 11)

I'd suggest to wait for @Stypox's review. It is better to double-check this PR.

**Review by Stypox — APPROVED** [review]

**Comment by opusforlife2** [comment]
Yay!

**Pull request merged**
