### PR TITLE
Migrate to AndroidX

### PR DESCRIPTION
**Pull request by Redirion**
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

ExoPlayer 2.10. moved forward to use AndroidX. NewPipe should keep up for easy integration of the new ExoPlayer version and possible other benefits.

I have converted the project by using Android Studio 3.4.1 "Refactor -> Migrate to AndroidX" and made small adjustments afterwards to the build.gradle in the app module. Furthermore I have removed the FlingBehavior.java as the original path that was overwritten with it doesn't exist in AndroidX. The original git project that was referenced in it, also removed the file recently in this commit: https://github.com/ToDou/appbarlayout-spring-behavior/commit/5575b3a33dc7e8d81590227823acb556b1c8c7f6
@yausername could you please check whether the custom FlingBehavior.java is still needed? You have added it initially with this commit: https://github.com/TeamNewPipe/NewPipe/commit/9fc38b5bb8a8fddb085a97220f7332c9df15ee21

### CODE REVIEW

**Comment by Redirion** [comment]
hm.. okay Travis fails, but I could build, install and run the apk on my device without problems. Will have to look into that later.

**Comment by Redirion** [comment]
Closing, as I am obviously unable to make this happen. Also the Flingbehavior.java seems to be required.

**Comment by yausername** [comment]
I was facing some scrolling issues/lag with the default, hence I added FlingBehavior.java. Not easily reproducible but happens often enough to be annoying. I was able to reproduce the same issue in the official twitter app also.

 issue_gif

Not sure if this is still an issue with AndroidX. I will check when I get time.

Default behavior
```
app:layout_behavior="@string/appbar_scrolling_view_behavior"
```

**Comment by Redirion** [comment]
I have no idea how to fix the build with Travis CI :(

**Comment by TobiGr** [comment]
@Redirion I can take a look at Travis later this week.

**Comment by TobiGr** [comment]
Let's try to fix it.

**Comment by TobiGr** [comment]
Strange. I restarted the travis build for your last commit and got a couple of `Duplicate class android.support.v4.XXX found in modules classes.jar (androidx.XX:1.0.X) and classes.jar (com.android.support:X:X.X.X)`. After reopening, the build for your commit was successful. Nevertheless. I think, we should keep the gradle.propperties file with its entries to keep close to the official migration guidelines.

**Comment by Redirion** [comment]
so it just failed, because gradle.properties were in git.ignore? that explains why it didn't fail on my local copy. Thanks!

**Comment by TobiGr** [comment]
Yes, that was the problem. It was removed and ignored because it only contained commented out defaults. See https://github.com/TeamNewPipe/NewPipe/commit/966ac0673c07c3fa6ef178f9f63f085890d8ac01 for more details. I think it shouldn't be a problem to re-add it. Everyone who stores local settings in that file, can move it to `local.properties`

**Comment by Redirion** [comment]
can anyone explain me, why my branch says "This branch is 24 commits ahead, 126 commits behind TeamNewPipe:dev." even though I did a rebase?

I did the following:
git remote add upstream https://github.com/TeamNewPipe/NewPipe.git
git fetch upstream
git rebase dev
git pull
git push -u origin androidx

It is compelling to just click on "Update branch" as github suggests, but as far as I remember, this isn't the suggested approach by NewPipe maintainers.

**Comment by Redirion** [comment]
can anyone help me with resolving the conflicts? I am no expert with command line git. I don't know why it isn't working.

I am trying a rebase to dev. It shows the conflicting files, tells me to fix them manually and use git add "conflicting_files" afterwards, which I did. But when I then try to perform git rebase --continue it just tells me "no changes", did you forget to use 'git add'?  git status then shows "nothing to comit" and the only option I have left is to git rebase --abort

**Comment by TobiGr** [comment]
I can take a look at it next weekend.

**Comment by Redirion** [comment]
I understand that you are very busy, could you maybe add a flag "help needed" to notify other contributors? Maybe the can provide help by pointing out my mistake or giving me some guidance.
Thanks.

**Comment by Redirion** [comment]
I will re do this PR as I obviously messed everything up here

**Pull request closed without merging**
