### PR TITLE
[Update check] Add cool down on server-side problems

### PR DESCRIPTION
**Pull request by TobiGr**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
Reduce load on API when checking for new version. When the last request failed, there is no cool down stored, so the app will make a new request once the app is restarted.
Add a cooldown of one hour before a new request is made

Follow up to #5474 

#### APK testing 

On the website the APK can be found by going to the "Checks" tab below the title and then on "artifacts" on the right.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by XiangRongLin — COMMENTED** [review]
Are all 4xx 5xx status codes evaluated as error and go into the error block?

**Comment by litetex** [comment]
Is this PR still a thing?
There have been massive changes to the Updatecheck in #6980

**Comment by opusforlife2** [comment]
@TobiGr ^

**Comment by litetex** [comment]
Converted to draft due to no activity and merge problems.

**Pull request closed without merging**
