### PR TITLE
Optimize UI

### LINKED ISSUE #11434: Inadequate accessibility of the app layouts and improper contrast between various views.
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

The app should have better contrast between titles and description, and layout should have better spacing around it.

### Why do you want this feature?

To improve accessibility and ease of use, currently it poses various issues over what is emphasized to what degree in the app like titles should be emphasized (bold) and channel names and other info should be de-emphasized (have lower/lighter font tones). It's making it visually difficult to use the app.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Hamza417**
#### What is it?
- [x] Bug fix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
Optimize the existing layout and how they work in the app with various accessibility improvements.

#### Before/After Screenshots/Screen Record

The list is optimized, the titles have better visibility and channel names have been italicized.

The grid list were incorrectly laid out in the app, the icons weren't evenly placed and have weird spacing, the same could be fixed easily by removing the fixed width and height constants and applying aspect ratio based resizing for the thumbnails. The rest of the changes were the same as list view.

The title has been emphasized, and comment usernames have better visibility now. The emphasis from the "X REPLIES" have been reduced to lower case so that it can be a little less loud.

#### Fixes the following issue(s)

- Fixes #11434

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR. You can find more info and a video demonstration [on this wiki page](https://github.com/TeamNewPipe/NewPipe/wiki/Download-APK-for-PR).

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Hamza417** [comment]
> @Hamza417 : could you check if it is optimized correctly on tablets too? I noticed that there are some problems on tablets. you could also take a look at the stories. #6869

Thanks for pointing out the exact issue, I'll see if these changes can be included as well before this PR gets merged.

**Review by acrodemocide — APPROVED** [review]
Code changes look good. I pulled down the APK and tested on my phone. I really love the new UI updates. Everything else on the APK appears to be working as expected.

**Comment by Stypox** [comment]
I built an APK if you want to test: [app-debug.zip](https://github.com/user-attachments/files/17804308/app-debug.zip)

**Comment by Stypox** [comment]
Hello and thank you for your design proposal @Hamza417. We have discussed with the team the new design and decided to reject it unfortunately, for these reasons:
- NewPipe is currently undergoing a refactor, and we are therefore limiting PRs to only bugfix or maintenance PRs
- During the refactor the UI is going to be redesigned anyway, see for example #11060 (in particular the "After (improved design)" screenshots)
- It is difficult to reach consensus on how exactly the UI should look like, and merging a PR like this one without consulting a designer and making a poll for users, might be controversial
- I see in the APK that various items have not been redesigned (e.g. playlists), but if we want to change things we need to first agree on some rules to apply everywhere in the app (e.g. all titles should be bold, ...)

**Pull request closed without merging**
