### PR TITLE
Feed group main-page tab

### LINKED ISSUE #3319: Allow adding custom feeds as tabs
#### Is your feature request related to a problem? Please describe it
The What's New tab is a feed of all your subscribed channels. Currently, you have to go to the subscriptions tab and tap on a channel group to see its feed.

#### Describe the solution you'd like
Just like you have the ability to add a kiosk as a tab from a list of available ones, you should have the ability to add your custom feeds as tabs.

Coincidentally, this would make Newpipe similar to the Slide for Reddit app in how subreddits are browsed. (Though that's not where I got the idea. The similarity struck me just as I was writing this.)

#### How will you/everyone benefit from this feature?
Easier access to dedicated feeds. The default feed you see when you open Newpipe can be a custom one.

### PR DESCRIPTION
**Pull request by Royosef**
#### What is it?
- [ ] Bug fix (user facing)
- [x] Feature (user facing)
- [ ] Code base improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

feat(group-feed-tab)

* add group feed as tab in the main page (by Settings > Content > Content of main page)

image

image

image

image

#### Fixes the following issue(s)

- fixes #3319 

#### Testing apk

[NewPipe_FeedGroupTab-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4603349/NewPipe_FeedGroupTab-debug.zip)

#### Agreement
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by opusforlife2** [comment]
Hallelujah!

**Comment by opusforlife2** [comment]
Suggestion: Add a button to "Add tab to Main Page" in the Feed creation dialogue. So that you can create the feed and add it as a tab right away. It would be handy to have, even though it would appear at the end of the list of tabs. One could always change positions later.

**Comment by opusforlife2** [comment]
Swiping between these Feed tabs is very jerky. Not sure if that's a bug or just a consequence of heavy loading.

Create 2 or 3 tabs and swipe through them all. Better yet, group all the feed tabs together. The behavior is very noticeable.

**Comment by khimaros** [comment]
are there any changes required to this PR before it can be merged?

**Comment by opusforlife2** [comment]
@Royosef Do you have time to finish this PR?

**Comment by Royosef** [comment]
Sorry, but I got no time for that 😕

**Comment by litetex** [comment]
Closing this for now:
* No progress
* no GitHub actions build
* merge conflicts

Feel free to reopen it when there is progress again.

**Comment by Coderdude112** [comment]
Any update on this PR?

**Pull request closed without merging**
