### PR TITLE
Update some AndroidX libraries

### PR DESCRIPTION
**Pull request by TacoTheDank**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

Taking out the lesser bumps here. As always, be sure to read the changelogs (including the beta releases leading up to it).

I added size change differences for release APK builds.

- Update AndroidX LocalBroadcastManager 1.0.0 -> 1.1.0 ([changelog](https://developer.android.com/jetpack/androidx/releases/localbroadcastmanager#1.1.0)) (this should eventually be replaced as it is a formal deprecation, but there's no harm in updating it right now) (no size change)
- Update AndroidX Media 1.4.3 -> 1.5.0 ([changelog](https://developer.android.com/jetpack/androidx/releases/media#media-1.5.0)) (drops 4 KB)
- Update AndroidX Preference 1.1.1 -> 1.2.0 ([changelog](https://developer.android.com/jetpack/androidx/releases/preference#1.2.0)) (adds 25 KB)
- Update Google Material 1.4.0 -> 1.5.0 ([changelog](https://github.com/material-components/material-components-android/releases)) (adds 224 KB (bruh))
  - This includes an AndroidX DrawerLayout bump from 1.0.0 -> 1.1.1 ([changelog](https://developer.android.com/jetpack/androidx/releases/drawerlayout))

#### APK testing 
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Stypox** [comment]
> Update Google Material 1.4.0 -> 1.5.0

They seem to have switched to Material 3, maybe that's the reason for the change in size

**Comment by TacoTheDank** [comment]
> Right. Would it be doable to replace it with `LiveData` in NewPipe?

Yes; however, that is something I'd rather have done in a different PR.

> They seem to have switched to Material 3, maybe that's the reason for the change in size

Probably, yeah.

**Comment by TacoTheDank** [comment]
I'm interested in moving this PR forward so I can start working on the other AndroidX updates as well as the MaterialComponents migration. I've already started somewhat, but I'd like for the MaterialComponents library to be at 1.5.0 in the dev branch so I can rebase my migration-branch on it.

So, any updates?

**Review by litetex — APPROVED** [review]
LGTM

Did a quick (smoke) test and everything works fine.
<sub>Emulator: Android 11 (API: 30) - Pixel 3a</sub>

**Pull request merged**
