### PR TITLE
resizeMode zoom to support 18:9 screens ratio.

### PR DESCRIPTION
**Pull request by SkyzohKey**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

**NOTE:** This applies to ALL devices, I don't know if it's going to have side-effect, this is not tested. 
@see Possible update by using TextureView => https://stackoverflow.com/a/35705070/3855007

### CODE REVIEW

**Comment by theScrabi** [comment]
Awsome. I'll take a look as soon as I find time to :)

**Comment by theScrabi** [comment]
By the way when you are already working on the player UI, could you please also take a look at [this issue here](https://github.com/TeamNewPipe/NewPipe/issues/996).

**Comment by wb9688** [comment]
I wouldn't do it like this, since then users don't have an option to watch it in the original aspect ratio.

**Comment by TobiGr** [comment]
@SkyzohKey Did you try to build and run your changes? I can't do it and [travis either](https://travis-ci.org/TeamNewPipe/NewPipe/builds/330531932#L1574). 

> I wouldn't do it like this, since then users don't have an option to watch it in the original aspect ratio.

@wb9688 Maybe we have to implement a logic which decides whether we can zoom in / skew the video depending on the ratio difference and enable/disable it via a new video setting. And we should take care of other typical ratios (1:1 or phone videos which are handled completely different).

**Comment by wb9688** [comment]
Yeah, and on for example Chrome OS, where you could resize the window of an
Android app iirc. So I'd go for a setting that's disabled by default.

**Comment by theScrabi** [comment]
I'll close it for now.

**Pull request closed without merging**
