### PR TITLE
Update Kotlin.

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [x] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Update Kotlin to 1.4.21 and use the `kotlin-parcelize` plugin.

#### APK testing 

[debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5825377/debug.zip)

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by XiangRongLin** [comment]
I have had a bad experience at work updating kotlin to 1.4.20 without unit tests covering all kotlin files.

It just silently broke a feature until i realized that it was broken some weeks later. Reason was that some usages of a generic higher order method were changed to return null instead of the nullable T?

Since there currently is no pressing need for it, i would postpone it, to avoid large manual testing.

**Comment by Redirion** [comment]
@Isira-Seneviratne do you have any literature recommendations to get into Kotlin?

**Comment by Isira-Seneviratne** [comment]
> @Isira-Seneviratne do you have any literature recommendations to get into Kotlin?

I use the [online documentation](https://kotlinlang.org/docs/reference/) (it's also available as a [PDF](https://kotlinlang.org/docs/kotlin-reference.pdf).)

JetBrains also provides an [interactive tutorial](https://kotlinlang.org/docs/tutorials/koans.html).

**Comment by Isira-Seneviratne** [comment]
Kotlin has been updated to 1.5.0, so I'll close this and create a new PR.

**Pull request closed without merging**
