### PR TITLE
Scale gestures to change aspect ratio

### LINKED ISSUE #1757: [Feature Request] Pitch to zoom in 18:9
Hi,
Is it possible to add a gesture to pitch to zoom in 18:9 like Youtube ?
Thanks !

### PR DESCRIPTION
**Pull request by MaX-Lo**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

closes #1757 

**Summary**
This pull request adds scale gesture detection inside the video player. A zoom-in-gesture sets the aspect ratio to `RESIZE_MODE_ZOOM` and a zoom-out-gesture to `RESIZE_MODE_FIT`. (such as in the Netflix app as well)

**Description**
I had to refactor the `PlayerGestureDetector` a little bit. When before the root view had `PlayerGestureDetector` registered as its onTouchListener directly, now `PlayerOnTouchListener` is registered as its onTouchListener. 
In `PlayerOnTouchListener` it gets checked if a scale gesture was detected, which is then handled by `PlayerScaleGestureDetector`. Wasn't that the case the event will be handled by  `PlayerGestureDetector` just as before.
For setting and storing the resize mode I used parts of #1748, since it's approved and was just not merged yet, when I created this pull request.  Hope that's not a problem.

**Testing**
Disabling gestures disables the zoom gesture as well. For all situations I could come up with, it worked well and didn't interfere with existing gestures for volume and brightness control.

### CODE REVIEW

**Comment by theScrabi** [comment]
Code is ok so far, could someone please QA these changes.

**Comment by MaX-Lo** [comment]
[Update] Added support for individual on/off setting of the scale gesture, introduced with #1644

**Comment by haistakaavittukaikkisaatana** [comment]
When I tried to use Zoom and Fill it doesnt fill up the entire screen on my Note 10+, it should fill up to the notch area too.

Can you please fix it? Note 10+ has 19:9 aspect screen.

**Comment by haistakaavittukaikkisaatana** [comment]
@thescrabi

Are you gonna fix this issue on the Note10+?

**Comment by PeterHindes** [comment]
> @theScrabi
> 
> Are you gonna fix this issue on the Note10+?

Does it work with regular zoom mode? This might not be related to the gesture.

**Comment by bellegarde-c** [comment]
Any news on this, it's really needee on devices like Oneplus 7 pro

**Comment by bellegarde-c** [comment]
Ok, just found it already exists without gestures

**Comment by PeterHindes** [comment]
Android 11 is implementing resizing for picture in picture. We might want to look at using picture in picture for the Android 11 release. having an option between overly and picture and picture would be pretty cool.

**Comment by Stypox** [comment]
Unfortunately this has gotten too old and would have to be re-done again, after player and gestures files were changed completely. So I'm closing this, sorry for not merging it in time

**Pull request closed without merging**
