### PR TITLE
Hold player controls to keep them shown and other player annoyances

### LINKED ISSUE #3842: Stop players from fading buttons and info, as long as the player is still being pressed.
#### Describe the feature you want

I think it would be nice if you add a feature which enables the user to keep player buttons and video information active (display), as long as the screen is still being pressed.

#### Is your feature request related to a problem? Please describe it

This is especially useful when a video has a long title. Because it's long, reading the whole title takes more time than available information is allowed to be active (display fade out).

#### Additional context

I'm talking about that UI thingy, which is displayed whenever you touch the player to see title, playlist, etc.

It may get fade out, before one can read the whole video title.

#### How will you/everyone benefit from this feature?

This is a feature available in any other video service I have ever seen: including YouTube app.

Maybe this is not even a feature, but a bug fix.

#### What are you NOT talking about?

About tapping the screen.
It's about pressing it once and holding indefinitely.

### PR DESCRIPTION
**Pull request by Stypox**
#### What is it?
- [x] Bug fix (user facing)
- [x] Feature (user facing)
- [ ] Code base improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
With this PR the player controls are never hidden while the user is touching the screen (e.g. while holding a finger on the touch screen or while making gestures). This enables long titles to be read even if the marquee would be too slow to read in the small amount of time granted by `showControlsThenHide()`. This PR also fixes controls hiding after hiding and reshowing them on a paused video: the problem was the single tap function did not respect "if paused never hide automatically".
This PR also fixes:
- controls not hiding after replaying
- icons layered on top of each other while  changing brightness or volume

If this will be merged after Unified UI, I'd be ok with rebasing or reimplementing.

#### Fixes the following issue(s)

- closes #3842

#### Testing apk
@hunkjazz @MD77MD could you test this thoroughly to confirm I didn't introduce nasty issues?
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4875473/app-debug.zip)

#### Agreement
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by hunkjazz** [comment]
@Stypox 

From what I have tested, I noticed this:

- [x] PR implements request #3842;
- [x] One minor bug caused by your PR (probably);
- [x] Two minor bugs **not caused** by your PR (worth mentioning).

#### minor bug 

It's nothing bad, but still something.
Also: possibly a feature, instead. _idk!_

1. Tap player;
2. Long press screen (don't move you finger, for a little while);
3. Now, move your finger in an attempt to make a gesture for activating brightness or volume controls;
4. Neither brightness or volume controls are triggered.

#### worth mentioning: minor bug 1

This one is just annoying.

1. Play a single video on main player;
2. When it finishes reproducing, tap replay button;
3. Avoid tapping or pressing the screen, at all;
4. Player controls fails to hide automatically, ever.

#### worth mentioning: minor bug 2

Only causes uglyness.

1. Tap player;
2. Make a gesture to activate brightness or volume controls;
3. Player controls fails to hide automatically, while brightness/volume icons are being displayed;
4. Icons are layered on top of each other, causing uglyness.

#### when I say...

**tap**: I mean to touch and move the finger away from the screen (like a mouse click).
**press**: Touch and hold finger indefinitely.

**Comment by Stypox** [comment]
> Also: possibly a feature, instead. idk!

I would consider this a feature. I would not like gestures kicking in after I have long-pressed the screen for a while: if I wanted to activate a gesture I would have moved the finger right away. Also, there is no way to achieve this unless with low-level touch event handling, since I guess Material Guidelines do not advise to make two gesture actions out of just one touch event). So I won't fix this.

> Player controls fails to hide automatically, ever.
>
> Icons are layered on top of each other, causing uglyness.

Fixed and fixed, please check that everything is good ;-)
Test apk: [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4886699/app-debug.zip)

**Comment by hunkjazz** [comment]
@Stypox 

Everything works, on my phone

- [x] player controls kept shown on long press;
- [x] replaying a video hides player controls, after a little while;
- [x] there's no icon layered, anymore.

Thanks for your time and effort.
Sorry for not being able to help!

**Comment by MD77MD** [comment]
ok so I tread the latest fix and this is what I found:
1. whenever brightness or volume gestures are used, player controls would show up after regardless if they were showing before or not. 

2. While player controls are showing, using double tap to seek would hold player controls hostage until you stop double taping. this makes seeking harder because player controls are abstracting the video.

My suggestion is that using any gestures would cause the player controls to immediately disappear regardless and not show unless the screen was taped again.

**Comment by Stypox** [comment]
> whenever brightness or volume gestures are used, player controls would show up after regardless if they were showing before or not

I explicitely paid attention in order not to break this, but it happened anyway ;-) 
Now fixed

> While player controls are showing, using double tap to seek would hold player controls hostage until you stop double taping. this makes seeking harder because player controls are abstracting the video. perhaps a "seek duration counter" could be shown instead smile.

If I understood correctly (i.e. that after double tap controls never hide) then fixed

----

Test apk: [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4902026/app-debug.zip)

**Comment by opusforlife2** [comment]
When you tap to show player controls, then change volume or brightness, 2 things can happen:
- if your gesture is short enough, the controls stay hidden.
- if it is long enough, the controls show up again.

I _like_ this new behavior, personally. The fluidity of the animation is pleasing, even though it's ultimately unnecessary. It is just inconsistent, which is the problem. I would prefer bullet two, although bullet one is probably the intended behavior and hence bug fix.

**Comment by Stypox** [comment]
No, bullet 2 is the intended behaviour, but with short gestures the show animation is started before the hide one finished animating, resulting in the show animation being ignored

**Comment by MD77MD** [comment]
there is one more thing. it has to do with the "double tap to pause gesture"... I think it's not suppose to be tied to the state of player controls, 
the same as "double tap to seek". what I'm trying to say is using "double tap to pause" should not trigger player controls to show up.

suggested behavior:
>player controls not showing=>double tap to pause=>player controls keep not showing up=>action pause  was interested for=>double tap to play

This unifies the double tap to seek/pause gestures behavior related to player controls showing.. it also gives a cleaner UI feeling whenever a quick pause and play action is needed such as reading a table or a chart, comparing two pics or even taking a screenshot because it keeps the controls out of the way

**Comment by Stypox** [comment]
I will finish this work after #2907 (which probably implies I have to do everything from the beginning)

**Comment by Stypox** [comment]
Closing this as @avently has already fixed many of these issues, this can be reconsidered in the future

**Comment by MD77MD** [comment]
man why dumb it on avently, he has enough already... you've done most of the work .. so why give at the last step.. beside issues we fixed here are still in the unified player latest debug.. maybe rebasing is all it needs.. anyway Im here to help with whatever you need

**Comment by Stypox** [comment]
@MD77MD I'm going to do this, but this pr is useless, as all of the code changed

**Comment by MD77MD** [comment]
thanks 👍

**Pull request closed without merging**
