### PR TITLE
Update Android Studio and Kotlin

### PR DESCRIPTION
**Pull request by TacoTheDank**
#### What is it?
- [ ] Bug fix (user facing)
- [ ] Feature (user facing)
- [x] Code base improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
- Update Android Studio 3.6.3 -> 4.0.1
- Update Kotlin 1.3.72 -> 1.4.10
- Update gradle wrapper to 6.1.1 using git bash
- Add a gradle wrapper validation action (see [this](https://github.com/marketplace/actions/gradle-wrapper-validation))

#### Testing apk
No testing needed.

#### Agreement
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by opusforlife2** [comment]
> gradle/wrapper/gradle-wrapper.jar

> Binary file not shown.

So. Is this a social engineering attack or not? Your link tells us to be cautious. :P

**Comment by wb9688** [comment]
I don't see any reason to upgrade the Gradle Wrapper (and if there was one, I'd prefer doing it myself), plus I don't think it makes sense to include a GitHub action for this while still doing the rest on Travis CI.

**Comment by opusforlife2** [comment]
:O

**Comment by wb9688** [comment]
To be clear: upgrading Gradle, AGP, and Kotlin are OK, at least, if F-Droid supports it, but the rest is not

**Comment by TacoTheDank** [comment]
@wb9688 Android Studio 4.x requires Gradle 6.1.1 or up, so it's forced to update.

**Pull request closed without merging**
