### PR TITLE
Grid layout fit width

### LINKED ISSUE #2181: deleted
deleted

### PR DESCRIPTION
**Pull request by nv95**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

Fix #2181

### CODE REVIEW

**Comment by TobiGr** [comment]
This looks way better, is cleaner and more understandable :+1: 
I'll test this during the week on different devices. I guess this implementation should not have any weird side effects :)

**Comment by Beapal** [comment]
That's super fast!

**Comment by TobiGr** [comment]
As I said, code looks good. But for some reason, scrolling is not smooth on my Android 5 tablet any more. Can someone confirm this?

**Comment by nv95** [comment]
Ok, using ConstraintLayout is not recommended with RecyclerView due to bad performance

**Pull request closed without merging**
