### PR TITLE
Draft: Decrease JVM memory to fix build

### LINKED ISSUE #6333: JVM Error on trying to build
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. \
https://github.com/TeamNewPipe/NewPipe/issues?q=is:issue+error+on+build
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

``` ./gradlew assembleDebug```
Refer https://developer.android.com/studio/build/building-cmdline#DebugMode

### Actual behaviour

```
Unable to start the daemon process.
-----------------------
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
```

### Screenshots/Screen recordings

image

### Logs

<details><summary><b>Command log </b></summary><p>

```
PS D:\5_Setups\17_src\NewPipe-patch-2>  ./gradlew assembleDebug
Starting a Gradle Daemon, 8 incompatible and 1 stopped Daemons could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/6.8.3/userguide/gradle_daemon.html
Process command line: C:\Program Files (x86)\Java\jre1.8.0_211\bin\java.exe -Xmx2048M -Dfile.encoding=windows-1252 -Duser.country=US -Duser.language=en -Duser.variant -cp C:\Users\Yash Pal Goyal\.gradle\wrapper\dists\gradle-6.8.3-all\6czipnbiesy2sl92ioo8dht91\gradle-6.8.3\lib\gradle-launcher-6.8.3.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 6.8.3
Please read the following process output to find out more:
-----------------------
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```
</details>

### PR DESCRIPTION
**Pull request by yashpalgoyal1304**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
- Decrease JVM memory to fix build since it `Could not reserve enough space for 2097152KB object heap` 
    - My interpretation: my system is not allowing it to occupy that much space - in the memory/RAM as i am told. My system has 8GiB RAM of which 3 remains occupied even when idle. \
    - This hypothesis fits well as the issue persists on increasing to 3g, turns fatal on 4g, and is resolved on decreasing the space requirement to 1g 
    - I tried various values, and initially it was showing this error on around 1500M too (tried 2-4X), but now it's working. But idk why it was increased (https://github.com/TeamNewPipe/NewPipe/commit/52895e7b6bfad3dac71a4a72c4e426b1304568f6) so, dk minimum value required. So, kept 1500M as roughly a functional middle-ground value. 
      - [ ] The reviewers please decide if the value can be further optimised.
- Read the first comment

#### Fixes the following issue(s)

- Fixes #6333 

#### APK testing 

On the website the APK can be found by going to the "Checks" tab below the title and then on "artifacts" on the right.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by yashpalgoyal1304** [comment]
Reserving

**Comment by Redirion** [comment]
I see that this was initially just added to fix release builds. I tried removing this line completely and could build a debug apk just fine. Did you also try that? I think @TobiGr should consider adding this line to jist local.properties instead ;)

**Comment by TobiGr** [comment]
> I think @TobiGr should consider adding this line to his local.properties instead

No. The release builds needs more memory, because it contains some optimizations which require much ram. The F-Droid builds as well as my local release builds failed with the default 1024MB. Every change in this PR needs to be checked against release builds, too.

**Comment by yashpalgoyal1304** [comment]
i got same error while trying to build for floriskeyboard, like newpipe, it has that set to `2G` too.

And for both these, even after setting to 1G, i faced the same issue for floris as i faced with newpipe: [SDK location not found](https://duckduckgo.com/?q=sdk.dir+path&t=vivaldi&ia=web)

so, i guess the problem might be something else/too. But seems t'll be worth documenting when found out about.

**Pull request closed without merging**
