### PR TITLE
optimized ic_subscriptions

### PR DESCRIPTION
**Pull request by RiedleroD**
TODO: check if either of the latter two commits broke anything, some bad SVG implementations don't like short arc flags and sometimes even arcs in general.

#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [x] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
- replace L instructions with appropriate V or H if possible
- change ordering of shapes to make relative instructions more efficient
- reorder instructions to make more closing lines redundant
- remove redundant closing lines (the z instruction already closes the shape with a straight line)
- replace curves with equivalent arcs
- shorten arc instructions

#### APK testing
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by RiedleroD** [comment]
yup, android doesn't like short arc flags it seems. reverting the commit in a bit

**Comment by RiedleroD** [comment]
looks like it works now. It's a bloody good icon btw, I really like its design. kudos to @marius1501

**Comment by RiedleroD** [comment]
ah, understandable

**Comment by Stypox** [comment]
I just noticed I probably sent you the wrong link. This is the correct one: https://github.com/google/material-design-icons

**Comment by RiedleroD** [comment]
thanks for the correction! I'll definitely upstream the optimisation when I get the time to read their contribution guidelines

**Comment by RiedleroD** [comment]
ah, google is doing the ol' "fake open source software" approach. just dump a bunch of files from prod into a repo and don't accept contributions. Very cool, 10/10 can't complain.

image

sorry for the rant, anyway

**Pull request closed without merging**
