### PR TITLE
[Feature Added] Restart Song From Start

### PR DESCRIPTION
**Pull request by PeterHindes**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

When playing a single background track, the expanded notification now also offers the ability to restart track, rather than only the ability to rewind

With a single song we have the option to restart the track.
Single Song
With A playlist we already have the option.
Single Song

[app-debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/3729381/app-debug.zip)

### CODE REVIEW

**Comment by Stypox** [comment]
Can you please provide a debug APK or some screenshots? Also, please edit make the issue title shorter and rather add something to the description. Thank you for the PR! :-)

**Comment by PeterHindes** [comment]
> Can you please provide a debug APK or some screenshots? Also, please edit make the issue title shorter and rather add something to the description. Thank you for the PR! :-)

Fixed the formatting mistakes, sorry for the lack of screenshots the first time. Silly mistake on my side.

**Comment by Stypox** [comment]
Buttons are too squished toghether on my phone. Could you please make sure buttons never overlap? As you can see in the second image the bounds of the "repeat" button overlap the bounds of the newly-added button.

**Comment by PeterHindes** [comment]
Ok, Ill work on that

**Comment by PeterHindes** [comment]
It looks like the timer on the video also overlaps buttons (including the regular rewind) on exceptionally small screens

**Comment by PeterHindes** [comment]
On screens that are extremely small, the thumbnail should gray out and the notification should take the whole width (displaying over the thumbnail)
## Currently

**Comment by PeterHindes** [comment]
what code can I use to check if the elements are overlaping?

**Comment by Stypox** [comment]
You can probably check whether the X coordinate of the left side of the newly added button is smaller than the X coordinate of the right side of the repeat button.

Also, I don't know if it is ok to hide thumbnail on small screens. @TobiGr what do you think?

**Comment by PeterHindes** [comment]
I was thinking more of a grayed out thumbnail with the text on-top

**Comment by Stypox** [comment]
That's ok, I think

**Comment by wb9688** [comment]
What's up with the 54(!) commits including those of others? Also imho we shouldn't touch notifications until #3178 has been merged.

**Comment by PeterHindes** [comment]
I don't know how those got there lol, this commit is kinda dead tbh, I'm probably gonna close it since no one seems interested in the feature, and it will likely be default behavior with the new notification.

**Comment by PeterHindes** [comment]
I am going to close this issue&pull request as it doesn't make as much sense as I had originally intended, and it is out of date. I better fix might be to have a tap&hold on the rewind button (which shows when only one song is qued) jump to the start of the song instead of a second button.

**Pull request closed without merging**
