### PR TITLE
Hotfix for the latest database migration

### LINKED ISSUE #3303: v0.19.0 crashes as soon I open the app
I was previously using v0.18.5 which was working fine for me, now after updating the app crashes as soon as I open it. I'm unable to even get into the app to backup my data. Please help.

### Version

- v0.19.0

### Steps to reproduce the bug

1. Open app

### Expected behavior
Open the app without it crashing.

### Actual behaviour
The app crashes as soon as I open it.

### Screenshots/Screen records
None.

### Logs
If your bug includes a crash, please head over to the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/). Copy the result. Paste it here:
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ US
* __Service:__ none
* __Version:__ 0.19.0
* __OS:__ Linux samsung/d2qsq/d2q:10/QP1A.190711.020/N975USQU2BTA9:user/release-keys 10 - 29

<details><summary><b>Crash log</b></summary><p>

```
io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | NOT NULL constraint failed: streams_new.uploader (code 1299 SQLITE_CONSTRAINT_NOTNULL[1299])
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
	at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:79)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.checkTerminated(FlowableObserveOn.java:209)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:399)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7770)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
Caused by: android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: streams_new.uploader (code 1299 SQLITE_CONSTRAINT_NOTNULL[1299])
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:1066)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:756)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:66)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:2322)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:2249)
	at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.execSQL(FrameworkSQLiteDatabase.java:242)
	at org.schabi.newpipe.database.Migrations$2.migrate(Migrations.java:84)
	at androidx.room.RoomOpenHelper.onUpgrade(RoomOpenHelper.java:87)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onUpgrade(FrameworkSQLiteOpenHelper.java:124)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:493)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:391)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:92)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:53)
	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:452)
	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:275)
	at androidx.room.RoomDatabase.query(RoomDatabase.java:304)
	at androidx.room.util.DBUtil.query(DBUtil.java:54)
	at org.schabi.newpipe.database.feed.dao.FeedDAO_Impl$10.call(FeedDAO_Impl.java:499)
	at org.schabi.newpipe.database.feed.dao.FeedDAO_Impl$10.call(FeedDAO_Impl.java:496)
	at io.reactivex.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:46)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.onNext(FlowableFlatMapMaybe.java:132)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:407)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:260)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:225)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: streams_new.uploader (code 1299 SQLITE_CONSTRAINT_NOTNULL[1299])
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:1066)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:756)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:66)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:2322)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:2249)
	at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.execSQL(FrameworkSQLiteDatabase.java:242)
	at org.schabi.newpipe.database.Migrations$2.migrate(Migrations.java:84)
	at androidx.room.RoomOpenHelper.onUpgrade(RoomOpenHelper.java:87)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onUpgrade(FrameworkSQLiteOpenHelper.java:124)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:493)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:391)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:92)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:53)
	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:452)
	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:275)
	at androidx.room.RoomDatabase.query(RoomDatabase.java:304)
	at androidx.room.util.DBUtil.query(DBUtil.java:54)
	at org.schabi.newpipe.database.feed.dao.FeedDAO_Impl$10.call(FeedDAO_Impl.java:499)
	at org.schabi.newpipe.database.feed.dao.FeedDAO_Impl$10.call(FeedDAO_Impl.java:496)
	at io.reactivex.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:46)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.onNext(FlowableFlatMapMaybe.java:132)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:407)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:260)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:225)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```
</p></details>
<hr>

### PR DESCRIPTION
**Pull request by mauriciocolli**
#### What is it?
- [x] :fire: fix
- [ ] Feature

#### Long description of the changes in your PR

Fix an oversight in the database migration to version 3.

#### Fixes the following issue(s)
- Fixes #3303

### CODE REVIEW

**Comment by XiangRongLin** [comment]
Are the migrations done in a transaction with rollback on error or could his database be partially migrated?

**Comment by TobiGr** [comment]
@XiangRongLin Good question

**Comment by mauriciocolli** [comment]
>@XiangRongLin: Are the migrations done in a transaction with rollback on error or could his database be partially migrated?

Yes, they are, take a look at the [documentation](https://developer.android.com/reference/androidx/sqlite/db/SupportSQLiteOpenHelper.Callback#onUpgrade(androidx.sqlite.db.SupportSQLiteDatabase,%20int,%20int)).

**Comment by mauriciocolli** [comment]
@wb9688: Yeah, it seems like [SQLite in particular does prefer lowercase](https://www.sqlite.org/lang_corefunc.html).

Now that this is already merged, feel free to fix that in your other PR. And if you do so, please replace the `\"\"` too, single quotes should be used instead.

**Comment by TobiGr** [comment]
@mauriciocolli If you want, I can still fix that for this release

**Comment by TobiGr** [comment]
@mauriciocolli See a5153f53752999aecd19911d270f17a5ef649776

**Comment by mauriciocolli** [comment]
@TobiGr: Feel free to do it.

However, be sure to run the integration tests locally before pushing, they were disabled for whatever reason from running in the CI (I think it was the long test times).

**Comment by EthanZeigler** [comment]
This does not appear to be completely fixed.

```json
{
   "user_action": "ui error",
   "request": "App crash, UI failure",
   "content_language": "US",
   "service": "none",
   "package": "org.schabi.newpipe",
   "version": "0.19.2",
   "os": "Linux Android 10 - 29",
   "time": "2020-04-18 15:17",
   "exceptions": [
      "java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.\n\tat androidx.room.RoomOpenHelper.checkIdentity(RoomOpenHelper.java:139)\n\tat androidx.room.RoomOpenHelper.onOpen(RoomOpenHelper.java:119)\n\tat androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.java:142)\n\tat android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:428)\n\tat android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:317)\n\tat androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:92)\n\tat androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:53)\n\tat androidx.room.RoomDatabase.beginTransaction(RoomDatabase.java:328)\n\tat org.schabi.newpipe.database.playlist.dao.PlaylistStreamDAO_Impl$9.call(PlaylistStreamDAO_Impl.java:409)\n\tat org.schabi.newpipe.database.playlist.dao.PlaylistStreamDAO_Impl$9.call(PlaylistStreamDAO_Impl.java:406)\n\tat io.reactivex.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:46)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4154)\n\tat io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.onNext(FlowableFlatMapMaybe.java:132)\n\tat io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:407)\n\tat io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)\n\tat io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:260)\n\tat io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:225)\n\tat androidx.room.TransactionExecutor$1.run(TransactionExecutor.java:45)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)\n\tat java.lang.Thread.run(Thread.java:919)\n"
   ],
   "user_comment": ""
}
```

**Pull request merged**
