### PR TITLE
[feature request] Forward/backward buttons in background mode

### PR DESCRIPTION
**Pull request by silbopower**
In background mode:
implementation of buttons or gestures that permits to go forward or backward of some seconds, like it's yet developed in standard mode tapping twice on left (-10") or right (+10") screen side
As is implemented in podcasts apps there are 2 main buttons:
+30 seconds
-10 seconds
That should be useful to resume easily some audio content that is lost during the listening.

Another helpful implementation could be a finest scrolling of timeline for long contents, putting time in manual mode or timebar in widescreen when mobile is tilted..

Thanks and btw... AMAZING APP!!

Screenshot_2019-10-11-11-21-22-324_com google android googlequicksearchbox

### CODE REVIEW

**Comment by gkeegan** [comment]
Um shouldn't this be an issue, not a PR?

**Comment by silbopower** [comment]
Well..I don't know, should I move it under ISSUE?

**Comment by gkeegan** [comment]
Yeah. Pull requests are for when you are submitting code or changes to files such as the README.MD file. Issues are for bugs, feature requests, discussion, etc. 

Btw, I really like this idea for the background player :)

**Comment by silbopower** [comment]
Thank you gkeegan, I'll move it now! ;)

**Comment by silbopower** [comment]
Moved under ISSUE

**Pull request closed without merging**
