### PR TITLE
Use DisplayCompat.getMode().

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Use [`DisplayCompat.getMode()`](https://developer.android.com/reference/androidx/core/view/DisplayCompat#getMode(android.content.Context,android.view.Display)) to get the current display mode. This method provides workarounds for retrieving the display size for Android TV devices.

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Isira-Seneviratne** [comment]
> Please, provide a "why" to your changes when opening PRs. I have no idea what `DisplayCompat` does and why this change would be an improvement, I only know it increases code size.

Sorry about that, I amended the change description.

**Comment by Stypox** [comment]
Thank you

> This method provides workarounds for retrieving the display size for Android TV devices.

Didn't it already work before, or is there an issue this PR fixes? What is the difference in behaviour?

**Comment by Isira-Seneviratne** [comment]
> Thank you
> 
> > This method provides workarounds for retrieving the display size for Android TV devices.
> 
> Didn't it already work before, or is there an issue this PR fixes? What is the difference in behaviour?

The documentation mentions that some 4K TVs might have trouble running the framework code, so a workaround is provided in the method.

**Comment by Stypox** [comment]
According to the Android docs, [Display.getSize()](https://developer.android.com/reference/android/view/Display#getSize(android.graphics.Point)) does something different than [DisplayCompat.getMode().getPhysicalHeight()](https://developer.android.com/reference/androidx/core/view/DisplayCompat.ModeCompat#getPhysicalHeight())/[display.getMode().getPhysicalHeight()](https://developer.android.com/reference/android/view/Display.Mode#getPhysicalHeight()). The first one gets the size of the screen used by the app (so removing system parts), while `getPhysicalHeight()` just returns the full screen size.

**Comment by Isira-Seneviratne** [comment]
> According to the Android docs, [Display.getSize()](https://developer.android.com/reference/android/view/Display#getSize(android.graphics.Point)) does something different than [DisplayCompat.getMode().getPhysicalHeight()](https://developer.android.com/reference/androidx/core/view/DisplayCompat.ModeCompat#getPhysicalHeight())/[display.getMode().getPhysicalHeight()](https://developer.android.com/reference/android/view/Display.Mode#getPhysicalHeight()). The first one gets the size of the screen used by the app (so removing system parts), while `getPhysicalHeight()` just returns the full screen size.

You're right, my bad. The backport implementation calls `Display#getRealSize()` on API levels 17-22 and `Display#getSize()` below API 17.

The documentation recommends using `WindowManager#getCurrentWìndowMetrics()` instead of `Display#getSize()`. I'll update this PR.

**Comment by Isira-Seneviratne** [comment]
I created a separate PR for the change I mentioned here: https://github.com/TeamNewPipe/NewPipe/pull/8656

**Pull request closed without merging**
