### PR TITLE
Use PackageInfoCompat.getSignatures().

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Use [`PackageInfoCompat.getSignatures`](https://developer.android.com/reference/androidx/core/content/pm/PackageInfoCompat#getSignatures(android.content.pm.PackageManager,%20java.lang.String)) to get the app signatures.

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TacoTheDank** [comment]
I don't know if bumping the compileSdk from 29 to 30 can be done yet. Developer thoughts?

**Comment by XiangRongLin** [comment]
If it can be done, it should be done seperatly and not packaged together like this

**Comment by TacoTheDank** [comment]
Any updates on this?

**Comment by Isira-Seneviratne** [comment]
Yeah, I moved the compileSdk bump to another PR a while ago.

**Comment by TacoTheDank** [comment]
@Isira-Seneviratne Lol I meant from the team members. This seems good to go, as far as I can tell.

**Review by Redirion — APPROVED** [review]
looks good. Thank you.

**Pull request merged**
