### PR TITLE
Add option to display channel groups as list instead of grid

### PR DESCRIPTION
**Pull request by cern1710**
#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Created a list view for channel groups in the subscriptions page
- Added a toggle button to toggle between the original card view to the newly added one
- Unlike sort, toggle button will exist at all times
- The newly formatted buttons conforms to the same logic as the ones previously. All existing buttons work as intended as they should and will automatically update the ones on the other display format when toggled
- Retains a separate toggle button

#### Before/After Screenshots/Screen Record
<table>
  <tr>
    <td></td>
    <td></td>
  </tr>
</table>

#### Fixes the Following issue: 
- Fixes: [https://github.com/TeamNewPipe/NewPipe/issues/8605](https://github.com/TeamNewPipe/NewPipe/issues/8605)
#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [X] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Stypox** [comment]
Why did you create two PRs? Which one should be merged, this one or #9204? Once you create a PR you can easily just push more commits to it, there is no need to create a new PR each time we ask you to make changes

**Comment by cernunnos1710** [comment]
@Stypox this one,. sorry for the confusion.

**Review by Stypox — CHANGES_REQUESTED** [review]
I pushed a commit that fixes a couple of implementation and logic issues. Some of the code not written by you (but that was there before this PR) had some problems that needed to be solved for this PR to work well. I also changed some of your code after some things around it changed: an important change is that I moved the list view state handling to the view model (which is the usual thing to do in Android). Take a look at the code in the commit for more information.

Please revert the changes to `5.json` and `FeedGroupEntity.kt`. I don't know where those came from. Then I can re-review the code and this can be merged. Thank you for this neat and needed feature!

Here is a testing APK: [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/9873868/app-debug.zip)

**Comment by opusforlife2** [comment]
While we're at it, I think the New button should be at the top.

**Review by Stypox — APPROVED** [review]
@opusforlife2 done. I'm merging this if no issues arise in this APK (please test!): [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/9879157/app-debug.zip)

**Comment by cern1710** [comment]
@Stypox Hi, I just ran through the APK and found a bug where the subscribers list would go slide from its original position to the bottom everytime someone exists after clicking something else.

**Comment by Stypox** [comment]
If you want to try to fix it go ahead, otherwise I will probably take care of it later or in the following days

**Comment by opusforlife2** [comment]
Looks great! One last thing: can the tap area of the layout change button be increased? I'm seeing some hits and misses trying to tap it. It's close enough to the edge of the screen that my phone cover is interfering somewhat.

**Comment by Stypox** [comment]
@opusforlife2 done

> Hi, I just ran through the APK and found an issue where the subscribers list would slide from its original position to the bottom everytime someone goes to another page and goes back to subscribers.

@cern1710 btw, I could not reproduce. Could you provide more precise reproduction instruction, or a video?

**Comment by opusforlife2** [comment]
> done

Perfect! The button can be easily tapped now.

**Comment by cern1710** [comment]
> @opusforlife2 done
> 
> > Hi, I just ran through the APK and found an issue where the subscribers list would slide from its original position to the bottom everytime someone goes to another page and goes back to subscribers.
> 
> @cern1710 btw, I could not reproduce. Could you provide more precise reproduction instruction, or a video?

1. Add a few channel groups.
2. Click on one of them.
3. Press the back button.

The subscription page (along with its channels) will fall down from the top, which has probably something to do with the animations? Perhaps this can be solved by another PR

**Comment by opusforlife2** [comment]
Oh. I got it. The exact same thing happens when you toggle from list layout to grid. The Subscriptions section moves down in a slow animation, which makes it overlay other stuff for a noticeable duration.

**Comment by cern1710** [comment]
@opusforlife2 @Stypox How about removing the animations?

**Review by Stypox — APPROVED** [review]
I tried to mess around with the animations, but I could not find a way to make everything work correctly. So yeah, let's stick with this implementation. Thanks!

**Pull request merged**
