### PR TITLE
name the regions according to the comments

### PR DESCRIPTION
**Pull request by evermind-zz**
this pull request replaces #6512

if a region is named android studio will show its name in the structure view.

#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- increase readabilty in android studio structure view

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by Stypox — APPROVED** [review]
Thank you!

**Comment by mhmdanas** [comment]
Are the decorative and large comments above the region comments necessary anymore? They look just like boilerplate to me now.

**Comment by Stypox** [comment]
> Are the decorative and large comments above the region comments necessary anymore? They look just like boilerplate to me now.

I personally use them to navigate, especially in GitHub where there is no folding behaviour (or even on Android Studio when I'm too lazy to press the buttons to fold ;-))

**Comment by mhmdanas** [comment]
If you say so...

**Review by mhmdanas — APPROVED** [review]

**Comment by mhmdanas** [comment]
Thanks!

**Pull request merged**
