### PR TITLE
remove beta

### PR DESCRIPTION
**Pull request by theScrabi**
- remove beta build type
- remove redundant menu items
- remove global IP range label
- make MenuItems in drawer be dynamical generated

### CODE REVIEW

**Comment by ildar** [comment]
Does it mean NP beta will have no more updates?

**Comment by theScrabi** [comment]
yes, everything is back to release again.

**Comment by ildar** [comment]
What about this?
> NewPipe Beta (Lightweight Mediaservices app) -
https://f-droid.org/app/org.schabi.newpipe.beta

Should it be killed?

**Comment by theScrabi** [comment]
I think it will stay for a while to still have the beta versions available, but i think in a month or two I'll remove it.

**Comment by ildar** [comment]
That's a bad idea. Beta is always looked at as a cutting edge.
Maybe move to archive?

> --
Ildar Mulyukov,
child of God

email: ildar.mulyukov@gmail.com
GoogleTalk: ildar.mulyukov@gmail.com
blog: http://johan-notes.blogspot.com/

**Comment by theScrabi** [comment]
> That's a bad idea.

So you say I should remove it from fdroid ASAP?

**Comment by ildar** [comment]
I don't know the details but shouldn't be hard to move to F-Droid archive
and back and fourth.
The reasons behind this:
1. Beta version older then stable losses the purpose of existence
2. It'll attract people who want the most freshest functionality. By
coincidence they are most desperate criticists 😉

But that's just my advice, nothing more. The main info for me personally
here (about beta version future) I already got, thanks.

**Comment by theScrabi** [comment]
Ok I will see.

**Pull request merged**
