### PR TITLE
Updated lt (Lithuanian) translation

### PR DESCRIPTION
**Pull request by mobtechpd**
Commit made via Stringlate

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by mobtechpd** [comment]
updated lithuanian translation

**Comment by mobtechpd** [comment]
resolved

**Comment by TobiGr** [comment]
Thanks for your translation. As said before in #631 please use [Weblate](https://hosted.weblate.org/projects/newpipe/) for translations. As you can see there are many unnecessary lines of code. Please remove them.

**Comment by TobiGr** [comment]
@mobtechpd Thanks for using Wablate. We can close this now.

**Pull request closed without merging**
