### PR TITLE
Random fixes and improvements

### PR DESCRIPTION
**Pull request by Stypox**
#### What is it?
- [x] Bug fix (user facing)
- [ ] Feature (user facing)
- [ ] Code base improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Fixes the following issue(s)
- ~~Fix invisible play queue item drag button: https://github.com/TeamNewPipe/NewPipe/issues/4332#issuecomment-701379310~~ reverted this, as it is already covered by #4360
- Fix play queue close button always being white regardless of theme.
- Prevent touches behind minimized player: https://github.com/TeamNewPipe/NewPipe/issues/4332#issuecomment-700726544
- Make player close button always white regardless of theme, like all other player controls.
- Make thumbnail in `large-land` minimized player a little bit bigger, since there is plenty of horizontal space.
- Fix `Context.startForegroundService() did not then call Service.startForeground()` crash, happening when the foreground service is started too late on really slow devices. So now I start the foreground service directly in `onCreate()`, instead of waiting for a play queue to arrive to `onStartCommand()` (see [this SO](https://stackoverflow.com/questions/44425584/context-startforegroundservice-did-not-then-call-service-startforeground) and https://github.com/TeamNewPipe/NewPipe/issues/4332#issuecomment-700153308). This shouldn't have any side-effect: I made sure there are no issues with notification initialization if the playback data is still not initialized and there can't be notification leaks since the notification is always deleted in the service's `onDestroy()`. https://github.com/TeamNewPipe/NewPipe/issues/4332#issuecomment-700127786
- Fix video detail controls visibility set inconsistently, see the discussion on IRC and [report on Reddit](https://www.reddit.com/r/NewPipe/comments/j0savf/release_candidates_for_0200/g76glux/?utm_source=reddit&utm_medium=web2x&context=3) 

#### Testing apk
I could not test on API 19 since the player won't open there (probably an issue with codecs, it used to work, I don't know why now it does not anymore), but it should work there, too. 
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5318405/app-debug.zip)

#### Agreement
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by avently** [comment]
So every element in the player is white regardless of the theme but close button will be black in white theme?

**Comment by opusforlife2** [comment]
Wasn't this fixed by #4360?

**Comment by Stypox** [comment]
@avently the play queue background is white in white theme, so then play queue close button should be black in that case. I'm not talking about the player close button, I didn't touch that.

**Comment by avently** [comment]
Oh, wait. Player close button from top left corner uses `?attr` instead of being white always. Could you make it always white?

**Comment by Stypox** [comment]
@avently done. I also fixed another issue pointed out in the 0.20.0 thread: https://github.com/TeamNewPipe/NewPipe/issues/4332#issuecomment-700726544. I updated the PR description accordingly.
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5317924/app-debug.zip)

**Comment by Stypox** [comment]
I now included in this PR a fix for the crash @Redirion was sometimes obtaining: https://github.com/TeamNewPipe/NewPipe/issues/4332#issuecomment-700127786
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5318233/app-debug.zip)

**Comment by Stypox** [comment]
Fix video detail controls visibility set inconsistently, see the discussion on IRC and [report on Reddit](https://www.reddit.com/r/NewPipe/comments/j0savf/release_candidates_for_0200/g76glux/?utm_source=reddit&utm_medium=web2x&context=3) 
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5318405/app-debug.zip)

**Review by TobiGr — APPROVED** [review]

**Comment by avently** [comment]
You said you added notification in oncreate. You check how it works when media buttons starts the player? For example, connect via Bluetooth and press on play. You should play something in NewPipe before this check so android will route media action to newpipe

**Comment by avently** [comment]
Thank you for your work!

**Comment by Stypox** [comment]
> You said you added notification in oncreate. You check how it works when media buttons starts the player? For example, connect via Bluetooth and press on play. You should play something in NewPipe before this check so android will route media action to newpipe

I didn't check this, I'm not sure what you are talking about 😅

**Pull request merged**
