### PR TITLE
Update RxJava to 3.1.5.

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Update RxJava to 3.1.5. Changelog: https://github.com/ReactiveX/RxJava/releases
   This should reduce power consumption on mobile devices: https://github.com/ReactiveX/RxJava/pull/7293

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by opusforlife2** [comment]
With that big a bump, I hope it magically fixes some bugs.

**Comment by Isira-Seneviratne** [comment]
> With that big a bump, I hope it magically fixes some bugs.

The newer version does fix some bugs (though I'm not sure if they apply in NewPipe.) It does make use of functionality only available on API 21+.

**Review by TobiGr — APPROVED** [review]

**Comment by AudricV** [comment]
Shouldn't you update RxAndroid to 3.0.2 as well (maybe in a separate PR)?

**Comment by Isira-Seneviratne** [comment]
> Shouldn't you update RxAndroid to 3.0.2 as well (maybe in a separate PR)?

Sure, but the changes aren't very major, and it seems active development is not happening.

**Review by Stypox — APPROVED** [review]
I tested and it seems to work well. I tested on API 33 and API 22. Thanks!

**Pull request merged**
