### PR TITLE
Feature/autoplay switch button highlight colour

### LINKED ISSUE #3254: Autoplay switch highlight color
The autoplay switch shows up in the same color regardless whether it is on or off. This makes it difficult to tell what's its current state is.

It would be nice to highlight the switch with color when it is turned on.

### PR DESCRIPTION
**Pull request by Bawya1098**
#### What is it?
- [ ] **Bug fix (user facing)**
- [x] **Feature (user facing)**

#### Fixes the following issue(s)
- fixes #3254

#### Description of the changes in your PR
**Autoplay ON**                                   
Screenshot_1597900874

  **Autoplay OFF**
Screenshot_1597900879

Test Apk
[app-debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/5100836/app-debug.apk.zip)

#### Agreement
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by opusforlife2** [comment]
What made you choose green for this? I would have thought that the enabled toggle would be the same colour as the service currently being used. Or, since all the toggles in the app settings are red, the enabled toggle would also be that same red.

**Comment by Bawya1098** [comment]
@opusforlife2, have made toggle as white.

**Comment by opusforlife2** [comment]
Now I'm confused. As I said in the issue, the toggle is already white when enabled. Did you change it to a different white?

Personally, as I said above, I would like the toggle to match the service colour of whichever service is active. If that isn't possible, then it should be the same red as all the toggles in Newpipe's settings.

But the devs and other users may have different opinions on this, so I think you should wait for some others to comment.

**Comment by TobiGr** [comment]
Yes, the toggle should match the service color.

**Comment by Bawya1098** [comment]
@TobiGr @opusforlife2, so toggle color should be red right.

**Comment by opusforlife2** [comment]
@Bawya1098 Red for Youtube, yes. Then orange for SoundCloud, a different orange for Peertube, and, if you want to be proactive, blue for Bandcamp (you can check the PR to see which blue, exactly).

@TobiGr I was about to say grey for MediaCCC, but that's the same colour as the disabled toggle... what to do here?

**Comment by opusforlife2** [comment]
The red coloured toggle for YouTube looks awesome!

**Comment by Bawya1098** [comment]
But how do I change for peertube, SoundCloud 
could you please help?

**Review by Stypox — CHANGES_REQUESTED** [review]
Could you apply the requested changes? Just use `?attr/colorPrimary`, e.g. see this commit: 80cc8a8e025b8c70d314a33adbb9e1f246c06cbe

**Comment by skyGtm** [comment]
This feature has been long overdue. I think the original developer has given up. Someone have to takeover this pull request.

**Comment by Stypox** [comment]
I tried but I couldn't understand how to change the switch colors just by changing XML files

**Comment by TobiGr** [comment]
Closing in favour of #6456

**Pull request closed without merging**
