### PR TITLE
Update ExoPlayer to 2.14.2

### PR DESCRIPTION
**Pull request by Redirion**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [X] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Updates ExoPlayer from 2.12.3 to 2.14.2. [Changelog](https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md#2142-2021-07-20)
- Makes use of the new [MediaParser](https://developer.android.com/reference/android/media/MediaParser) feature that has been added in ExoPlayer 2.14.0 for Android11+
- fixes most deprecations that came with the ExoPlayer update

#### Fixes the following issue(s)

Since ExoPlayer 2.13 codec capabilities are checked by ExoPlayer which lead to issue #6207. This is a topic affecting some LinageOS users with older SOCs. However I hope that when using LineageOS 18.1 the delegation through MediaParser API will fixthis issue. Feedback is appreciated regarding this!

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tsiflimagas** [comment]
This seems to have introduced a couple of issues with audio. Switching to popup player can sometimes lead to no sound or distorted audio. Here's a log i captured [log-newpipe.txt](https://github.com/TeamNewPipe/NewPipe/files/7073403/log-newpipe.txt)

**Comment by Redirion** [comment]
thank you @tsiflimagas I was able to reproduce the issue. I will need more time to investigate this

**Comment by Redirion** [comment]
turns out I was exactly once able to reproduce it. Now tried with logcat running and couldn't reproduce it any more.

**Comment by litetex** [comment]
@Redirion 
This PR probably fixes:
* https://github.com/TeamNewPipe/NewPipe/issues/7262#issuecomment-962496103
* #5843

Can we prioritize it?

**Comment by litetex** [comment]
Smoke tested it on the following devices:
* Pixel 3a (emulated) API 31 - Android 11
* Pixel 3a (emulated) API 30 - Android 10
* Huawei P20 lite API 28 - Android 9
* Samsung Galaxy S3 API 19 - Android 4.4

The following works as expected: 
* Playing a normal video
  * Different speeds work
  * Different qualities work
* Background player
* Popup player

**Comment by litetex** [comment]
@Redirion 

I don't understand the changes inside ``PlaybackResolver`` completely.
You applied some changes to some factories.

However I would change it like his:
```diff
diff --git a/app/src/main/java/org/schabi/newpipe/player/resolver/PlaybackResolver.java b/app/src/main/java/org/schabi/newpipe/player/resolver/PlaybackResolver.java
index 48ee305ee..17dd40500 100644
--- a/app/src/main/java/org/schabi/newpipe/player/resolver/PlaybackResolver.java
+++ b/app/src/main/java/org/schabi/newpipe/player/resolver/PlaybackResolver.java
@@ -9,6 +9,7 @@ import androidx.annotation.Nullable;
 import com.google.android.exoplayer2.C;
 import com.google.android.exoplayer2.MediaItem;
 import com.google.android.exoplayer2.source.MediaSource;
+import com.google.android.exoplayer2.source.MediaSourceFactory;
 import com.google.android.exoplayer2.util.Util;
 
 import org.schabi.newpipe.extractor.stream.StreamInfo;
@@ -42,24 +43,28 @@ public interface PlaybackResolver extends Resolver<StreamInfo, MediaSource> {
                                              @C.ContentType final int type,
                                              @NonNull final MediaSourceTag metadata) {
         final Uri uri = Uri.parse(sourceUrl);
+        final MediaItem mediaItem = new MediaItem.Builder()
+                .setTag(metadata)
+                .setUri(uri)
+                .setLiveTargetOffsetMs(PlayerDataSource.LIVE_STREAM_EDGE_GAP_MILLIS)
+                .build();
+
+        final MediaSourceFactory factory;
         switch (type) {
             case C.TYPE_SS:
-                return dataSource.getLiveSsMediaSourceFactory().setTag(metadata)
-                        .createMediaSource(MediaItem.fromUri(uri));
+                factory = dataSource.getLiveSsMediaSourceFactory();
+                break;
             case C.TYPE_DASH:
-                return dataSource.getLiveDashMediaSourceFactory().setTag(metadata)
-                        .createMediaSource(
-                                new MediaItem.Builder()
-                                        .setUri(uri)
-                                        .setLiveTargetOffsetMs(
-                                                PlayerDataSource.LIVE_STREAM_EDGE_GAP_MILLIS)
-                                        .build());
+                factory = dataSource.getLiveDashMediaSourceFactory();
+                break;
             case C.TYPE_HLS:
-                return dataSource.getLiveHlsMediaSourceFactory().setTag(metadata)
-                        .createMediaSource(MediaItem.fromUri(uri));
+                factory = dataSource.getLiveHlsMediaSourceFactory();
+                break;
             default:
                 throw new IllegalStateException("Unsupported type: " + type);
         }
+
+        return factory.createMediaSource(mediaItem);
     }
 
     @NonNull
@@ -72,25 +77,30 @@ public interface PlaybackResolver extends Resolver<StreamInfo, MediaSource> {
         @C.ContentType final int type = TextUtils.isEmpty(overrideExtension)
                 ? Util.inferContentType(uri) : Util.inferContentType("." + overrideExtension);
 
+        final MediaItem mediaItem = new MediaItem.Builder()
+                .setTag(metadata)
+                .setUri(uri)
+                .setCustomCacheKey(cacheKey)
+                .build();
+
+        final MediaSourceFactory factory;
         switch (type) {
             case C.TYPE_SS:
-                return dataSource.getLiveSsMediaSourceFactory().setTag(metadata)
-                        .createMediaSource(MediaItem.fromUri(uri));
+                factory = dataSource.getLiveSsMediaSourceFactory();
+                break;
             case C.TYPE_DASH:
-                return dataSource.getDashMediaSourceFactory().setTag(metadata)
-                        .createMediaSource(MediaItem.fromUri(uri));
+                factory = dataSource.getDashMediaSourceFactory();
+                break;
             case C.TYPE_HLS:
-                return dataSource.getHlsMediaSourceFactory().setTag(metadata)
-                        .createMediaSource(MediaItem.fromUri(uri));
+                factory = dataSource.getHlsMediaSourceFactory();
+                break;
             case C.TYPE_OTHER:
-                return dataSource.getExtractorMediaSourceFactory().setTag(metadata)
-                        .createMediaSource(
-                                new MediaItem.Builder()
-                                        .setUri(uri)
-                                        .setCustomCacheKey(cacheKey)
-                                        .build());
+                factory = dataSource.getExtractorMediaSourceFactory();
+                break;
             default:
                 throw new IllegalStateException("Unsupported type: " + type);
         }
+
+        return factory.createMediaSource(mediaItem);
     }
 }
```

This has a few advantages:
1. It fixes the deprecation of ``setTag``
2. It makes the code more consistent
3. It de-duplicates a lot of code

**Comment by litetex** [comment]
** Updated test results **

Smoke tested it on the following devices:
* Pixel 3a (emulated) API 31 - Android 11
* Pixel 3a (emulated) API 30 - Android 10
* Huawei P20 lite API 28 - Android 9
* Samsung Galaxy S3 API 19 - Android 4.4

The following works as expected: 
* Playing a normal video
  * Different speeds/pitch work
  * Different qualities work
* Background player
* Popup player
* Watching a live-stream

**Review by litetex — APPROVED** [review]
LGTM

**Comment by Redirion** [comment]
Thank you litetex

**Comment by opusforlife2** [comment]
Woohoo!

**Pull request merged**
