### PR TITLE
Change retry & subscribe buttons background color based on service color

### LINKED ISSUE #1134: Different colors of "Retry" button and services
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.

In NewPipe 0.12.0-beta, Retry button has red color on SoundCloud tab, as on YouTube.

### PR DESCRIPTION
**Pull request by B0pol**
#### What is it?
- [ ] Bug fix (user facing)
- [x] Feature (user facing)
- [ ] Code base improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- change retry (when there is a network error) button color, to follow service's color

#### Fixes the following issue(s)

- fixes #1134

#### Testing apk

[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4605400/app-debug.zip)

#### Agreement
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by Stypox** [comment]
I guess this is already done by #3482 (will test in a bit and report back)

**Comment by Stypox** [comment]
Is RedButton used anywhere else? If that's not the case it could be removed

**Comment by B0pol** [comment]
It's used for subscribe button

**Comment by Stypox** [comment]
Can't the subscribe button also be changed? Its red background looks a little bit strage on platforms other than youtube, and in material guidelines buttons usually have the primary color (go [here](https://material.io/develop/android/components/buttons/) and search for `A contained button has a text label, a filled container and an optional icon.`. In the section below the background color of the button in `?attr/colorPrimary`).

**Comment by B0pol** [comment]
Done @Stypox

**Pull request merged**
