### PR TITLE
Fix grid span count calculation

### LINKED ISSUE #6664: 0.21.6 Tablets thumbnails+title too big
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open app on a tablet
2. Find all the videos messed up

### Actual behavior

The thumbnails of the videos is too big. See screenshot

### Expected behavior

Its supposed to fit?

### Screenshots/Screen recordings

image2

### Device info

 - Android version/Custom ROM version: LineageOS 16. Android 9
 - Device model: SM-T813

Related: #6674

### PR DESCRIPTION
**Pull request by Stypox**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
- Fix grid span count calculation
- Move the duplicate methods `shouldUseGridLayout()` and `getGridSpanCount()` into `ThemeHelper`. They were both duplicated in three classes: `BaseLocalListFragment`, `FeedFragment` and `SubscriptionFragment` and had a different (maybe wrong) implementation each time.
- In `getGridSpanCount()`, instead of doing `(int) Math.floor(screenWidth / ((float) minWidth))`, I just do `screenWidth / minWidth` since the default integer division already yields the floor-ed result.

#### Before/After Screenshots/Screen Record
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

#### Fixes the following issue(s)

- Fixes #6664

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.
@onkq @Thewisem does this work for you?

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Thewisem** [comment]
Ummm how can I get the apk?

**Comment by Thewisem** [comment]
Ok I think I got it

**Comment by Thewisem** [comment]
Yeah I checked. Its fixed

**Comment by Thewisem** [comment]
Hmmm is this commit gonna fix the reordering of grids as you reload the feed?

**Review by TobiGr — APPROVED** [review]
Code looks good to me. I did not have the chance to test it yet.

**Comment by Stypox** [comment]
> Hmmm is this commit gonna fix the reordering of grids as you reload the feed?

@Thewisem nope, it just fixes the text/thumbnail-too-big problems

**Comment by Thewisem** [comment]
Tested it out. Working ok

**Pull request merged**
