### PR TITLE
Integrate YoutubeThrottlingDecoder into exoplayer

### LINKED ISSUE #6510: Buffering video unrelated to connection
[Screen recording](https://linksharing.samsungcloud.com/5PFO7lkTlSVj) 

As you can see in the screen record videos randomly buffer when in video mode, however in background mode the audio plays fine.

This issue is limited to newpipe and other video apps work fine.

Samsung galaxy s10+ android 11

Reinstalling newpipe doesn't work
Changing Internet connection doesn't work

### LINKED ISSUE #6672: Apply YoutubeThrottlingDecoder on youtube stream urls
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
In my attempt to solve https://github.com/TeamNewPipe/NewPipe/issues/6510 I have a decoder implemented in order to modify the "n" query parameter of url in order to bypass the throttling by youtube (I think). https://github.com/TeamNewPipe/NewPipeExtractor/pull/683

The problem is that except on the first url, which is returned by the extractor, on the urls afterwards that decoder is not applied. Reason being that Exoplayer somehow handles those urls itself.

I could not find any resources on how to modify that url and am looking for help in order to solve the throttling problem

### PR DESCRIPTION
**Pull request by XiangRongLin**
#### What is it?
- [x] Bugfix (user facing)

#### Description of the changes in your PR

<details>
<summary>old</summary>
Going with this https://exoplayer.dev/customization.html#customizing-server-interactions the `ResolvingDataSource.Resolver` should be called, but it isn't.  
I think it has something to do with exoplayer using different Extractors depending on the media type, see https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/ProgressiveMediaSource.html . But I once again have no clue why it's not calling my resolver since, MP4 is a Progressive media type, see https://exoplayer.dev/supported-formats.html#progressive-container-formats
</details>

Apply `YoutubeThrottlingDecoder` when fetching more of a video. This only solves streaming, not downloading

The code is shit and it most likely broke some other stuff, but for know i just want to know if this solves the throttling problem

#### Fixes the following issue(s)

- Closes #6510 

#### Relies on the following changes

- https://github.com/TeamNewPipe/NewPipeExtractor/pull/683

#### APK testing 
~~[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/6834390/app-debug.zip)~~  
/
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/6850652/app-debug.zip)

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by njmdietrich** [comment]
Hey, so I installed this debug apk for testing, but have unfortunately now run into the buffering issue using it.
This time, the video played fine for a minute or so, which is different from how it usually works with the "main" app, where it occurs immediately upon playing a video. Again, I barely know what I am doing, but I have created another logcat [here](https://gist.github.com/njmdietrich/27181f2df95dc457936e92bf0286651d)

**Comment by opusforlife2** [comment]
[2021-07-17-yt-throttling.log](https://github.com/TeamNewPipe/NewPipe/files/6834250/2021-07-17-yt-throttling.log)

This is a log of the buffering issue starting, where I filtered the log using the word "newpipe". It's just one line repeating itself.

[2021-07-17-yt-throttling-2.log](https://github.com/TeamNewPipe/NewPipe/files/6834258/2021-07-17-yt-throttling-2.log)

Same log, but this time filtered using the PID. Much more detailed.

**Comment by XiangRongLin** [comment]
Thanks for the logs. Luckily it was just a simple error on my part of replacing the wrong thing inside the url. I updated the debug apk at the top

**Comment by justmax437** [comment]
I can confirm that this PR fixes the issue for me.
POCO X3, Android 11.

**Comment by Thewisem** [comment]
Found this error on the app debug version
## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=kuaFD-tXMrE
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ YouTube
* __Version:__ 0.21.6
* __OS:__ Linux Android 7.1.1 - 25
<details><summary><b>Exceptions (2)</b></summary><p>
<details><summary><b>Crash log 1</b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get like count
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getLikeCount(YoutubeStreamExtractor.java:365)
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractOptionalData(StreamInfo.java:276)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:73)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$YTHJjScxCJNO1LTCqs3IKy35iyY.call(lambda)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15753)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:762)
Caused by: org.schabi.newpipe.extractor.exceptions.ParsingException: Ratings are enabled even though the like button is missing
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getLikeCount(YoutubeStreamExtractor.java:356)
	... 29 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getLikeCount(YoutubeStreamExtractor.java:352)
	... 29 more

```
</details>
<details><summary><b>Crash log 2</b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get dislike count
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getDislikeCount(YoutubeStreamExtractor.java:391)
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractOptionalData(StreamInfo.java:281)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:73)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$YTHJjScxCJNO1LTCqs3IKy35iyY.call(lambda)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15753)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:762)
Caused by: org.schabi.newpipe.extractor.exceptions.ParsingException: Ratings are enabled even though the dislike button is missing
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getDislikeCount(YoutubeStreamExtractor.java:382)
	... 29 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getDislikeCount(YoutubeStreamExtractor.java:378)
	... 29 more

```
</details>
</p></details>
<hr>

**Comment by XiangRongLin** [comment]
@Thewisem those are unrelated to my changes. If you take a look, you can see that it's like/dislike

**Comment by tsiflimagas** [comment]
It seems to have gotten more resistant to throttling, but not fixed for me. What's weird is that it seems to be getting fixed (most of the times) when switching to popup player, but buffering is throttled again when switching back to normal player.

**Comment by Thewisem** [comment]
Oh yeah quick question, why does the video lag at 3x?

**Comment by Thewisem** [comment]
This is specific to this debug version. Its not there in 0.21.6

**Comment by XiangRongLin** [comment]
> 
> 
> This is specific to this debug version. Its not there in 0.21.6

Can't reproduce in either debug apk or release version => off topic, create an issue if you want to see it addressed

**Comment by Thewisem** [comment]
Try watching this video in 3x.
https://www.youtube.com/watch?v=oIKmsy4aTVw
Its not there in current newpipe. Only debug version

**Comment by XiangRongLin** [comment]
I updated the apk with the changes from the extractor. Functionality-wise nothing changed

**Comment by Thewisem** [comment]
It didn't fix the lag when 3x is done on that video

**Comment by njmdietrich** [comment]
I have run into the buffering issue using this version (though not the one with the changes from extractor, I hope that doesn't matter), although this time, instead of only playing for a second or two between buffering, it played for maybe 10 seconds at a time or so. But again, force closing the app was the only way to get it to play seamlessly. 
I managed to [record another log and filtered it](https://gist.github.com/njmdietrich/e4477f12f653fd7691c32d45f157f410). (hopefully correctly!)
[The video in question](https://www.youtube.com/watch?v=AqiDaj0NH0A)

**Comment by opusforlife2** [comment]
So I've been using this PR for the whole of last week, and I have encountered the rapid buffering issue only a couple of times. But fortunately, it lasted for only 10 seconds or so, and then the buffer immediately expanded, loading 50 seconds ahead as expected.

**Comment by bibin-v2020** [comment]
The issue is not fixed completely in this apk but can see some improvements... For videos having issues:

- Buffering for some second's initially and then back to normal speed 
- Wipe Cache Data always fix the issue for me
- Using Android 11 (Realme 3 Pro)

**Comment by infinitewaveparticle** [comment]
I used this apk successfully (no buffering) for 4 days, but today, after watching 2 videos, the issue has returned for every single video. I can no longer watch any videos above 360p and most I have to watch at 240p or 144p. I really want to use NewPipe. I love it. I appreciate all the hard work you put into it too. I will continue using it daily until this issue happens, and then I will use Vanced.

**Comment by XiangRongLin** [comment]
These changes are not needed anymore. Closing in favor of #6792

**Pull request closed without merging**
