### PR TITLE
Respect cutouts when playing in MultiWindow

### LINKED ISSUE #5787: Automatic Notchless Mode View - Just like Netflix
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Rest of the mode such as full screen, fit to screen or zoom don't work as they still use the notch.

#### Is your feature request related to a problem? Please describe it

Not a problem at all.

#### Additional context

Not any.

#### How will you/everyone benefit from this feature?

Everyone who is stuck with a notch of any form will be eternally grateful to your effort.

### PR DESCRIPTION
**Pull request by Cheechaii**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

This fixes the half overlaying cutout on devices with API version 28 and higher. Currently, there are undesirable black bars.

This also respects the cutout when rotating the phone and resizes the video accordingly when in fullscreen. At the moment this leaves undesirable black bars at the top and bottom on devices that have a cutout and a screen that is nearly or exactly the resolution of the video. Maybe a setting can help here or a check for video/device resolution. Let me know what behavior you prefer.

This is my first encounter with Android in about 7 years, so please go easy on me. Let me know if there are bad behaviors or APIs that I missed.

#### Before/After Screenshots/Screen Record

- Before:
before-cutout

- After:
after-cutout

#### Fixes the following issue(s)

- Fixes #5787

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by litetex** [comment]
Thank you for the PR!

I checked if the problem exists on my device (Android 9; Huawei EMUI 9.1.0) and I'm unable to reproduce it in the first place.
Does this only happen on specific devices/Android versions?

**Comment by Cheechaii** [comment]
I have seen this problem on hardware on a Nokia 7.2 and can reproduce this in the emulator for the virtual device definition "Pixel 3 XL" (which is in the screenshot) and also when I create a custom device with resolution 1920x1080 plus enabling the cutout setting in the developer tools.

Maybe the author of the original issue #5787, @desmonk can tell us their device.

**Comment by mhmdanas** [comment]
@Cheechaii the code seems to be duplicated between two difference places; can you de-duplicate it?

**Comment by litetex** [comment]
I'm also pretty sure that the code can be shrunk with the ["?:" aka ternary operator](https://en.wikipedia.org/wiki/%3F:#Java)

**Comment by Cheechaii** [comment]
I extracted the code and replaced 3 code duplications and used the ternary expression.

**Review by Redirion — APPROVED** [review]
looks good to me. Thank you!

**Comment by litetex** [comment]
I think we should revert this PR as it casues multiple problems:
* #7915 - Fails to fill the notch correctly
* #7912 - Fails to align the system menu properly

**Pull request merged**
