### PR TITLE
Remove the redundant/overlapping toast "Copied to clipboard" for Android 13+

### LINKED ISSUE #8957: Remove the redundant/overlapping toast "Copied to clipboard" for Android 13+
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

That would be nice to disable **Copied to clipboard** toasts for android 13+

### Why do you want this feature?

On android 13 there is already a system toast for copied stuff, so it overlap + it's redundant.

### Additional information

I'm not sure but maybe it's just needed to replace  

https://github.com/TeamNewPipe/NewPipe/blob/ebce4c5b7e437d0d3fc7c3e82f9257f6825bdd03/app/src/main/java/org/schabi/newpipe/util/external_communication/ShareUtils.java#L317

and

https://github.com/TeamNewPipe/NewPipe/blob/ebce4c5b7e437d0d3fc7c3e82f9257f6825bdd03/app/src/main/java/us/shandian/giga/util/Utility.java#L203

with 

```
if(android.os.Build.VERSION.SDK_INT < 33) { 
 Toast.makeText(context, R.string.msg_copied, Toast.LENGTH_SHORT).show();
}
```

?

### PR DESCRIPTION
**Pull request by dhruvpatidar359**
#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
This PR removes the extra toast when some text is copied using `ShareUtils.copyToClipboard`, for Android 13 and above.
The `copyToClipboard` method of the `Utility` class has been removed and its usages have been replaced by the method of `ShareUtils`.

#### Before/After Screenshots/Screen Record

- Before:

before

- After:

after

#### Fixes the following issue(s)

- Fixes #8957

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dhruvpatidar359** [comment]
@AudricV can you please review the PR

**Comment by dhruvpatidar359** [comment]
In case if there is any issue please tell me , I will resolve it

**Comment by dhruvpatidar359** [comment]
@AudricV  is the PR is ready to merge or i have to do some more modifications in this ?

**Comment by opusforlife2** [comment]
We already have a release candidate for the next version, so wait for it to be released.

**Comment by dhruvpatidar359** [comment]
> We already have a release candidate for the next version, so wait for it to be released.

👍

**Review by TobiGr — APPROVED** [review]
Thank you

**Review by AudricV — COMMENTED** [review]
Thank you, there is no need here to use the full qualified name of the Android `Build` class, as this class can be imported without any conflicts (there is no other `Build` class used in the files modified).

Also, this class is already imported in the files modified by this PR.

@dhruvpatidar359 Could you apply these changes, please? Thank you in advance!

**Review by AudricV — APPROVED** [review]

**Pull request merged**
