### PR TITLE
Overlapping fonts #5096

### LINKED ISSUE #5096: Overlapping fonts
### Checklist

- [x] I am using the latest version - 0.20.5 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
Use the largest font size in Android setting.

### Actual behaviour

Texts are overlapped.

### Expected behavior

Everything works correctly.

### Screenshots/Screen recordings

Screenshot_20201204-202824

### Device info

 - Android version/Custom ROM version: Android 10, Stock ROM.
 - Device model: Nokia 8.1

### LINKED ISSUE #5804: Crash on tapping anywhere on video after long-pressing 'Popup' button
### Checklist

- [x] I am using the latest version - 0.20.11 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open any video (play it or pause it, doesn't matter).
2. Long-press (press and hold) the 'Popup' button, 'Enqueued' dialog appears.
3. Tap anywhere on video.

### Actual behaviour

The app immediately crashes and displays crash log.

The app still crashes when you:
- play next video and tap anywhere on the video.
- go to Downloads by long-pressing the Download button, then come back to the video and like above tap anywhere on the video.

### Expected behavior

Tapping anywhere on the video should display the controls (Play/Pause and others) rather than crashing.

### Screenshots/Screen recordings

crash-recording

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.20.11
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException
	at org.schabi.newpipe.player.event.BasePlayerGestureListener.onDownInPopup(BasePlayerGestureListener.kt:232)
	at org.schabi.newpipe.player.event.BasePlayerGestureListener.onDown(BasePlayerGestureListener.kt:222)
	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:661)
	at org.schabi.newpipe.player.event.BasePlayerGestureListener.onTouchInPopup(BasePlayerGestureListener.kt:108)
	at org.schabi.newpipe.player.event.BasePlayerGestureListener.onTouch(BasePlayerGestureListener.kt:82)
	at android.view.View.dispatchTouchEvent(View.java:14372)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3857)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:733)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1922)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4051)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:691)
	at android.view.View.dispatchPointerEvent(View.java:14644)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6526)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6313)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5751)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5804)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5770)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5926)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5778)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5983)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5751)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5804)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5770)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5778)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5751)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8910)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8771)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8724)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9046)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:194)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:197)
	at android.app.ActivityThread.main(ActivityThread.java:7948)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

```
</details>
<hr>

### More Information

I was also able to reproduce this on Android 6.0.1 - 23 and NewPipe v0.20.10 as well; all on Samsung devices (J4+, Tab E and J2 Prime, all Galaxy series). 

However, I couldn't reproduce it on NewPipe v0.20.8 (on Xioami Redmi Note 3), because when the 'Popup' button is long-pressed, video plays on Popup mode. But after upgrading to the latest version I could reproduce the crash on this device too.

### PR DESCRIPTION
**Pull request by wangear**
issue : #5096
changed : sp -> dp

#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
To fix bug, I converted some string attributes from sp to dp.

#### Fixes the following issue(s)

- Fixes #5096
- Fixes #5804

#### APK testing 

bugfix_ui
On the website the APK can be found by going to the "Checks" tab below the title and then on "artifacts" on the right.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TobiGr** [comment]
That does not really look like a good solution to me, because `sp` is a relative unit which is specifically for texts as it links to the user's preferred font size. Users might have a good reason to use a larger font size. If they cannot read the texts, because they are too small, this PR does not help them. 
I'd rather suggest to only show the first line of the stream's title if there is not enough space.

**Comment by wangear** [comment]
All right. So I did only show the first line of the stream's title if there is not enough space.

**Comment by wangear** [comment]
Please comment about my pr.

**Review by Stypox — DISMISSED** [review]
Thank you! This fixes the issue, and I also really like the fact that some XML files were converted to ConstraintLayout. This should be done for each one, using RelativeLayout sucks ;-)
This will be merged after 0.21.0 is released.

**Comment by wangear** [comment]
oh..my god. 2 issues mixed.

**Review by Stypox — APPROVED** [review]
Looks good and works well. Thank you!
Btw, making a single PR for two issues is not a good idea, it's better to separate them.
Also, next time create your PRs from a branch named according to your change, not `dev`, otherwise you won't be able to make multiple PRs.
And add a "Fixes " before the issues you fixed so that they are closed automatically when the PR is merged.

**Comment by wangear** [comment]
@Stypox Thank you. And I apologize my mistake. I will take you advice.

**Pull request merged**
