### PR TITLE
Moved resources from mipmap to drawable

### LINKED ISSUE #5256: No NewPipe logo on Fire TV Stick
### Checklist

- [x] I am using the latest version - 0.20.6 
- [x ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
 - side load the apk to amazon fire tv stick (2020)
   - FireOS 7.2.2.8
   - Starteseitenversion 6300180.1

following this guide: https://www.aftvnews.com/how-to-fix-missing-or-broken-icons-for-sideloaded-apps-on-amazon-fire-tv/ fixes the issue 

### Actual behaviour
 - It appears in the installed apps menu but without a logo

### Expected behavior
 - the app should have the newpipe logo

### Device info

 - Android version/Custom ROM version:
 - Device model:
 - Fire TV Stick (2020)
   - FireOS 7.2.2.8
   - Starteseitenversion 6300180.1

### PR DESCRIPTION
**Pull request by Mouli-Sanketh-Maturi**
#### What is it?
- [X] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- moved resources from mipmap to drawable

#### Fixes the following issue(s)

- Fixes #5256

#### APK testing 

On the website the APK can be found by going to the "Checks" tab below the title and then on "artifacts" on the right.

#### Due diligence
- [X] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mhmdanas** [comment]
@vladtepesch does this PR fix the issue for you?

**Comment by fynngodau** [comment]
I understand that this fixes a device-specific bug, but it's not best practice to place the app icon in the `drawable` resources folder for the reasons outlined here: https://stackoverflow.com/a/28065664.

As such, to my understanding, this would introduce the new bug that whenever a launcher tries to display a large version of the app icon, it might display a lower resolution than it should (scaled up).

**Comment by freispiel** [comment]
Could you possibly consider proceeding here despite the PR not being best practice? I for one could live with some launchers scaling up the icon themselves instead of using a hi-res resource. The icon is so simple that scaling it up will probably not be overly visible. But having no icon at all on Fire TV makes the entire thing hardly usable...

**Review by freispiel — COMMENTED** [review]
Looks good to me, matches the suggestion from https://www.aftvnews.com/how-to-fix-missing-or-broken-icons-for-sideloaded-apps-on-amazon-fire-tv/

**Review by freispiel — APPROVED** [review]
(Still) looking good to me. Please, let's proceed.

**Comment by Stypox** [comment]
This is an issue in Fire TV, not in NewPipe: I would not worsen the experience of all other users in order to fix a device specific bug

**Comment by mhmdanas** [comment]
I think in this specific situation I disagree with you, @Stypox; I don't think the upscaling measurably worsens the experience.

**Comment by Stypox** [comment]
Mmmh ok, maybe you are right. Then @Sanketh-Maturi please rebase and fix conflicts; then I will test and if I don't notice big artifacts with upscaling this is good to go.

**Pull request closed without merging**
