### PR TITLE
Update Invidious URL list in the manifest

### PR DESCRIPTION
**Pull request by opusforlife2**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Update list of Invidious URLs that work in the app.

#### Fixes the following issue(s)

- New Invidious URLs don't work in Newpipe.

#### Relies on the following changes

- https://github.com/TeamNewPipe/NewPipeExtractor/pull/463

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Stypox** [comment]
Are you sure we should include all of them in the manifest? It will slow down the global share menu for the users installing NewPipe on their phones, and I guess many of those instances are not popular

**Comment by opusforlife2** [comment]
This is reducing the number of instances by two, so I'm sure it won't make it slower than it currently is, but probably a tiny bit faster.

**Comment by Stypox** [comment]
Oh, then ok, this can be merged right after 0.20.3

**Comment by opusforlife2** [comment]
> It will slow down the global share menu for the users 

As for this, maybe once we're able to figure out how that PeerTube app is accepting share intents without putting URLs in the manifest, we could use that?

**Comment by Stypox** [comment]
@opusforlife2 yes

**Review by TobiGr — APPROVED** [review]

**Pull request merged**
