### PR TITLE
ExoPlayer 2.11

### PR DESCRIPTION
**Pull request by Redirion**
New main ExoPlayer version: https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md

This PR also makes use of two new features:
setHandleWakeLock and
setHandleAudioBecomingNoisy

Test apk based on latest commit:
https://github.com/Redirion/NewPipe/releases/tag/exo211

Edit: Reverted some changes in favor of the new PR #2912 

- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by Redirion** [comment]
turns out that the io.reactivex.Observable was causing the "player accessed on wrong thread" messages and IllegalStateException

However playback still fails as the player immediately enters blocked state:

```
BasePlayer: Playback - onPlaybackBlock() called
BasePlayer: changeState() called with: state = [123]
BasePlayer: onBlocked() called
```

**Comment by Redirion** [comment]
Playback works now. Underlying problem was a ClassCastException as the MasingMediaSource is not compatible with the ManagedMediaSource interface:

> java.lang.ClassCastException: com.google.android.exoplayer2.source.MaskingMediaSource cannot be cast to org.schabi.newpipe.player.mediasource.ManagedMediaSource
 	at org.schabi.newpipe.player.mediasource.ManagedMediaSourcePlaylist.get(ManagedMediaSourcePlaylist.java:32)
 	at org.schabi.newpipe.player.playback.MediaSourceManager.isCorrectionNeeded(MediaSourceManager.java:425)
 	at org.schabi.newpipe.player.playback.MediaSourceManager.maybeLoadItem(MediaSourceManager.java:364)
 	at org.schabi.newpipe.player.playback.MediaSourceManager.loadImmediate(MediaSourceManager.java:354)
 	at org.schabi.newpipe.player.playback.MediaSourceManager.onPlayQueueChanged(MediaSourceManager.java:254)
 	at org.schabi.newpipe.player.playback.MediaSourceManager.access$600(MediaSourceManager.java:45)
 	at org.schabi.newpipe.player.playback.MediaSourceManager$1.onNext(MediaSourceManager.java:200)
 	at org.schabi.newpipe.player.playback.MediaSourceManager$1.onNext(MediaSourceManager.java:190)
 	at io.reactivex.internal.util.HalfSerializer.onNext(HalfSerializer.java:45)
 	at io.reactivex.internal.subscribers.StrictSubscriber.onNext(StrictSubscriber.java:97)
 	at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:407)
 	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
 	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119)
 	at android.os.Handler.handleCallback(Handler.java:789)
 	at android.os.Handler.dispatchMessage(Handler.java:98)
 	at android.os.Looper.loop(Looper.java:164)
 	at android.app.ActivityThread.main(ActivityThread.java:6944)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

I have created a quick workaround by creating a composite class that wraps the "offending" MaskingMediaSource". Playback now works. I will later investigate whether there is a better solution to this workaround.
The MaskingMediaSource got introduced with this commit in ExoPlayer 2.11.0:
https://github.com/google/ExoPlayer/commit/0145edb60d218a939d869f0dbab0ab7fc0a34477#diff-cbfda77de193e56c98e2befa7f6f7a19

**Comment by TobiGr** [comment]
Thanks. I think this change can wait until 0.18.0 is released (a first RC will come soon).

**Comment by opusforlife2** [comment]
Am I the only one that finds it weird that there is an unknown entity called _Robin_ in this PR?

**Comment by Redirion** [comment]
😁 no worries, that's me pushing commits from the command line

**Comment by Pentaphon** [comment]
@Redirion thanks for updating to 2.11.1

**Comment by TobiGr** [comment]
The changes look good. Can you please resolve the conflicts which were introduced in #2690

**Comment by Redirion** [comment]
I am able to reproduce the issue but I don't know how to fix it (yet). Will have to take a look again another time.

Maybe anyone else has an idea how to solve it?

**Comment by Redirion** [comment]
closing this for now due to the issues with the MaskingMediaSource.

sorry @Pentaphon but it will take a little longer

**Pull request closed without merging**
