### PR TITLE
fix button cannot be seen when download popup file already exists

### LINKED ISSUE #8179: Download popup file already exists action buttons display issue
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

1. Go to "Settings" -> "Video and audio" -> Behavior / Preferred 'open' action -> Select "Download"
2. Open Chrome (should work with other web browner)
3. Go to a video link (search "me at the zoo" for example)
4. Open the link with NewPipe
5. The NewPipe download box will open, click on OK to download the video.
6. Wait the download is over
7. On Chrome, select again the same video link
8. Open the link with NewPipe
9. The NewPipe download box will open, click on OK to download the video.
10. The popup "A downloaded file with this file name is already exists" will open but the action buttons "Cancel" and "Overwrite" will not be display

### Expected behavior

Action buttons "Cancel" and "Overwrite" should be display in the the popup "A downloaded file with this file name is already exists"

### Actual behavior

Action buttons "Cancel" and "Overwrite" are not display in the the popup "A downloaded file with this file name is already exists"
The button are there because we can click on them to have the good behavior but they are not displayed.

### Screenshots/Screen recordings

Screenshot_20220412-121359
Screenshot_20220412-122153__01
Screenshot_20220412-122147__01
Expected : 
Screenshot_20220412-122330

### Logs

_No response_

### Affected Android/Custom ROM version

Android 11 / OxygenOS 11.1.2.2

### Affected device model

OnePlus 6T

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by blackwang08**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Because In some cases, the original way of creating Alterdialog will make the text of the button become the same color of the background so it seems to be invisible. To solve this question, I set the color of the text of the button different from background(In light mode it is black, in dark and black mode it is white) to avoid this problem.

#### Before/After Screenshots/Screen Record

- Before:

https://user-images.githubusercontent.com/76472486/165902899-f32b86fd-21a3-402c-b971-5c07b9992b3f.mp4
 
- After:

https://user-images.githubusercontent.com/76472486/165903291-313fdff5-46ca-4f95-9cb8-ef7bacc332d3.mp4

#### Fixes the following issue(s)

- Fixes #8179 

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by Stypox — COMMENTED** [review]
<sub/>

**Review by Stypox — APPROVED** [review]
Thank you! This seems the correct thing to do, though I would like @litetex to confirm

**Comment by blackwang08** [comment]
thanks for your reply!


> Thank you! This seems the correct thing to do, though I would like @litetex to confirm

**Review by litetex — CHANGES_REQUESTED** [review]
Thank you for the PR.

The underlying problem - which is not addressed here but in #8332 - is that the RouterActivity is not implemented correctly (it e.g. set's colorPrimary to transparent) which causes multiple problems.

This can be closed in favor of #8332 - a fix is better than a workaround.

**Comment by litetex** [comment]
Superseded by #8332 and #8340

**Pull request closed without merging**
