### PR TITLE
Change player progress bar update from 500 ms to 1 s

### LINKED ISSUE #7062: High CPU usage
### Checklist

- [x] I am using the latest version - 0.21.9 
- [x ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
Search for any song.
Press background play
Measure cpu time with adb shell top
Turn the screen off to disable gui to make sure gui is not rendering something

### Actual behavior
CPU usage either 6% or 10% in top for newpipe process

### Expected behavior
0% cpu usage for newpipe process as with other players where only media.codec is using 1% cpu

### Device info
Moto G4 stock
Android 7

### PR DESCRIPTION
**Pull request by thefalsedev**
Just like in the issue #7062, this doesn't affect UI as it updates every one second anyway, but reduces very heavy android widget progress bar high cpu usage. With every 500 ms there is 6% cpu usage and with 1 s only 4%. However further changes will have to be made to disable updating of player progress bar when screen is off to further reduce power consumption. With this, total power savings would be 20% in mAh consumption in background playback. This pull request does approx 10% longer screen-off playback.

#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

Change frequency of player progress bar update to 1s

#### Fixes the following issue(s)

- Fixes #7062 

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by thefalsedev** [comment]
Testing results in 0.0395 mAh / s versus 0.046 mAh / s, so therefore with 500 ms the power consumption on Moto g4 with android 7 is 16% higher. Note this is done in controller way the way that the player is started from scratch. After some time it grows 2x but when changing playlist it does reduce but not to the minimum. Hence stopping progress update on screen off would really increase playback time a lot.

**Comment by litetex** [comment]
Fun fact:
This was originally 1s. However it got changed to 500ms in 
https://github.com/TeamNewPipe/NewPipe/commit/455385041205a51c274cc334705bbacb3f120092#diff-7a10d4f22d171ff412c4fd220a9c6eeffe68ba93c4a88fe9b8088c3017795c85L334
https://github.com/TeamNewPipe/NewPipe/commit/455385041205a51c274cc334705bbacb3f120092#diff-2ed842dce430debfa98eadea4336fe9e0ed85295c56e8959d361cc88bcedd07bR148

And never got changed back...

**Review by Redirion — APPROVED** [review]
good catch!

**Comment by TobiGr** [comment]
Do we want to inlcude this into 0.21.10? If yes, we need to change the target branch.

**Comment by opusforlife2** [comment]
@TobiGr I vote yes.

**Comment by Redirion** [comment]
can this be done with the "Rebase and merge" option? I didn't use it yet and don't want to break anything.

**Comment by TobiGr** [comment]
@Redirion It's done via the `Edit` button next to the PR title.

**Review by TobiGr — APPROVED** [review]

**Comment by zubayy** [comment]
@TobiGr don't PRs get merged into TeamNewPipe:dev not TeamNewPipe:release/0.21.10?

**Comment by TobiGr** [comment]
generally: yes
But this case is different. We already started the release process for 0.21.10, i.e. new features and code chages are merged to dev while the release process continues in a separate branch. This is a significant improvement which should be included in the next release and is therefore merged into the release branch. The release branch is later merged back into dev.

**Comment by opusforlife2** [comment]
> However further changes will have to be made to disable updating of player progress bar when screen is off to further reduce power consumption.

@thefalsedev Have you documented this anywhere? If not, please open a new issue with whatever you think is required (or reopen your linked issue if it already contains the relevant info).

**Pull request merged**
