### PR TITLE
Update some misc libraries

### PR DESCRIPTION
**Pull request by TacoTheDank**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
- Update Checkstyle 10.0 -> 10.3.1 ([changelog](https://checkstyle.sourceforge.io/releasenotes.html))
- Update AssertJ 3.22.0 -> 3.23.1 ([changelog](https://assertj.github.io/doc/#assertj-core-3-23-1-release-notes))
- Update desugar_jdk_libs 1.1.5 -> 1.1.6 ([changelog](https://github.com/google/desugar_jdk_libs/blob/master/CHANGELOG.md))
- Update Ktlint 0.44.0 -> 0.45.2 ([changelog](https://github.com/pinterest/ktlint/releases))
- Update AndroidX Constraintlayout 2.1.3 -> 2.1.4 ([changelog](https://developer.android.com/jetpack/androidx/releases/constraintlayout#constraintlayout-2.1.4))
- Update AndroidX Core 1.6.0 -> 1.8.0 ([changelog](https://developer.android.com/jetpack/androidx/releases/core)) (please note the new interfaces in the 1.8.0 alphas, they might be useful)
- Update AndroidX Media 1.5.0 -> 1.6.0 ([changelog](https://developer.android.com/jetpack/androidx/releases/media#version_160_3))
- Update jsoup 1.14.3 -> 1.15.2 ([changelog](https://jsoup.org/news/))
- Update PrettyTime 5.0.2 -> 5.0.3 ([changelog](https://github.com/ocpsoft/prettytime/compare/5.0.2.Final...5.0.3.Final))
- Update AGP 7.2.0 -> 7.2.1 ([changelog](https://developer.android.com/studio/releases#patch-releases))

#### APK testing 
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TacoTheDank** [comment]
@mhmdanas I forgot about that. That also works.

**Comment by mhmdanas** [comment]
We've some new updates now:
- ktlint 0.46.1
- desugar_jdk_libs 1.2.0

**Comment by TacoTheDank** [comment]
@mhmdanas Oh, I'm aware :P

**Review by litetex — APPROVED** [review]
LGTM

**Comment by Stypox** [comment]
I tested a little on API 31 and API 22 and couldn't notice anything bad.

> please note the new interfaces in the 1.8.0 alphas, they might be useful

Good!

**Pull request merged**
