### PR TITLE
Replace `R.string.yes` with `R.string.ok`

### PR DESCRIPTION
**Pull request by Stypox**
Android doesn't use yes/no but ok/cancel usually, so this should be done here, too

#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Related info
This can be considered a followup to #7024. I thought all `yes` were replaced by `ok` in that PR, but apparently it was not the case (as I could notice in #5878), hence this PR.

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by litetex — APPROVED** [review]
LGTM

**Comment by Redirion** [comment]
any reason why we don't use android.R.string.yes or android.R.string.ok ?

**Comment by TiA4f8R** [comment]
No, we can't for some languages: see the PR linked and #5454.

**Comment by Redirion** [comment]
ok yeah but that was regarding the well known "cancel". But anyway :)

**Pull request merged**
