### PR TITLE
Add subscriptions

### PR DESCRIPTION
**Pull request by ksyko**
**(Ongoing)**

Use subscribe button from channel activity.

screenshot_20170415-154328

### CODE REVIEW

**Comment by ksyko** [comment]
Can use help with a layout.

**Comment by theScrabi** [comment]
Hm, could you please put every database related stuff into a folder inside org/schabi/newpipe first.

**Comment by ksyko** [comment]
#14 #209

**Comment by ksyko** [comment]
@theScrabi How long are service ids?

**Comment by ksyko** [comment]
Apparently, there's no channel_url in ChannelInfo :/

**Comment by ksyko** [comment]
screenshot_20170427-135146

Its a separate activity for time being.

**Comment by theScrabi** [comment]
Nice looks good :)

**Comment by ptah-alexs** [comment]
When this will have merged with master?

**Comment by theScrabi** [comment]
When it works.

**Comment by ranomier** [comment]
+1

**Comment by ksyko** [comment]
I cant figure out where to place the fragment

**Comment by ksyko** [comment]
Need help with adding the fragment @theScrabi

**Comment by theScrabi** [comment]
@ksyko can you try to get [these](https://github.com/TeamNewPipe/NewPipeExtractor/blob/master/channel/ChannelInfoItem.java) information into the database.

**Comment by theScrabi** [comment]
I'm sorry to have you informed, that I could not merge it anymore, there where so much changes in the last few weeks, that It's almost not possible now.

Also I want to make some architectural decommissions before I introduce databases into NewPipe. I would want to have the code for the database at a central place.

**Comment by ksyko** [comment]
its okay.

**Comment by rodneyrod** [comment]
Any idea when something like this could be added?

**Comment by theScrabi** [comment]
The thing I'm struggling right now is adding a central database. I want a proper solution for that. I had some ideas, but I'm not able to implement it in the moment.

**Comment by rodneyrod** [comment]
I'm guessing this is going to be a minimal sqlite sort of database, since it would be pulling all of the info from the user's online account from Google's servers wouldn't it be possible to start developing one and if there are any breaking changes, just dump the database and fetch from the servers again?

**Comment by mauriciocolli** [comment]
@theScrabi Hey, you could open a issue with a TODO list with the requirements for the database (like what we will store there, etc.), it would help others (who would want to contribute) and yourself to have a clear "roadmap", and of course, discussion about the ideas.

**Comment by HeatedTea** [comment]
@theScrabi Any update on the database situation?

**Comment by theScrabi** [comment]
It's merged, subscription is already part of newpipe. Just pull master.

**Pull request closed without merging**
