### PR TITLE
Changed Autoplay to Autoqueue to remove ambiguity

### PR DESCRIPTION
**Pull request by opusforlife2**
#### What is it?
- [x] Bug fix (user facing)
- [ ] Feature (user facing)
- [ ] Code base improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- The toggle which appends related streams is called Autoplay. Now that there is an actual Autoplay setting, this can cause confusion for users.

#### Fixes the following issue(s)

- Confusion

#### Agreement
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Review by TobiGr — COMMENTED** [review]
`Auto-queue next stream` is quite long, some translations are even longer, e.g. https://github.com/TeamNewPipe/NewPipe/blob/f8cc3180e83578f2d96ca3da5cc664dbff197a9c/app/src/main/res/values-oc/strings.xml#L75 https://github.com/TeamNewPipe/NewPipe/blob/d8b5549fd98e43f18b993c5f36f2385cf9a80620/app/src/main/res/values-gl/strings.xml#L76

I think we should just use `auto-queue` or `auto-enqueue`

**Comment by opusforlife2** [comment]
So should I add a new string instead?

**Comment by TobiGr** [comment]
I'd vote for that.

**Comment by opusforlife2** [comment]
#4252.

**Pull request closed without merging**
