### PR TITLE
Add Japanese translation of README

### PR DESCRIPTION
**Pull request by ryota-hasegawa**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [x] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

Translate README into Japanese

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by XiangRongLin — CHANGES_REQUESTED** [review]
Isn't the iso code for japan `jp`?

**Comment by ryota-hasegawa** [comment]
Yes. The country code for Japan is jp, but the language code is ja.

**Review by XiangRongLin — COMMENTED** [review]
Well then i learned something.

I don't know how to remove my "changes requested" review, so just dismiss my review

**Comment by mhmdanas** [comment]
@ryota-hasegawa could you also please add a link to `README.pt_BR.md`?

**Comment by ryota-hasegawa** [comment]
@mhmdanas Done.

**Review by mhmdanas — APPROVED** [review]
LGTM

**Comment by mhmdanas** [comment]
@XiangRongLin can you figure out how to remove your requested changes and approve the PR instead? I can't merge the PR unless you do so.

**Review by XiangRongLin — APPROVED** [review]

**Comment by XiangRongLin** [comment]
@mhmdanas done

**Comment by ryota-hasegawa** [comment]
Thank you for merging :)

**Pull request merged**
