### PR TITLE
Make unhooked playback speed changes the default

### PR DESCRIPTION
**Pull request by BarnabyShearer**
I agree the are other great opotunities discussed in #1536 but this seems such a quick win.

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by Stypox** [comment]
Thank you for the contribution! Could you please provide an apk for testing? Thanks ;-)

**Comment by BarnabyShearer** [comment]
Here is a debug build with my change:
[app-debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/3979584/app-debug.apk.zip)
I am afraid I also managed to forget to add half the change; and I can't work out how to push to this PR. So I have included a patch.

**Comment by BeeeWall** [comment]
I'm pretty sure that to add to the PR you just push the commit to the branch you're trying to merge.

**Comment by gillhash** [comment]
@BarnabyShearer
Thanks for fantastic feature. Would you provide fresh apk based on 0.18.2 fixes as above given apk is not working.

@Stypox 
I would love to get this feature added asap to this beautifully crafted lightweight app.

**Comment by Stypox** [comment]
@gillhash this PR has to be redone, since the original branch was deleted and the provided apk seems to be corrupt, so we can't test. But it wouldn't take that much time to do it.

**Pull request closed without merging**
