### PR TITLE
Add option to display channel groups as list instead of grid

### PR DESCRIPTION
**Pull request by cernunnos1710**
#### What is it?
- [ ] Bugfix (user facing)
- [X] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Created a list view for channel groups in the subscriptions page
- Added a toggle button to toggle between the original card view to the newly added one
- Unlike sort, toggle button will exist at all times
- The newly formatted buttons conforms to the same logic as the ones previously. All existing buttons work as intended as they should and will automatically update the ones on the other display format when toggled

#### Before/After Screenshots/Screen Record

- Before:
Screenshot_20221025-115648-2

- After:
Screenshot_20221025-114840
Screenshot_20221025-114829

#### Fixes the Following issue: 
- Fixes: [https://github.com/TeamNewPipe/NewPipe/issues/8605](https://github.com/TeamNewPipe/NewPipe/issues/8605)
#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [X] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cernunnos1710** [comment]
Depending on the maintainers' decision, this could also fix https://github.com/TeamNewPipe/NewPipe/issues/8913.

**Comment by cernunnos1710** [comment]
@SameenAhnaf  I will fix this ASAP. Thanks for the response.

**Comment by opusforlife2** [comment]
@cernunnos1710 Why did you delete the branch and close the PR?

When discussing UI changes, it is better to try things out in your local repo and then post screenshots directly. If you go to all the effort of opening another PR, and yet more changes are suggested, then that means your time is wasted.

**Comment by cernunnos1710** [comment]
Oops! I accidentally deleted this PR. I wanted to create a new branch which is why I deleted this, sorry.

**Comment by opusforlife2** [comment]
You can post your latest screenshots in the issue itself before opening any PR. It will mean less effort on your part.

**Comment by cernunnos1710** [comment]
Okay understood. Thanks!

**Pull request closed without merging**
