### PR TITLE
[Localization] Fix lang code for Chinese Simplified (again!)

### PR DESCRIPTION
**Pull request by chr56**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
First spotted in #2865.

> However, it seems this problem has still been existing after merging #2865 .
It merely fixed the half of this problem.

> The strings.xml file in /values-b+zh+HANS+CN should be moved to /values-zh-rCN again. Then the /values-b+zh+HANS+CN should be deleted and Weblate should be configured correctly.

You can also skip reading these complicated PR & Issues, see summary below:

Currently, there are two resource value files to Chinese Simplified:

- **b+zh+HANS+CN**
`BCP 47 language tags`, supported _ONLY_ since **Android N (API 24)**, (See [Android Devoloper](https://developer.android.com/guide/topics/resources/providing-resources#:~:text=Android%207.0%20(API%20level%2024)%20introduced%20support%20for%20BCP%2047%20language%20tags) ), Weblate **always updates** this one, but it's supported only since Android 7, and honestly, BCP 47 is seldom seen( `zh-rCN`  is quite been used regularly).

- **zh-rCN**
Standard language code under `ISO 639-1` and `ISO 3166-1-alpha-2` (See [Android Devoloper](https://developer.android.com/guide/topics/resources/providing-resources#:~:text=The%20language%20is%20defined%20by%20a%20two%2Dletter%20ISO%20639%2D1%20language%20code%2C%20optionally%20followed%20by%20a%20two%20letter%20ISO%203166%2D1%2Dalpha%2D2%20region%20code) ), supported  almost at a very beginning, but it is outdated because Weblate will **NOT** update this one.

What I did in this PR is removing weird  `b+zh+HANS+CN` and moving it to standard and ordinary `zh-rCN`.

#### Before/After Screenshots/Screen Record
Changes of resource, no need to make Screenshots.

#### Fixes the following issue(s)
Just **Potential** bugs, <del>no issues related.</del>
UPDATE: Actually #6469 (it should be seen on Android 5.0 to Android 6 now) and  #6468 (It might be **a side effort** that Weblate could not recognize `BCP 47` tag, so failed to build plural strings. see also PR #6545). 
Besides, [Weblate#7312](https://github.com/WeblateOrg/weblate/issues/7312)

#### APK testing 
No need, but 
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/8983889/app-debug.zip) (Signed with my key)

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mhmdanas** [comment]
> > The strings.xml file in /values-b+zh+HANS+CN should be moved to /values-zh-rCN again. Then the /values-b+zh+HANS+CN should be deleted and Weblate should be configured correctly.

@stypox @litetex I believe both of you have Weblate access, can you see if you can do anything about this?
@stypox

**Comment by Stypox** [comment]
Doesn't this fix #6469? If so please link it in the "Fixes the following issues" section

**Comment by chr56** [comment]
> Doesn't this fix #6469? If so please link it in the "Fixes the following issues" section

Yes and no, only devices running Android 6 (API 23) and below might meet the problem of "not consistent with source code (#6469)", Android 7 and higher should not have this problem.

**Comment by chr56** [comment]
Also, These duplicated files might also cause [this](https://github.com/WeblateOrg/weblate/issues/7312).

**Comment by Geeyun-JY3** [comment]
> > Doesn't this fix #6469? If so please link it in the "Fixes the following issues" section
> 
> Yes and no, only devices running Android 6 (API 23) and below might meet the problem of "not consistent with source code (#6469)", Android 7 and higher should not have this problem.

No. As I detailed in #6469, I can reproduce it on Android 9. String is consistent with `zh-rCN` if it is included in the `strings.xml` file in `/values-zh-rCN`. If not, it is consistent with `b+zh+HANS+CN`.

**Review by litetex — APPROVED** [review]
LGTM

@Stypox Can we merge this or should we wait until after the release.

**Comment by chr56** [comment]
> LGTM
> 
> @Stypox Can we merge this or should we wait until after the release.

If you asked me, I would like to choose waiting until release of v0.23.1.
After all, this is a manual modification on localization except source string. 
I am afraid this PR might have potential damages to other localizations (such as causing unsynchronized translation, data loss or something else).
And if possible, please sync with Weblate as soon as possible, if this PR were really merged.
@Stypox @litetex

**Review by mhmdanas — APPROVED** [review]

**Review by Stypox — APPROVED** [review]
Thank you! I made sure everything is ok with Weblate by:
- locking weblate
- pushing all of the weblate changes since the release onto `dev`: 8d26d9da46f72937a373feb4638d7f034d52c457
- resetting weblate, since weblate was complaining about conflicts
  - this did not cause any loss of information, as I just pushed all changes manually the step above ^
  - -> weblate now shows 0 pending changes, 0 outgoing commits and 0 missing commits
- rebasing this PR on top of `dev`
- force-pushing this PR
- merging this PR
- resetting weblate again
- unlocking weblate

**Pull request merged**
