### PR TITLE
Add whitelist to only retrieve supported YouTube itags/streams

### PR DESCRIPTION
**Pull request by TobiGr**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [x] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
This PR makes NewPipe compatible with the changes from https://github.com/TeamNewPipe/NewPipeExtractor/pull/488 and https://github.com/TeamNewPipe/NewPipeExtractor/pull/706

#### Relies on the following changes
https://github.com/TeamNewPipe/NewPipeExtractor/pull/488 and https://github.com/TeamNewPipe/NewPipeExtractor/pull/706 can, but do not have to be merged

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Stypox** [comment]
Great!

This is service-dependent, isn't it? Though I doubt there is any way around this.

**Comment by TobiGr** [comment]
oh yes, I could also add a condition to check the current service to make sure that there are no side effects. I did not test this PR with other services.

**Comment by TobiGr** [comment]
Tested with the other services as well. I did not encounter any problems

**Comment by Stypox** [comment]
Shouldn't the filtering happen on a client level? What if NewPipe isn't able to play a specific video, while Piped is, or viceversa?

**Comment by TobiGr** [comment]
> Shouldn't the filtering happen on a client level? What if NewPipe isn't able to play a specific video, while Piped is, or viceversa?

This PR is opened in the client / app repo and not the extractor repo :)

**Review by Stypox — APPROVED** [review]
Sorry, I don't know why I thought we were on the extractor... Anyway, looks good to me. Note that we have `getUrlAndNonTorrentStreams` too, which is used for external players, and we might want to prevent/allow other kinds of streams from being opened in external streams, too.

**Pull request merged**
