### PR TITLE
Update placeholder variants

### LINKED ISSUE #9044: Placeholder Variants
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

If possible, there should be placeholder variants. For example: If you currently open NewPipe and scroll down, then the thumbnail loads. Instead of the placeholder thumbnail with the play icon, there could be an hourglass to signal that it loads the thumbnail. Or if a video has been deleted, the thumbnail is provided with an X or trash can.

Example thumbnail loads (hourglass):
Loading Thumbnail
Example for deleted video thumbnail (X):
X Thumbnail
Example for deleted video thumbnail (trash can):
Trashcan Thumbnail

### Why do you want this feature?

Currently, there is only one placeholder thumbnail for loading video and when a video has been deleted (play icon). This could lead you to think that the thumbnail is still loading. So you could show that the video has been deleted.

### Additional information

You could also do this for private videos. Also for channel avatars placeholders. But I don't know if the feature request is not already a lot of work and effort. I came up with this idea through the 0.24.0 update. Because at the first start of the version, the thumbnail took a little longer. And so I thought that all videos are deleted or private, because of the placeholder thumbnail.

### PR DESCRIPTION
**Pull request by HighGr0und**
#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Add two new placeholder thumbnail  (hourglass_thumbnail and close_thumbnail).
- Replace placeholder_thumbnail_video with placeholder_thumbnail_hourglass.
- Show placeholder_thumbnail_off when cover URL is empty

#### Before/After Screenshots/Screen Record
<table>
  <tr>
    <th>Before</th>
    <th>After hourglass</th>
    <th>After close</th>
  </tr>
  <tr>
    <td>Before</td>
    <td>After</td>
    <td>After</td>
  </tr>
</table>

#### Fixes the following issue(s)

- Fixes #9044

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by Stypox — CHANGES_REQUESTED** [review]
Mmmh, why do you think this should be done? Also, I think the top-filled-bottom-empty hourglass would look better (just like the one for the buffering video)

**Comment by opusforlife2** [comment]
They ignored the template section for linking the fixed issue. @HighGr0und You're not supposed to ignore provided templates.

**Comment by TobiGr** [comment]
I don't know whether this is a good addition. The new placeholders look very old-fashioned. 
We could try to use the three loading dots for the loading placeholders, but I'd prefer to keep the old placeholder in case of a failure.

**Comment by HighGr0und** [comment]
I have changed the style of hourglass, should I use this or three loading dots
Screenshot 2022-10-28 152628

**Comment by Stypox** [comment]
Please explain why you think we need multiple types of placeholder images. And explain use-cases for the various situations.

**Comment by HighGr0und** [comment]
> Please explain why you think we need multiple types of placeholder images. And explain use-cases for the various situations.
I apologise for missing the issue that this Pull request relates to, it is specific to this issue: https://github.com/TeamNewPipe/NewPipe/issues/9044

**Comment by Stypox** [comment]
See https://github.com/TeamNewPipe/NewPipe/issues/9044#issuecomment-1336504293. Also, I don't think the images proposed here fit into the app design and I don't think it's worth to spend time on this niche feature. Sorry for that and thank you for the contribution anyway!

**Pull request closed without merging**
