### PR TITLE
Reduce the size of thumbnails on big screens to fit more grid columns

### LINKED ISSUE #9763: Layout changed after upgrade to v.0.25.0 from 6 to 4 thumbnails per row !
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.0

### Steps to reproduce the bug

Upgrade tolatest version

### Expected behavior

Keep layout as in v0.24.1.

### Actual behavior

I cannot go back to v0.24.1
Uninstalling and installing v.0.24..1 is throwing an error !

### Screenshots/Screen recordings

_No response_

### Logs

_No response_

### Affected Android/Custom ROM version

Andoid v5.1

### Affected device model

Tablet 10.5 inch

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Stypox**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
Reverts a small piece of #9310, which introduced bigger grid thumbnail sizes on big screens, because some users reported not being happy about having too few grid columns. See https://github.com/TeamNewPipe/NewPipe/pull/9310#discussion_r1070670806.

#### Before/After Screenshots/Screen Record
<table>
  <tr>
    <th>Before #9310</th>
    <th>Before</th>
    <th>After</th>
  </tr>
  <tr>
    <td>Before #9310</td>
    <td>In #9310</td>
    <td>After</td>
  </tr>
</table>

#### Fixes the following issue(s)

- Fixes #9763

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by s2r** [comment]
Its better, but why not go back to 5 or 6 grids, or at least give that choice?

And if possible even removing a lot of the white space/border space between thumbnails, this from 3 to 4 is just mimicking mobile youtube, currently on newpipe it shows me a 3 grid and on m.youtube shows me a 4 grid but on m.youtube the 4 thumbnails seem even bigger than the 3 on newpipe just because there is is very little border space between the thumbnails, you guys have to give us better usability or else whats the point?

**Comment by peat80** [comment]
4 grids is the perfect size, please proceed. 🤔 😀

**Comment by Stypox** [comment]
If in 0.24.1 you had 6 items per row, with this PR you would probably get 5.

**Comment by Stypox** [comment]
Thank you for testing. I know this is not the optimal solution, but at least it will hopefully suit a bit better both people who want large thumbnails, and people who want more data on the screen at once. I'm merging this and soon we'll ship 0.25.1.

**Comment by s2r** [comment]
@Sypox not happy, but i still appreciate your work, thanks!

**Pull request merged**
