### PR TITLE
Fix failing test

### PR DESCRIPTION
**Pull request by coffeemakr**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

The update of the extractor changed the signature of the `VideoStream` and `VideoStream`. I've changed the test accordingly.

**Update**: Also fixes installation of Android components in Travis CI

### CODE REVIEW

**Comment by coffeemakr** [comment]
I'm not sure why travis is complaining about SDK licenses. Seems like travis changed something on their end. I'll try to fix the configuration file.

**Comment by wb9688** [comment]
It does if there's version mismatch between .travis.yml and build.gradle.

**Comment by coffeemakr** [comment]
gradle and travis didn't change 😕 
From the logs:
>  Downloading SDK Platform Android 8.1.0, API 27, revision 1
> Download finished with wrong size. Expected 65606517 bytes, got 65738431 bytes.
>  Done. Nothing was installed.

**Comment by theScrabi** [comment]
I see it fails because of the license not accepted. Can we fix this?

**Comment by coffeemakr** [comment]
I think the main problem is that build tools 27.0.1 are not installed correctly. 

I suspect that Travis CI caches the build tools by using a proxy and didn't expect google to change the SDK.  (See https://issuetracker.google.com/70292819 for more information.)

The byte sizes are exactly the once show here: https://verification.f-droid.org/build-metadata/platform-27_r01.html where they compare the two different versions.

**Comment by coffeemakr** [comment]
It may be possible to manually create the lincense file for android with the correct hash in it. I will have a look at it later.

**Comment by wb9688** [comment]
Yeah, but I'd consider that a hack, we should just contact Travis.

**Comment by wb9688** [comment]
This is Travis' response:

>Thank you for reporting this issue and I'm sorry for the inconveniences this is currently causing you.
>
>That's interesting and it might be caused because we are using the old `android` CLI to install the Android SDKs under the hood. I'm not sure how fast we'll be able to fix that but in the meantime, I was wondering if you could try to install it yourself using the `sdkmanager` CLI instead? Here's what you would need to add to your .travis.yml file:
>
>
>`before_install: - yes | sdkmanager "platforms;android-27"`
>
>Please let us know if this helps or not and we will follow-up upon your reply.
>
>Thanks in advance and have a great Friday!

**Comment by coffeemakr** [comment]
I didn't expect the support for unpaid project to be this good and responsive.

**Comment by coffeemakr** [comment]
The fix worked! 
@wb9688  Thank you for getting in contact with Travis. If you hear anything new I'd be pleased to hear more about this issue and what caused it.

**Pull request merged**
