### PR TITLE
Change mute button color for more visibility

### PR DESCRIPTION
**Pull request by B0pol**
#### What is it?
- [x] Bug fix ??
- [ ] Feature

#### Long description of the changes in your PR

The recently introduced mute button #3165 is not really visible the sound is unmuted, it's in gray. I made it white everytime, therefore it's more visible.

Screenshots:
Before: 
Screenshot_20200321-170322_NewPipe_Debug
After:
Screenshot_20200321-165830_NewPipe_mute_button

When it's muted, it stays the same icon, same color (it's the icon on the first screenshot but in white).

#### Agreement
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by opusforlife2** [comment]
Test apk?

**Comment by wb9688** [comment]
@opusforlife2: Not really needed for small changes like this.

@B0pol: Code looks fine, however we should have the discussion about whether it should show the current state or what it will do when you press it. @TobiGr: What do you think?

**Comment by TobiGr** [comment]
I'd show the action, so when volume is on, show the mute icon and when muted show the volume icon

**Comment by B0pol** [comment]
> Test apk?

Is it really needed for 5 lines changes?
You can build by yourself otherwise: `git remote add bopol https://github.com/B0pol/newpipe`, then `git fetch bopol`, `git checkout mute_button`, and you go in Android Studio and press run button. And of course change mute_button and B0pol depending on the branch name /developper name).

**Comment by opusforlife2** [comment]
Olrite.

**Comment by B0pol** [comment]
@wb9688 is right, in android settings that's the pattern.
Plus I vatched other players: ReadReader player (it's a reddit client app), dailymotion, peertube, firefox player, and they all show the current state instead of action @TobiGr. Then I don't think it should be changed.

**Comment by opusforlife2** [comment]
For the sake of thoroughness: the Play/Pause button is the only one that shows the intended state instead of the current one.

**Comment by wb9688** [comment]
Shouldn't this be changed in the other players as well then?

**Comment by B0pol** [comment]
> Shouldn't this be changed in the other players as well then?

I've done it. Though, I can't change color when adding an icon, because Android Studio crashes, so for the black theme, the icon is 72dp instead of 24dp.
If someone can change select color of icons, please do it, you just need to add volume up 24 dp icon and change [this line](https://github.com/TeamNewPipe/NewPipe/blob/07ccc4b2b0366e4e2010cbafce068223ab136727/app/src/main/res/values/styles.xml#L143) with the newly added icon.

**Pull request merged**
