### PR TITLE
Option to show suggested by default instead of comments, fixes #2238

### LINKED ISSUE #2238: Feature request: Option to show suggested by default instead of comments
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Nice work adding comments! They look really good. Unfortunately, I usually don't want to look at them, but prefer to see Suggested Videos below the description. I'd really appreciate an option to show this by default, and still allow sliding to see comments (so the comment disabling option isn't really what I'm looking for). 

Thanks :)

### PR DESCRIPTION
**Pull request by Redirion**
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by yausername** [comment]
> @theScrabi @Redirion @yausername In which category do you think the two settings fit best?

I think they fit best in the content settings category

- Show "Next" and "Similar" videos
- Show comments
- Prefer "Next" and "Similar" videos over "Comments"

**Comment by theScrabi** [comment]
Aaaah no new setting.

@yausername can you just make it so NewPipe rememberes waht was opened last? I mean if commends whas the last thing open next time NewPipe will show commends again, and vice versa? I want to reduce the amount of settings keys we need to add.

**Comment by TobiGr** [comment]
@theScrabi Sounds good. Nevertheless, we should get some order into the settings.

**Comment by Redirion** [comment]
@theScrabi you are right.

**Comment by yausername** [comment]
> @yausername can you just make it so NewPipe rememberes waht was opened last? I mean if commends whas the last thing open next time NewPipe will show commends again, and vice versa? I want to reduce the amount of settings keys we need to add.

Ok

**Pull request closed without merging**
