### PR TITLE
Update Desugaring to 1.1.8

### PR DESCRIPTION
**Pull request by TacoTheDank**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
- Update desugar_jdk_libs 1.1.6 -> 1.1.8 ([changelog](https://github.com/google/desugar_jdk_libs/blob/master/CHANGELOG.md))

Some other things:
- Update ACRA 5.9.3 -> 5.9.7 ([changelog](https://github.com/ACRA/acra/releases))
- Update AGP 7.3.0 -> 7.3.1

#### APK testing
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by Stypox — CHANGES_REQUESTED** [review]
Trending and search results would never load while I was trying to test this out. I could consistently reproduce on API 31, API 33 emulated and API 30 on my phone. API 22 emulated works. The commit before yours has no problems. Search suggestions seem to work and if you look in the network tab of Android Studio's app inspection you will see that requests are actually being made for trending and search results, though for some reason the results never show up.

**Comment by TacoTheDank** [comment]
Interesting 🤔 Let's try 1.1.8 instead.

**Comment by Isira-Seneviratne** [comment]
> Trending and search results would never load while I was trying to test this out. I could consistently reproduce on API 31, API 33 emulated and API 30 on my phone. API 22 emulated works. The commit before yours has no problems. Search suggestions seem to work and if you look in the network tab of Android Studio's app inspection you will see that requests are actually being made for trending and search results, though for some reason the results never show up.

Yeah, it seems to be related to this issue: https://issuetracker.google.com/issues/246512175

**Review by Stypox — APPROVED** [review]
I tested and with `1.1.8` it works. I hope they'll fix this soon

**Comment by Isira-Seneviratne** [comment]
> I tested and with `1.1.8` it works. I hope they'll fix this soon

I believe it's fixed in 2.0, which requires AGP 7.4.

**Pull request merged**
