### PR TITLE
Set image-minimizer to specify image width ...

### PR DESCRIPTION
**Pull request by yashpalgoyal1304**
Fix https://github.com/TeamNewPipe/NewPipe/issues/9469 for portrait like orientations

#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [x] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- record videos
- create clones
- take over the world

#### Before/After Screenshots/Screen Record

- Before:
- After:

#### Fixes the following issue(s)

- Fixes https://github.com/TeamNewPipe/NewPipe/issues/9469

#### Relies on the following changes

- 

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by yashpalgoyal1304** [comment]
Please do check this if this is correct, i have not tested as i did.... umh, wait...

**Comment by opusforlife2** [comment]
You could spend 30 seconds to clean up the default template text...

**Comment by yashpalgoyal1304** [comment]
> You could spend 30 seconds to clean up the default template text...

it requires data, which i am gathering currently

**Comment by yashpalgoyal1304** [comment]
I renamed the branch, per the instructions in "APK-testing" section in description, and now github thinks i deleted it, So, i opened the new https://github.com/TeamNewPipe/NewPipe/pull/9471

**Pull request closed without merging**
