### PR TITLE
make video title & controls more compact

### PR DESCRIPTION
**Pull request by jaromeyer**
#### What is it?
- [ ] Bugfix (user facing)
- [X] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Increase default video title to 2 lines: I have found that almost every video title fits in two lines, but not in one (which is the current default). Also everywhere else in the app (and in the official YT app iirc) video titles currently can take up two lines, so this will unify the UI throughout the app.
- merge primary and secondary controls: This decouples showing additional options from expanding the title and thus makes the UI more intuitive in my opinion. I have tested it on various screen sizes and even on very small screens it works fine, so I currently don't see any downsides of always showing all controls.
- only show the expansion arrow when the title is ellipsized (longer than 2 lines)

#### Before/After Screenshots/Screen Record

<table>
  <tr>
    <th>Before (default)</th>
    <th>Before (expanded)</th>
    <th>After</th>
  </tr>
  <tr>
    <td></td>
    <td></td>
    <td></td>
  </tr>
</table>

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [X] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SameenAhnaf** [comment]
Keeping the `Share` and `Open in` buttons in the middle instead of the end would make the experience a little more symmetrical.

**Comment by peat80** [comment]
Since the control icons are more or less self explaining, why not remove the labels and just show the icons? Would look even better i think. 🤔 😀

**Comment by Stypox** [comment]
I agree the buttons should be more compact, since on most devices there is a lot of wasted space in between buttons. But on some devices 4 buttons barely fit, adding 3 more just makes it worse there (remember, there is also Kodi, which is hidden unless enabled)... And the buttons are also more difficult to tap.

I tried a while ago to make that row of buttons horizontally scrollable, so that if they were too large, they would become scrollable, but was unable to do it. Maybe you could try?

Btw, take a look at how I edited your PR description. Now images are of the correct size ;-)

> Since the control icons are more or less self explaining, why not remove the labels and just show the icons? Would look even better i think.

@peat80 well, I also agree it would look even better. But I don't know about discoverability... Once we have an "introductory course" the first time a user opens NewPipe, then yeah, we can remove labels completely, but otherwise... I don't know. Many people to which I share NewPipe do not realize what the background button does even if currently there is a label. I think it would only be worse if we removed the label. I would put this to votes

**Comment by opusforlife2** [comment]
Please try to do only one thing per PR, not just for easier reviewing, but also so that discussions on separate things happen separately.

- Labels should not be removed at all. These icons aren't universal. As Stypox says, without the labels, our somewhat cryptic UI would become even less usable by 'the normies'. That's practically everyone I've shared this app with.
- The 7 buttons in a row would be horrifying to use on a 4.7 inch screen. Hard no.
- I fully agree with the title changes, both the 2 line thing and the ellipsis for longer titles.

This PR should only focus on the video title changes, I think.

**Comment by Stypox** [comment]
Closing as there is still no consensus, because of the problems already highlighted, and because of inactivity. If you still wish to work on this feel free to try to reach consensus and then reopen @jaromeyer :-)

**Pull request closed without merging**
