### PR TITLE
[localization]remove duplicate string file

### PR DESCRIPTION
**Pull request by chr56**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

delete duplicate value-b+zh-HANS+CN file (localization of Simplified Chinese).

#### Fixes the following issue

- [on Weblate]Warning of "Duplicated translation."
screenshot2021-01-09 130822
Since "zh-rCN" is quite more common and formal than "b+zh+HANS+CN",so I remove "b+zh+HANS+CN",it should fix this warning(unless Weblate fools us).

#### APK testing 

_Does it matter?_ / _Is it necessary?_

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TobiGr** [comment]
IIRC, this translation has been removed previously and was added again. I don't see any reason why it should be removed.
Is the traditional Chineese localization conflicting with the simplified version?

**Comment by chr56** [comment]
The problem is ,OS fetched string in zh-rCN first (if it fails,then fetch b+zh+HANS+CN), however, Weblate always updates b+zh+HANS+CN. So this made many "dead" strings in zh-rCN (you can't change them via Weblate).
@TobiGr

**Comment by chr56** [comment]
Besides, did you mean this file was removed once before,but it was added again by Weblate?
So didn't you try to config Weblate to make this language "redirect" to zh-rCN?
@TobiGr

**Comment by chr56** [comment]
🤔It seems so. Weblate is configurated to "b+zh+HANS+CN".

**Pull request closed without merging**
