### PR TITLE
Resolved conflicts with dev branch for new player

### PR DESCRIPTION
**Pull request by avently**
I really hope that you guys, @theScrabi @karyogamy @mauriciocolli @wb9688 will base your future work on the /embed branch. That conflict resolving was like a hell. Mostly because layout conflicts since popup and main players use one layout. 

I didn't tested all new functionality but what i tested is working.

  @karyogamy i have a question. I added screen resizing to popup but couldn't get any difference between the original resize mode and others. Does it work only on limited number of videos? For main player i see the difference.

- [ x ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by justanidea** [comment]
You're so hard working... congrats

**Comment by karyogamy** [comment]
Thanks for the update. 

You are right, the popup resizing only works on certain videos since the player is forcing an aspect ratio of 16:9, and will only work on [certain videos](https://www.youtube.com/watch?v=qN80_7rNmcE). However, popup player shouldn't allow zoom resizing as certain videos under that setting can expand outside the popup window.

**Comment by avently** [comment]
@karyogamy added commit for properly support of ZOOM mode

**Comment by avently** [comment]
@theScrabi what's need to be done from my side if I want to merge it to the dev branch as soon as possible? 
A kind of checklist. 
I mean I need you to be interested in it as well as I am.

**Comment by theScrabi** [comment]
Still my opinion was to wait until the development around the player has settled a bit.

However @mauriciocolli should review the code once again, he was the one who wrote our current player, he should be the one who gives the green light.

**Comment by avently** [comment]
@mauriciocolli you was mentioned here but didn't receive notification about it since it was happened in edited comment.

**Comment by avently** [comment]
@theScrabi since @mauriciocolli didn't respond on your comment can you make the decision yourself?

**Comment by theScrabi** [comment]
No, since I am not that familiar with the code. @karyogamy could maybe take a look at it as well.

**Comment by avently** [comment]
@karyogamy in the first PR you made great reviews.  If I remember correctly every issue was fixed. Maybe now it is a good time to think about the future of the app and make the step to that future with my code and your review of it. Since your review will be the final step i'm asking you about that.

**Comment by karyogamy** [comment]
@avently Hang in there, I will soon find the time to do the review as well as creating patches to speed up the merge. However, right now, my focus is on getting livestream and the `BasePlayer` to a stable state, so we don't have worry about it in the future. Having embedded player and seamless player switching is quite crucial in providing a good user experience, so I will definitely be getting to them.

**Comment by avently** [comment]
@karyogamy 
>I will soon find the time to do the review as well as creating patches to speed up the merge

Are you ready now? I have some time on that week

**Pull request merged**
