### PR TITLE
Add dialog to confirm a download's deletion

### LINKED ISSUE #1430: [Improvement] Add  Confirmation dialog box when delete downloaded video
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.

I found that my video straightly deleted when I touch on the "delete" button accidentally.
It is so closed for "play" and "delete" button that it may be easily wrong touch.
If so, your video downloaded just now would gone !
For avoid this, please consider adding a 
Confirmation dialog box when user touch "delete" buton, or mv this button another place hard to touch by accident.
Thanks!

### PR DESCRIPTION
**Pull request by TobiGr**
Closes #1430

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by acrosca** [comment]
Code is fine but UX is not ideal.
In most cases the delete is intentional and only in rare cases accidental.

A nice UX solution is to show a Snackbar with the UNDO action. If user does not act before the Snackbar is hidden,  delete the file. If user presses UNDO, cancel the scheduled delete.

**Comment by theScrabi** [comment]
@acrosca you are right, it would be a more materialish solution. So eather way, I would merge both solutions.

**Comment by TobiGr** [comment]
@theScrabi I can change that, but as I said, I am in Berlin. So I guess, this has to wait until next weekend.

**Comment by umunais** [comment]
an option to clear the list of downloads will be good. also showing download progress in status bar will be good.

**Comment by acrosca** [comment]
@TobiGr let me know if I can take over and implement the snackbar. I have the time.

**Comment by TobiGr** [comment]
@acrosca Feel free to do it. I am busy at a local film festival until Monday.

**Comment by theScrabi** [comment]
i went with  #1472

**Pull request closed without merging**
