### PR TITLE
Solving issue #2810 by changing drawer_layout.xml

### LINKED ISSUE #2810: A small part of the sidebar is in the status bar
Hi,

when I open the sidebar under Android 7 in the NewPipe app (0.17.4). You can see a small part of the sidebar in the status bar.

I've seen friends using a much bigger Android phone (Samsung Galaxy S10+ - Android 9) that even the "NewPipe logo + NewPipe" in the sidebar is almost in the status bar and it doesn't look right anymore.

### PR DESCRIPTION
**Pull request by hemilpanchiwala**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

I have tried to fix #2810 
Now the sidebar has been set below the status bar.
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/3925397/app-debug.zip)

### CODE REVIEW

**Comment by Ozyc** [comment]
screenshot

**Comment by TobiGr** [comment]
Thanks for the contribution @hemilpanchiwala! Unfortunately, there are some changes required.

From my https://github.com/TeamNewPipe/NewPipe/issues/2810#issuecomment-562697126:

> 
> The navigation drawer should be under the status bar as you can read and see [here](https://material.io/components/navigation-drawer/#anatomy) in the material guidelines. 
> 
> >I've seen friends using a much bigger Android phone (Samsung Galaxy S10+ - Android 9) that even the "NewPipe logo + NewPipe" in the sidebar is almost in the status bar and it doesn't look right anymore.
> 
> This needs to be addressed, though.

**Comment by hemilpanchiwala** [comment]
@TobiGr I have addressed that problem also and I have tested it on OnePlus 6 where this issue seems to be resolved after making the changes in the code. So please check my PR once as to me it seems to be resolved.

**Comment by Stypox** [comment]
@hemilpanchiwala could you address what @TobiGr explained? With this pr the drawer does not go below the status bar, but it should. The only thing that shouldn't go below the status bar is the content of the drawer

**Comment by wb9688** [comment]
Not needed anymore as we properly fixed it in #3334

**Pull request closed without merging**
