### PR TITLE
persist shuffle mode using sharedPreferences

### LINKED ISSUE #1795: Remember shuffle mode
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

I use NewPipe for listening to music and I use shuffle mode alot. Therefore I think it would be nice to remember shuffle mode, maybe this can be set as an option in settings. What do you think?

I usually start a playlist from bookmarks, and from there I have to navigate to the player queue and turn on shuffle mode.

### PR DESCRIPTION
**Pull request by AliJavanJ1**
#### What is  it?
- [ ] Bug fix (user facing)
- [X] Feature (user facing)
- [ ] Code base improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
saves the shuffle mode in shared preferences and retrieves it after initiating player.
the shared preferences resets in main activities `onDestroy` method

#### Fixes the following issue(s)
- fixes #1795

#### Testing apk

debug.zip

#### Agreement
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by opusforlife2** [comment]
Upload a test apk in the OP after you're done making changes, dudeman.

**Comment by wb9688** [comment]
@opusforlife2: Not really needed for such small changes.

@AliJavanJ1: Could you please rebase on `dev` and fixup your commits? Also, why would we want to disable shuffling as soon as the `MainActivity` gets destroyed?

**Review by Stypox — CHANGES_REQUESTED** [review]
Looks good to me, apart from the MainActivity change. Could you provide an explanation @AliJavanJ1 ? Otherwise I will revert that change and then merge, since the other changes look good. Thank you ;-)

**Comment by litetex** [comment]
Closing this for now:
* no progress
* no GitHub actions build
* merge conflicts
* no feedback from author

Feel free to reopen it when there is progress again.

**Pull request closed without merging**
