### PR TITLE
removed the gema strings.

### PR DESCRIPTION
**Pull request by sherlockbeard**
#2208  as stated in the issue the code related to Gema is removed.

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by sherlockbeard** [comment]
@TobiGr please review it.

**Comment by sherlockbeard** [comment]
@TobiGr done can you review it again?

**Comment by Redirion** [comment]
issue #2208 can be closed

**Comment by TobiGr** [comment]
@Redirion Done

**Pull request merged**
