### PR TITLE
Fix reproducible builds

### LINKED ISSUE #6486: doesn't build reproducibly (due to bug in coreLibraryDesugaring)
I compared the APKs from the last 5 releases on GitHub to the APKs built and published by F-Droid.
Some of them are identical (apart from the signature), but not all of them are.

I've done multiple clean builds of `0.21.4`; they were not always identical.
I've seen 3 variants, one identical to the GitHub APK, another identical to the F-Droid APK.
The differences I've seen were always in `j$/util/Collection$-EL.class`.

### diffoscope output

<details>

```
--- NewPipe_v0.21.4.apk
+++ org.schabi.newpipe_970.apk
├── zipinfo {}
│ @@ -1430,11 +1430,11 @@
│  -rw----     0.0 fat      186 b- stor 81-Jan-01 01:01 res/drawable-hdpi-v4/abc_textfield_activated_mtrl_alpha.9.png
│  -rw----     0.0 fat     1824 b- defN 81-Jan-01 01:01 res/layout/notification_template_big_media_narrow.xml
│  -rw----     0.0 fat      106 b- stor 81-Jan-01 01:01 res/drawable-xxxhdpi-v4/exo_ic_fullscreen_exit.png
│  -rw----     0.0 fat      360 b- defN 81-Jan-01 01:01 res/xml/standalone_badge_offset.xml
│  -rw----     0.0 fat      516 b- defN 81-Jan-01 01:01 res/drawable/abc_seekbar_tick_mark_material.xml
│  -rw----     0.0 fat     4384 b- defN 81-Jan-01 01:01 res/xml/video_audio_settings.xml
│  -rw----     0.0 fat      212 b- stor 81-Jan-01 01:01 res/drawable-hdpi-v4/notification_bg_normal.9.png
│ --rw----     2.0 fat   166112 b- defN 81-Jan-01 01:01 META-INF/SCHABI_K.SF
│ --rw----     2.0 fat     1187 b- defN 81-Jan-01 01:01 META-INF/SCHABI_K.RSA
│ +-rw----     2.0 fat   166112 b- defN 81-Jan-01 01:01 META-INF/EE8807D2.SF
│ +-rw----     2.0 fat     1334 b- defN 81-Jan-01 01:01 META-INF/EE8807D2.RSA
│  -rw----     2.0 fat   165985 b- defN 81-Jan-01 01:01 META-INF/MANIFEST.MF
│ -1438 files, 14878729 bytes uncompressed, 8633241 bytes compressed:  42.0%
│ +1438 files, 14878876 bytes uncompressed, 8633255 bytes compressed:  42.0%
├── classes2.dex
│ ├── classes2.jar
│ │ ├── zipinfo -v {}
│ │ │ @@ -3024,15 +3024,15 @@
│ │ │    version of encoding software:                   2.0
│ │ │    minimum file system compatibility required:     MS-DOS, OS/2 or NT FAT
│ │ │    minimum software version required to extract:   2.0
│ │ │    compression method:                             none (stored)
│ │ │    file security status:                           not encrypted
│ │ │    extended local header:                          no
│ │ │    file last modified on (DOS date/time):          1980 Jan 1 00:00:00
│ │ │ -  32-bit CRC value (hex):                         6608aac0
│ │ │ +  32-bit CRC value (hex):                         2ce3d6ec
│ │ │    compressed size:                                1704 bytes
│ │ │    uncompressed size:                              1704 bytes
│ │ │    length of filename:                             28 characters
│ │ │    length of extra field:                          0 bytes
│ │ │    length of file comment:                         0 characters
│ │ │    disk number on which file begins:               disk 1
│ │ │    apparent file type:                             binary
│ │ ├── j$/util/Collection$-EL.class
│ │ │ ├── procyon -ec {}
│ │ │ │ @@ -1,14 +1,14 @@
│ │ │ │  
│ │ │ │  package j$.util;
│ │ │ │  
│ │ │ │  import j$.util.stream.Stream;
│ │ │ │  import j$.util.function.Predicate;
│ │ │ │ -import java.util.List;
│ │ │ │  import java.util.Set;
│ │ │ │ +import java.util.List;
│ │ │ │  import java.util.SortedSet;
│ │ │ │  import java.util.LinkedHashSet;
│ │ │ │  import java.util.Iterator;
│ │ │ │  import java.util.Objects;
│ │ │ │  import j$.util.function.Consumer;
│ │ │ │  import java.util.Collection;
│ │ │ │  
│ │ │ │ @@ -33,16 +33,16 @@
│ │ │ │          if (collection instanceof LinkedHashSet) {
│ │ │ │              return w.m((Collection)(LinkedHashSet)collection, 17);
│ │ │ │          }
│ │ │ │          if (collection instanceof SortedSet) {
│ │ │ │              final SortedSet set = (SortedSet)collection;
│ │ │ │              return (Spliterator)new v(set, (Collection)set, 21);
│ │ │ │          }
│ │ │ │ -        if (collection instanceof Set) {
│ │ │ │ -            return Set$-CC.$default$spliterator((Set)(SortedSet)collection);
│ │ │ │ -        }
│ │ │ │          if (collection instanceof List) {
│ │ │ │              return List$-CC.$default$spliterator((List)collection);
│ │ │ │          }
│ │ │ │ +        if (collection instanceof Set) {
│ │ │ │ +            return Set$-CC.$default$spliterator((Set)(SortedSet)collection);
│ │ │ │ +        }
│ │ │ │          return Collection$-CC.$default$spliterator(collection);
│ │ │ │      }
│ │ │ │  }
├── original/META-INF/MANIFEST.MF
│ @@ -217,15 +217,15 @@
│  Name: assets/mpl2.html
│  SHA-256-Digest: iPab3imJW9Oh7oo7DAHIVYhGvM1I/iIteLPlxsLK7IA=
│  
│  Name: classes.dex
│  SHA-256-Digest: 5WQQ5NRR4pSehErw5UNwC37Z6yaIwm6dUtmSzJ0ttZM=
│  
│  Name: classes2.dex
│ -SHA-256-Digest: vSB9FF9aTkw7iyZ/4V0EqWMiG0ffS4Od2x6OeXHgzcE=
│ +SHA-256-Digest: RndUCOiBahWYKoC8EdGgkUFPUR+sIfGyPBni0e6NSYI=
│  
│  Name: icepick/Bundler.java
│  SHA-256-Digest: /CpGZxU8bJLUhTWFDvrD6Ubdl7FQAcjXQ4HwVQRH45k=
│  
│  Name: icepick/Icepick.java
│  SHA-256-Digest: YxL+Da05WHp50ET+GaCfRsvo24Vb82O8yBWbbbTWtN8=
├── smali_classes2/j$/util/Collection$-EL.smali
│┄ Ordering differences only
│ @@ -91,34 +91,34 @@
│  
│      invoke-direct {v0, p0, p0, v1}, Lj$/util/v;-><init>(Ljava/util/SortedSet;Ljava/util/Collection;I)V
│  
│      return-object v0
│  
│      .line 4
│      :cond_2
│ -    instance-of v0, p0, Ljava/util/Set;
│ +    instance-of v0, p0, Ljava/util/List;
│  
│      if-eqz v0, :cond_3
│  
│ -    check-cast p0, Ljava/util/Set;
│ +    check-cast p0, Ljava/util/List;
│  
│ -    invoke-static {p0}, Lj$/util/Set$-CC;->$default$spliterator(Ljava/util/Set;)Lj$/util/Spliterator;
│ +    invoke-static {p0}, Lj$/util/List$-CC;->$default$spliterator(Ljava/util/List;)Lj$/util/Spliterator;
│  
│      move-result-object p0
│  
│      return-object p0
│  
│      :cond_3
│ -    instance-of v0, p0, Ljava/util/List;
│ +    instance-of v0, p0, Ljava/util/Set;
│  
│      if-eqz v0, :cond_4
│  
│ -    check-cast p0, Ljava/util/List;
│ +    check-cast p0, Ljava/util/Set;
│  
│ -    invoke-static {p0}, Lj$/util/List$-CC;->$default$spliterator(Ljava/util/List;)Lj$/util/Spliterator;
│ +    invoke-static {p0}, Lj$/util/Set$-CC;->$default$spliterator(Ljava/util/Set;)Lj$/util/Spliterator;
│  
│      move-result-object p0
│  
│      return-object p0
│  
│      :cond_4
│      invoke-static {p0}, Lj$/util/Collection$-CC;->$default$spliterator(Ljava/util/Collection;)Lj$/util/Spliterator;
│   --- original/META-INF/SCHABI_K.SF
├── +++ original/META-INF/EE8807D2.SF
│┄ Files 0% similar despite different names
│ @@ -1,10 +1,10 @@
│  Signature-Version: 1.0
│  Created-By: 1.0 (Android)
│ -SHA-256-Digest-Manifest: v84EC0vUrqI92WWNlzvCDyzKBpRViJBa+1ANFUj3N1A=
│ +SHA-256-Digest-Manifest: jbpSSD1njen1Cd7aLsGllyyJnQm5fUXo/AXzUAVgKvo=
│  X-Android-APK-Signed: 2, 3
│  
│  Name: AndroidManifest.xml
│  SHA-256-Digest: YtCQDh3t22jNAHVEF2NdaHZaQQXjmFXz3vrlsVwz5zY=
│  
│  Name: META-INF/CHANGES
│  SHA-256-Digest: LZASpfoSLdLbuVdC6w+hzvq04iMCTYYZavDj5G/cQw0=
│ @@ -220,15 +220,15 @@
│  Name: assets/mpl2.html
│  SHA-256-Digest: XL4KAvbh+E+7aLFiSCQfL8ePvML7GrrJdeHTneISqQ0=
│  
│  Name: classes.dex
│  SHA-256-Digest: 9D36aPSLr9vuEqWg/izmbo+vuX3tpkzOX06IbrxuiX0=
│  
│  Name: classes2.dex
│ -SHA-256-Digest: SR2GclUxR2ti2Fm1HWB+hl17NxodXhyO9uraAab4nUE=
│ +SHA-256-Digest: NHRGCjGDHWl55ZrMs6hopXK4YNYq7lyPaEeVjylO8AA=
│  
│  Name: icepick/Bundler.java
│  SHA-256-Digest: 9DRM1Vta36bnfE+4a7Ux385cxv/nW8Lw1KrGoi9bf4I=
│  
│  Name: icepick/Icepick.java
│  SHA-256-Digest: gskitOskS7dphCVTFTv+FRC2+3Dknet5ruDcAsxKQBk=
```

</details>

cc @eighthave

---

- [x] I am using the latest version - 0.21.4
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] I have read the contribution guidelines.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### PR DESCRIPTION
**Pull request by Stypox**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [x] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
We want to have reproducible builds on F-Droid so that they can ship our own APK signed with our keys, which would prevent some uninstalling and reinstalling when users switch sources.
All credits for the fix go to @obfusk, also see https://issuetracker.google.com/issues/231837768. It has been confirmed that this works [here](https://github.com/TeamNewPipe/NewPipe/issues/6486#issuecomment-1398748847).

#### Fixes the following issue(s)

- Closes #6486

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by TobiGr — APPROVED** [review]
Great! I don't have time to check this, but I you guys found a fix, I am more than happy!

**Comment by obfusk** [comment]
I'm fairly confident the fix works correctly as it simply reuses the relevant AGP code (and I've tested it works).

I can't guarantee it won't break if something changes in AGP though.

And it's a bit ugly since it uses some kotlin functions/variables marked `internal` (which the JVM doesn't enforce, so I can).

I'm also not that familiar with groovy, so the code could probably be written more idiomatically.

**Comment by Stypox** [comment]
He posted the fix in the Google issue tracker: https://issuetracker.google.com/issues/231837768

**Comment by obfusk** [comment]
> @obfusk Are the Reproducible Builds people aware of this?

We are ;p

**Comment by obfusk** [comment]
> He posted the fix in the Google issue tracker: https://issuetracker.google.com/issues/231837768

I posted my workaround there and told them exactly what & where the problem in the AGP code is.
So it should be trivial to fix now. Hopefully they'll do that soon.

Also: who's "he"? If you meant me, I use "they"(/them) :)

**Comment by obfusk** [comment]
> So it should be trivial to fix now. Hopefully they'll do that soon.

They [fixed it](https://android.googlesource.com/platform/tools/base/+/2f2c6b30b55e18e2672edf5ee8e8e583be759d3e).

Not sure when it'll be part of a new AGP release; that'll take a while longer I expect.

**Comment by Stypox** [comment]
Sorry about the "He", I sometimes forget to use "They" for people I don't know ;-)

**Comment by obfusk** [comment]
> Not sure when it'll be part of a new AGP release; that'll take a while longer I expect.

The `.profm` fix will be in AGP `8.1.0-alpha03`; so I guess we'll probably need the workaround for a while.

**Pull request merged**
