### PR TITLE
Remove icon duplicates and fix some theming issues

### PR DESCRIPTION
**Pull request by mauriciocolli**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

Some icons are not consistently themed (it affects the other pull request #7516):

<table><tr>
  <td>Drawing</td>
  <td>Drawing</td>
</tr></table>

---

- Remove unnecessary duplicates of some icons, as it is a bad practice that leads to mistakes. As vectors are used, color resources are available.
  - [The documentation recommends the `?colorControlNormal` attribute.](https://developer.android.com/guide/topics/ui/look-and-feel/darktheme#themes-styles) It's the default value when creating a new vector drawable.
  I chose the night-qualified resources route to stay consistent with current behavior. Do share your thoughts on this.
  - Take a look at the "live tv" icon, [it was left at the default value (`?colorControlNormal`)](https://github.com/TeamNewPipe/NewPipe/blob/ad405d9e0b63ac96949953f9fca0c125ee35f3c4/app/src/main/res/drawable/ic_live_tv.xml#L2), so it's already using the attribute and its color is different than the rest.
- Use menu resources instead of manually creating it, let the system do its job and get the correct resources.
  - Some menu items were not themed properly because the toolbar itself had a custom theme overriding some values.

---

Now only some drawables are different in behavior than the rest of the `ic_` prefixed icons:
- The heart icon.
- Headphone with shadow.
- Play with shadow.

Do you think they should be renamed to something else to make it consistent?

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Stypox** [comment]
Woah, the APK size is reduced by 300kb :-D
Great work, I will review and give feedback soon. I tried other times, too, but never found out how to properly style icons on Android without creating duplicates everywhere or having to write Java code for each icon. Just one thing: does this work well in all situations on API 19 too?

**Comment by mauriciocolli** [comment]
> Just one thing: does this work well in all situations on API 19 too?

I think so, the app is currently using the support library for vectors and [the proper build configuration is already set](https://github.com/TeamNewPipe/NewPipe/blob/ad405d9e0b63ac96949953f9fca0c125ee35f3c4/app/build.gradle#L26). 

Also, the test icon preview in the original post was working in every API I tested (19,23,26,28,30,31,32-preview). Both using it in layouts (normal layouts, menu, drawer) and getting the drawable with `AppCompatResources.getDrawable`.

I think that should cover all uses, right?

**Comment by litetex** [comment]
@mauriciocolli 
How did you get the view with all icons? (in the PR-description)

**Review by litetex — APPROVED** [review]
LGTM
Tested it in my emulator (Android 11) and didn't saw any specific problems.

**Review by Stypox — CHANGES_REQUESTED** [review]
Code looks good. I could only find one issue after testing anything that came to my mind in both white and dark theme on API 19:
- on white theme the icon on top of local and remote playlist items is black instead of white image

**Comment by TacoTheDank** [comment]
This is fantastic work. Thanks so much! 💟

**Comment by litetex** [comment]
Note: This PR might be affected by #7577 and vice versa.

**Comment by Stypox** [comment]
I pushed a commit that fixes the issue I reported above

**Review by Stypox — APPROVED** [review]
I rebased and pushed a commit that fixes the issue I reported above. I tested again various miscellaneous things on API 19, on API 22, and on my API 29 phone, and I found no issue. Ready for merge in my opinion.

**Pull request merged**
