### PR TITLE
add header/footer to drawer

### PR DESCRIPTION
**Pull request by theScrabi**
add header and footer do drawer, so it looks and behaves more advanced:
screenshot_20180216-141359 screenshot_20180216-141428

### CODE REVIEW

**Comment by speednroll** [comment]
wow, it looks great!!!

**Comment by theScrabi** [comment]
Thank you :)

**Comment by wb9688** [comment]
Is there a point of that empty header?

**Comment by theScrabi** [comment]
I dind't know what to put there yet.

**Comment by speednroll** [comment]
a good logo of Newpipe, also could make it become a button, by pressing the logo you send to the button "about"

**Comment by justanidea** [comment]
For what the download button is ?

**Comment by TobiGr** [comment]
The download button should open the download page where all your downloads are listed.

**Comment by wb9688** [comment]
I just noticed there's no about button.

Btw nice PR number ;)

**Comment by TobiGr** [comment]
> I just noticed there's no about button.

The [idea](https://github.com/TeamNewPipe/NewPipe/issues/650#issuecomment-326998318) was to put it in the settings.

**Comment by theScrabi** [comment]
The button for the about page should be moved into the main settings page in my opinion.

**Comment by theScrabi** [comment]
@TobiGr dou you still have the teamplate of the new Website backgroud. We could make thos greay boxes a png with alpha value so this image can adapt to the color, than it can be used as a backgroud for the header.

**Comment by theScrabi** [comment]
Full header will come in next PR.

**Comment by TobiGr** [comment]
Great idea. Give me some time and I'll generate you the png file. Btw. can you add the SVG of the beta logo to this or the website repository?

**Comment by theScrabi** [comment]
@TobiGr I might already have something.

**Comment by theScrabi** [comment]
This background is something a friend of mine create some time ago. She intended it to be the background for the website however it was not used yet.

screenshot_20180216-235651

**Comment by speednroll** [comment]
I like it! Hey, I have an idea and if they make that of the pipes that are behind change the plot according to the service? I mean they change direction.
only as an extra ornament (?

**Comment by theScrabi** [comment]
Good fun implementing such xD

**Pull request merged**
