### PR TITLE
Convert SubscriptionEntity to a data class.

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Convert `SubscriptionEntity` to a Kotlin data class, and make some of the properties immutable.
- Make use of the Kotlin data class's `copy` method to create new subscription entities.

#### Fixes the following issue(s)

- Fixes #

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TacoTheDank** [comment]
I think you could squash the commits together.

**Comment by Stypox** [comment]
What are the differences? Why is this an improvement? Also here many unrelated changes that make reviewing harder.

**Comment by Isira-Seneviratne** [comment]
> What are the differences? Why is this an improvement?

It removes the need to define the equals and hash code methods separately.

**Comment by Stypox** [comment]
Mmmh, converting classes from Java to Kotlin usually doesn't require database changes. I might be able to understand it by reading the code and checking out Room and Kotlin docs, but since you have already done so please explain it in the PR description. I am sorry, but I am closing this for three reasons, even though I would approve this PR if it just was described better:
- many unrelated changes
- PRs just to convert from Java to Kotlin, unless for a good reason, are currently [not allowed by Contribution Guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md#kotlin-in-newpipe)
- changes are not explained well

**Pull request closed without merging**
