### PR TITLE
remove Bountysource from readme

### PR DESCRIPTION
**Pull request by TobiGr**
- [x] I carefully reed the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
We don't provide any information about BountySource on our website, so we shouldn't promote it here either.

### CODE REVIEW

**Comment by theScrabi** [comment]
Well I forgot to mention it, i became Admin of our bountysource page two days ago. So they seem to do something. I'll take care of that thing later.

**Comment by TobiGr** [comment]
That is good to know. Please tell me when our BountySource site is set up correctly so I can then publish more information about it on our website.

**Comment by theScrabi** [comment]
All right :)

**Comment by wb9688** [comment]
I just got a mail from Bountysource

**Comment by TobiGr** [comment]
I got this mail too.

**Pull request closed without merging**
