### PR TITLE
Optimize svg assets

### PR DESCRIPTION
**Pull request by RiedleroD**
I wanted to finish optimizing all of them before opening the PR but I think that's not happening anymore. As far as I can see, none of those SVGs are actually directly used inside the app. Otherwise, this would probably be a significant performance improvement. So this PR really only saves about 60KiB when downloading the repo and not much else. Maybe next time someone wants to change some of those icons it'll be easier because they're less messy. idk.

I'll probably optimize some of the worse xml files that actually get used some other time and open another PR.

#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [x] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
- optimized svg files in various ways

#### APK testing
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Profpatsch** [comment]
The github preview shows that all optimized svgs now have a size of 0x0px, e.g.:
 
image

I feel like this might lead to problems if some code implicitly depends on these default height/widths?

**Comment by RiedleroD** [comment]
huh, will look into it in a month or so. Currently absolutely swamped with work from my thesis, diploma project & finals  😓

**Comment by Profpatsch** [comment]
@RiedleroD I’d close this PR for now, given that we only save about 60k and haven’t really checked whether everything still works as expected … I’d rather focus on the UI rewrite for now.

But feel free to open a separate one (and link this discussion) if you ever get around to it again!

**Comment by RiedleroD** [comment]
yeah fair point. I don't think I'll be revisiting this anytime soon though, there's just too much to do 😓

**Comment by Profpatsch** [comment]
No worries! Thanks for giving it a shot!

**Pull request closed without merging**
