### PR TITLE
Display meta info about search query, stream creator or topic

### LINKED ISSUE #4614: Display YouTube's "fake news" warnings and infoboxes
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
NewPipe should display YouTube's "Fake News" warnings, for example when the video is about Corona and YouTube links to legit information from the WHO. And when a YouTube channel belongs to a public broadcast service there's also an info box NewPipe should display too.

YouTube infocards

#### How will you/everyone benefit from this feature?
NewPipe users will also be able to identify misleading contents, fake news and propaganda and to get legit facts about the respective topic.

### PR DESCRIPTION
**Pull request by TobiGr**
#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
Add support for displaying stream and search query meta info. Can be disabled in the content settings.

#### Fixes the following issue(s)
Closes #4614

#### Relies on the following changes
TeamNewPipe/NewPipeExtractor#451

#### APK testing 
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5698843/app-debug.zip)

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by opusforlife2** [comment]
What happened to the code which would automatically name zips and the included apks according to the branch name?

**Comment by opusforlife2** [comment]
The Learn More link for COVID-19 takes you to https://webcache.googleusercontent.com/search?q=cache:< your health ministry website here >

Do we really want users to use this link?

**Comment by TobiGr** [comment]
Webcache URL is not used anymore and links to non-google information are shown.

**Comment by Stypox** [comment]
Improved layout @TobiGr @B0pol [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5721016/app-debug.zip)

**Comment by TobiGr** [comment]
Code changes look perfect. So do the UI changes.

**Review by Stypox — APPROVED** [review]
I think you can also merge this

**Pull request merged**
