### PR TITLE
Migrate AboutActivity to ViewPager2

### PR DESCRIPTION
**Pull request by TacoTheDank**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
- Migrates AboutActivity to viewpager2, the first (and hands-down the easiest) of the viewpager trio (the others being MainFragment and VideoDetailFragment (oh god no), respectively). Whoever dares migrate the next two, may the odds be ever in your favor.

#### Fixes the following issue(s)

- Nothing, and if we're lucky, doesn't create any either

#### APK testing 
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5396845/app-debug.zip)

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by opusforlife2** [comment]
> Whoever dares migrate the next two, may the odds be ever in your favor.

xD

**Comment by TacoTheDank** [comment]
If you want https://github.com/TeamNewPipe/NewPipe/pull/3697 to be done first, this could be merged to a separate branch for viewpager2 and saved until after viewbinding is done (though at the rate it seems to be going, might not be until 2023).

**Review by Stypox — APPROVED** [review]
Thank you for improving the code base! This looks good and works correctly: I tested playing with tabs and licenses on emulated Android 4.4 and Android 10, and on device Android 7.0.

> If you want #3697 to be done first, this could be merged to a separate branch for viewpager2 and saved until after viewbinding is done

No, I tested this now and it works now, so I'd merge it right away. @wb9688 can I?

> (though at the rate it seems to be going, might not be until 2023).

Yeah, that's also something ;-)

**Comment by wb9688** [comment]
Code looks OK. Did you test on Android 4.4 and 11?

**Comment by opusforlife2** [comment]
Can I merge? :3

**Comment by Stypox** [comment]
@opusforlife2 yes ;-)

**Comment by TacoTheDank** [comment]
Wonderful, thanks!

**Pull request merged**
