### PR TITLE
Sonar workflow

### LINKED ISSUE #5825: [SonarQube] Add workflow file for analysis and adjust gradle file
Make adjustments to repo according to setup guide of sonarcloud.

https://sonarcloud.io/project/configuration?analysisMode=GitHubActions&id=TeamNewPipe_NewPipe

### PR DESCRIPTION
**Pull request by TobiGr**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [x] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Add sonar plugin and github actions file for sonar analysis
- Copied from sonarcloud.io setup page with minor adjustments. Adjusted branch to 'dev' and updated versions

#### Fixes the following issue(s)

- closes #5825 

#### Relies on the following changes

- #5822 This needs to be done beforehand

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TobiGr** [comment]
I don't understand the result, but maybe that needs to be configured first. @XiangRongLin

**Comment by XiangRongLin** [comment]
For PRs it should only show results for files that were changed. So since no code was changes, it shows that everything is perfect

**Comment by TobiGr** [comment]
The checkstyle changes work for JDK 8, so this should be good to merge.

**Comment by XiangRongLin** [comment]
@TobiGr see the initial post. another thing needs to be done first

**Review by XiangRongLin — APPROVED** [review]

**Pull request merged**
