### PR TITLE
Replace AsyncTask implementations with coroutines.

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
#### What is it?
- [ ] Bug fix (user facing)
- [ ] Feature (user facing)
- [x] Code base improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Rewrite implementations of `AsyncTask` as Kotlin suspend functions, as [`AsyncTask`](https://developer.android.com/reference/android/os/AsyncTask) has been deprecated starting with API level 30.

#### Testing apk

[debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5361240/debug.zip)

#### Agreement
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by Stypox** [comment]
Thank you! Why coroutines and not ReactiveX? That would prevent us form adding three more libraries

**Comment by Isira-Seneviratne** [comment]
> Thank you! Why coroutines and not ReactiveX? That would prevent us form adding three more libraries

I'm a bit more familiar with coroutines than ReactiveX.

Should I use ReactiveX instead?

**Comment by Stypox** [comment]
I'd prefer that, if it does not create problems

**Comment by wb9688** [comment]
You should definitely use ReactiveX in NewPipe, yeah.

I don't know how good it is to change anything in the GigaGet though.

**Pull request closed without merging**
