### PR TITLE
Long links now work correctly.

### PR DESCRIPTION
**Pull request by Somethingweirdhere**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

#1390 This should now be fixed.

### CODE REVIEW

**Comment by theScrabi** [comment]
Uff, could be done, but you try to get everything by hand. Take a look at the backend, i recently added a Utill with which you can detect liks in a string.

**Comment by Somethingweirdhere** [comment]
@theScrabi I did, but for https://www.youtube.com/watch?v=6UcGyTD8twE I get 11 Links and the longer one is again shortened. Using `URLDecoder.decode` on the whole String before trying this will return the whole href but I would still need to cut the unwanted parts of href by hand.

Additionally there doesn't seem to be an easy way to replace the links back in an easy way.

image

**Comment by theScrabi** [comment]
Hm the thing is that string parsing should be part of the back end, so it makes sense to do semtheing there. I'll think about what.

**Comment by Somethingweirdhere** [comment]
@theScrabi Alright, great!

**Comment by theScrabi** [comment]
Here you go. By Overriding this methode for the YoutubeStreamExtractor you should be able to set the links specialized for youtube:
https://github.com/TeamNewPipe/NewPipeExtractor/pull/85/files#diff-d2e57174c082b2ead102d53de59728baR147

**Comment by theScrabi** [comment]
Maybe you should think about rewriting the 'getDescription()' function so the links get replaced directly in the actual description.

**Comment by theScrabi** [comment]
I think here is what you would want to do. Fix the links in the description html when it gets returned here:
https://github.com/TeamNewPipe/NewPipeExtractor/blob/master/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamExtractor.java#L151

**Comment by Somethingweirdhere** [comment]
https://github.com/TeamNewPipe/NewPipeExtractor/pull/86

Here you go.

Both requests need to be merged for this to work.

**Comment by theScrabi** [comment]
@Somethingweirdhere what effect does it have to remove the autolinkify line?

**Comment by theScrabi** [comment]
lets reopen this once backend is fixed :)

**Comment by Somethingweirdhere** [comment]
@theScrabi alright, but I am not at home for the next month or so, I will take a look at it when Im back and have a PC again :)

**Comment by theScrabi** [comment]
Ok :)

**Comment by Somethingweirdhere** [comment]
@theScrabi Alright, taking a look at backend. The autolinkify makes it so that if there is a link in the text, it is clickable and goes to where the link says. But we don't want that because it overwrites long links (these are invisible) with the shorter one (that is in the text but not complete).

**Comment by theScrabi** [comment]
:) understood.

**Pull request closed without merging**
