### PR TITLE
added top padding for comments and related videos

### PR DESCRIPTION
**Pull request by yausername**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

closes https://github.com/TeamNewPipe/NewPipe/issues/2146 ?

### CODE REVIEW

**Comment by yausername** [comment]
new1 old1

**Comment by gkeegan** [comment]
👏Meme Review👏

Jokes aside, this looks like it fixes it for phone. How about for tablets, as that was part of that issue as well?

**Comment by yausername** [comment]
Hi, fellow 9 year old.
This should work for tablet as well.
I tested on emulator.

**Comment by theScrabi** [comment]
@yausername does is part :D

**Pull request merged**
