### PR TITLE
Two finger to close player gesture

### LINKED ISSUE #4469: 2 finger swipe to close player
### Checklist

- [x] I checked, but didn't find any duplicates of this issue in the repo.
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

It would be nice if it's possible to swipe down with 2 fingers on the player in order to close it, like you could currently do by swiping down twice. In e.g. Android's notification bar, you could also swipe down with 2 fingers to do the same action as swiping down twice, so I think this gesture would make sense.

#### Is your feature request related to a problem? Please describe it

I usually don't want to have the bottom sheet, so I currently have to swipe twice, which is annoying, especially as the bottom sheet is a relatively (compared to the full player) small area that's on the, so it's harder to swipe at.

### PR DESCRIPTION
**Pull request by vkay94**
#### What is it?
- [ ] Bug fix (user facing)
- [x] Feature (user facing)
- [ ] Code base improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

This PR adds a 2-finger-touch gesture to the `CustomBottomSheetBehavior` to dismiss/close the player when the player is pulled down with two fingers.

#### Fixes the following issue(s)

- closes #4469 

#### Testing apk

[app-debug-two-finger-close-player.zip](https://github.com/TeamNewPipe/NewPipe/files/5358993/app-debug-two-finger-close-player.zip)

#### Agreement
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Review by Stypox — APPROVED** [review]
Code looks good, it works as expected, and I agree with #4469
@avently can you confirm this is the correct implementation?
Thank you!

**Comment by avently** [comment]
@Stypox it can be written like this:
```java
setSkipCollapsed(event.getPointerCount() == 2);
if (event.getPointerCount() == 2) {
return super.onInterceptTouchEvent(parent, child, event);
}

``` 
Just something with less code. Other than that looks ok for me.

**Comment by vkay94** [comment]
Okay, I've simplified the code snippet.

**Review by Stypox — APPROVED** [review]

**Comment by Stypox** [comment]
Thank you @vkay94 @avently :-D

**Pull request merged**
