### PR TITLE
Apply theme to switches

### LINKED ISSUE #3254: Autoplay switch highlight color
The autoplay switch shows up in the same color regardless whether it is on or off. This makes it difficult to tell what's its current state is.

It would be nice to highlight the switch with color when it is turned on.

### PR DESCRIPTION
**Pull request by TobiGr**
#### What is it?
- [x] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
- Added v21 theme for Bandcamp fixing some night theme related color issues
- Applied `primaryColor` as active color to switches

#### Fixes the following issue(s)

- Fixes #3254
- Replaces / Closes #4162 

#### Screenshots

Screenshot_1623176089 Screenshot_1623176073 Screenshot_1623176117 
#### APK testing 

On the website the APK can be found by going to the "Checks" tab below the title and then on "artifacts" on the right.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TobiGr** [comment]
One thing, we need to decide on:
Using `androidx.appcompat.widget.SwitchCompat` or `Switch` in `related_items_lheader.xml` (the switch seen in the screenshots).
Using `SwitchCompat` results in a material styles switch, `switch` results in a _well themed_, but not material toggle on KitKat.

**Review by Stypox — COMMENTED** [review]
Uhm, ok, I tried everything this afternoon and nothing worked... Great that you could find out how!

**Comment by Stypox** [comment]
I'd go with `SwitchCompat`, what are its downsides? Wouldn't it also be _well themed_?

**Comment by TobiGr** [comment]
No, because the `android:colorControlActivated` attribute was added with API 21

**Comment by peat80** [comment]
Could the seekbar also themed with the color of the service in use? Would look even better. 🤔

(For example, in the above bandcamp screenshot it should be blue).

**Comment by Stypox** [comment]
@TobiGr I think I solved the problem. The first commit I added makes the switch well-themed everywhere (tested with multiple services on API 19 and Android 10). I also added a commit converting RelativeLayout to ConstraintLayout.

**Comment by TobiGr** [comment]
Looks good to me!

**Comment by TobiGr** [comment]
@Stypox Can you approve this PR?

**Review by Stypox — APPROVED** [review]

**Comment by litetex** [comment]
I stumbled upon a few problems when checking using the ``dev``-branch. 
I think they are related to this issue.

Was this supposed to be only added to switches?
Because now also e.g. progress-bars are also colored:
grafik

The above thing is not a big problem however the following is one:
grafik
grafik
grafik

Looks like the - I don't know what its called correctly - cursor on the keyboard also uses that color and therefore goes missing.

**Comment by Stypox** [comment]
The first thing is expected, the second should be solved

**Pull request merged**
