### PR TITLE
Enable SoundCloud kiosks as main page fragment for debug and beta

### LINKED ISSUE #1107: NewPipe Beta 0.11.6
SoundCloud trends are the same as YouTube trends :/

### PR DESCRIPTION
**Pull request by TobiGr**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

Closes #1107

### CODE REVIEW

**Comment by wb9688** [comment]
I'd show the first kiosk of the service by default, but have some chips at
the top to switch to another kiosk of the service (and then remember the
last used kiosk). I'd then remove the kiosk menu from the menu and on the
settings page I'd just have a selection for kiosk (and not for the specific
kiosk like now).

**Comment by theScrabi** [comment]
> have some chips

I don't know. they would take away a loot of screen space. When we are done with the drawer we don't nee the three dots menu in the main screen any more. So we can dedicate them completely to the kiosk selection.

> and then remember the last used kiosk

Yes

> I'd then remove the kiosk menu from the settings page

definetly

**Comment by TobiGr** [comment]
> When we are done with the drawer we don't nee the three dots menu in the main screen any more. So we can dedicate them completely to the kiosk selection.

I agree with that.

The whole PR was meant rather as a quick fix than providing a good solution for later. So if you want to refactor the kiosk methods in the next days, feel free to do it. I don't have time for it, because I have two exams left and the website has a higher priority for me since it needs some major improvements.

**Comment by theScrabi** [comment]
> I don't have time for it, because I have two exams

I know this :D. I barely finished my exams now i actually have no time since i move to Spain in two weeks.

**Comment by TobiGr** [comment]
> PS: Good luck ;D

Thanks! Moving to Spain sounds interesting :D

**Pull request merged**
