### PR TITLE
Changed 'Video preview thumbnail' -> 'Info'

### LINKED ISSUE #7583: Accessibility: "Video preview thumbnail"
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behavior

Before the title of each subscription and each video, I hear the phrase:

"Video preview thumbnail"

### Expected behavior

The screen reader does not announce this phrase. That is, the screen reader immediately announces the name of the subscription, or the name of the video.

### Device info

 - Android version/Custom ROM version:
 
6.0

 - Device model:

Impression ImSmart-C551

### PR DESCRIPTION
**Pull request by bolshoytoster**
#### What is it?
- [ x ] Change accessibility text (user facing)

#### Description of the changes in your PR
- I've changed the accessibility description `list_thumbnail_view_description` from 'Video preview thumbnail' to 'Info'
This is discussed in #7583 

#### Fixes the following issue(s)
- Fixes #7583

#### Due diligence
- [ x ] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by litetex** [comment]
I don't think we should merge this and should close the PR.
Why? Because when there is an image where the video preview thumbnail is displayed in it should also be named "Video preview thumbnail".

**Review by litetex — CHANGES_REQUESTED** [review]
I don't think we should merge this and should close the PR.
Why? Because when there is an image where the video preview thumbnail is displayed in it should also be named "Video preview thumbnail".

**Comment by TiA4f8R** [comment]
We should probably rename this string to `Content preview thumbnail`, to better reflect support of audio streaming services in the app.

**Comment by litetex** [comment]
Superseded by #7619

**Pull request closed without merging**
