### PR TITLE
Add search field on stream history list

### PR DESCRIPTION
**Pull request by spk**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

Hi this add a search field to the history view; this allow to search for obsolete videos ; filter the list by title, cheers

screenshot_1546794457

screenshot_1546794409

### CODE REVIEW

**Comment by TobiGr** [comment]
Hey @spk, thanks for that nice addition to the history view.
Can you please align the new elements with the existing ones:
grafik

**Comment by spk** [comment]
Hi @TobiGr thanks i've tried something with 43e909809d1ca0a409e0082db5d4419c385ccf1a but i'm not sure about it (i'm new to android development), let me know if there is a better way to do that

screenshot_1547069279

**Comment by theScrabi** [comment]
Please embeded the search field into the  toolbar.

**Comment by spk** [comment]
> Please embeded the search field into the toolbar.

Done in https://github.com/spk/NewPipe/commit/c5f201de5581381f3b2d7655b4dd236201448aa5

**Comment by spk** [comment]
> Please post a screenshot.

Sure did not want to flood since the UI is the same 

screenshot_1547747464

**Comment by TobiGr** [comment]
I think, @theScrabi meant something like this. move the search button and bar into the toolbar to have a cleaner ui. Juts like it is on the main page. @theScrabi Is this correct? 
grafik

**Comment by theScrabi** [comment]
Yes

**Comment by spk** [comment]
Ok did not get that will try to do that if it get stalled feel free to close the PR

**Pull request closed without merging**
