### PR TITLE
Fix and improve setting import and export paths

### LINKED ISSUE #6397: Unable to navigate internal storage to export database
### Checklist

- [x] I am using the latest version - 0.21.3 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 

### Steps to reproduce the bug
1. Go to 'Settings, Content, Export database'
2. Allow permissions if necessary.
3. Navigate to external drive, and attempt to save.  NOTE: The default save folder has now changed, locking you out of any ability to ever navigate to a viable folder, and effectively making the database unsavable.
4. After save fails (see https://github.com/TeamNewPipe/NewPipe/issues/5198 ) attempt to navigate back to internal storage.
5. Many folders are not displayed, especially the folder(s) necessary to navigate back to a viable internal save folder.

 ##

### Device info

 - Android version/Custom ROM version: android 9 / lineage 16.
 - Device model: xt1687

### PR DESCRIPTION
**Pull request by XiangRongLin**
#### What is it?
- [x] Bugfix (user facing)

#### Description of the changes in your PR

- Set ImportExportDataPath only on successful export
- Set ImportExportDataPath only on successful import
- Commit path immediately when import backup 

#### Fixes the following issue(s)

- Fixes #6397

#### APK testing 

On the website the APK can be found by going to the "Checks" tab below the title and then on "artifacts" on the right.
https://github.com/TeamNewPipe/NewPipe/suites/2872990922/artifacts/64206682

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by TobiGr — COMMENTED** [review]
LGTM
One small thing: please annotate the parameters as `@Nonnull`

**Comment by mhmdanas** [comment]
@cubetronic could you please test this PR?

**Comment by XiangRongLin** [comment]
> 
> One small thing: please annotate the parameters as `@Nonnull`

Done

**Comment by Redirion** [comment]
could we take the opportunity and replace the System.exit calls with getActivity.finishAffinity() and launch of the main activity?

so 

`System.exit(0);`

to

`getActivity().finishAffinity();
getActivity().getPackageManager().getLaunchIntentForPackage(getActivity().getPackageName());`

**Comment by XiangRongLin** [comment]
> 
> 
> could we take the opportunity and replace the System.exit calls with getActivity.finishAffinity() and launch of the main activity?


@Redirion I don't see a reason for why it would NEED to be done here together. Since you already know what those methods do, you could open a seperate PR for that.

**Review by TobiGr — APPROVED** [review]

**Pull request merged**
