### PR TITLE
Playback positions in lists

### PR DESCRIPTION
**Pull request by nv95**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

Implementation of displaying playback progress in lists

| Screenshot_2019-04-15-22-25-20 | Screenshot_2019-04-15-22-25-54 |
|---|---|

Code based on #2286 ~~and is not ready for release yet~~

### CODE REVIEW

**Comment by TobiGr** [comment]
@nv95 can you please resolve the conflicts? I don't speak Ukrainian:)

**Comment by nv95** [comment]
@TobiGr ok

**Comment by nv95** [comment]
Sorry for delay

**Comment by Stypox** [comment]
I'm trying to fix conflicts for #2368 and I don't understand what `resumePlayback`'s value should be in `playOn..Player` and `enqueueOn..Player` [functions](https://github.com/nv95/NewPipe/blob/2a41802f36aae3ac983e44161df3ae362387d4b7/app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java#L120-L124). (especially when they are used in the long-press menu)
I see you are using it differently in `showStreamDialog()`s:
- [In `BaseListFragment`](https://github.com/nv95/NewPipe/blob/2a41802f36aae3ac983e44161df3ae362387d4b7/app/src/main/java/org/schabi/newpipe/fragments/list/BaseListFragment.java#L276-L284) it is always `true`
- [In `StatisticsPlaylistFragment`](https://github.com/nv95/NewPipe/blob/2a41802f36aae3ac983e44161df3ae362387d4b7/app/src/main/java/org/schabi/newpipe/local/history/StatisticsPlaylistFragment.java#L379-L393), [in `ChannelFragment`](https://github.com/nv95/NewPipe/blob/2a41802f36aae3ac983e44161df3ae362387d4b7/app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java#L173-L186), [in `PlaylistFragment`](https://github.com/nv95/NewPipe/blob/2a41802f36aae3ac983e44161df3ae362387d4b7/app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java#L156-L170) and [in `LocalPlaylistFragment`](https://github.com/nv95/NewPipe/blob/2a41802f36aae3ac983e44161df3ae362387d4b7/app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java#L535-L551) it is `false` for enqueue actions, `true` otherwise

In the long-press menu I assume `resumePlayback` should be `false` for enqueue actions and `true` otherwise. I also assume in `BaseListFragment` it is always `true` due to an oversight, since overriding classes don't do that. Can you confirm?
If my second assumption is true, I will fix the oversight in #2368

**Pull request merged**
