### PR TITLE
Handle intents for youtube streams in "vnd.youtube:videoId" format

### LINKED ISSUE #3091: java.net.MalformedURLException: unknown protocol: vnd.youtube
If i click a YouTube link or thumbnail in an app like FeedMe or other RSS reader, NewPipe starts but crashes instantly with the error "org.schabi.newpipe.extractor.exceptions.ParsingException: Malformed url: vnd.youtube:thi73589" or some similar error. If I open the same link with standard YouTube app, the right video is opened.

### PR DESCRIPTION
**Pull request by XiangRongLin**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

Closes #3091

Tested it by opening "vnd.youtube:Jb8BqYYqDMQ" in the browser and the opening it with NewPipe.

@Offerel Could you check if it works for you, since i don't have those apps you mentioned

[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4205823/app-debug.zip)

### CODE REVIEW

**Comment by TobiGr** [comment]
I think this belongs into the extractor. @Stypox What do you think?

**Comment by XiangRongLin** [comment]
I looked there first, but the LinkHandlerFactory already tries to create an URL object from it in the LinkHandlerFactory [here](https://github.com/TeamNewPipe/NewPipeExtractor/blob/dev/extractor/src/main/java/org/schabi/newpipe/extractor/linkhandler/LinkHandlerFactory.java#L47) before it even calls any methods from the YoutubeStreamLinkHandlerFactory.

And i don't think that something only related to the android front end should go into the extractor, which is supposed to be used for other frontends too. (like the web-api)

**Comment by Stypox** [comment]
This should go into the extractor, since it is something tightly related to the Youtube service, not the app implementation or platform. If one were to build a desktop app, he would need the exact same link handler, even though it is in a different environment

**Comment by Offerel** [comment]
Many thx. Indeed the debug version solves my issue.

**Pull request closed without merging**
