### PR TITLE
Update action dependencies in workflows

### PR DESCRIPTION
**Pull request by TacoTheDank**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [x] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
- https://github.com/actions/checkout/releases
- https://github.com/actions/cache/releases
- https://github.com/actions/upload-artifact/releases
- https://github.com/actions/setup-java/releases
- https://github.com/actions/setup-node/releases
- https://github.com/actions/github-script/releases

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by opusforlife2** [comment]
Does dependabot not take care of these?

**Comment by TacoTheDank** [comment]
> Does dependabot not take care of these?

We, uh... we don't use dependabot in this repo 😀

**Comment by opusforlife2** [comment]
Oh. Shouldn't we?

**Comment by TacoTheDank** [comment]
I successfully lobbied against using dependabot lol: https://github.com/TeamNewPipe/NewPipe/pull/7154

**Comment by opusforlife2** [comment]
Ah... I forgot about that. xD

**Review by litetex — APPROVED** [review]

**Pull request merged**
