### PR TITLE
Fixed Hardcoded String reference in a xml file

### PR DESCRIPTION
**Pull request by Grandolf49**
#### What is it?
- [ ] Bug fix
- [ ] Feature
- [x] Code Enhancement 

#### Long description of the changes in your PR

A hardcoded string in the **text** field for a **TextView** is changed to a strings.xml variable reference

#### Agreement
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by Grandolf49** [comment]
@Stypox Welcome!

**Comment by TobiGr** [comment]
Thank you for the contribution. But is this change necessary? The hardcoded text is like a placeholder, it is overridden in `onCreate`.

**Comment by Stypox** [comment]
I tried looking for references but couldn't find any. If the text is overridden then the attribute android:text should be removed completely and replaced by tools:text

**Comment by TobiGr** [comment]
@Stypox correct. @mauriciocolli Already did this in #3259.

@Grandolf49 Thank you again, this will be done in #3529.

**Pull request closed without merging**
