### PR TITLE
Make language of download folder setting more consistent and less ambiguous

### PR DESCRIPTION
**Pull request by opusforlife2**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by opusforlife2** [comment]
Should I just click on "Update branch" or do I need to take other actions as well?

**Comment by TobiGr** [comment]
@opusforlife2 No, you don't need to do anything. We'll wait until 0.17.3 is released and after that that I am going to merge your changes.

**Comment by opusforlife2** [comment]
Woohoo! 🥳 Thanks for the help, guys.

So now I can safely delete the forked repo, I assume?

**Comment by Stypox** [comment]
@opusforlife2 You should be safe deleting the forked repo, but I suggest that you just delete the branch `opusforlife2-patch-1` so that you don't have to re-fork the repo when you want to contribute again ;-)

**Pull request merged**
