### PR TITLE
Made the content restriction toggles dependent on each other

### LINKED ISSUE #9354: Youtube content restriction toggles should not be independent
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my question isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).-

### What is/are your question(s)?

How can i turn both restricted mode and show adult content side by side? What happens if i turn both on will it show me something interesting 🤔 (you know what i'm talking about) or maybe not see screenshot below.

Screenshot_2022-11-09-17-09-14-82_79bc5d99886106bfc3f2688bf01a61d3

### Additional information

Nothing special here

### PR DESCRIPTION
**Pull request by Marius1501**
#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
- Made the  content restriction toggles dependent of each other
- When you click on one toggle the other toggle is disabled

#### Before/After Screenshots/Screen Record
- Before:

https://user-images.githubusercontent.com/109673982/205660719-88478d83-f58a-42f2-a7c2-0589f8e566bd.mp4

- After:

https://user-images.githubusercontent.com/109673982/205659949-0ef3a250-f017-40ba-8dc4-f58581268a6c.mp4

#### Fixes the following issue(s)

- Fixes #9354 

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Marius1501** [comment]
Another solution which might be better is to merge the two toggles to one toggle. Should I make this change or leave it as it is?

**Comment by opusforlife2** [comment]
Not at all. The toggles are separate because the underlying features are separate. The current method is perfectly fine.

**Comment by opusforlife2** [comment]
No. What I mean is, that your current solution is fine. Also, you changed the PR title back to wrong grammar after I corrected it. :/

**Comment by Marius1501** [comment]
Oh ok sry! 😄

**Comment by Stypox** [comment]
Thanks and sorry for not saying something earlier. See https://github.com/TeamNewPipe/NewPipe/issues/9354#issuecomment-1368483604 for why I'm closing

**Pull request closed without merging**
