### PR TITLE
Option for download is redundant and thus removed when linkType is CH…

### LINKED ISSUE #6371: "Preferred 'Open' Action" setting should be applicable for videos only
### Checklist

- [x] I am using the latest version - 0.21.2 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

It seems like that shared URL action doesn't always work the way as expected. In reality, people share videos, channels and playlists for different reasons. However, playback options are actually quite relevant for videos.

But that's not always the case with channels or playlists. Many users share directly by long press on link without opening the link. Checkback is a necessary feature and that's one of the key reasons why long press menu was not added for unsubscribed channels and playlists. That's why, info should always be shown.

One more thing, "Video Player" and "Show Info" works exactly the same for videos. So, having both options makes no real sense.

### Actual behaviour

"Preferred 'Open' Action" setting should be applicable for videos only. "Download" option ends up giving us no output for channels and playlists.

### Expected behavior

Info should always be shown for channels and playlists.

### Device info

 - Android version/Custom ROM version:
 - Device model:

### PR DESCRIPTION
**Pull request by sauravrao637**
…ANNEL or PLAYLIST

#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- The Download button should not be included in option action choices when linkType is CHANNEL or PLAYLIST (as it will just give unsupported url ) , thus done the needed changes

#### Fixes the following issue(s)

- Fixes #6371 

#### APK testing 

On the website the APK can be found by going to the "Checks" tab below the title and then on "artifacts" on the right.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by SameenAhnaf** [comment]
Please, wait a minute. Bulk download was actually a requested feature. See: https://github.com/TeamNewPipe/NewPipe/issues/5782. It's expected that 'Download' option will work the same way.

However, https://github.com/TeamNewPipe/NewPipe/issues/6145 and https://github.com/TeamNewPipe/NewPipe/issues/5741 are requested for sorting videos within a playlist. That's why, I asked for 'Show info' option only for playlists as users may want to sort or enqueue videos according to their preferences. In fact, that's when Newpipe app will come in handy the most.

**Comment by sauravrao637** [comment]
From what I can understand, for linkType CHANNEL download is completely redundant and thus should not be shown as an option and till "bulk Download" is pending we should rely on this and when it's available we can put the option back for linkType PLAYLIST (I'll myself add back as soon as the feature is available)
And by "'Show info' option only for playlists" ,I think this should be an option for CHANNELS as well as for any STREAM, as user may only want to see say "Description" of a video
If I've misinterpreted , I would like to be further assisted with the issue :)

**Comment by SameenAhnaf** [comment]
>From what I can understand, for linkType CHANNEL download is completely redundant and thus should not be shown as an option 

Your points are quite valid and logical. So, this PR still makes sense.

>and till "bulk Download" is pending we should rely on this and when it's available we can put the option back for linkType PLAYLIST (I'll myself add back as soon as the feature is available)

Thank you so much for your help in advance.

>And by "'Show info' option only for playlists" ,I think this should be an option for CHANNELS as well as for any STREAM, as user may only want to see say "Description" of a video

Unfortunately, 'Show info' is still useless for videos. Enabling auto-play makes the video play. Disabling it doesn't do so as expected. Rather, shared videos should not be dependent on such a setting.

Show info: Don't auto-play videos
Video player: Play videos on main player

Could you please add this feature on some other PR? It would be really nice of you.

>If I've misinterpreted , I would like to be further assisted with the issue :)

It's me who should have apologized. Pardon me for my vague explanation at first. Also, thanks once again for your time and efforts.

**Review by TobiGr — APPROVED** [review]
Thank you

**Comment by sauravrao637** [comment]
@SameenAhnaf 
Thanks for being patient while explaining and also for reporting the issue 
Also feel free to open an Issue for any feature you feel can be useful

**Pull request merged**
