### PR TITLE
Fix surface view not resizing video correctly + other player fixes

### PR DESCRIPTION
**Pull request by Stypox**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
The surface view is the view that contains the playing video, on which exoplayer draws. Its height was never being initialized, leaving it to 0, so the view did not have enough information to respect the video aspect ratio (which instead was being set correctly), leading to https://github.com/TeamNewPipe/NewPipe/pull/8170#issuecomment-1191217817. The height was never being set because the code tried to set it when the surface view hadn't been initialized yet. Now the height-setup is `post`ed to a `Handler`, this way the player initialization completes (creating the surface view) and then the height is initialized.

This PR should also fix https://github.com/TeamNewPipe/NewPipe/pull/8678#issuecomment-1200483145, since now all `null` checks are done inside the lambda `post`ed to the main thread loop. See the comments.

#### Before/After Screenshots/Screen Record
<table>
  <tr>
    <th>Before</th>
    <th>After</th>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
</table>

#### Fixes the following issue(s)
Fixes https://github.com/TeamNewPipe/NewPipe/pull/8170#issuecomment-1191217817
Also fixes https://github.com/TeamNewPipe/NewPipe/pull/8678#issuecomment-1200483145

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by PJansky** [comment]
This pull request definitely fixes https://github.com/TeamNewPipe/NewPipe/pull/8170#issuecomment-1191217817, but has introduced a regression in the screen rotation animation. This regression is new to this pull and not previously seen in https://github.com/TeamNewPipe/NewPipe/pull/8170. As you can see in the videos below, the animation now has some artifacts while rotating and briefly fades to black before showing the video. As a result the animation looks choppy and the fade to black before showing the video is perceptible as an unpleasant flash.

Animation after https://github.com/TeamNewPipe/NewPipe/pull/8731:

https://user-images.githubusercontent.com/46072333/183301624-4cd3156c-e53f-4ce2-901d-2c742f8d710d.mp4


Animation before:

https://user-images.githubusercontent.com/46072333/183301620-ae89ff4f-f7f1-45a3-8c67-8d4fa8000488.mp4

**Comment by opusforlife2** [comment]
Crash. Same STR as https://github.com/TeamNewPipe/NewPipe/pull/8678#issuecomment-1207270580:

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ CH
* __Content Language:__ en-IN
* __App Language:__ en_IN
* __Service:__ none
* __Version:__ 0.23.1
* __OS:__ Linux Android 12 - 32
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalArgumentException: STATE_SETTLING should not be set externally.
	at com.google.android.material.bottomsheet.BottomSheetBehavior.setState(BottomSheetBehavior.java:1200)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.setupBottomPlayer(VideoDetailFragment.java:2285)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.initListeners(VideoDetailFragment.java:694)
	at org.schabi.newpipe.BaseFragment.onViewCreated(BaseFragment.java:68)
	at org.schabi.newpipe.fragments.BaseStateFragment.onViewCreated(BaseStateFragment.java:42)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.onViewCreated(VideoDetailFragment.java:607)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3019)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:551)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1374)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2841)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2784)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:262)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:478)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1471)
	at android.app.Activity.performStart(Activity.java:8082)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3732)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```
</details>
<hr>

**Comment by opusforlife2** [comment]
Also seeing the choppy animation PJanksy mentions above.

**Comment by opusforlife2** [comment]
Pasting a mysterious crash report here as suggested by Stypox:

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ CH
* __Content Language:__ en-IN
* __App Language:__ en_IN
* __Service:__ none
* __Version:__ 0.23.1
* __OS:__ Linux Android 12 - 32
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalArgumentException: STATE_SETTLING should not be set externally.
	at com.google.android.material.bottomsheet.BottomSheetBehavior.setState(BottomSheetBehavior.java:1200)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.setupBottomPlayer(VideoDetailFragment.java:2285)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.initListeners(VideoDetailFragment.java:694)
	at org.schabi.newpipe.BaseFragment.onViewCreated(BaseFragment.java:68)
	at org.schabi.newpipe.fragments.BaseStateFragment.onViewCreated(BaseStateFragment.java:42)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.onViewCreated(VideoDetailFragment.java:607)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3019)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:551)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1374)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2841)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2784)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:262)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:478)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1471)
	at android.app.Activity.performStart(Activity.java:8082)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3732)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```
</details>
<hr>

**Comment by Stypox** [comment]
I pushed 8b7c78522 to fix the choppy animation, can you confirm that it is fixed @PJansky @opusforlife2?

For comparison, here is a video showing the behavior before fixing (5e094ab7d763f24da3e6be5f21f72a6c9f2903d2), the behavior in v0.23.2 and the behavior after the fix (8b7c78522). I couldn't reproduce better than in the video on the left :sweat_smile:.

**Comment by Stypox** [comment]
_Originally posted by @opusforlife2 in https://github.com/TeamNewPipe/NewPipe/issues/8678#issuecomment-1207270580_

<hr>

> Which problems does your phone have with that little piece of code? 😂

Here's possibly another. <3

Rough STR (might not work): ~~Opened a video, it didn't load. Realised internet was off. Turned it on. Tried to close and reopen the video details screen. <- crash occurred somewhere here.~~ Happened again. Not network-related. Actual STR:
- Have "Start in full screen" toggled on, Autoplay toggled off, and rotation locked to portrait. (Not sure if needed, but that's my setup.)
- Open a video details page.
- ASAP, before the video details can load, tap the thumbnail area. The player will go into full screen. (BTW, can it be made so that the "thumbnail area" cannot be tapped until the thumbnail itself has loaded, along with video details? I think that would fix a lot of bugs.)
- Before it can start playing (while it is still fetching the streams), tap Back ASAP to rotate back to portrait, and then close the minimised player.

Tested on 2 devices, so fully reproducible. Doesn't occur on 0.23.1.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ CH
* __Content Language:__ en-IN
* __App Language:__ en_IN
* __Service:__ none
* __Version:__ 0.23.1
* __OS:__ Linux Android 12 - 32
<details><summary><b>Crash log </b></summary><p>

```
android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{2fc9070 u0 org.schabi.newpipe.debug.mediasessionui/org.schabi.newpipe.player.PlayerService}
	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:1965)
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:1936)
	at android.app.ActivityThread.access$2700(ActivityThread.java:256)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2190)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: android.app.StackTrace: Last startServiceCommon() call for this service was made here
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1877)
	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1832)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:781)
	at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(ContextCompat.java:931)
	at androidx.core.content.ContextCompat.startForegroundService(ContextCompat.java:703)
	at org.schabi.newpipe.player.helper.PlayerHolder.startService(PlayerHolder.java:126)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.openMainPlayer(VideoDetailFragment.java:1217)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.$r8$lambda$7cA0nfOW4EXxLpA03fs92UQohwM(Unknown Source:0)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$$ExternalSyntheticLambda13.run(Unknown Source:2)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.replaceQueueIfUserConfirms(VideoDetailFragment.java:2130)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.openVideoPlayer(VideoDetailFragment.java:1184)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.openVideoPlayerAutoFullscreen(VideoDetailFragment.java:1197)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.onClick(VideoDetailFragment.java:511)
	at android.view.View.performClick(View.java:7455)
	at android.view.View.performClickInternal(View.java:7432)
	at android.view.View.access$3700(View.java:835)
	at android.view.View$PerformClick.run(View.java:28810)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	... 6 more

```
</details>

**Comment by Stypox** [comment]
@opusforlife2 actually, the bug reported in https://github.com/TeamNewPipe/NewPipe/pull/8731#issuecomment-1225796040 (I moved the comment here) has an even simpler STR: just open a video and tap on the thumbnail before the video details can load. Anyway, I fixed it as you said, i.e. by ignoring any click on the thumbnail when nothing has loaded yet.

I tried to go deeper and understand the causes of the problem, and actually understood them, but they depend on the value of `playAfterConnect` received [here](https://github.com/TeamNewPipe/NewPipe/blob/8187a3bc04704e8b1cc380ccbf0c0274a4514494/app/src/main/java/org/schabi/newpipe/player/helper/PlayerHolder.java#L165) the second time the player tries to start: in the case reported it is `false`, so [`openVideoPlayerAutoFullscreen` is not called](https://github.com/TeamNewPipe/NewPipe/blob/68336786f36d66d8bd5504159bbc0eca14ba5bfd/app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java#L249) when the service is connected, which implies no intent with a queue is ever sent to the player, so `startForeground` is not called. This shall not be fixed by this PR but rather by #7673.

**Comment by opusforlife2** [comment]
> actually it's the same as 8731 (comment) ;-)

Oh wow you found it! So my past self did report the crash in time, and is not as silly as I thought.

> This will not be fixed by this PR but rather in 7673.

Okay, so then this PR is only blocked on the choppy animation problem. I'll test that just now.

**Comment by Stypox** [comment]
Triggered a new build

**Comment by opusforlife2** [comment]
> Triggered a new build 

Eh? Don't you need to rebase to include the hotfixed code?

**Comment by Stypox** [comment]
I'm stupid, sorry, now I have rebased

**Comment by opusforlife2** [comment]
Okay, so, if compared with the current release, there is a noticeable lag between the rotations. The choppiness is gone. But the black screen remains for longer than on the current release. However, since users will only be rotating roughly once per video and won't be comparing builds like I am, you could consider this a non-issue.

**Comment by Stypox** [comment]
I am merging this PR even though it didn't receive reviews yes because it needs to be included in the release, and also because both me and opus tested and it seems to work. @litetex you can always review later ;-)

**Comment by opusforlife2** [comment]
There's still time while the RC bakes, after all.

**Pull request merged**
