### PR TITLE
Stringlate fr 9616

### PR DESCRIPTION
**Pull request by SkyzohKey**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by wb9688** [comment]
1. Please use our Weblate.
2. Why are you also merging Android TV support?

**Comment by SkyzohKey** [comment]
I dunno, used Weblate, it did made the PR for me, but it's experimental, feel free to use the strings for Weblate. As I have no account there nor do I know how it works

**Comment by theScrabi** [comment]
You can use your github accout to log in :)

**Comment by SkyzohKey** [comment]
Stringlate, woops*

**Comment by M2ck** [comment]
French translation is already up to date via Weblate.

**Comment by theScrabi** [comment]
So we can closw this?

**Comment by M2ck** [comment]
Apparently yes :)

**Pull request closed without merging**
