### PR TITLE
Update Lifecycle to 2.5.1.

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [x] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Update AndroidX Lifecycle from 2.3.1 to 2.5.0. [Changelog](https://developer.android.com/jetpack/androidx/releases/lifecycle)

#### Fixes the following issue(s)

- Fixes #

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TacoTheDank** [comment]
For library bumps, it would be good to include the changelog link.

**Review by Stypox — APPROVED** [review]
I added a commit refactoring the view model factory according to what the changelog suggests. I tested and everything seems to work fine.

**Comment by TacoTheDank** [comment]
https://developer.android.com/jetpack/androidx/releases/lifecycle#2.5.1

**Comment by TacoTheDank** [comment]
@Stypox Also, is there a reason you improved only the FeedViewModel? Could the improvements also be applied to the FeedGroupDialogViewModel?

**Comment by Stypox** [comment]
> Is there a reason you improved only the FeedViewModel? Could the improvements also be applied to the FeedGroupDialogViewModel?

No, my bad, sorry

**Pull request merged**
