### PR TITLE
Add settings for default download media type.

### PR DESCRIPTION
**Pull request by vmazoyer**
#### What is it?
- [x] Feature (user facing)

#### Description of the changes in your PR
- Users can now select a default media type for their downloads.

#### Fixes the following issue(s)
- Closes feature request #3490. This implementation follows the suggestion (1): a default value in preferences.

#### Relies on the following changes
- Added a new setting in the download preferences.

#### Agreement
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them. Please note that I do not plan to maintain this feature.

### CODE REVIEW

**Comment by TobiGr** [comment]
The better approach is to store the last used download type and auto-select it.

**Comment by vmazoyer** [comment]
How about adding "Last used" as a 4th option?
In my use case I prefer to be able to select a media type rather than "last used".

**Comment by opusforlife2** [comment]
> How about adding "Last used" as a 4th option?

Best of both worlds.

**Comment by Stypox** [comment]
> Best of both worlds.

Nope, @TobiGr suggested to always use the last configuration in order not to add yet another niche option.

**Comment by opusforlife2** [comment]
> Nope, @TobiGr suggested to always use the last configuration in order not to add yet another niche option.

Throw it in a new Miscellaneous Settings menu we've discussed earlier, I say!

**Comment by vmazoyer** [comment]
I made the changes according to the feedback here: no additional setting; just remember the last option used.
To keep things clean I decided to rebase and open a new PR: #4038.

**Pull request closed without merging**
