### PR TITLE
Remove unused resources

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Clean up unused resources using Android Studio's "Remove unused resources" option.

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TobiGr** [comment]
Be careful with that. Android Studio has always marked resources as unused which actually were used. Build fails for that reason.

**Comment by Tyson39** [comment]
@haggaie

**Comment by Tyson39** [comment]
#9981

**Review by TobiGr — APPROVED** [review]
LGTM
Did not find any new problems while testing

**Pull request merged**
