### PR TITLE
VideoDetailFragment: Don't exit fullscreen on rotation in tablet UI

### PR DESCRIPTION
**Pull request by Atemu**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

Going from portrait to landscape doesn't toggle fullscreen in tablet mode, so
the reverse action shouldn't do it either.

#### Fixes the following issue(s)

- https://github.com/TeamNewPipe/NewPipe/issues/4936

#### APK testing 

~~(Upload doesn't work, gets stuck :/)~~

€: It was localCDN

[app-debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/5578022/app-debug.apk.zip)

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by opusforlife2** [comment]
> (Upload doesn't work, gets stuck :/)

If you're using uBO, have you allowed the required domain?

**Comment by MD77MD** [comment]
I think there should be a toggle for this as there are others who prefer the original behavior

**Comment by Atemu** [comment]
I can't imagine a single scenario where you'd went the previous behavior (it was awful honestly) and I therefore don't think it's worth bloating the options for.

**Review by Stypox — APPROVED** [review]
Looks good to me. Thank you ;-)
Can we merge this @TobiGr ?

**Comment by TobiGr** [comment]
We can merge this, but `DeviceUtils.isTV()` and `DeviceUtils.isTablet()` are not completely reliable.

**Pull request merged**
