### PR TITLE
Update Room to 2.3.0.

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [x] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Update Room to the stable 2.3.0 release.
- Convert `Converters` to a Kotlin object.

#### APK testing 

On the website the APK can be found by going to the "Checks" tab below the title and then on "artifacts" on the right.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Redirion** [comment]
thanks for the update but what improvement does "Convert Converters to a Kotlin object." do? I don't think it is directly related to this dependency update and I also don't see any improvement over the java object. But maybe I am missing it as I am not familiar with Kotlin.

**Comment by Stypox** [comment]
@Isira-Seneviratne

**Comment by Isira-Seneviratne** [comment]
Yeah, the conversion to Kotlin was mostly to make the code a bit simpler, and Room 2.3 introduced support for Kotlin objects as converters.

**Review by Stypox — APPROVED** [review]
Ok, good, thank you :-)

**Pull request merged**
