### PR TITLE
Remove search icon in search mode. Issue: #3183

### PR DESCRIPTION
**Pull request by jonas-skywalker**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

This is a preview of the changes that match the requested change in issue #3183 

newpipe

### CODE REVIEW

**Comment by wb9688** [comment]
What's up with those commits?

**Comment by jonas-skywalker** [comment]
Sorry i amended the commit as I put the wrong issue number in the commit message, sorry.

**Comment by XiangRongLin** [comment]
@jonas-skywalker Could you provide a debug apk. You'll have to zip it to upload it here

**Comment by wb9688** [comment]
@XiangRongLin: That's not really needed for such a small change.

@jonas-skywalker: Next time I'd recommend to do an interactive rebase for editing the commit message, so that you won't have 3 commits.

**Comment by jonas-skywalker** [comment]
Alright, thank you very much for your feedback I'm just getting into github!

**Pull request merged**
