### PR TITLE
Add info on how to use a local NewPipe Extractor version

### PR DESCRIPTION
**Pull request by TobiGr**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [x] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
Added a few lines on how to use a local extractor version for debugging and developing the extractor and testing those changes in the app.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by wb9688 — CHANGES_REQUESTED** [review]
Spelling of NewPipe Extractor

**Comment by Stypox** [comment]
Oh, good to know, I always pushed changed and then used Jitpack 😅

**Comment by wb9688** [comment]
@Stypox: Have you not read [NPE's readme](https://github.com/TeamNewPipe/NewPipeExtractor#testing-changes)?

**Review by wb9688 — APPROVED** [review]

**Comment by opusforlife2** [comment]
Why can I delete the local-extractor branch? Never seen that before.

**Comment by TobiGr** [comment]
Correct. forgot to delete it.

**Comment by opusforlife2** [comment]
> You don't use a forked repo

^

**Pull request merged**
