### PR TITLE
Created Brazilian Portuguese Readme

### PR DESCRIPTION
**Pull request by DavidBrazSan**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [x] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

Created Readme file Brazilian Portuguese

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TobiGr** [comment]
Thank you.

Please link this file in the other READMEs.

**Comment by DavidBrazSan** [comment]
Okay, I'm going to do this.

**Comment by mhmdanas** [comment]
@DavidBrazSan you don't need to create a separate PR for each file that is changed. You can change multiple files in a single PR.

**Review by TobiGr — APPROVED** [review]
Thank you. I took the commits from your other PRs, squashed them and added them to this PR.

**Comment by DavidBrazSan** [comment]
@mhmdanas sorry, I'm new to github.
@TobiGr  I'm the one who appreciates letting this beautiful project help.

**Pull request merged**
