### PR TITLE
Update to ExoPlayer 2.11.4

### PR DESCRIPTION
**Pull request by Stypox**
#### What is it?
- [ ] Bug fix (user facing)
- [ ] Feature (user facing)
- [x] Code base improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
This PR updates ExoPlater to 2.11.4, which should hopefully fix some player issues like slowdowns. On my phone and on emulators I noticed that stream loading is (roughly speaking) twice as fast with regards to the old player, but I can't provide a proof ;-)
This PR also includes the changes made by @Redirion in #2859, i.e. making use of two new features: `setHandleWakeLock` and `setHandleAudioBecomingNoisy`.
I fixed the bug faced by @Redirion with `MaskingMediaSource`s: the issue was that the new version wraps around `MediaSource`s being fed to it with a `MaskingMediaSource`, preventing direct access to the original media source. NewPipe made use of this feature in the `ManagedMediaSource` interface to keep track of whether streams were pre-buffered (probably among other things), by storing stream data inside `MediaSource`s. After some dedication I found out that a way to access the underlying `MediaSource` of a `MaskingMediaSource` exists: `getTag()`. That function can be overridden to return any type of variable, so I made it return `this` in the `ManagedMediaSource` interface. I guess this also fixed the issue reported by @TobiGr, i.e. "When changing the resolution while playing, the video stops and the current position jumps to the end".

ExoPlayer release notes: https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md

#### Testing apk
I was able to test thoroughly only on my Android 7.0 phone, since on my pc emulators are too slow to play a video and I can't get audio to work with `pulseaudio`. Anyway I was able to test the basic features on Android API 19 (4.4) and Android API 29 (10) emulators.
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4566122/app-debug.zip)

#### Agreement
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by Redirion** [comment]
@Stypox that solution looks really nice! Good idea by using that getTag(). Looks like getTag() is just used as a window tag in a dummy timeline (so not really used at all).

**Comment by opusforlife2** [comment]
Whoa. I'm getting insane speedups of _5 to 10 times_ compared to the current release. Most of the time, the loading circle can't even complete one rotation before the video starts playing. This is awesome!

**Comment by Stypox** [comment]
@opusforlife2 are you sure you have the same resolution set as default?

**Comment by opusforlife2** [comment]
Of course! That is the first thing I do when I set up a new debug apk. It would have been quite a silly mistake otherwise. 🤣

**Comment by rithans** [comment]
I love the newpipe audio/ video player. hence >> 

1. can you please enable to play already stored  audio / video using newpipe ? 
2. or enable option to locate folders to play audio / videos. 
3. or suggest me its name if this player is downloadable  which is inbuilt in new pipe, so it can be used to play audio / video which are already in sdcard, / or any way to make newpipe default audio/ video player)


can help many students who listen to lectures or audios with skip silence and speed feature. can save hours and help learning.

kind regards,

ritesh shah

**Comment by Stypox** [comment]
@rithans these are the open issues #478 #155

**Comment by wb9688** [comment]
I can't play YouTube videos on API 19/21 at resolutions higher than 360p.

**Comment by Stypox** [comment]
@wb9688 maybe it's due to the slowness of the emulator. Or do you mean it crashes?

**Comment by wb9688** [comment]
@Stypox: Emulator isn't slow at all. It gives an unrecoverable error in a toast (so no crash report :/) when I try to play it. I only tried MPEG-4 though and not WebM yet, but it still shouldn't happen. Try it yourself in an AVD. ;)

**Comment by TobiGr** [comment]
> I can't play YouTube videos on API 19/21 at resolutions higher than 360p.

This happened to me in odder versions, too. But with the new exoplayer version I am able to play more videos. We might want to ping one of the people having a KitKat device to test the new player on a real device.

<details><summary>FYI: stacktrace</summary>

```
5-09 10:30:32.955 3635-5772/? E/SoftAVC: Decoder failed: -2
05-09 10:30:32.955 3635-5771/? E/ACodec: [OMX.google.h264.decoder] ERROR(0x80001001)
05-09 10:30:32.955 3635-5770/? E/MediaCodec: Codec reported an error. (omx error 0x80001001, internalError -2147483648)
05-09 10:30:32.965 3635-5628/? E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalStateException
        at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1441)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:657)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:136)
        at android.os.HandlerThread.run(HandlerThread.java:61)
05-09 10:30:32.965 3635-5628/? E/ExoPlayerImplInternal: Disable failed.
    java.lang.IllegalStateException
        at android.media.MediaCodec.flush(Native Method)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:706)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.flushOrReleaseCodec(MediaCodecVideoRenderer.java:606)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:584)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:451)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:158)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1088)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:851)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:813)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:399)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:136)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```
</details>

**Comment by Stypox** [comment]
@Domiuns @mqus @jojoxl01 @ask6155 @skil3z you have Android 4.4, right? Could you please test the apk provided above on your device and see if it works correctly? Thank you in advance ;-)

**Comment by jojoxl01** [comment]
I found the apk provided by # 3513 and tested it. The background cannot be
played! Display: Cannot play this stream. The latest version 0.19.3 is the
same!
0.19.3 is the same 😂. Also, when you click on the video, a network error
is displayed when playing in the foreground! Thank you!

在 2020年5月9日星期六，Stypox <notifications@github.com> 写道：

**Comment by wb9688** [comment]
@jojoxl01: To be clear: are you saying the behavior is exactly the same as in v0.19.3? Btw was there any previous version last year where it worked correctly?

**Comment by jojoxl01** [comment]
Yes, the test version is the same as 0.19.3. No problem with 0.19.2, before
that I used 0.19.2. I will try 0.19.2 again

在 2020年5月10日星期日，wb9688 <notifications@github.com> 写道：

**Comment by jojoxl01** [comment]
Sorry, it may be that my network is not good, I tried again after
changing the VPN, 0.19.3 background and foreground playback are no
problem, and the test version is also fine. It should be my network
problem.


在 2020年5月10日星期日，jo jo <jojo042625@gmail.com> 写道：

**Comment by jojoxl01** [comment]
I found that it has something to do with the network, many VPNs can not use
it, 0.19.3 and test version
在 2020年5月10日星期日，jo jo <jojo042625@gmail.com> 写道：

**Comment by mqus** [comment]
> you have Android 4.4, right? Could you please test the apk provided above on your device and see if it works correctly? Thank you in advance ;-)

I tested it just now and apart from the usual shenanigans (can't browse soundcloud, the particular peertube video I tried didn't play but downloading it kinda freezed my phone for a while, others played fine) everything worked fine. One thing that I was positively noticing is that peertube lets me resize the popup player more easily then when I last tried (a while ago). But playing videos(fullscreen/popup/background, 360p/1080p60/various) works just fine, although I mostly had MPEG4 videos and only a single webm video. I don't know if there are other codecs I should try. If you have a youtube link which such a case I can try it out.

**Comment by Domiuns** [comment]
@stypox I have been testing your debug app for 13 days (since this PR came out), and i have no problem with YouTube....... Yes with YouTube.

I have this problemi with SoundCloud but it is not your fault but my device.

## Exception
* __User Action:__ requested kiosk
* __Request:__ https://soundcloud.com/charts/new
* __Content Language:__ it_IT
* __Service:__ SoundCloud
* __Version:__ 0.19.2
* __OS:__ Linux Android 4.4.4 - 19


<details><summary><b>Crash log</b></summary><p>

```
javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x62064ca0: Failure in SSL library, usually a protocol error
error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version (external/openssl/ssl/s23_clnt.c:741 0x59b64890:0x00000000)
	at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:420)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:320)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:284)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:169)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:258)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
	at okhttp3.RealCall.execute(RealCall.java:93)
	at org.schabi.newpipe.DownloaderImpl.execute(DownloaderImpl.java:214)
	at org.schabi.newpipe.extractor.downloader.Downloader.get(Downloader.java:70)
	at org.schabi.newpipe.extractor.downloader.Downloader.get(Downloader.java:29)
	at org.schabi.newpipe.extractor.services.soundcloud.SoundcloudParsingHelper.clientId(SoundcloudParsingHelper.java:49)
	at org.schabi.newpipe.extractor.services.soundcloud.SoundcloudChartsExtractor.computeNextPageAndStreams(SoundcloudChartsExtractor.java:54)
	at org.schabi.newpipe.extractor.services.soundcloud.SoundcloudChartsExtractor.getInitialPage(SoundcloudChartsExtractor.java:81)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:19)
	at org.schabi.newpipe.extractor.kiosk.KioskInfo.getInfo(KioskInfo.java:72)
	at org.schabi.newpipe.extractor.kiosk.KioskInfo.getInfo(KioskInfo.java:58)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getKioskInfo$11(ExtractorHelper.java:184)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$3nu_IUHVaX-6ert-LLLuUGJnfDU.call(lambda)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:838)
Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x62064ca0: Failure in SSL library, usually a protocol error
error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version (external/openssl/ssl/s23_clnt.c:741 0x59b64890:0x00000000)
	at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method)
	at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:378)
	... 44 more

```
</p></details>
<hr>

**Comment by wb9688** [comment]
@Domiuns: Nothing regarding that has changed in this PR. I think you should see the same error when using it in the latest released version.

**Comment by Domiuns** [comment]
@wb9688 yes i have same issues with last update

**Comment by wb9688** [comment]
@TobiGr: I didn't encounter any bugs. I don't know if using `getTag()` is the proper way to handle it though.

**Comment by evildog1** [comment]
Latest version still lag as usual on my low end tablet running 4.4 with 512 MB, nothing has really changed. I'm still using MX Player app for better performance

**Pull request merged**
