### PR TITLE
Add workflows for action-template

### PR DESCRIPTION
**Pull request by mhmdanas**
#### What is it?
- [X] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

Add workflows for the [template action](https://github.com/mhmdanas/action-template) that I wrote (you can see it in action [here](https://github.com/mhmdanas/action-template-test/issues?q=is%3Aissue)).
- There's a cron job workflow that runs daily (and can be run on demand too) and closes any issues that still have `doesnt-follow-template` or `template-not-used` (the labels are customizable) for a customizable amount of days.
- There is another workflow that runs on issue labeling, and if the label is `doesnt-follow-template` or `template-not-used`, it will make a comment (which has a different body depending on the label, and the comment bodies are customizable too).

My reasoning for using `template-not-used` and `doesnt-follow-template` instead of the existing `template-ignored` and `doesnt-follow-template` is the distinction. As far as I know, currently, we use `template-ignored` when an issue was opened from the GitHub website (we can know this by checking if a label was added automatically), and `doesnt-follow-template` when it was opened from somewhere else (e.g. third-party client). I believe a better distinction to make is when an issue removes the template completely (`template-not-used`) and it has the template but doesn't follow it properly (`doesnt-follow-template`).

Here are the default comment bodies for each label:
<details>
<summary><code>template-not-used</code></summary>

Hi @{authorLogin}! Thank you for opening an issue! Please choose the appropriate template at the bottom of this comment, edit your issue to follow it properly, and then make a comment that you edited the issue. If you do not edit your issue to follow a template properly in {daysUntilClose}, this issue will be closed. Thanks!

_Issue templates will be shown here_
</details>

<details>
<summary><code>doesnt-follow-template</code></summary>
Hi @{authorLogin}! Thank you for opening an issue! Unfortunately, it seems like you didn't follow the template's instructions properly. Please edit your issue to follow all of the template's instructions properly and then make a comment saying that you edited the issue. If you do not edit your issue to follow the template's instructions properly in {daysUntilClose}, this issue will be closed. Thanks!
</details>

I configured it to close an issue if it's not edited in 4 days, but if you find that too much time or too little feel free to comment.

Finally, I'm not sure if we should be merging this in a repo that has 700+ issues without being more confident in its reliability. I tested it and didn't find any bugs, but I don't want to risk it. Maybe we should try it in a smaller repo like NewPipe Legacy where the impact of a bug would be smaller?

#### APK testing 

Unnecessary.

#### Due diligence
- [X] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by XiangRongLin** [comment]
1. Is it possible to delete the comment after either a new one is posted by the action or after the issue is adjusted properly?
2. If you are not confident in it's reliability then i don't think it is tested properly enough. Since the concerns are what happens with the exisitng 700+ issues, those scenarios should be tested. Preferably automated, since this way the tests also serve as documentation.
3. If im seeing correctly the labels have to be added manually. What are the benefits of this, if that still has to be done from hand?

**Comment by mhmdanas** [comment]
1. Yes, I can add that if necessary.
2. Perhaps I can get a copy of the NewPipe issue tracker and run tests on it.
3. Using a regex or whatever to detect if an issue follows a template is very difficult and will NEVER be accurate enough (having to add one of two labels makes it even more difficult and less accurate). Letting people add a label manually is better. Also, it's not like adding a label takes up a lot of time.

I'll be marking this PR as a draft till I finish my changes.

**Comment by XiangRongLin** [comment]
Did I understand it correctly that that action only acts on issues with labels that have to be added beforehand by something/someone else? Shouldn't then basically nothing happen to old issues, that don't have those labels?

**Comment by mhmdanas** [comment]
Yes, your understanding is correct.

**Pull request closed without merging**
