### PR TITLE
Fix for missing audio downloads

### LINKED ISSUE #391: downloads missing
there is an issue that i have.After downloading videos or audio i can see them in the downloads folder.If i exit the application and re-enter the downloaded audio/video are gone.Tested on two smartphones.I tried re installing several times and issue persists

### PR DESCRIPTION
**Pull request by coffeemakr**
I changed the DownloadManger's location to a list of locations from where the files are loaded in the constructor.
The audio files are showing up and it could fix #391 if it is only related to audio files. 
I think i haven't tested it fully because I'm not sure when toolbar.onMenuItemClick is called in the DownloadActivity.

### CODE REVIEW

**Comment by theScrabi** [comment]
Boy you are doing a lot of work xD recently :) You aren't at 33c3 are you?

**Comment by coffeemakr** [comment]
Sadly not. I didn't get a ticket :(

**Comment by theScrabi** [comment]
Hm thats not such a bad thing, but you may need to be able to still remove all the download entires without deleting the actual contend. 
I now have the problem that all the music I downloaded shows up in my download list now.

**Comment by coffeemakr** [comment]
I'll look into this 👍

**Comment by theScrabi** [comment]
All right thanks.

**Comment by coffeemakr** [comment]
How about this; Unfinished downlaods have this `.giga` file and once a Download finished it is stored in a SQLite database.

I'm not that sure if the downloaded size should be stored.. Or something else?
It looks like it's working but not I haven't fully tested it.

**Comment by coffeemakr** [comment]
The following things need to be done:

- [ ] Remove downloads (does nothing for finished downloads)
- [ ] Replacing a file (will probably fail)
  - [ ] Remove from DB
  - [ ] Ask before overwriting?

**Comment by coffeemakr** [comment]
oh boy I did something wrong.

**Comment by coffeemakr** [comment]
I think I did something wrong by merging the master or did too small commits :/ I can rewrite the history if you want.

I changed the following things:
 * Added a test
 * Fixed some issues
 * Downloads can be started with Intents to the BackgroundManagerService (no Binding required) 3ed2843fcdb4d81213f3a96c020c37995bd44c99		
   * This ensures that DownloadDialog or DoaloadActivity don't fall into an endless loop while waiting
   * Makes it easier to start and stop for the service
 *  Use FileProvider to open downloaded files (23c76a2fb440299ec74ab7ee48323ef5f505d12d) because I got this issue:
```
01-10 11:54:35.977 17390-17390/org.schabi.newpipe E/MissionAdapter: Unable to start activity
                                                                    android.os.FileUriExposedException: file:///storage/emulated/0/Movies/NewPipe/Idiot_Test_90_fail.webm exposed beyond app through Intent.getData()
                                                                        at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
                                                                        at android.net.Uri.checkFileUriExposed(Uri.java:2346)
                                                                        at android.content.Intent.prepareToLeaveProcess(Intent.java:8981)
                                                                        at android.content.Intent.prepareToLeaveProcess(Intent.java:8942)
                                                                        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1519)
                                                                        at android.app.Activity.startActivityForResult(Activity.java:4225)
                                                                        at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:48)
                                                                        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:77)
                                                                        at android.app.Activity.startActivityForResult(Activity.java:4183)
                                                                        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
                                                                        at android.app.Activity.startActivity(Activity.java:4522)
                                                                        at android.app.Activity.startActivity(Activity.java:4490)
                                                                        at us.shandian.giga.ui.adapter.MissionAdapter$2.onMenuItemClick(MissionAdapter.java:236)
                                                                        at android.widget.PopupMenu$1.onMenuItemSelected(PopupMenu.java:104)
                                                                        at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
                                                                        at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
                                                                        at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
                                                                        at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
                                                                        at com.android.internal.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
                                                                        at android.widget.AdapterView.performItemClick(AdapterView.java:310)
                                                                        at android.widget.AbsListView.performItemClick(AbsListView.java:1156)
                                                                        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3128)
                                                                        at android.widget.AbsListView$3.run(AbsListView.java:4043)
                                                                        at android.os.Handler.handleCallback(Handler.java:751)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6126)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```
It works with the builtin media player but VLC seems to have  a problem with some of the video files :/

**Comment by theScrabi** [comment]
you can rebase, and than squash all that tiny commits so they are not that much.

**Comment by coffeemakr** [comment]
Done

**Comment by coffeemakr** [comment]
Would it be better if I removed the part with the permissions and ContentProvider? Seems like a bad mix to me.

**Comment by theScrabi** [comment]
What do you mean? The part with tha ContentProvider was added recently, and is necessary. Otherwise the Music app would not know that there is a now tune available.

**Comment by coffeemakr** [comment]
ok!

**Comment by theScrabi** [comment]
Hm ok now I'll merge it, but still we need a way to remove database entries without deleting the actual file.

**Pull request merged**
