### PR TITLE
Switch to the Java 8 Date/Time API.

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Use the Java 8 Date/Time API in both NewPipe and the NewPipe extractor.

#### Relies on the following changes

- https://github.com/TeamNewPipe/NewPipeExtractor/pull/417

#### APK testing 

[debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5468440/debug.zip)

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by wb9688** [comment]
Could you please make a separate PR for the multidex changes? I'm hoping it'll fix an issue with ACRA not finding classes in another dex.

**Comment by Isira-Seneviratne** [comment]
> Could you please make a separate PR for the multidex changes? I'm hoping it'll fix an issue with ACRA not finding classes in another dex.

Sure.

> Edit: you also forgot to change NPE to your fork causing this PR to fail on CI

Thanks!

**Comment by Isira-Seneviratne** [comment]
@wb9688 I created a PR: https://github.com/TeamNewPipe/NewPipe/pull/4557

**Comment by Isira-Seneviratne** [comment]
Closing and reopening to trigger a rebuild.

**Review by Stypox — APPROVED** [review]
Thank you for improving the codebase! I tested thoroughly the APK you provided, trying multiple actions with dates, amd everything worked fine.

**Pull request merged**
