### PR TITLE
Update to ExoPlayer 2.10.5

### LINKED ISSUE #2257: ExoPlayer memory leak
I noticed one problem, the allocated video memory is increased after seeking playback position.

Screenshot_20190331_183423
This bug available only on one of my devices. I found [this](https://github.com/google/ExoPlayer/issues/5151). Look like this is a internal bug of ExoPlayer, but I`m not sure. Are anyone has the same problem?

### PR DESCRIPTION
**Pull request by Redirion**
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

As we now finally have AndroidX I was able to update ExoPlayer to the latest version.
This brings numerous of needed fixes and improvements to NewPipe. Have a look at the ReleaseNotes: https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md

This might close #2257 and #2373 and possible other issues.

Debug apk for testing: https://github.com/Redirion/NewPipe/releases/download/v0.17.3-exo/app-debug.apk

Notes for Review:

- Changes to the MediaSessionManager and PlayQueueNavigator were mainly required due to this commit in ExoPlayer: https://github.com/google/ExoPlayer/commit/063f5704cd80a733bf770375d8fbf402a6c5d958
- I also had to fiddle again in CustomTrackSelector as there have been changes again. I already tried subtitles (it seems to be working fine this time :D)
- I have updated Gradle to 3.4.0 to match ExoPlayer's gradle version
- okhttp has been updated as well to match ExoPlayer (thus deemed stable)
- With the new isPlaying() method in BasePlayer NewPipe makes already use of a new feature added in ExoPlayer 2.10.5

### CODE REVIEW

**Comment by TobiGr** [comment]
I think something went wrong while rebasing / merging. Should I force push the branch to get it right?

**Comment by TobiGr** [comment]
I tried to open a video
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ GB
* __Service:__ none
* __Version:__ 0.17.3
* __OS:__ Linux ,release-keys 6.0 - 23


<details><summary><b>Crash log</b></summary><p>

```
java.lang.RuntimeException: Unable to destroy activity {org.schabi.newpipe.debug/org.schabi.newpipe.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.viewpager.widget.ViewPager.setAdapter(androidx.viewpager.widget.PagerAdapter)' on a null object reference
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3852)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3870)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4074)
	at android.app.ActivityThread.-wrap15(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1360)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.viewpager.widget.ViewPager.setAdapter(androidx.viewpager.widget.PagerAdapter)' on a null object reference
	at org.schabi.newpipe.fragments.MainFragment.onDestroy(MainFragment.java:115)
	at androidx.fragment.app.Fragment.performDestroy(Fragment.java:2830)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1028)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1310)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
	at androidx.fragment.app.FragmentManagerImpl.dispatchDestroy(FragmentManagerImpl.java:2644)
	at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:329)
	at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:366)
	at androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java:233)
	at org.schabi.newpipe.MainActivity.onDestroy(MainActivity.java:352)
	at android.app.Activity.performDestroy(Activity.java:6415)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1165)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3839)
	... 10 more
java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.viewpager.widget.ViewPager.setAdapter(androidx.viewpager.widget.PagerAdapter)' on a null object reference
	at org.schabi.newpipe.fragments.MainFragment.onDestroy(MainFragment.java:115)
	at androidx.fragment.app.Fragment.performDestroy(Fragment.java:2830)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1028)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1310)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
	at androidx.fragment.app.FragmentManagerImpl.dispatchDestroy(FragmentManagerImpl.java:2644)
	at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:329)
	at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:366)
	at androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java:233)
	at org.schabi.newpipe.MainActivity.onDestroy(MainActivity.java:352)
	at android.app.Activity.performDestroy(Activity.java:6415)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1165)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3839)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3870)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4074)
	at android.app.ActivityThread.-wrap15(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1360)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

```
</p></details>
<hr>

**Comment by TobiGr** [comment]
I think the last `git pull` is wrong. However, where does the merge commit come from?

**Comment by Redirion** [comment]
from git pull --rebase upstream dev, it automatically created the merge. 
I don't see how your crash is related to the ExoPlayer Updat (also unable to reproduce)

**Comment by TobiGr** [comment]
> from git pull --rebase upstream dev, it automatically created the merge.

Not for me :thinking: 

> I don't see how your crash is related to the ExoPlayer Updat (also unable to reproduce)
 
Oh yeah, I cannot reproduce it either... It just happened the first time I tried to open a video.

**Comment by TobiGr** [comment]
I'll do some further testing on most supported Android versions during the day to make sure nothing broke. NewPipe without a working player is quite useless. When testing succeeds, I'll merge and start preparations for a new release.

**Comment by Redirion** [comment]
Samsung Galaxy S7 with Android 8.0.0 looking good so far

**Comment by Stypox** [comment]
Changing resolution and then changing it again before the video has finished loading  causes the playback time to reset to 0:00. This bug is not present in the latest app release.

**Comment by Pentaphon** [comment]
>Increase maximum video buffer size from 13MB to 32MB. The previous default was too small for high quality streams.

Yes! We needed this for Newpipe videos for sure.

**Comment by Redirion** [comment]
> Changing resolution and then changing it again before the video has finished loading causes the playback time to reset to 0:00. This bug is not present in the latest app release.

what kind of usage scenario is this? :grinning: do you consider this blocking? I am not even fast enough to switch between resolutions to reproduce that..

**Comment by Stypox** [comment]
I was trying to play a video with low internet, so I had to switch resolution, but I pressed on the wrong one so I got this problem. I agree this is not blocking, but if it's just a small problem fixable in no time it could as well be fixed. Though if it would be too much of a hassle to fix it then nevermind.

**Comment by Redirion** [comment]
I have compared MainFragment with the other Fragment classes and added a null check that is inline with the other onDestroy methods as a simple fix. I have replaced the debug apk for retesting.
(This might sound as the lazy fix, but was also the most reasonable I think :smile:)

**Comment by Redirion** [comment]
@TobiGr the winter semester has begin. Could you try to prepare a RC so that testing AndroidX and ExoPlayer 2.10 gets more traction? Thank you!

**Comment by TobiGr** [comment]
Sorry, for the late response, I though you were trying to fix the issue mentioned by @Stypox. But I agree that this is not blocking. Nevertheless it should be fixed.

**Comment by Redirion** [comment]
> Sorry, for the late response, I though you were trying to fix the issue mentioned by @Stypox. But I agree that this is not blocking. Nevertheless it should be fixed.

But I did a commit with a null check to fix the crash. I explained it in a comment here and in the AndroidX PR to you.

**Comment by Redirion** [comment]
I thought that was the same issue, as I was able to reproduce the bug by wildly rotating the screen. The error message did not always appear (it was hidden by the rebuild fragment) but playback was reset.

@Stypox are you still able to reproduce the playback reset bug with the latest debug apk?

**Comment by TobiGr** [comment]
Oh yes. I cannot repro it with latest comment either. Before I was able to do so. Perfect :+1:

**Comment by Stypox** [comment]
No, it seems to be fixed, thanks :-)

**Pull request merged**
