### PR TITLE
Update User-Agent in Downloader

### PR DESCRIPTION
**Pull request by Nickoriginal**
#### What is it?

- [x] Codebase improvement (dev facing)

#### Description of the changes in your PR
This PR updates the USER_AGENT string in DownloaderImplementation to match the latest Firefox ESR 91 release.

#### APK testing
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by opusforlife2** [comment]
@Nickoriginal Would you like to open a corresponding PR in the extractor repo like litetex says?

**Comment by Stypox** [comment]
@litetex have you tested that this works with NPE tests?

**Comment by opusforlife2** [comment]
Shouldn't have this and the NPE PR been merged together? The extractor version for this release has already been published, so that pushes the NPE PR to the next release cycle. Or are they unrelated?

**Comment by litetex** [comment]
> Or are they unrelated?

Yes, they are unrelated. 
The extractor DownloaderTestImpl is just used inside tests ;)

**Pull request merged**
