### PR TITLE
Spelling: Some devices are incompatible

### PR DESCRIPTION
**Pull request by comradekingu**
: smallversal is incompatible. This does away with the potential for errors.

### CODE REVIEW

**Comment by Stypox** [comment]
What does ": smallversal is incompatible" mean? I am not sure I understand correctly, sorry

**Comment by comradekingu** [comment]
@Stypox The others are : A : B : C etc.

**Comment by gkeegan** [comment]
I'm not sure what this would fix either. Can you explain what the problem is?

**Comment by comradekingu** [comment]
@gkeegan 
Colon bigversal
https://github.com/TeamNewPipe/NewPipe/blob/e14b7851b1b001bfa95635e210d1103335cc82af/app/src/main/res/values/strings.xml#L370
https://github.com/TeamNewPipe/NewPipe/blob/e14b7851b1b001bfa95635e210d1103335cc82af/app/src/main/res/values/strings.xml#L402

Colon smallversal
https://github.com/TeamNewPipe/NewPipe/blob/e14b7851b1b001bfa95635e210d1103335cc82af/app/src/main/res/values/strings.xml#L591

My fix moves everything into the former group, so that it is consistent.
(All the others are ": %1$s")

**Comment by opusforlife2** [comment]
OH! I get it now. Don't make up your own words, man! 🤣 Searching for bigversal gives nothing, and smallversal just links to your profile because of this very issue.

https://en.wiktionary.org/wiki/versal#Noun gives the explanation. One learns new things everyday.

It's the first letter after the colon. That's all. Since the majority are capital letters, the rest should be, too.

**Comment by Stypox** [comment]
Thank you!

**Pull request merged**
