### PR TITLE
List addition fix

### PR DESCRIPTION
**Pull request by yausername**
fixes controls animation flicker
fixes issues addressed here https://github.com/TeamNewPipe/NewPipe/issues/2483#issuecomment-518071432

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by theScrabi** [comment]
You could commit directly into the release branch? Do you have permissions for this?

**Comment by theScrabi** [comment]
If not one should give you.

**Comment by yausername** [comment]
I don't think I have permissions for that.

```
$ git push upstream release_v0.17.0
ERROR: Permission to TeamNewPipe/NewPipe.git denied to yausername.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by TobiGr** [comment]
> If not one should give you.

@theScrabi done. GitHub's permission handling is rubbish. There are far too few options... I gave @yausername `write` access, which includes way more permissions than pushing to the release branch.
@theScrabi Feel free to undo this, if I misunderstood you.

**Comment by yausername** [comment]
Pushed directly to release branch, hence closing this.

**Pull request closed without merging**
