### PR TITLE
Android Auto

### PR DESCRIPTION
**Pull request by frankkienl**
#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Android Auto

#### Fixes the following issue(s)

- https://android-developers.googleblog.com/2020/10/introducing-android-for-cars-app-library.html

#### Relies on the following changes

- minSdkVersion 23

#### Due diligence
- [ ] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).
I read it, but sorry guys, had to include a google library.

### CODE REVIEW

**Comment by Stypox** [comment]
Unfortunately it seems like the library you added is not open source, therefore this can't be merged because it conflicts with the license (GPL v3). @TheAssassin

**Comment by frankkienl** [comment]
Understandable. I'll close the PR.

**Comment by dtheodor** [comment]
I don't get this. Are you saying that it is impossible to support Android Auto because of GPL?

**Comment by Stypox** [comment]
Yes, since NewPipe should be open source, and as such should not include closed source libraries

**Pull request closed without merging**
