### PR TITLE
Add all (HTTP(S)) Invidious instances

### PR DESCRIPTION
**Pull request by 2secslater**
Public Invidious instances from https://github.com/omarroth/invidious/wiki/invidious-instances have been added to the AndroidManifest.xml to allow opening of the public Invidious (not just `invidio.us`) links in NewPipe.

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by theScrabi** [comment]
Did you add support for this in the extractor? If not you need to otherwise its not working.

**Comment by Serkan-devel** [comment]
The APIs do quite differ between that and YT

**Comment by theScrabi** [comment]
Thats not the issue however the StreamLinkHandlerFactories in the extractor have to know the invidious instances as well, otherwise the app will accept the links but the backend would not know what to do with them.

**Comment by 2secslater** [comment]
I've added the domains to the link factory for YouTube. https://github.com/TeamNewPipe/NewPipeExtractor/pull/182

**Comment by Perflyst** [comment]
@theScrabi can we get this merged for the next release?

**Pull request merged**
