### PR TITLE
Allow starting the search fragment via intent

### LINKED ISSUE #3475: Search URI
Expose a way for third party app to call search action in newpipe.

For example, sesame would like to integrate search in newpipe: https://www.reddit.com/r/sesame/comments/73supb/sesame_shortcuts_222_beta/dnvlbot/

Thank you guys in advance for your hard work.

### PR DESCRIPTION
**Pull request by jiahengguo123**
#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Extended custom URL scheme to include service selection: Implemented the ability for third-party apps to initiate a search in NewPipe on a specific service by using the custom URL scheme `newpipe://search?service=SERVICE_NAME\&q=YOUR_QUERY`.
- Added intent-filter to RouterActivity: Updated AndroidManifest.xml to include an intent-filter in RouterActivity to handle the custom URL scheme.
- Enhanced RouterActivity to handle 'service' parameter: Modified RouterActivity to parse the incoming service parameter from the intent, retrieve the corresponding service ID, and start MainActivity with the specified service and search query.
- Added error handling for invalid service names: Implemented validation for the service parameter to check if the provided service name is valid. If the service name is invalid, the app displays an error message to the user.
- Tested the implementation: Used ADB commands to send an intent with the custom URI and verified that NewPipe performs the search as expected, such as `adb shell am start -a android.intent.action.VIEW -d "newpipe://search?service=Soundcloud\&q=funny%20cats"`.

#### Fixes the following issue(s)

- Fixes #3475

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR. You can find more info and a video demonstration [on this wiki page](https://github.com/TeamNewPipe/NewPipe/wiki/Download-APK-for-PR).

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jiahengguo123** [comment]
> How does this interact with service selection? If Soundcloud is selected by the user before this intent is sent, will it still work?

I think it will still work. Through ServiceHelper. GetSelectedServiceId (this) in RouterActivity service for the currently selected user ID is the keypoint. This ID is then passed to the MainActivity and used to initialize the SearchFragment, make sure that the search operation is performed for the currently selected service by the user. Therefore, if the user has selected SoundCloud before sending this intent, the search will be performed on SoundCloud.

**Comment by jiahengguo123** [comment]
I understand the question. I can add a match to the URL with the service parameter in the Intent filter. The new command can be newpipe://search? service=youtube&q=funny cats

**Comment by jiahengguo123** [comment]
I have improved the code so that now users can specify a service to search by adding a service name to the URL. And an error notification for the wrong name. I also modified the Pull Request description.

**Comment by Stypox** [comment]
Closing as there has not been recent activity and because NewPipe is currently not accepting new feature PRs, as noted in the README. This feature, however, would be pretty neat. It should probably be implemented in MainActivity though.

**Pull request closed without merging**
