### PR TITLE
Enhanced UI design of tempo and pitch adjustment options

### LINKED ISSUE #8962: Tempo and Pitch adjustment options with a button like design instead of falt text based
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

The interface here have option to adjust tempo and pitch but they have a flat text based layout instead of some kind of clickable buttons. With little bit of design change there, we can know visualize much better as for now they just look like video statistics menu.

### Why do you want this feature?

To enhance the visibility of the tempo and pitch functions giving users the ability to differentiate with ease by having more understanding about the app usability.

### Additional information

Just a simple layout change can do wonders for users. Below is just an example.
IMG_21739813

### PR DESCRIPTION
**Pull request by u7280973**
#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
Enhanced UI design of playback parameters (tempo and pitch) by implementing a more button-like design to improve accessibility.

#### Before/After Screenshots/Screen Record

- Before:

image

- After:

image

#### Fixes the following issue(s)
- Fixes #8962

#### APK testing
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by opusforlife2** [comment]
The "-/+100%" in the top two circles for Tempo look a bit cramped. Try some other shapes? Maybe squares there as well?

**Comment by u7280973** [comment]
Here is what it looks like with square buttons:
image

**Comment by opusforlife2** [comment]
Thanks for the quick change! Could you update the screenshot?

**Comment by u7280973** [comment]
Here is the updated screenshot:
Screen Shot 2022-10-22 at 9 50 02 am

**Comment by opusforlife2** [comment]
Does the tappable area correspond to the coloured area? If so, that's a nice accessibility boost, I think.

**Comment by Stypox** [comment]
I don't think these changes look good: the style of the buttons is inconsistent and does not fit well with the app's look. And they also do not increase accessibility that much, since the new buttons do not look more like buttons than before. The problem is that you are not using standard Material Design buttons. Try, for example, the OutlinedButton or the ContainedButton as seen [here](https://www.geeksforgeeks.org/material-design-buttons-in-android-with-example/).

**Comment by opusforlife2** [comment]
@u7280973 ANU student?

**Comment by opusforlife2** [comment]
Hi. Since a different layout has been decided upon after discussions, this PR is being closed. Please don't hesitate to get in touch if you're interested in working on the proposed design!

**Pull request closed without merging**
