### PR TITLE
removed resizing text from popup player

### PR DESCRIPTION
**Pull request by karkaminski**
#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- removed resizing text from popup player
-  #5514

#### APK testing 

On the website the APK can be found by going to the "Checks" tab below the title and then on "artifacts" on the right.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by XiangRongLin** [comment]
Could you add before/after images?
I can't immediatly think of what is meant with "resizing text"

**Comment by karkaminski** [comment]
obraz
obraz

First one is before. Text "Resizing" is shown in top left corner while you resizing the pop-up window.

**Review by XiangRongLin — APPROVED** [review]

**Comment by XiangRongLin** [comment]
Thank you. After the current release is done, this can be merged.

**Comment by alienthief** [comment]
@karkaminski thanks for making that ugly text go away

**Pull request merged**
