### PR TITLE
Use official Kotlin codestyle

### PR DESCRIPTION
**Pull request by TacoTheDank**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [x] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
- Declare usage of official Kotlin codestyle, because why not

#### APK testing 
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by opusforlife2** [comment]
@TacoTheDank Welcome to the team!

You must now join the Newpipe IRC channel so you can be hooked into the Mother Brain. ( ⚆ _ ⚆ )

**Comment by Redirion** [comment]
Kotlin code style differs from Java code style alot. In my opinion we should not enforce it, as long as Kotlin is not the major language of the project.

**Comment by TacoTheDank** [comment]
> @TacoTheDank Welcome to the team!
> 
> You must now join the Newpipe IRC channel so you can be hooked into the Mother Brain. ( ⚆ _ ⚆ )

Pretty sure I'm already in it haha, thanks!

**Comment by opusforlife2** [comment]
> Pretty sure I'm already in it haha, thanks!

Are you sure? Check again. (⊙_◎)

**Comment by TacoTheDank** [comment]
@opusforlife2 ...I guess y'all changed the server again lol. I'll join then.

**Review by litetex — CHANGES_REQUESTED** [review]
When this style should be enabled (which also needs some discussion as seen above) all kotlin files have to be reformatted:
https://kotlinlang.org/docs/code-style-migration-guide.html#migration-to-a-new-code-style

I don't see any reformatted files here although this should definitely be the case here:
https://kotlinlang.org/docs/code-style-migration-guide.html#differences-between-kotlin-coding-conventions-and-intellij-idea-default-code-style

**Comment by litetex** [comment]
BTW: I marked some of the above comments as "Off-Topic" because these are not related to this PR.

**Comment by TacoTheDank** [comment]
> When this style should be enabled (which also needs some discussion as seen above) all kotlin files have to be reformatted: https://kotlinlang.org/docs/code-style-migration-guide.html#migration-to-a-new-code-style
> 

I see. Then I guess it would be better to just close this, then?

**Comment by TacoTheDank** [comment]
Agree. Alright.

**Pull request closed without merging**
