### PR TITLE
bbc sounds support

### PR DESCRIPTION
**Pull request by yausername**
#### What is it?
- [ ] Bug fix (user facing)
- [x] Feature (user facing)
- [ ] Code base improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
- bbc sounds support

I am not totally sure about the svg decoder thing. It works though.

#### Relies on the following changes
-  https://github.com/TeamNewPipe/NewPipeExtractor/pull/364 and https://github.com/TeamNewPipe/NewPipe/pull/3803

#### Testing apk
[app-debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/4884537/app-debug.apk.zip)

#### Agreement
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by TobiGr** [comment]
@yausername Thank you. I got in touch with the user requesting the feature and asked him to test your changes.

**Comment by yausername** [comment]
> @yausername Thank you. I got in touch with the user requesting the feature and asked him to test your changes.

Sure, thanks!

**Comment by ingingin** [comment]
Big Black C?

**Comment by wb9688** [comment]
@ingingin: No: https://www.bbc.co.uk/sounds

**Comment by MainTomato** [comment]
Love this feature, been using It at work. I hope this gets added to the main release. 👍

**Comment by yausername** [comment]
@MainTomato I'm glad you like it. :)

**Comment by TobiGr** [comment]
I'll look at the extractor once I finished my review of TeamNewPipe/NewPipeExtractor#232

**Comment by MainTomato** [comment]
I can see some improvements that can be made.

1. It would be nice to be able to view all the categories on this page In the app - https://www.bbc.co.uk/sounds/categories
2. On the homepage of https://www.bbc.co.uk/sounds, there's tons of featured content like "Unmissable Sounds". Adding a featured tab to the app would be nice as well. As of right now I think It's hard to view all the content sounds has to offer unless you search for It.

**Comment by yoshimo** [comment]
Does this cover the display of the currently played song which is available for a few programmes?

**Comment by litetex** [comment]
Closing this for now:
* replies on closed PRs
* no progress
* no GitHub actions build
* merge conflicts

Feel free to reopen it when there is progress again.

**Comment by ShareASmile** [comment]
i would like to bump this one, so that it is picked up again.

> I can see some improvements that can be made.

Yes, I woluld request among other  improvements to include Asian feed also
https://www.bbc.co.uk/sounds/play/live:bbc_asian_network

**Comment by opusforlife2** [comment]
Don't comment on a closed PR. Comment in the open issue.

**Pull request closed without merging**
