### PR TITLE
Delete pending missions with invalid storage

### LINKED ISSUE #6687: Crashing when downloading because of SAF
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

download any video or go to see download folder in the app, app restarts a couple of time and crashes

happening only if I enable SAF, its default in 0.21.6 also happens in 0.21.5 if I enabled it

but in 0.21.5, I could atleast see my downloads folder, in 0.21.6 it crashes in both cases, seeing the downloads folder or downloading a video/audio

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/84063610/126030104-584b3d52-d456-4769-9c7d-dbb55cd1a863.mp4

### Logs

`## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.6
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to create service us.shandian.giga.service.DownloadManagerService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4412)
	at android.app.ActivityThread.access$1800(ActivityThread.java:274)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2118)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at us.shandian.giga.service.DownloadManager.loadPendingMissions(DownloadManager.java:165)
	at us.shandian.giga.service.DownloadManager.<init>(DownloadManager.java:77)
	at us.shandian.giga.service.DownloadManagerService.onCreate(DownloadManagerService.java:142)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4400)
	... 8 more

```
</details>
<hr>
`

### Device info

 - Android version/Custom ROM version:
 - Device model:

### PR DESCRIPTION
**Pull request by Stypox**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
When loading pending missions from disk, sometimes an invalid mission with `storage == null` would be read (because of a corrupted file or with an outdated file format). This caused `NullPointerException`s down the line. So I added `hasInvalidStorage()` to the prelimiary checks on the mission object loaded from file, and if that's the case the related file is deleted. (each pending mission has its own file)

#### Fixes the following issue(s)

- Fixes #6687

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.
@timjefferies @bew @castrik does this fix the problem for you?

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by XiangRongLin — APPROVED** [review]
Makes sense and since it seems to work for the issue opener, gogo 🏃

**Comment by kannes** [comment]
> #### APK testing
> 
> The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

That "app" text is not clickable when not logging in to Github, here is a direct URL in the hopes that it is not login-gated: https://github.com/TeamNewPipe/NewPipe/suites/3292080699/artifacts/76861038

**Comment by esdnm** [comment]
You can't just delete a mission if it has invalid storage, you need to handle it differently.

**Comment by opusforlife2** [comment]
@esdnm You're most welcome to submit a PR proposing your solution.

**Comment by esdnm** [comment]
> @esdnm You're most welcome to submit a PR proposing your solution.

I don't have a solution on my head. But I must say that fixing this issue in a destructive way is _utterly_ insane.

**Comment by opusforlife2** [comment]
It's a matter of perspective. Another user could easily claim that leaving incomplete corrupted files lying around in storage causing bloat is what's utterly insane.

**Pull request merged**
