### PR TITLE
Update screenshots

### PR DESCRIPTION
**Pull request by TobiGr**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

This updates the screenshots in the README and also on F-Droid to a newer version including trending and playlists.

### CODE REVIEW

**Comment by theScrabi** [comment]
should we delete the old screenshots from the history again, in order to not bload up the reop?
Maybe we should host the screenshots somwhere else.

**Comment by TobiGr** [comment]
> should we delete the old screenshots from the history again, in order to not bload up the reop?

We can do this although I am not  fan of deleting commits which are on several repositories.

> Maybe we should host the screenshots somwhere else.

This are the same screenshots as I used [here](https://newpipe.schabi.org/press/screenshots/) so we could link the other repository. But I don't know how Fastlane and F-Droid handle links.

**Comment by TobiGr** [comment]
And these images need only 1.0MB. So I'd rather keep the files in this repository.

**Comment by theScrabi** [comment]
Ow right, because of fastlane we need to keep them where they are.

**Pull request merged**
