### PR TITLE
Fix NPE for issue #1901

### PR DESCRIPTION
**Pull request by Ping20002015**
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
Fix NPE for issue #1901
This fix was tested as local debug build in my phone.

### CODE REVIEW

**Comment by TobiGr** [comment]
Hey @Ping20002015, 
thanks for taking a look at then Background player crash. The development happens on the `dev` branch and we only push to master for releases. That's why your branch is quite outdated. Please [rebase](https://github.com/TeamNewPipe/NewPipe/wiki/How-to-merge-a-PR) your branch onto dev.
FYI, the bug has already been fixed by @beNitinhere  in #1874. The important thing happened in [this line](https://github.com/TeamNewPipe/NewPipe/pull/1874/files#diff-d45c9b9532307e47fd7c4399ebcead8bL300). I am not aware of the player code, but your solution looks more specific to the actual problem and might not leak memory. @theScrabi What do you think about this?

**Comment by Ping20002015** [comment]
Hi, i'm new to this. 
I merged the fix from master to dev on my fork. Must i create an new pull request?

About the fix: I was aware of the problem, that at this point maybe simpleExoPlayer has to be not NULL. But i gave it a shot and solutions worked. It's hard to understand the consequences of #1874, maybe this will lead to memory leak, maybe not ... I don't have reengineered the apps logic till now.

**Comment by theScrabi** [comment]
@Ping20002015 you can change the branch to push on github.

**Comment by Ping20002015** [comment]
Hi, acutal i want to push my changes to TeamNewPipe:dev. Should i change that?

**Comment by Ping20002015** [comment]
Hi, is there anything i can or have to do?

**Comment by theScrabi** [comment]
@Ping20002015 no that is correct :)

**Comment by hueldoeu** [comment]
fixed in 0.15.1 for me.

**Pull request merged**
