### PR TITLE
Improve player UI and navigability for Android TV

### LINKED ISSUE #7935: implement repeat/loop for Android TV
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [x] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

i think the most logical/intuitive way to add this would be to add a repeat checkbox in the tempo/pitch menu under the fast forward checkbox (if this got implemented i would remove the playlist repeat opion as it would be a duplicate)

thank you

### Why do you want this feature?

right now i cannot use repeat/loop function on a tv with android 9, there is no notifications bar and playlist repeat button is not available (nor touch screen),

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Stypox**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
- As demonstrated in https://github.com/TeamNewPipe/NewPipe/pull/7894#issuecomment-1049331109 the in-player play queue controls were not reachable on Android TV; this PR fixes that.
- While fixing the issue above I noticed controls kept showing up at random below the play queue. I also fixed that.
- As requested in https://github.com/TeamNewPipe/NewPipe/pull/7894#issuecomment-1049331109 I made it so that player popup menus (e.g. quality) now use correct dark background theming, instead of setting a fixed dark color, so that when you touch on an item you now get the ripple or the focused color, instead of no feedback at all.
- The above issue also required me to use `androidx` `PopupMenu`s, otherwise strange things would happen on API 19 (it took me an hour to figure this out...)

I tested everything both on emulated phone API 19 and on emulated Android TV API 29, and everything worked well.

#### Fixes the following issue(s)

- See https://github.com/TeamNewPipe/NewPipe/pull/7894#issuecomment-1049331109
- Fixes #7935

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by peat80** [comment]
Great improvements. Works fine on real androidtv too. 👌

**Comment by peat80** [comment]
Should probably fix this recently opened issue too:

implement repeat/loop for Android TV #7935

**Comment by litetex** [comment]
> implement repeat/loop for Android TV https://github.com/TeamNewPipe/NewPipe/issues/7935

New PR please.

**Comment by Stypox** [comment]
@litetex I think what he meant is that this PR also fixes that issue (and it indeed does, even though it doesn't provide the exact solution requested there)

**Comment by townkat** [comment]
@peat80, @Stypox, i cannot find how i can use repeat/loop on this developement version on my Android 9 tv, also this dev version crashes after few seconds on some long clips for me

**Comment by peat80** [comment]
NewPipe android-tv-player_20220307_004734

@townkat press the marked button in the player ui and you will find out. 😀
Buttons were always there but without this pr they are not focusable with remote.

Have you an example url for a crashing clip to try? I personally did not experience any crashes yet while using this pr.

**Comment by peat80** [comment]
@townkat
There has to be more than one video in the queue for this button to appear. (It would make no sense to show when there is only one video. 😂)
If you enqueue a playlist or more than one video it should appear. So if you have the auto-enqeue next stream setting disabled and you start a video it does not show.

**Comment by litetex** [comment]
> but i still think "repeat current clip" should be in the tempo/pitch window, unrestricted by using a playlist, it is not intuitive how it is now, but still good that the function is present at least
>
> another observation as this bug fix seems to be about selecting interface items, i still cannot return to the playback bar to restore the playing clip, with the remote, after browsing some channel or search or go to menu/settings etc. with a clip playing, you know, the bar on the bottom with the current playing clip

Please open new issues for these problems (if there aren't already some open 😉)

**Review by litetex — APPROVED** [review]
Code LGTM

Did a quick test - couldn't find any problems
The testers also said that everything is ok → approved

**Pull request merged**
