### PR TITLE
Added Icelandic, Latvian, Malayalam to language selector

### LINKED ISSUE #9094: Clean up translations
In #9092 @AudricV noticed new, but empty translations.I took a closer look at Weblate: We have 
9 languages at 0% (0 of 721 translated) [ars, ay, ayc, dum, enm, ang, nds, ks, scn]
1 at 1% (1 of 721), [af]
1 at 1% (2 of 721), [kk]
1 at 1% (4 of 721), [si]
1 at 1% (13 of 721) [ace]
I suggest to remove those if no activity occurs until the next RC. T**his should be done by an admin on weblate,**

_Originally posted by @TobiGr in https://github.com/TeamNewPipe/NewPipe/issues/9092#issuecomment-1272626998_

-----

Done in #9179:

While cleaning up the translations, we should also add the new localisations to our in-app language chooser, e.g. see #5721. New languages are e.g. Icelandic. This is an **easy task which can be done by everybody** and might be good to get used to the codebase a little. Help is appreciated.

### PR DESCRIPTION
**Pull request by OneGuitars**
#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

 I downloaded newpipe-strings-is from NewPipe weblate. I created directory(values-is) in res.  I added strings (newpipe-strings-is) to values-is. I added Icelandic, Latvian, Malayalam to language selector.

#### Before/After Screenshots/Screen Record

<table>
  <tr>
    <th>Before</th>
    <th>After 1</th>
    <th>After 2</th>
  </tr>
  <tr>
    <td>Before</td>
    <td>After</td>
    <td>After</td>
  </tr>
</table>

#### Fixes the following issue(s)

- Addresses parts of #9094 

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by TobiGr — CHANGES_REQUESTED** [review]
Thank you for working on this.

Please do not upload translation files via GitHub. The changes need to be pulled from the weblate repository. I suggest to sync all translations in this step to prevent conflicts.
To add the weblate repo to your local git repo, run 
```sh
git remote add weblate https://hosted.weblate.org/git/newpipe/strings/
```
reset your feature branch to weblate's dev and apply the changes to `settings-key.xml`. Commit and force push the changes to this branch.

**Comment by OneGuitars** [comment]
Thanks to your guidance. I completed the task and deleted the files I had previously added manually. I have tested the language selector in alphabetical order and everything works fine. Please feel free to let me know if there are any more problems?

**Review by Stypox — APPROVED** [review]
Looks good to me, but let's wait for @TobiGr ;-)

**Review by TobiGr — APPROVED** [review]
Thank you.

I committed the pending changes in weblate, _rebased_ the PR on weblate/dev and removed some of the unneeded commits in the process.

**Comment by TobiGr** [comment]
@OneGuitars Just for internal tracking: was your PR part of the ANU SE course?

**Comment by OneGuitars** [comment]
> @OneGuitars Just for internal tracking: was your PR part of the ANU SE course?

Yes, I am taking this course.

**Pull request merged**
