### PR TITLE
Bump gradle

### PR DESCRIPTION
**Pull request by TacoTheDank**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

### 1st commit
- Add mavenCentral and de-prioritize jcenter (to make the project use mavenCentral first)
- Update groupie's artifact names (see [here](https://github.com/lisawray/groupie#try-it-out))

### 2nd commit
- Update buildTools 29.0.3 -> 30.0.3
- Update Android Gradle Plugin 4.1.3 -> ~4.2.1~ 4.2.2
- Update Gradle 6.8.3 -> ~7.1~ 7.1.1 (using git bash)
- Fix a bunch of Gradle-related deprecations (existing and new)

#### Fixes the following issue(s)
- Fixes using old versions, gets us closer to removing jcenter :) (only one (1) library stands in the way: ExoPlayer)

#### APK testing 
On the website the APK can be found by going to the "Checks" tab below the title and then on "artifacts" on the right.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jimman2003** [comment]
If you add google() (google maven repo) you may be able to get rid of jcenter  see:https://github.com/google/ExoPlayer#using-exoplayer

**Comment by TobiGr** [comment]
> If you add google() (google maven repo) you may be able to get rid of jcenter see:https://github.com/google/ExoPlayer#using-exoplayer
> `allprojects { repositories { google() ...}}}`

Not in this PR, see #5843

**Review by Stypox — DISMISSED** [review]
Thank you! I tried building on my PC and everything went well. I tested the app on API 19 emulated and my API 29 phone and there were no issues whatsoever.

**Comment by TacoTheDank** [comment]
@Stypox Thanks! Also, I repushed the last commit to update Android Studio to 4.2.2, as well as Gradle to 7.1.1. Feel free to test it again if you wish, although it shouldn't affect anything at all :)

**Review by Stypox — APPROVED** [review]

**Pull request merged**
