### PR TITLE
Improve playlist dialogs, use only one layout

### PR DESCRIPTION
**Pull request by Stypox**
#### What is it?
- [x] Bug fix (user facing)
- [ ] Feature (user facing)
- [x] Code base improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
Use the same class and the same layout both to append an item to a local playlist and to choose a local/remote playlist tab. The resulting `PlaylistDialog` class is the result of a merge between the old `local.dialog.Playlist*Dialog` and `SelectPlaylistFragment` classes. In particular:
- The custom adapter found in `SelectPlaylistFragment` has been kept, to allow for both local and remote items to exist in the list
- The correct state saving behaviour is taken from `local.dialog.PlaylistDialog`
Fixes ui issues with the select playlist tab dialog, which didn't show uploaders and stream counts, looked strange and had double title on Android 4.4.

#### Depends on
#3982 (due to bug report fix)

#### Testing apk
Tested on emulated Android 4.4 and device Android 7.0.
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4987201/app-debug.zip)

#### Agreement
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by TobiGr** [comment]
I did not test if this is also in the current version, but the info should be aligned properly.
NewPipe_playlist-dialogs

**Comment by Stypox** [comment]
@TobiGr that's unrelated from this PR, let's create an issue

**Comment by Domiuns** [comment]
I have find bug 
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ IT
* __Content Language:__ it-IT
* __App Language:__ it_IT
* __Service:__ none
* __Version:__ 0.19.6
* __OS:__ Linux Android 4.4.4 - 19
<details><summary><b>Crash log </b></summary><p>

```

```
</details>
<hr>

**Comment by Domiuns** [comment]
Add to playlist button make app crash :( 
https://i.imgur.com/VQEVqqa.jpg
I paste an "log" yes "log" because is empty.
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ IT
* __Content Language:__ it-IT
* __App Language:__ it_IT
* __Service:__ none
* __Version:__ 0.19.6
* __OS:__ Linux Android 4.4.4 - 19
<details><summary><b>Crash log </b></summary><p>

```

```
</details>
<hr>

I think log report have problem

**Comment by Stypox** [comment]
Hi @Domiuns , thank you for testing ;-)
Unfortunately I am unable to reproduce on the emulator. Could you point out the exact steps leading to the crash since opening the app?

Since you have Android 4.4, would you like to join the testers (@mentioned in PRs needing tests on old devices)? If so, please add yourself here: https://github.com/TeamNewPipe/NewPipe/wiki/Testers

**Comment by Domiuns** [comment]
Hi @Stypox the app crash happens in all sections, I just press add to the playlist (I loaded the zip file with the old configurations) but I also tried with a clean installation and the app continues to crash. try the feed section or the trend section

**Comment by Stypox** [comment]
@Domiuns in #3982 I fixed the problem you had with missing stack trace. Could you test this new apk and provide me the bug report, which should now be non-empty?
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4987201/app-debug.zip)

**Comment by litetex** [comment]
@Stypox 
Any progress here?
Or should we close this?

**Comment by Stypox** [comment]
This would have to be redone from scratch, as there have been changes in the meantime. Closing it

**Comment by litetex** [comment]
Some cleanup will be done with #7194

**Pull request closed without merging**
