### PR TITLE
Add updating section to README

### PR DESCRIPTION
**Pull request by gkeegan**
This will help cull the number of "how to update?" Issues whenever we need to push out a fix, like how recently NewPipe got completely broken.

This attempts to be an all-inclusive guide to updating NewPipe. If there are any (clean/official) links to additional info, please comment them and I will add it.

Also let me know if this section should be relocated within the README. I figured it would be best to keep it up top, so people see it right away, and then don't make a new Issue.

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by theScrabi** [comment]
Yea that is ok I guess, ee should put it into te faq as well.

**Comment by gkeegan** [comment]
@theScrabi What location within the Readme should this be put? On second thought it seems odd to have it above the screenshots and other parts. Could it be better to just have a "Having issues updating to the newest version" link at the top like how Screenshots, Description, Features, etc. do?

**Comment by TobiGr** [comment]
> Yea that is ok I guess, ee should put it into te faq as well.

 @theScrabi Put it on my list 👍 
@gkeegan can you please add a link to #1981 which resolves the problem with different signing keys? @theScrabi Is there a way other people except you and theAssasin can help to get reproducible builds running? If yes, we could add an encouragement to maybe find someone who can help.

**Comment by theScrabi** [comment]
Wupwup merged PR 2048. This means until 4096 I am not able to continue.

**Pull request merged**
