### PR TITLE
Add subscribe button next to channel name

### LINKED ISSUE #7277: Add SUBSCRIBE button next to channel name while watching a video.
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

Add a subscribe button next to the channel name while watching a video like youtube does it.

### NewPipe UI
IMG_20211019_104504

### YouTube UI
IMG_20211019_104547

#### Why do you want this feature?

It will be easier to subscribe a channel while watching their content without opening the channel. Right now you have to open their channel to subscribe.

### PR DESCRIPTION
**Pull request by u7284728**
#### What is it?
- [ ] Bugfix (user facing)
- [X] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Added subscribe button next to the channel name when watching a video. Moved the location of likes and views so that the subscribe button fits nicely (see the below screenshots). 
- NOTE: This change is only on the UI and the button does not currently do anything. I was hoping that this could be used to then implement the workings of the button in the backend with this UI change.

#### Before/After Screenshots/Screen Record

- Before: 
image

- After:
image

#### Fixes the following issue(s)

- See #7277

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [X] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by tsiflimagas** [comment]
Or it could be done the way it is in YT app, kinda. Views and likes can be horizontally aligned (keeping them to the left and right position of the screen, as they are), and add a proper amount of vertical padding from the title.

**Comment by opusforlife2** [comment]
Yeah, the current modification looks like they are being stuffed wherever space was found.

Also, if your button doesn't actually do anything, then don't link to the issue. It will be closed automatically if the PR is merged, which is misleading in this case.

**Review by Stypox — COMMENTED** [review]
This won't be merged until the button action is implemented, sorry. The behavior of the button should be exactly the same as that in the channel screen.

Also, I don't like the UI. I don't think there is a good solution right now, unfortunately, see https://github.com/TeamNewPipe/NewPipe/issues/7277#issuecomment-1291006163. This should go back to the drawing board, i.e. the issue, and let's see if anybody has a solution.

**Review by TobiGr — CHANGES_REQUESTED** [review]
blocked for the reasons stated above.

**Comment by u7284728** [comment]
I agree with what others have said, sorry I didn't realise that this was not what people wanted and further discussion on the issue page itself would be great to give more understanding of what is best and to find the optimal solution. Others are welcome to take up the task of fixing. Thanks.

**Comment by Stypox** [comment]
Thanks to you for trying :-)

**Pull request closed without merging**
