### PR TITLE
Use ContextCompat.getSystemService() where possible.

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
#### What is it?
- [ ] Bug fix (user facing)
- [ ] Feature (user facing)
- [x] Code base improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Use `ContextCompat.getSystemService()` wherever possible to avoid unnecessary casting.
- In blocks of code that run only on Android Marshmallow or higher, call `Context.getSystemService(Class)` instead of `Context.getSystemService(String)`.

#### Testing apk

[debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4832341/debug.zip)

#### Agreement
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by Redirion** [comment]
LGTM but why did you have to make a commit for each changed file?

**Comment by Isira-Seneviratne** [comment]
> 
> 
> LGTM but why did you have to make a commit for each changed file?

Shall I combine them into one commit, then?

**Comment by TobiGr** [comment]
Yes, please

**Comment by opusforlife2** [comment]
@Isira-Seneviratne Hey. You've opened over a 100 PRs by this point, I think. xD Would you like to join the team as a developer?

**Comment by Isira-Seneviratne** [comment]
> @Isira-Seneviratne Hey. You've opened over a 100 PRs by this point, I think. xD

Oh, wow. 😂

> Would you like to join the team as a developer?

Sure, sounds good to me.

**Comment by opusforlife2** [comment]
@Isira-Seneviratne If you go to the homepage of the repo or the org, you should see an invite.

**Comment by opusforlife2** [comment]
Awesome. I forgot: do you have a Matrix account? If not, could you make one and join our IRC channel?

**Comment by Isira-Seneviratne** [comment]
> Awesome. I forgot: do you have a Matrix account? If not, could you make one and join our IRC channel?

Sure, I'll do that. Could you send the IRC channel?

**Comment by opusforlife2** [comment]
#newpipe:libera.chat

**Comment by Isira-Seneviratne** [comment]
> #newpipe:libera.chat

Thanks, I'll join tomorrow, since it's pretty late at my time.

**Comment by opusforlife2** [comment]
@Isira-Seneviratne Yo. Can't see you in the channel.

**Comment by Isira-Seneviratne** [comment]
> @Isira-Seneviratne Yo. Can't see you in the channel.

Sorry about that, been a bit busy these days. I'll join today.

**Pull request closed without merging**
