### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by B0pol**
fix typo

#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
fix typo

#### Fixes the following issue(s)

- 

#### Relies on the following changes

- 

#### APK testing 

On the website the APK can be found by going to the "Checks" tab below the title and then on "artifacts" on the right.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TobiGr** [comment]
Not to dev. the transnlations ahve not been merged to dev. See #5904

**Comment by B0pol** [comment]
this one has already been merged to dev, because it was in another pull request

**Comment by Stypox** [comment]
Shouldn't this go to weblate?

**Comment by B0pol** [comment]
This string isn't on weblate …

**Comment by Stypox** [comment]
Oh, right

**Pull request merged**
