### PR TITLE
Remove GSON lib

### PR DESCRIPTION
**Pull request by acrosca**

### CODE REVIEW

**Comment by theScrabi** [comment]
Could you please giva a description, for example why to remove the gson lib.

**Comment by acrosca** [comment]
Removing GSON reduces method count (1345), apk size (188Kb).

The project does not need a large and powerful JSON parser to serialize/deserialize a single class.
Having fewer dependencies is a good thing.

**Comment by wb9688** [comment]
Yeah, and it's also weird that we use another JSON parser in NewPipeExtractor.

**Comment by theScrabi** [comment]
All right.

**Pull request merged**
