### PR TITLE
Make Turkish translate more accurate

### PR DESCRIPTION
**Pull request by berkaygunduzz**
#### What is it?
- Translate correction

#### Description of the changes in your PR

When i'm using NewPipe, i see some irritating mistakes at Turkish translate. I fixed some of them:
##### Word Translation Corrections: 
- öntanımlı (default) --> varsayılan ("varsayılan" is more common and correct)
- davranış (behavior) --> tercihler (We use "davranış" for humans, animals etc. "tercihler" means "preferences" but it's more suitable for that)
- yeğlenen (preferred) --> tercih edilen ("tercih edilen" is more common and correct Turkish)
- kip (mode) --> mod (We don't use "kip" for that pupose, it sounds like Google Translate, "mod" is the right word for that meaning)
- besleme (feed) --> akış (We use "besleme" for like "feeding cats", "akış" is more suitable for that)
- sıkı (compact) --> küçük (We use "sıkı" for "fit", "küçük" means "small" but it's more suitable for that)
- sağlama (checksum) --> doğrulama ("doğrulama" is more correct for that)
- küme (group) --> grup (We use "küme" for "sets in math", "grup" is more suitable)
- adanmış (dedicated) --> özel (We use "adanmış" for like "divine", "özel" is more suitable)

##### Grammar Corrections:
- açılır pencere oynatıcına --> açılır pencere oynatıcısına ("-sı" is needed for Turkish grammar)
- başlatma gerektirir --> başlatmak gerekir (More accurate for Turkish grammar)
- altyazı --> alt yazı (It should be seperated for grammar rules)
- Oynatma Listesine Ekle --> Oynatma listesine ekle (Just for making capitalized words same with others)
- "error_report_open_github_notice" translated more accurate and meaningful

#### Fixes the following issue(s)

- My irritation

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by berkaygunduzz** [comment]
Is it possible to see what i did wrong with security?

**Comment by opusforlife2** [comment]
@berkaygunduzz You're supposed to use Weblate for translation fixes. https://github.com/TeamNewPipe/NewPipe#contribution

**Comment by berkaygunduzz** [comment]
@opusforlife2 I know but it doesn't give me control, all my contribution is being wasted. For example i translated error messages when they implemeted first, but after that i see wrong translated messages on app.

**Comment by B0pol** [comment]
Because newpipe does not download and update translations, it only update translation every update.

Then you should wait for 0.20.3

**Comment by berkaygunduzz** [comment]
@opusforlife2 @B0pol then i'm sorry for wasting your time.

**Pull request closed without merging**
