### PR TITLE
Add functionality to rename Playlist Name from playlist interface

### LINKED ISSUE #5570: More logic renaming of playlists
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Make the user able to change the name of playlists using the 3 dots on the playlist interface. 

#### Is your feature request related to a problem? Please describe it

Many Android apps use the 3 dots to set basic functions and Newpipe is missing the basic use of 3 dots.

#### Additional context

Use of the 3 dots of playlists: 
Imagepipe_0

#### How will you/everyone benefit from this feature?

It will make the use similar to many Android apps. Although the ability to change the playlist's name is already there by pressing the playlist box on the playlist area, it would make the use more simple.

### PR DESCRIPTION
**Pull request by PulkitGarg67**
#### What is it?
- [ ] Bugfix (user facing)
- [X] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Functionality to rename Playlist Name from playlist interface

#### Fixes the following issue(s)

- Fixes #5570

#### APK testing 

On the website the APK can be found by going to the "Checks" tab below the title and then on "artifacts" on the right.

#### Due diligence
- [X] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Redirion** [comment]
thanks for your contribution! However I don't understand why you did basically add doubled code. What was the reason not to use createRenameDialog() ?

Also please refrain from using hardcoded text, use String resources please so that text can be translated.

**Comment by PulkitGarg67** [comment]
Thanks for the information. I have updated the code accordingly.

**Comment by Stypox** [comment]
@Redirion I've assigned this to you, feel free to merge if you think it is ready. Code looks fine to me, but I did not test.

**Comment by Redirion** [comment]
tested, works. @PulkitGarg67 can you squash your two commits into one? 

git reset --soft HEAD~2
git add .
git commit -m "rename Playlist Name from playlist interface"
git push -fu origin issue5570

**Comment by Stypox** [comment]
@Redirion you can squash and merge via GitHub

**Review by Redirion — APPROVED** [review]

**Pull request merged**
