### PR TITLE
Make all buttons in player have selectable item background borderless

### PR DESCRIPTION
**Pull request by Stypox**
#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
I replaced all `selectableItemBackground`s in the player with `selectableItemBackgroundBorderless`, so that the press animation looks better. I also did this to text buttons (fit-fill-zoom, captions, resolution, time), and I think it is better than non-borderless even though there are some small issues: the text changing when tapping fit-fill-zoom and when opening the resolution menu (MPEG-4 is added to the string) causes some artifacts in the animation, and the captions button, since it contains a long text, causes a big circle. Please provide your feedback :-)
I also ran `CTRL+ALT+L` to auto format and fixed some RTL warnings.

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by litetex** [comment]
Code looks good 👍 

However the background when tapping the button gets a bit too big on some buttons in my opinion:
grafik
Personally I was fine with the rectangular background-buttons 😄

**Comment by opusforlife2** [comment]
Before/after screenshot, pls.

**Comment by TiA4f8R** [comment]
I think we should keep the rectangular background for ratio, subtitles and quality selector commands.

**Comment by Stypox** [comment]
> Before/after screenshot, pls.

I would have to upload something like twenty screenshots, one for each button, so I don't think it would be much useful in this case.

> I think we should keep the rectangular background for ratio, subtitles and quality selector commands.

I did this @TiA4f8R @litetex

**Review by litetex — APPROVED** [review]
LGTM

I'm personally okay with the changes 😄

**Comment by opusforlife2** [comment]
> one for each button

Just one example would be enough, I think? It's only needed to get an idea of what the change looks like. I can't figure that out from your description.

**Comment by Stypox** [comment]
<table>
  <tr>
    <th>Before</th>
<th>After</th>
  </tr>
  <tr>
    <td>  </td>
<td> </td>
  </tr>
</table>

**Comment by opusforlife2** [comment]
Thanks, @Stypox. After seeing the screenshot, I agree with TiA4f8R. The icons certainly look better with a circular background, but text menus should still have a rectangular one.

> I think we should keep the rectangular background for ratio, subtitles and quality selector commands.

**Comment by Stypox** [comment]
Ok, that's done (only the speed selector still has a circular background), thanks for the feedback ;-)

**Comment by Stypox** [comment]
(just tested on API 19 emulated and it works)

**Pull request merged**
