### PR TITLE
Call DateWrapper's offsetDateTime() instead of date().

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Fixes an issue [mentioned](https://github.com/TeamNewPipe/NewPipe/issues/4851#issuecomment-730120966) by @opusforlife2.

#### APK testing 

[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5570398/app-debug.zip)

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by opusforlife2** [comment]
April's Fool? There's no APK to test. xD

**Comment by Isira-Seneviratne** [comment]
> April's Fool? There's no APK to test. xD

My bad :P
I've uploaded an APK now.

**Comment by opusforlife2** [comment]
Fixed!

**Review by TobiGr — APPROVED** [review]
Thanks

**Comment by opusforlife2** [comment]
@Isira-Seneviratne This worked for the debug build, but in the 0.20.4 release Newpipe keeps crashing and opening in an infinite loop, just like another open issue here describes.

Could you test this with both a debug and a release build?

**Comment by Isira-Seneviratne** [comment]
> @Isira-Seneviratne This worked for the debug build, but in the 0.20.4 release Newpipe keeps crashing and opening in an infinite loop, just like another open issue here describes.
> 
> Could you test this with both a debug and a release build?

I think the issue you're talking about has been fixed [here](https://github.com/TeamNewPipe/NewPipe/pull/4995).

**Comment by opusforlife2** [comment]
Sure? There is no crash report involved here. Just loading Newpipe after it's booted from RAM. I could ask for a release build there if you're certain, though.

**Comment by Isira-Seneviratne** [comment]
> Sure? There is no crash report involved here. Just loading Newpipe after it's booted from RAM. I could ask for a release build there if you're certain, though.

I'll apply the changes and see if I encounter any issues.

**Comment by Isira-Seneviratne** [comment]
After making `ErrorInfo`'s constructor public, the error activity displays without issue.

Screenshot_20201127-161734701

**Comment by opusforlife2** [comment]
Wait, I'm confused now.

When I reported the issue and you provided a debug build to test, it worked fine.

But the 0.20.4 release build doesn't work. Assuming there were no changes to the relevant code between this PR and the release, that means something is going wrong in the release builds.

Even after that public constructor PR is merged, it still leaves the problem that Newpipe is crashing upon resuming if it was removed from RAM. Somehow, this is fixed in debug builds, but not in release builds.

Is that correct?

**Comment by Isira-Seneviratne** [comment]
> Wait, I'm confused now.
> 
> When I reported the issue and you provided a debug build to test, it worked fine.
> 
> But the 0.20.4 release build doesn't work. Assuming there were no changes to the relevant code between this PR and the release, that means something is going wrong in the release builds.
> 
> Even after that public constructor PR is merged, it still leaves the problem that Newpipe is crashing upon resuming if it was removed from RAM. Somehow, this is fixed in debug builds, but not in release builds.
> 
> Is that correct?

I tried minimizing and then restoring the app, but I didn't encounter any issues 😕

**Comment by opusforlife2** [comment]
:O

So if you open a bunch of RAM hungry apps again and again and then try to resume a paused video in the main player, it restores state successfully? (The 'Minimize' setting should be set to 'None' so that there is no notification when the main player is paused.)

**Comment by Isira-Seneviratne** [comment]
I didn't encounter any issues with that setting either

**Comment by opusforlife2** [comment]
ಠ▃ಠ

This calls for a logcat.

[Newpipe.txt](https://github.com/TeamNewPipe/NewPipe/files/5610351/Newpipe.txt)

**Comment by Isira-Seneviratne** [comment]
> ಠ▃ಠ
> 
> This calls for a logcat.
> 
> [Newpipe.txt](https://github.com/TeamNewPipe/NewPipe/files/5610351/Newpipe.txt)

It seems like an issue with `ErrorInfo`'s constructor, but that shouldn't be the case, it's now a public constructor.

**Comment by opusforlife2** [comment]
This is the 0.20.4 release. It looks like I'll need a release build of the ErrorInfo PR.

@XiangRongLin Could you upload a release APK with your change, please?

**Comment by opusforlife2** [comment]
Yoohoo! Now that 0.20.5 is finally out, I could get a proper error report.

It's the same exception as the original, but from a different function this time.

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ CH
* __Content Language:__ en-IN
* __App Language:__ en_IN
* __Service:__ none
* __Version:__ 0.20.5
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'char java.lang.String.charAt(int)' on a null object reference
	at j$.util.DesugarGregorianCalendar.from(:1)
	at org.schabi.newpipe.util.Localization.relativeTime(Localization.java:317)
	at org.schabi.newpipe.info_list.holder.StreamInfoItemHolder.getFormattedRelativeUploadDate(StreamInfoItemHolder.java:98)
	at org.schabi.newpipe.info_list.holder.StreamInfoItemHolder.getStreamInfoDetailLine(StreamInfoItemHolder.java:83)
	at org.schabi.newpipe.info_list.holder.StreamInfoItemHolder.updateFromItem(StreamInfoItemHolder.java:65)
	at org.schabi.newpipe.info_list.InfoListAdapter.onBindViewHolder(InfoListAdapter.java:337)
	at org.schabi.newpipe.info_list.InfoListAdapter.onBindViewHolder(InfoListAdapter.java:360)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
	at android.view.View.layout(View.java:20693)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
	at android.view.View.layout(View.java:20693)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
	at android.view.View.layout(View.java:20693)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
	at android.view.View.layout(View.java:20693)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20693)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20693)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
	at com.google.android.material.bottomsheet.BottomSheetBehavior.onLayoutChild(BottomSheetBehavior.java:414)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
	at android.view.View.layout(View.java:20693)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
	at android.view.View.layout(View.java:20693)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20693)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20693)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20693)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20693)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:753)
	at android.view.View.layout(View.java:20693)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2799)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2316)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1463)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7190)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```
</details>
<hr>

**Comment by Stypox** [comment]
@Isira-Seneviratne ^

**Comment by Isira-Seneviratne** [comment]
I'll check it out.

It seems like the zone ID is being set to null for whatever reason, even though its documentation explicitly says that it's non-null.

**Comment by Isira-Seneviratne** [comment]
It's working fine on my device 😕



In any case, I have a potential workaround, and I'll link to it here. @opusforlife2 could you see if it works for you?

**Comment by Isira-Seneviratne** [comment]
https://github.com/TeamNewPipe/NewPipe/pull/5067

**Pull request merged**
