### PR TITLE
Extract settings import

### PR DESCRIPTION
**Pull request by XiangRongLin**
#### What is it?
- [x] Codebase improvement (dev facing)

#### Description of the changes in your PR

- Extract logic for settings import out of `ContentSettingsFragment` into `ContentSettingsManager` and `ZipHelper`
- Add basic unit tests for `ContentSettingsManager`
- Introduce `NewPipeFileLocator` which resolves the db and settings files. Inject it into `ContentSettingsManager`
- remove subclass `ExportTest`. No benefit with only one test
- added real zip file and newpipe.settings of export as test resources 

#### APK testing 

~~[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5719734/app-debug.zip)~~

https://github.com/TeamNewPipe/NewPipe/actions/runs/459642451

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

#### Notes
- The git history went wide, because while extracting it I found my initial approach for DI and testing not good. Easiest would be to just squash everything together.
- With this changes to the import/export logic should always be covered by additional unit tests

### CODE REVIEW

**Review by Stypox — APPROVED** [review]
Looks good to me. Thank you!

**Comment by Stypox** [comment]
I am unable to run `ContentSettingsManagerTest` on my machine:
```
Cannot mock/spy class org.schabi.newpipe.settings.NewPipeFileLocator
Mockito cannot mock/spy because :
 - final class
 ```
 
If I make `NewPipeFileLocator` an `open` class (in kotlin classes are `final` by default), I get null pointer exceptions whenever something is being mocked, like `'when'(fileLocator.db).thenReturn(db)`.

**Comment by XiangRongLin** [comment]
Did you sync the Gradle files? Because the mockito-inline dependency should fix the problem with mocking final classes

**Comment by XiangRongLin** [comment]
@Stypox the `NullPointerException`occurs for the same reason. Methods are final by default, so mockito can't mock then out of the box.

**Pull request merged**
