### PR TITLE
Add ability for beta build in fdroid

### PR DESCRIPTION
**Pull request by theScrabi**
This adds the ability to release beta versions of our app, as discussed [here](https://github.com/TeamNewPipe/NewPipe/issues/681).

Your opinion pls.

### CODE REVIEW

**Comment by wb9688** [comment]
Something about that logo doesn't feel right. Btw is there a reason that it
isn't minifyEnabled?

**Comment by theScrabi** [comment]
No I forgot it. I'll fix that.

**Comment by theScrabi** [comment]
This is the description I want to use on fdroid:

CAUTION: This is a test version of the NewPipe App. Please consider that this version might haver errors, and might not work in some point. Use at your own risk.

Lightweight YouTube frontend that's supposed to be used without the proprietary YouTube-API or any of Google's (proprietary) play-services. NewPipe only parses the YouTube website in order to gain the information it needs.

This a very early version of the app, so not all functionality is implemented, and there may still be a lot of bugs. But all in all it's doing what it is supposed to do. It makes it possible to watch YouTube videos. So don't be cruel to this app. It will improve...

**Comment by coffeemakr** [comment]
I've done some testing to minify the app on [my branch](coffeemakr/NewPipe/tree/feature-minify-app)
You can cherry-pick the commit 401cda49a71001078f73acc6bf6d472a425b2c3a if you want. Maybe it needs some adaption.

**Comment by theScrabi** [comment]
Ok here is a [pull request](https://github.com/TeamNewPipe/NewPipe/pull/691) for enabling minify.

**Comment by theScrabi** [comment]
What do you think of this?

whatsapp image 2017-09-14 at 21 44 19
whatsapp image 2017-09-14 at 21 39 52

**Comment by theScrabi** [comment]
Previous discussion here: https://github.com/TeamNewPipe/NewPipe/issues/681

**Comment by theScrabi** [comment]
I locked down master branch.

**Comment by mauriciocolli** [comment]
Now that it comes to mind, I think that it'll mess up with the WebLate system. A simple solution is to change the target branch to dev.

**Comment by theScrabi** [comment]
You are right, I have to fix that asap.

**Comment by mauriciocolli** [comment]
@theScrabi wouldn't make sense to make the `dev` branch the default one too?

**Comment by theScrabi** [comment]
i set up dev branch as main branch. Also since I don't know how to tell weblate to push to another branch, i gave it access to master, although thats a REAL bad solution.

**Comment by mauriciocolli** [comment]
Yes **it is**, I think you can do it by going into the Administration panel in WebLate and settting up the url.

Btw, it is pointing to the old url (https://github.com/theScrabi/NewPipe.git) and when you change to the new, maybe it will point to the default branch automatically.

**Comment by theScrabi** [comment]
bildschirmfoto vom 2017-09-19 19-08-44

This is what it looks like to me.  (At least that was what I found looked like an adminpannel the most).
However according to [docs](https://docs.weblate.org/en/latest/admin/projects.html#project-configuration) there should be more options.

**Comment by mauriciocolli** [comment]
@theScrabi I saw in the doc that the url is https://hosted.weblate.org/admin, did you tried that?

**Comment by theScrabi** [comment]
Ahh I see. The problem is that I can only access this if we would host this our self. However this is hosted by the people from Weblate.
I guess I have to write them a mail then.

**Comment by mauriciocolli** [comment]
Oh now I realized that the `/admin` if for people who host their WebLate instance, sorry about that.

**Comment by theScrabi** [comment]
No thats good. I wrote Michal Čihař a mail, now, so hopefully he will change that for us :)

**Comment by theScrabi** [comment]
I merged wit dev, so I close this here.

**Comment by mauriciocolli** [comment]
@theScrabi any news about WebLate?

**Comment by theScrabi** [comment]
He didn't answer yet.

**Comment by mauriciocolli** [comment]
People are already adding words to translate in the `strings` files in their pull requests (myself included).

In the mean time, I think we'll have to pass the changes to the master anyway (which is **_not_** ideal, but due to the circumstances...).

**Comment by theScrabi** [comment]
Yes for now thats still ok.

**Comment by mauriciocolli** [comment]
@theScrabi I've just used the "Contact us" button at the bottom of the page, I think we'll have more success using it.

**Comment by theScrabi** [comment]
Hopefully. Thank you.

**Comment by mauriciocolli** [comment]
That was quick :) 
https://hosted.weblate.org/projects/newpipe/strings/en/#information

**Comment by theScrabi** [comment]
I've seen. :)

**Pull request closed without merging**
