### PR TITLE
Re-add APK testing section to PR template

### PR DESCRIPTION
**Pull request by XiangRongLin**
#### What is it?
- [x] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Re-add APK testing section to PR template
- Add instructions on how to navigate to the APK created by the CI pipeline
- basically reverts #5284

#### Fixes the following issue(s)

- Here i asked a user to test the bug fix, but he did not know where to install the apk from https://github.com/TeamNewPipe/NewPipe/pull/5464#issuecomment-763735114

#### APK testing 

On the website the APK can be found by going to the "Checks" tab below the title and then on "artifacts" on the right.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

fyi @mhmdanas 

@brnwlshubh Would you find the description under the APK testing section sufficient for someone who hasn't used github beforehand?

### CODE REVIEW

**Comment by brnwlshubh** [comment]
@XiangRongLin @mhmdanas Yes I understand.

**Comment by brnwlshubh** [comment]
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ IN
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.20.8
* __OS:__ Linux samsung/on7xeltedd/on7xelte:8.1.0/M1AJQ/G610FDDU1CSK2:user/release-keys 8.1.0 - 27
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.RelativeLayout org.schabi.newpipe.databinding.ChannelHeaderBinding.getRoot()' on a null object reference
	at org.schabi.newpipe.fragments.list.channel.ChannelFragment.handleResult(ChannelFragment.java:443)
	at org.schabi.newpipe.fragments.list.channel.ChannelFragment.handleResult(ChannelFragment.java:69)
	at org.schabi.newpipe.fragments.list.BaseListInfoFragment.lambda$startLoading$0$BaseListInfoFragment(BaseListInfoFragment.java:135)
	at org.schabi.newpipe.fragments.list.-$$Lambda$BaseListInfoFragment$Gn1fP3-8OJnktT5gkmUmbW-egTg.accept(Unknown Source:4)
	at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:7000)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

```
</details>
<hr>

**Comment by brnwlshubh** [comment]
This report by different device:-

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ IN
* __Content Language:__ en-IN
* __App Language:__ en_IN
* __Service:__ none
* __Version:__ 0.20.8
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to read from field 'androidx.appcompat.widget.AppCompatButton org.schabi.newpipe.databinding.ChannelHeaderBinding.channelSubscribeButton' on a null object reference
	at org.schabi.newpipe.fragments.list.channel.ChannelFragment.updateSubscribeButton(ChannelFragment.java:353)
	at org.schabi.newpipe.fragments.list.channel.ChannelFragment.lambda$monitorSubscription$1$ChannelFragment(ChannelFragment.java:247)
	at org.schabi.newpipe.fragments.list.channel.-$$Lambda$ChannelFragment$00sQ8kobTMBsYnX1bMmu1QeN9lg.accept(Unknown Source:4)
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7405)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

```
</details>
<hr>

**Comment by mhmdanas** [comment]
@XiangRongLin yes, I agree that it was too early for my PR to be merged.

**Comment by XiangRongLin** [comment]
@brnwlshubh thanks for the feedback. 

This thread is about adding how to get the APK from a pull request.
So if you have more information, add that to the other thread #5464 and not here

**Comment by brnwlshubh** [comment]
@XiangRongLin Sure sir

**Review by mhmdanas — APPROVED** [review]

**Pull request merged**
