### PR TITLE
Optimize assets.

### PR DESCRIPTION
**Pull request by RDKRACZ**
#### What is it?
- [x] Meta improvement to the project (dev facing) **I THINK**
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)

#### Description of the changes in your PR
Lossless compression. I used oxipng.

#### Before/After Screenshots/Screen Record
No visual differences

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [X] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Stypox** [comment]
What is the APK size difference?

**Comment by mhmdanas** [comment]
@Stypox I'll check and come back with the results.

**Comment by mhmdanas** [comment]
I built a release APK for each of this PR's commit and the previous commit. This PR's APK is 8904298 bytes long, while the previous APK is 8906273 bytes long, a difference of around 2 kilobytes.

**Review by mhmdanas — CHANGES_REQUESTED** [review]
I believe it may not be worth it to minify anything not included in the APK, as I believe it would increase the Git repo's size, as Git does not store diffs of binary files (correct me if I'm wrong though).

**Comment by TobiGr** [comment]
Minimizing the screenshots makes sense to me, because that results in faster loading of the readme

**Comment by Stypox** [comment]
> Minimizing the screenshots makes sense to me, because that results in faster loading of the readme

Also to me

**Review by mhmdanas — APPROVED** [review]

**Comment by mhmdanas** [comment]
@RDKRACZ thanks!

**Pull request merged**
