### PR TITLE
Ensure order of search history entries in tests

### LINKED ISSUE #7553: CI pipeline maybe flaky (HistoryRecordManagerTest#deleteSearchHistory)
### Checklist

- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

The CI pipeline failed on the android tests. It fixed itself after rerunning it, which could indicate a flaky test.
This Issue should serve as place to collect the logs and discuss the problem if it occurs more often. If it does not occur again this can be closed.

### Logs
```
org.schabi.newpipe.local.history.HistoryRecordManagerTest > deleteSearchHistory[test(AVD) - 5.0.2] FAILED 
	java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)

> Task :app:connectedDebugAndroidTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:connectedDebugAndroidTest'.
```
Log of failed CI job: [logs_5027.zip](https://github.com/TeamNewPipe/NewPipe/files/7740706/logs_5027.zip)
https://github.com/TeamNewPipe/NewPipe/runs/4571396354?check_suite_focus=true

### PR DESCRIPTION
**Pull request by XiangRongLin**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Ensure order of search history entries in tests

#### Fixes the following issue(s)

- Fixes #7553

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

❗  squash merge

### CODE REVIEW

**Review by litetex — COMMENTED** [review]
LGTM, however the same problem might also happen here:
https://github.com/TeamNewPipe/NewPipe/blob/4a7cfd1a6cc63a95140c03a937c9f607303e1a57/app/src/androidTest/java/org/schabi/newpipe/local/history/HistoryRecordManagerTest.kt#L147

Could you fix it also there? 
A constant would be great 😄

**Comment by XiangRongLin** [comment]
> however the same problem might also happen here:

How would it also happen there? every line has the `.minusSeconds(x)`

**Comment by litetex** [comment]
@XiangRongLin 

The problem here is that the value can't be controlled by the test.
``OffsetDateTime.now()`` is not a constant, if there is e.g. a leap second or system clock update between the two lines in https://github.com/TeamNewPipe/NewPipe/blob/4a7cfd1a6cc63a95140c03a937c9f607303e1a57/app/src/androidTest/java/org/schabi/newpipe/local/history/HistoryRecordManagerTest.kt#L147-L148 the test might fail.

I'm strongly in favor of implementing a hard-coded/current time independent timestamp like
```java
OffsetDateTime.of(LocalDateTime.of(2000, 1, 1, 1, 1), ZoneOffset.UTC)
```
and then use that one for the tests.

**Comment by litetex** [comment]
There seems to be something wrong with the test on Emulator API 29:
```
org.schabi.newpipe.local.history.HistoryRecordManagerTest > onSearched[test(AVD) - 10] FAILED 
	org.junit.runners.model.TestTimedOutException: test timed out after 1 seconds
	at org.assertj.core.internal.Strings.instance(Strings.java:118)
```

not sure what's causing that but according to https://stackoverflow.com/questions/17016011/junit-test-times-out-despite-executing-quickly and 
grafik
 it has has be an ``InterruptedException`` inside
https://github.com/TeamNewPipe/NewPipe/blob/3c21be8fa5d66383d2fb1b2d4be28d2e409b2929/app/src/androidTest/java/org/schabi/newpipe/local/history/HistoryRecordManagerTest.kt#L44-L53

**Comment by litetex** [comment]
Above error should be fixed with https://github.com/TeamNewPipe/NewPipe/pull/7670/commits/a6515d5450d4eac4b85b9644ea3dfa9d7140a49c.
There seems to be a performance problem with GH actions which causes the Android API 29 test do not run fast enough (needs more than 1s) on the VM which causes the above problems.

The internal was - for a unknown reason - changed from 10s to 1s inside https://github.com/TeamNewPipe/NewPipe/commit/7d6688f4976d1c998938843f5c29d5db8c0ea7fc#diff-52b3c5a209220512cb671827511b090b467afb544abcd94da776e7273072ffc0R24

**Review by litetex — APPROVED** [review]
LGTM

**Pull request merged**
