### PR TITLE
Migrate to AndroidX

### PR DESCRIPTION
**Pull request by Redirion**
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

This is a second attempt following to my failed PR #2372.

Copy from the original description of the PR:

ExoPlayer 2.10. moved forward to use AndroidX. NewPipe should keep up for easy integration of the new ExoPlayer version and possible other benefits.

I have converted the project by using Android Studio 3.4.1 "Refactor -> Migrate to AndroidX" and made small adjustments afterwards to the build.gradle in the app module. Furthermore I have removed the FlingBehavior.java as the original path that was overwritten with it doesn't exist in AndroidX. The original git project that was referenced in it, also removed the file recently in this commit: ToDou/appbarlayout-spring-behavior@5575b3a
@yausername could you please check whether the custom FlingBehavior.java is still needed? You have added it initially with this commit: 9fc38b5

### CODE REVIEW

**Comment by Redirion** [comment]
:open_mouth: All cecks have passed!
Quick, merge it :smile:

**Comment by Redirion** [comment]
okay, comments and related views are missing (probably related to the removed FlingBehavior.

**Comment by theScrabi** [comment]
> okay, comments and related views are missing. Probably related to the removed FlingBehavior.

All right :) tell us when its fixed.

**Comment by Redirion** [comment]
I was not yet able to fix it. It appears that the app:layout_behavior="@string/appbar_scrolling_view_behavior" for the ViewPager in fragment_video_detail.xml is causing the problem. When I remove that line the comments and related videos are shown but using the complete screen.

I will have to investigate further.
@yausername do you maybe have an idea?

**Comment by yausername** [comment]
Hi, I'll have a look at it tonight.

**Comment by yausername** [comment]
I'm sorry but I didn't get time to check. I won't be able to dig into it until after the weekend.
However, I tried this PR https://github.com/TeamNewPipe/NewPipe/pull/2309 which also has androidx migration and it did work.

**Comment by Redirion** [comment]
... okay, looks like my PR is obsolete then. Well, it was a new experience ..

**Comment by TobiGr** [comment]
@Redirion Thanks for your work although we didn't merge it. Your ongoing contributions are important to the project :+1:

**Pull request closed without merging**
