### PR TITLE
Update ExoPlayer to 2.9.6

### PR DESCRIPTION
**Pull request by Redirion**
Updated ExoPlayer, its dependency OkHttp (to 3.12.1) and fixed all deprecations as a bonus

Tested a bit on Android 7.1.2. I will of course do some more testing, but looks good so far.

- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by Redirion** [comment]
Played a few videos in foreground and background without issues. What I am now inspecting is the removal of the CustomTrackSelector.java, which was a bug workaround over an issue with language normalization of ExoPlayer on version 2.7.0.
I have added some logging (not commited here of course to keep it clean) to see if my faith in removing that workaround was justified.

**Comment by Redirion** [comment]
Found an issue, but not the original NPE that was worked around by adding the CustomTrackSelector.java.
Normalization of caption language of ExoPlayer created lowercase names for languages that are written uppercase. Example from my logging:
    captionLanguage was normalized to: deutsch
    captionLanguage: Deutsch
    captionLanguage: English
    captionLanguage: français
    captionLanguage: italiano
    captionLanguage: português
    captionLanguage: español

this was fixed by adding a little helper method to search for matching caption languages case insensitive. Captions were working just fine, this last commit just fixed the captionTextView which would show R.string.caption_noneeven though captions were shown for the selected language.

**Comment by Redirion** [comment]
btw. note to Legacy version maintainer: the commit where I have removed checks for Jellybean were actually for compatibility with ICS (4.0). As 4.1 is the minimum version for the Legacy version this PR should cause no headache.

**Comment by Redirion** [comment]
in a few hours I will prepare a comment in which I go over each significant change in each file and explain it. This should make reviewing the pr easier.

**Comment by Redirion** [comment]
DownloadActivity.java
	- This method was deprecated in official Android API 16.

BasePlayer.java
	- see changes for PlayerHelper.java to see why BandwithMeter is not a parameter for getQualitySelector anymore
	- Call to ExoPlayerFactory.newSimpleInstance now requires a Context parameter

MainVideoPlayer.java
ServicePlayerActivity.java
	- Just got rid of unnecessary workarounds for old API 15.

VideoPlayer.java
	- Little adjustments to use ExoPlayers'DefaultTrackSelector instead of the CustomTrackSelector

AudioReactor.java
	- adding or removing AudioRendererEventListener to SimpleExoPlayer was deprecated in ExoPlayer
	- Cleaned up empty methods instead of trying to find a matching alternative with AnalyticsListener

CacheFactory.java
	- TransferListener does not have generic type arguments anymore in ExoPlayer

LoadController.java
	- Using the Builder instead of the deprecated context of ExoPlayer is more convenient:
	the DefaultAllocator and DEFAULT-constants are already set there.

PlayerDataSource.java
	- using setMinLoadableRetryCount was deprecated in ExoPlayer

PlayerHelper.java
	- providing a BandwithMeter for AdaptiveTrackSelection.Factory was depcrecated in ExoPlayer. Instead the BandwidthMeter from the (Simple-)ExoPlayer instance is used which is automatically created from BasePlayer ExoPlayerFactory.newSimpleInstance due to its constructor chaining

FailedMediaSource.java
LoadedMediaSource.java
PlaceholderMediaSource.java
	- simple adjustments for changes in ExoPlayer classes that these classes inherit

ManagedMediaSourcePlaylist.java
MediaSourceManager.java
	- a Handler is now required from ExoPlayer where it runs the Runnable after removing a playlist entry.

CustomTrackSelector.java
	- Removal of CustomTrackSelector as it was a workaround introduced for ExoPlayer 2.7.0


as you can see the changes are as minimal as possible. In general when I saw a deprecation due to the new player I just looked at javadoc for the recommend alternative or looked at the code of ExoPlayer.

**Comment by Redirion** [comment]
is anyone interested in testing NewPipe with the new ExoPlayer version? I could share my debug apk here.

**Comment by justanidea** [comment]
Ofc 👍

**Comment by Redirion** [comment]
https://github.com/Redirion/NewPipe/releases/tag/publictest

let me know if you find any issues that might be related to the new ExoPlayer version.
The apk is debug signed and contains the latest dev commits since the last official release.

**Comment by TobiGr** [comment]
Thank you for updating the dependencies. I won't be able to review this until next Friday. Please be patient :)

**Comment by theScrabi** [comment]
@TobiGr to make you're live easier here is a build by me.
[NewExoplayer.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/2949469/NewExoplayer.apk.zip)

**Comment by TobiGr** [comment]
@theScrabi thanks. I'll look into this after #1968 and #1851 are merged (unless you or someone else did). Theae two PRs are on my list for this week.

**Comment by theScrabi** [comment]
yap looks pretty stable to me :)

**Comment by theScrabi** [comment]
But say is this new?
Screenshot_20190311-204431_NewPipe

**Pull request merged**
