### PR TITLE
More miscellaneous little fixes and improvements

### PR DESCRIPTION
**Pull request by TacoTheDank**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Don't use dumb loser numbers when checking the Android OS version
- Replace a getSystemService(LayoutInflater) with LayoutInflater.from
- Updates the viewpager2 to use the preferred version of the state adapter
- Add missing app:iconSpaceReserved settings
- Some miscellaneous code improvements

#### Fixes the following issue(s)
- None that I'm aware of

#### APK testing 
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5469751/app-debug.zip)

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by TobiGr — COMMENTED** [review]
Thank you! Looks good to me.

@Stypox Can you please have a look at c9d9c599ea34b5d35e836c14338f8ea6c05d2274? I think there was a reason, why you didn't use vector drawables.

**Comment by TacoTheDank** [comment]
I remember reading a thing about that, but I don't remember where.

**Comment by Stypox** [comment]
I used PNGs since there is no way to use vector drawables in notifications on android 4.4

**Comment by TacoTheDank** [comment]
@Stypox 🤔 Interesting...

**Comment by TacoTheDank** [comment]
I decided to remove the vector commit, I rebased on top of latest commits, and regenerated a new APK.

**Review by Stypox — APPROVED** [review]
Code looks good. I also tested the apk in the activities you changed and it works fine. Thank you!

**Comment by Stypox** [comment]
@TobiGr merge (Can synk be disabled or fixed? It is preventing me from merging any PR)

**Pull request merged**
