### PR TITLE
Change Video not available PNG image to a vector drawable

### LINKED ISSUE #5609: The "Video unavailable" thumbnail on "unavailable" videos needs some changes
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Video unavailable message is hardcoded to the thumbnail on unavailable/unplayable videos. It would be great if it's changed to a "Video unavailable" text that follows app language instead of using this [English] thumbnail on every video and on every language.

#### Additional context

Example video: https://m.youtube.com/watch?v=r4JWI4UDOrc

Screenshot: 
Screenshot_20210216-202417

#### How will you/everyone benefit from this feature?

People will better understand what's going on because they will see the message in their language also the text on the thumbnail is a bit out of the border (text is too close to the border and not aligned to the center also part of of the last letter E is "cut").

### PR DESCRIPTION
**Pull request by sherlockbeard**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

Fixes #5609

#### Fixes the following issue(s)
removed png image and cropped and changed into vector drawable.

photo6269502245057964727

-

### CODE REVIEW

**Comment by Stypox** [comment]
Uh, interesting :-)
Remove the `ic_` from the file name, `ic_` stands for "icon" but this is not an icon ;-)

**Comment by Stypox** [comment]
I tried this, but the image seems to me a little bit uncentered. Could you improve the vector drawable by making sure the two points representing the nose lie at the center?

**Comment by sherlockbeard** [comment]
which one is better ?
1)
photo6271376581670841470


2)
photo6271376581670841471

**Comment by Stypox** [comment]
I prefer the first, but maybe just put it a little bit to the right and add some padding (like before)

**Comment by sherlockbeard** [comment]
current

photo6271376581670841477

**Comment by Stypox** [comment]
@sherlockbeard that looks good, thank you for the changes :-D
I'm gonna keep this open for some days, and if nobody complains I'm gonna merge it @TobiGr @TiA4f8R @mhmdanas @opusforlife2

**Review by Stypox — APPROVED** [review]
@sherlockbeard that looks good, thank you for the changes :-D
I'm gonna keep this open for some days, and if nobody complains I'm gonna merge it @TobiGr @TiA4f8R @mhmdanas @opusforlife2

**Comment by TiA4f8R** [comment]
Just a thing that I want to know is your advice about the background color of the monkey. Should this be black or grey like on the PNG image before?

**Comment by Stypox** [comment]
@TiA4f8R I think this is ok. One could argue that it should be inverted for white theme, though, what do you think?

**Comment by opusforlife2** [comment]
How about black (like in the preview images) for black theme, dark grey for dark theme, and light grey for light theme?

**Comment by TiA4f8R** [comment]
Nice idea!

**Comment by Stypox** [comment]
@sherlockbeard please create three different drawables with the same shape but with different colors:
- white background & black foreground for white theme
- gray background & white foreground for dark theme
- black background & white foreground  for black theme

And then select the correct drawable according to the current theme.

**Comment by mhmdanas** [comment]
@sherlockbeard where did you get the vector drawable from? Did you make it yourself?

**Comment by sherlockbeard** [comment]
@mhmdanas Converted the image online. Then positioned it by changing the value's in Editor.

**Comment by alienthief** [comment]
@sherlockbeard thank you for this. I would recommend zooming out the sad face a bit and moving the bellow text in the video window which is more convenient as I implied in my issue (the one this PR fixes)

**Comment by Stypox** [comment]
@alienthief I don't think the image should be further zoomed out, and moving the error panel higher is not related to this PR

**Comment by sherlockbeard** [comment]
final int lightTheme = R.style.LightSettingsTheme;
        final int blackTheme = R.style.BlackSettingsTheme;
         if(ThemeHelper.getSettingsThemeStyle(requireContext()) == lightTheme){
            binding.detailThumbnailImageView.setBackgroundColor(Color.WHITE);
        }else if(ThemeHelper.getSettingsThemeStyle(requireContext()) == blackTheme){
            binding.detailThumbnailImageView.setBackgroundColor(Color.BLACK);
        }else{
            binding.detailThumbnailImageView.setBackgroundColor(Color.GRAY);
        }
is there any other way for it ?

**Comment by Stypox** [comment]
Maybe in the XML you can set the background color of detailThumbnailImageView to the same color as important text (e.g. check the color of the video title and copy that)

**Comment by TobiGr** [comment]
Thank you. That's what I get on a TV / tablet
<details><summary>Screenshots</summary>


</details>

**Comment by TacoTheDank** [comment]
> @mhmdanas Converted the image online. Then positioned it by changing the value's in Editor.

Did you use some sort of online SVG path editor, or is there an actual site that can convert images to vectors? I'm interested to know what site you used to do this :thinking:

**Comment by sherlockbeard** [comment]
@TacoTheDank
 https://shapeshifter.design/
https://vectr.com

**Comment by TobiGr** [comment]
@sherlockbeard CAn you please address https://github.com/TeamNewPipe/NewPipe/pull/5925#issuecomment-813040872

**Comment by Stypox** [comment]
@sherlockbeard ping

**Comment by sherlockbeard** [comment]
@TobiGr @Stypox . No i don't think i can mention the #5925 . i tried it only in mobile before the comment .After testing it on tablet i got the same result as in #5925 . I tried to search for a solution but i was not able to come up with a answer . Sorry i am noob developer .

**Comment by nadiration** [comment]
@sherlockbeard Did you abandon thid? This is kinda important. We've been waiting for this.

**Comment by sherlockbeard** [comment]
@nadiration . Sorry i have abandon this pull request . i will be closing this pull request

**Comment by nadiration** [comment]
> @nadiration . Sorry i have to abandon this pull request . i will be closing this pull request

@sherlockbeard May I ask why? Just curious it seemed to work

**Comment by sherlockbeard** [comment]
@nadiration actually it is not working for android tv or tablet . anything with large screen size 
https://github.com/TeamNewPipe/NewPipe/pull/5925#issuecomment-813040872

**Comment by nadiration** [comment]
@sherlockbeard This may be fixed later on as phone users are the majority and it's working fine there?? This is really useful feature.

**Comment by mhmdanas** [comment]
@nadiration just because phone users are the majority does not mean we ignore the rest (even temporarily).

**Comment by TobiGr** [comment]
there is an additional `fragment_video_detail.xml` in the `land` layout directory for tablets and TVs. You did not modify it.

**Comment by sherlockbeard** [comment]
i have decided to open a new pull request and fixed the issue . Thanks @TobiGr for pointing me in the right direction

**Pull request closed without merging**
