### PR TITLE
Use DrawableCompat.

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Use `DrawableCompat` to tint the retrieved notification icon in `NotificationSettingsFragment`.

#### APK testing 

[debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5419320/debug.zip)

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Stypox** [comment]
I remember doing this differently in order to prevent doing more actions than needed on >=Lollipop (e.g. calling `wrap()` and `mutate()` on the drawable). But if you think that doesn't improve anything in terms of performance this can be merged

**Comment by Stypox** [comment]
Oh, according to [this SO](https://stackoverflow.com/questions/36279909/drawablecompat-settint-tints-all-new-drawables-with-the-same-id#36281825) just calling `setTint` was bad, so yeah, this is the best implementation. Thank you! Could you rebase? Then I'll merge

**Comment by Isira-Seneviratne** [comment]
> I remember doing this differently in order to prevent doing more actions than needed on >=Lollipop (e.g. calling `wrap()` and `mutate()` on the drawable). But if you think that doesn't improve anything in terms of performance this can be merged

There are issues with [some types](https://github.com/androidx/androidx/blob/8e421071a87cadfa1a1603ce5dfadeb900e9c118/core/core/src/main/java/androidx/core/graphics/drawable/WrappedDrawableApi21.java#L115) of drawables on Lollipop.

**Review by Stypox — APPROVED** [review]

**Comment by Stypox** [comment]
@TobiGr could you merge? I can't

**Pull request merged**
