### PR TITLE
Downgrade to ExoPlayer 2.11.8

### LINKED ISSUE #6510: Buffering video unrelated to connection
[Screen recording](https://linksharing.samsungcloud.com/5PFO7lkTlSVj) 

As you can see in the screen record videos randomly buffer when in video mode, however in background mode the audio plays fine.

This issue is limited to newpipe and other video apps work fine.

Samsung galaxy s10+ android 11

Reinstalling newpipe doesn't work
Changing Internet connection doesn't work

### PR DESCRIPTION
**Pull request by Redirion**
#### What is it?
- [X] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

Well here we go again. Yet another ExoPlayer downgrade to see if that helps with the buffering issues.
I included by accident the changes from #6515, but that shouldn't hurt.

#### Fixes the following issue(s)

- Fixes  #6510 (hopefully)

#### APK testing 

On the website the APK can be found by going to the "Checks" tab below the title and then on "artifacts" on the right.

#### Due diligence
- [X] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by opusforlife2** [comment]
Holy poop. I think this is it!

I didn't realise this before, but (probably) since the update to 2.12, the player didn't buffer ahead that much (the bright red line wasn't visible or was very short).

With 2.11, the difference is clearly visible. The player buffers ahead by a LOT (the bright red line looks like it's buffered ahead at least a minute or more).

At least this is how the UI behaves. Whether that clearly loaded buffer is a placebo or there is actually a difference in buffering, I don't know.

**Comment by TacoTheDank** [comment]
Reject modernity, return to old versions... 😭

**Comment by CBSkarmory** [comment]
This seems to have fixed the issue for me

**Comment by TobiGr** [comment]
@Redirion Please target the master branch, allowing us to make another hotifx version

**Comment by Redirion** [comment]
done in #6542

**Comment by opusforlife2** [comment]
Isn't there a button to switch branches in the same PR? I'm pretty sure I've seen something like that being used earlier.

**Comment by plusterkopp** [comment]
Is there any build available for download?

**Comment by Redirion** [comment]
Checks -> Artifacts
But I would not recommend it. This PR does not improve anything

**Pull request closed without merging**
