### PR TITLE
Revert "Control media volume with the hardware buttons."

### PR DESCRIPTION
**Pull request by theScrabi**
Reverts TeamNewPipe/NewPipe#1076

Is not compiling.

### CODE REVIEW

**Comment by theScrabi** [comment]
I merged faster that I should.
Acording to travis this is not compiling.

**Comment by wojcik-online** [comment]
It does. I simply forgot to add the import on the first commit.

**Comment by michaelblyons** [comment]
Can you un-revert if the import fixes the compile issue? I'd really like to have NewPipe control the media volume specifically, rather than the main system volume. It really screws up my ringer volume preferences.

cc #1072 https://github.com/TeamNewPipe/NewPipe/commit/fddcade1fbf60c2988ce515160b40ae0810df8ed

**Comment by Stypox** [comment]
Do not resume old closed PRs/issues. Even if the code worked 5 years ago, today it wouldn't be usable at all today anyway.

**Pull request merged**
