### PR TITLE
Error handling in subscribe() in DownloadDialog

### LINKED ISSUE #6107: App crashes when i download in Pop-up mode
### Checklist

- [x] I am using the latest version - x.xx.x 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to 'a video'
2. Press on 'Pop-up mode'
3. Press on  'the channel and download any video while Pop-up is playing, it crashes.'

### Actual behaviour

The app crashes.

### Expected behavior
 Proceed to Download the selected video

### Screenshots/Screen recordings
!
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-GB
* __App Language:__ en
* __Service:__ none
* __Version:__ 0.21.0
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
io.reactivex.rxjava3.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.NullPointerException: The callable returned a null value
	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:717)
	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:714)
	at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:46)
	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8349)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
Caused by: java.lang.NullPointerException: The callable returned a null value
	at java.util.Objects.requireNonNull(Objects.java:228)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version:
 - Device model:

### PR DESCRIPTION
**Pull request by sauravrao637**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- The result output in subscribe may throw error and thus need to be handled, so I did it :)

#### Fixes the following issue(s)

- Fixes #6107

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by TobiGr — CHANGES_REQUESTED** [review]
Thank you for fixing this issue!

With your implementation NewPipe is going to ignore the error which makes it hard to fix the, / find the underlying cause. For this reason, I suggest to do something like this to allow users reporting the problem:
``` java
throwable -> ErrorActivity.reportErrorInSnackbar(context,
    new ErrorInfo(throwable, UserAction.DOWNLOAD_GET_SIZE,
            "Downloading video stream size", currentInfo.getServiceId()))));
```
Replace "Downloading video stream size" with the proper description for each error.I think showing the snackbar should be ok. I did not test this, so there might be issues with that. E.g. it could be hidden by the download dialog overlay and thus be not accessible. If this is the case, we need to find another solution.

The change above requires
``` Java
DOWNLOAD_STREAM_SIZE("download stream size")
```
or something similar to be added to `org.schabi.newpipe.error.UserAction`

**Comment by sauravrao637** [comment]
As @TobiGr  mentioned "ErroSanckbar could be hidden by the download dialog overlay and thus be not accessible. If this is the case, we need to find another solution."  so it must be tested before merging.
The bug couldn't be reproduced as no case link  was provided with the[ bug report](https://github.com/TeamNewPipe/NewPipe/issues/6107) .

**Comment by TobiGr** [comment]
I am not able to reproduce the crash, but I think the snackbar will not be hidden and if it is, the user can still try to send the report by closing the download dialog and using the report button. If we do not get a response in the original issue, I suggest to merge this PR by the end of next week.

**Review by TobiGr — APPROVED** [review]
Sorry, I forgot about this PR

**Comment by sauravrao637** [comment]
No worries :) @TobiGr

**Pull request merged**
