### PR TITLE
added apk upload and comment on pr in travis

### PR DESCRIPTION
**Pull request by yausername**
Implemented the feature requested in https://github.com/TeamNewPipe/NewPipe/pull/3196#issuecomment-596200424
Travis will put a comment like [this](https://github.com/yausername/NewPipe/pull/1#issuecomment-597382609) on every build of a PR.
`CI_USER_PASSWORD` environment variable has to be added in travis settings. (I can share this with someone who has access to travis settings.)

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by wb9688** [comment]
Does this even work? Travis doesn't give access to secrets in cases of PRs, as someone could change the build scripts to print that secret and make a PR, and then they'll know the secret if that wasn't the case.

**Comment by yausername** [comment]
> Does this even work? Travis doesn't give access to secrets in cases of PRs, as someone could change the build scripts to print that secret and make a PR, and then they'll know the secret if that wasn't the case.

Ok. I didn't think of that.

**Comment by TobiGr** [comment]
Thanks for the effort. See my https://github.com/TeamNewPipe/NewPipe/pull/3196#issuecomment-598222796. If you want, feel free to use my workflow file and finish my draft.

**Comment by yausername** [comment]
@TobiGr I wanted to add apk download link as a comment in PR. But it is not possible even with github actions because the `secrets.GITHUB_TOKEN` is read-only for PRs from forked repos.

Anyway, with your workflow we are able to upload the artifact which is useful nonetheless.

**Pull request closed without merging**
