### PR TITLE
Convert AudioReactor to Kotlin.

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Convert the `AudioReactor` class to Kotlin.

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TacoTheDank** [comment]
Can you combine these two commits into one? It'd probably be cleaner.

**Comment by Isira-Seneviratne** [comment]
The first commit was produced by Android Studio, and it makes changes easier to identify: https://github.com/TeamNewPipe/NewPipe/pull/6657/commits/c29b3be92ccd630e5d6588430e2434177785eeda

**Comment by Redirion** [comment]
can you move the companion object to the top of the class? I personally prefer to have constants and class variables next to each other like in Java. You need to scroll down the whole file to find them.

**Comment by TacoTheDank** [comment]
> can you move the companion object to the top of the class? I personally prefer to have constants and class variables next to each other like in Java. You need to scroll down the whole file to find them.

As far as I can tell, Kotlin's coding conventions guide seems to suggest that companion objects would be [best kept at the bottom of a class](https://kotlinlang.org/docs/coding-conventions.html#:~:text=If%20the%20classes%20are%20intended%20to%20be%20used%20externally%20and%20aren%27t%20referenced%20inside%20the%20class%2C%20put%20them%20in%20the%20end%2C%20after%20the%20companion%20object.). Would it be better to adhere as closely as possible to Kotlin's official coding conventions for the sake of less confusion?

**Comment by mhmdanas** [comment]
I believe this PR goes against #6659?

**Comment by Isira-Seneviratne** [comment]
> I believe this PR goes against #6659?

Okay, I'll close this.

**Pull request closed without merging**
