### PR TITLE
Create README.asm.md

### PR DESCRIPTION
**Pull request by WirelessAlien**
#### What is it?
- [ ] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [x] Meta improvement to the project (dev facing)

#### Relies on the following changes

- Adds Readme in Assamese Language 
   Assamese have language codes "asm"

#### APK testing
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by WirelessAlien** [comment]
I have seen this comment - 
i will close this one, will start fresh in new PR tomorrow. sorry for the mess up @ShareASmile . That's why I started a new in the doc folder

**Comment by ShareASmile** [comment]
@WirelessAlien , you should add the link to Assamese READMe inside the others READMEs & also in english one.

**Comment by WirelessAlien** [comment]
> @WirelessAlien , you should add the link to Assamese READMe inside the others READMEs & also in english one.

Done.

**Comment by TobiGr** [comment]
Thank you for your work. Your changes were merged in #10240

**Pull request closed without merging**
