### PR TITLE
Remove unused strings

### LINKED ISSUE #574: Unused resource strings
I've noticed that title_activity_channel string (saying "ChannelActivity" in English currently) is not used anywhere in the UI (as far as my grep skills allow me to know). It's been sitting there confusing translators for some time (9a0f61e60bf325811fe8529880acaf97386f08bb) and there's now a variety of different kinds of translations people came up with, otherwise I wouldn't raise this issue. So can we remove this string?

Or maybe there's a bigger question. I'm not an android developer, but is there a way to see if a particular string is unused currently? Can it be automated in a way that makes sense and put into e.g. CI?

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

### PR DESCRIPTION
**Pull request by mauriciocolli**
- Remove some unused and redundant strings

Closes #574

### CODE REVIEW

**Comment by mauriciocolli** [comment]
@theScrabi I think it's good to merge (have to merge this quickly because it'll soon cause more conflicts, and to update weblate to the new translators see only strings that are worth translating)

**Comment by theScrabi** [comment]
All right I see it the same way.

**Comment by mauriciocolli** [comment]
Hey @theScrabi, we have to fix it fast, as translators are already contributing in weblate but it isn't updated/synced to this repository yet, I think you'll have to manually push the changes there.

**Comment by theScrabi** [comment]
Yes I did it once, but it broke again.

**Comment by mauriciocolli** [comment]
It's not fixed yet, I guess you just pulled the changes from there (adding again the unnecessary strings).

I think you'll have to lock the translations until you fix this issue, as people continue translating...
So don't pull the translations from there, **push** the changes from **here**.

Checking the documentation, I found some useful links:
[`wlc pull`](https://docs.weblate.org/en/latest/wlc.html#cmdoption-wlc-arg-pull) and [`wlc reset`](https://docs.weblate.org/en/latest/wlc.html#cmdoption-wlc-arg-reset)
https://docs.weblate.org/en/latest/faq.html#why-does-weblate-still-shows-old-translation-strings-when-i-ve-updated-the-template

**Comment by theScrabi** [comment]
Hm all right.

**Pull request merged**
