### PR TITLE
Migrate to AndroidX

### LINKED ISSUE #2641: update to Android X
please update newpipe code to androidx

### PR DESCRIPTION
**Pull request by Redirion**
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

Third attempt.
This PR supersedes PR #2598 (seems to be no longer maintained).
This was finally possible after PR #2535 was merged.
I took the stable approach for continued usage of the modified FlingBehavior.java from this commit 0d25645de9e1e5cf6d48d85d6253351ae3e6f8dc

Closes #2641 

Debug apk: https://github.com/Redirion/NewPipe/releases/download/v0.17.4/app-debug.apk

Note that I left everything unchanged, the Extractor still has the NullPointerException on getChannelCount.

### CODE REVIEW

**Comment by snappyapple632** [comment]
Tested the APK, no issues on my end.

**Comment by EmmanuelMess** [comment]
> This PR supersedes PR #2598 (seems to be no longer maintained).

Very sorry about that.

**Comment by mauriciocolli** [comment]
Oh, just noticed that I don't have the permissions to approve pull requests anymore (was inactive for some time), it is good to merge though.

**Comment by TobiGr** [comment]
@Redirion Below is the exception from #2697. I was able to reproduce it. It happens when rotating the screen on a channel page _twice_. E.g from portrait to landscape and back again. I guess this is what I did when opening the video and rotating the phone to view a video in landscape. However, I tried this with commits before this PR and did produce the crash. Would be good if you can take a look at it.
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ GB
* __Service:__ none
* __Version:__ 0.17.3
* __OS:__ Linux ,release-keys 6.0 - 23


<details><summary><b>Crash log</b></summary><p>

```
java.lang.RuntimeException: Unable to destroy activity {org.schabi.newpipe.debug/org.schabi.newpipe.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.viewpager.widget.ViewPager.setAdapter(androidx.viewpager.widget.PagerAdapter)' on a null object reference
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3852)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3870)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4074)
	at android.app.ActivityThread.-wrap15(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1360)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.viewpager.widget.ViewPager.setAdapter(androidx.viewpager.widget.PagerAdapter)' on a null object reference
	at org.schabi.newpipe.fragments.MainFragment.onDestroy(MainFragment.java:115)
	at androidx.fragment.app.Fragment.performDestroy(Fragment.java:2830)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1028)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1310)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
	at androidx.fragment.app.FragmentManagerImpl.dispatchDestroy(FragmentManagerImpl.java:2644)
	at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:329)
	at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:366)
	at androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java:233)
	at org.schabi.newpipe.MainActivity.onDestroy(MainActivity.java:352)
	at android.app.Activity.performDestroy(Activity.java:6415)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1165)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3839)
	... 10 more
java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.viewpager.widget.ViewPager.setAdapter(androidx.viewpager.widget.PagerAdapter)' on a null object reference
	at org.schabi.newpipe.fragments.MainFragment.onDestroy(MainFragment.java:115)
	at androidx.fragment.app.Fragment.performDestroy(Fragment.java:2830)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1028)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1310)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
	at androidx.fragment.app.FragmentManagerImpl.dispatchDestroy(FragmentManagerImpl.java:2644)
	at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:329)
	at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:366)
	at androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java:233)
	at org.schabi.newpipe.MainActivity.onDestroy(MainActivity.java:352)
	at android.app.Activity.performDestroy(Activity.java:6415)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1165)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3839)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3870)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4074)
	at android.app.ActivityThread.-wrap15(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1360)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

```
</p></details>
<hr>

**Comment by Redirion** [comment]
It might be easily mitigated with a null check but fixing the root cause which looks like a race condition between destroying and recreating the views. I will have a look tomorrow morning

**Comment by Redirion** [comment]
I went ahead with the simple fix. There was no obvious root cause and nulling the adapter of the ViewPager to clean it up is the correct thing to do. So I just added the null check inline with the other Fragment classes.

**Pull request merged**
