### PR TITLE
[YouTube] Fix broken likes in comments

### LINKED ISSUE #6323: Likes aren't shown in the YT videos comments
### Checklist

- [x] I am using the latest version - 0.21.2 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go on a YT Video
2. Check likes
3. Observe

### Actual behaviour

Likes on comments are showing 0

### Expected behavior

Should report the number of likes of the comments

### Device info

 - Android version/Custom ROM version: Android 10 QP1A.190711.020 / MIUM 12.0.10
 - Device model: Xiaomi Note 9 (M2003J15SG)

### PR DESCRIPTION
**Pull request by litetex**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
- Applies the changes of https://github.com/TeamNewPipe/NewPipeExtractor/pull/628 to fix #6323

Demo:
grafik grafik

⚠️ Note: The string is currently not localized and always in "en-GB"

#### Fixes the following issue(s)
- Fixes #6323 

#### Relies on the following changes
- https://github.com/TeamNewPipe/NewPipeExtractor/pull/628

#### APK testing 

On the website the APK can be found by going to the "Checks" tab below the title and then on "artifacts" on the right.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by XiangRongLin** [comment]
You need to update the NewPipeExtractor dependency and change it to your fork

**Comment by litetex** [comment]
This PR may no longer be required, because ``likeCount`` was fixed.
However due to the fact that yt now returns localized strings like ``3.3k``, ``15k`` or ``3.3M`` the number of likes may be inaccurate when the ``likeCount`` is bigger than 1000.
The ``likeCount`` functionality will also break if the language to get the comments is not anymore hardcoded to ``en`` (which may happen in the future).

**Review by B0pol — CHANGES_REQUESTED** [review]
As asked in https://github.com/TeamNewPipe/NewPipeExtractor/pull/628#pullrequestreview-669502785, please round the count using Localization.shortCount()

**Comment by litetex** [comment]
Changed the PR so that it uses the "old" likeCount with localization:
Now it looks like this:
grafik

**Review by B0pol — DISMISSED** [review]
It still shows 0 likes.

You have to update the extracton version to the last dev commit:

Copy the commit hash from here https://github.com/TeamNewPipe/NewPipeExtractor/commits

Replace v0.21.3 by the commit hash here https://github.com/TeamNewPipe/NewPipe/blob/f739ed7581b16eaf6adb217aba4c35ef08533aec/app/build.gradle#L186

**Review by TobiGr — APPROVED** [review]

**Review by B0pol — APPROVED** [review]

**Pull request merged**
